### PR TITLE
Add name for Mi Light

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Can you add this ?

**Comment by gizmocuz** [comment]
How about Easybulb ? and there are more names also

**Comment by ghost** [comment]
But look at forum that user agree with me to add Mi Light. More people search hardware Mi Lisght and can dont know that is the same as Limitless.... Mi Light is also popular as Limitless/AppLamp and should be set in name hardware in Domoticz.
Please add this

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
