### PR TITLE
Fix webserver initialization failure

### PR DESCRIPTION
**Pull request by gaudryc**
Because I changed the moment of acceptor initialization the server was always initialized with the listening address "::" which should be wrong in your environment.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Our build systems (both) have some problems with this commit

**Comment by gaudryc** [comment]
Bad diff issue...

Sorry.

**Comment by gizmocuz** [comment]
No worries, no stress
Bdw i receive this with version #4738

```
2016-02-23 08:56:28.589 Error: [web:443] missing SSL certificate chain file parameter !
2016-02-23 08:56:28.592 Error: [web:443] missing SSL private key file parameter !
2016-02-23 08:56:28.592 Error: [web:443] missing SSL DH file parameter
```

HTTP working, HTTPS not

**Comment by gaudryc** [comment]
Using the default command line (./domoticz) ?

**Comment by gizmocuz** [comment]
no, with the default domoticz.sh contents:

DAEMON_ARGS="-daemon -www 8080 -sslwww 443"

I am now building with your new commit and will test it on a raspberry

**Comment by gizmocuz** [comment]
I hope it still uses the default 'server_cert.pem' file ?

**Comment by gaudryc** [comment]
So strange.
If "missing SSL ... parameter" is reported, the parameter is really missing...
Does it work if you add the argument "-sslcert ./server_cert.pem" ?

**Comment by gaudryc** [comment]
Do you think I can have hazardous results with the function ?

```
std::string get_valid_value(const std::string & old_value, const std::string & new_value) {
        if ((!new_value.empty()) && (new_value != old_value)) {
            return new_value;
        }
        return old_value;
    }
```

**Comment by gizmocuz** [comment]
This version works better on my raspberry pi

only the error message from HTTP is not clear

```
2016-02-24 18:56:47.836  Domoticz V2.4753 (c)2012-2016 GizMoCuz
2016-02-24 18:56:47.836  Build Hash: d875cbf-modified, Date: 2016-02-24 17:53:22
2016-02-24 18:56:47.837  System: Raspberry Pi
2016-02-24 18:56:47.837  Startup Path: /home/pi/domoticz/
2016-02-24 18:56:48.049  Sunrise: 07:13:00 SunSet:19:13:00
2016-02-24 18:56:48.049  EventSystem: reset all events...
2016-02-24 18:56:48.069  Active notification subsystems: (0/11)
2016-02-24 18:56:48.074  Webserver(HTTP) started on address: 0.0.0.0, port: 8080
2016-02-24 18:56:48.097  Error: Failed to start the web server: bind: Permission denied
2016-02-24 18:56:48.098  Error: check privileges for opening ports below 1024
2016-02-24 18:56:48.099  Proxymanager started.
2016-02-24 18:56:48.103  Starting shared server on: 0.0.0.0:6144
2016-02-24 18:56:48.104  TCPServer: shared server started...
2016-02-24 18:56:48.105  RxQueue: queue worker started...
2016-02-24 18:56:50.105  Hardware Monitor: Started
2016-02-24 18:56:50.106  EventSystem: reset all events...
2016-02-24 18:56:50.107  EventSystem: reset all device statuses...
2016-02-24 18:56:50.110  EventSystem: Started
2016-02-24 18:56:53.106  Hardware Monitor: Fetching data (System sensors)
```

`Error: Failed to start the web server: bind: Permission denied`

this is for the SSL (port 443) i think... not sure... but port 8080 is working

control-c crash is still there:

```
2016-02-24 18:57:49.623  Mainworker Stopped...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injec  tor<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted
```

Starting the service (runs as sudo), works good:

2016-02-24 18:59:46.558 Webserver(HTTP) started on address: 0.0.0.0, port: 8080
2016-02-24 18:59:46.575 Webserver(SSL) started on address: 0.0.0.0, port: 443

would be great if we can log something like:

`Error: Webserver(SSL) Failed to start the web server: bind: Permission denied`

**Comment by gaudryc** [comment]
I will see these two points this evening (termination issue and log).
What about missing parameters ? Is it hazardous ?

**Comment by gizmocuz** [comment]
No, this commit works good on the raspberry (except for the termination)
i dont want to make a new beta yet to test on the cubieboard yet...

Don't work too hard! There will be another day tomorrow....

**Comment by gaudryc** [comment]
Don't worry about me ;-)
But I prefer to make thing clean as much as possible (and you begin to work before me tomorrow ;-)

**Comment by arjanwaard** [comment]
In the stable version I did not need to add the -sslwww option from the command line and domoticz started without the ssl part. This version always starts the ssl part or tries to do, port 443 on my machine is already taken so domoticz tries to start the ssl part every 5 seconds. Is this supposed to happen ?

On Control-C it exits with Segmentation fault: 11 (This is on OS X)

**Comment by gaudryc** [comment]
@arjanwaard 

Yes if nothing is set in the command line HTTPS is starting on the port 443 by default (it is the same for HTTP on the port 8080).
If you want to disable HTTPS, just add the following to your command line : -sslwww 0

**Pull request merged**
