### PR TITLE
Fix: Logitech Media Server: wrong status on other devices...

### PR DESCRIPTION
**Pull request by EddyK69**
...after switching LMS-player
Added support for Controller & Receiver

### CODE REVIEW

**Comment by gizmocuz** [comment]
i dont see where the new variable "Status" is being used in the LightsController.js ?
Maybe this should not have been committed ?

**Comment by EddyK69** [comment]
It's no new variable ;)
In fact,  it IS used (in line 1734/1735) but it never was set to "", so everytime a switch was swichted AFTER a media-player update, this switch got the same (=previous) state. By setting the initial state to "", this problem is fixed.

**Comment by gizmocuz** [comment]
Thanks, no i see ! Thanks ;)

**Comment by EddyK69** [comment]
Thank you!

**Pull request merged**
