### PR TITLE
Always send RxMessage on first time adding bridge

### PR DESCRIPTION
**Pull request by arjanwaard**

### CODE REVIEW

**Comment by gizmocuz** [comment]
You mean on first startup ?

**Comment by arjanwaard** [comment]
On first time adding the Hue bridge hardware.

**Comment by arjanwaard** [comment]
See http://www.domoticz.com/forum/viewtopic.php?f=6&t=11346

**Comment by gizmocuz** [comment]
Ok, Thanks for the patch!

**Pull request merged**
