### PR TITLE
Add Python plugins AwoxSMP

### PR DESCRIPTION
**Pull request by zaraki673**
Awox plugins to control Awox SmartPlug over bluetooth with Bluepy

https://www.domoticz.com/forum/viewtopic.php?f=4&t=15233#p115348

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!, But i am waiting for a change of the Python author to make the scripts object based (classes)
Otherwise when this is done, everyone should rewrite their scripts
Hope this is done asap

**Comment by zaraki673** [comment]
Thanks you for all your works, 
I will wait so :D

**Comment by gizmocuz** [comment]
@dnpwwo, maybe you could have a look at this ?

**Comment by gizmocuz** [comment]
Is it possible to rebuild it like the new dlink example plugin (using a class... does not have to be named BasePlugin of course

**Comment by zaraki673** [comment]
yep, i will do that ASAP  (i hope this week)

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
