### PR TITLE
Milight colorfix

### PR DESCRIPTION
**Pull request by mosjonathan999**
I have put back disapeared code,
and fixed the red issue

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!, Also for the reformatting ;)

**Comment by bizziebis** [comment]
Does this solve the problem for only some specific Mi-light devices? I have two RGBW lightbulbs, which after this change have red and green swapped.

**Comment by gizmocuz** [comment]
Are you controlling them with an RFLink or with the MiLight gateway ?

**Comment by bizziebis** [comment]
RFLink.
I've reverted this commit and compiled again and now it's working well again.

**Comment by gizmocuz** [comment]
As far as i can see, only this case has changed:

case Limitless_SetRGBColour

Is it possible you could ask on the forum if more people have problems with this (RFLink MiLight)
If yes, we need to revert this patch...

**Pull request merged**
