### PR TITLE
AnnaThermostat Added  proximity Switch allowing you to control the proximity sensor from Domoticz 

### PR DESCRIPTION
**Pull request by p-hagen**
This pull request does include the code changes from the pull request from Jgaalen
`**Changed AnnaTherm states from Text Sensor to Switch #3031**`
The update is tested against Firmware 3.1.4
First switch added that can be manipulated from Domoticz

This code change also will allow the easy addition of a few other simple switches  as the update code is now implemented.

Question for experienced maintainers:
The Anna has two settings that could benefit from a selector switch, 
If anyone has a good example/pseudo code  that would be appreciated

### CODE REVIEW

**Review by gizmocuz — COMMENTED** [review]
Could you move the defines to the cop file?

**Comment by p-hagen** [comment]
Yep.. Will Do.

**Comment by p-hagen** [comment]
Ok Moved the defines to the cpp file as requested

**Comment by p-hagen** [comment]
Ok resolved the define issues
PS. I'm working on extending the functionality of the plug in so expect more updates in the near future..

**Comment by p-hagen** [comment]
Is there anything i need to pass  the Appveyor build ?

**Comment by gizmocuz** [comment]
It will probably pass on a few hours

**Comment by p-hagen** [comment]
ok... patience is a virtue they say

**Comment by gizmocuz** [comment]
Why is this PR closed? If you continue development, please continue pushing to your repo and this PR will be updated

**Pull request closed without merging**
