### PR TITLE
Handle other units (m3, s) for Managed Counters in reports

### PR DESCRIPTION
**Pull request by guillaumezin**
Mainly for future (for instance Gazpar smart gas meter)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR, i would say start with 0 = kwh, then the rest... the default/current value is 0 right ?
Is it possible to change this ?

**Comment by guillaumezin** [comment]
Default is "?", I will change as requested anyway

**Comment by guillaumezin** [comment]
Done, I took the opportunity to correct reports for customized counters, that now display configured quantity and units in axis and total usage and hide costs that return NaN anyway

**Comment by gizmocuz** [comment]
Thanks !!

**Pull request merged**
