### PR TITLE
update index.html comboyear weather

### PR DESCRIPTION
**Pull request by steph10200**
Add year 2019 and 2020 for comboyear for show weather function.
Maybe it would be interesting to make this selection dynamic, or configurable.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Is it possible to compare this against the temperature and or the electic meter year combo’s ?
Maybe these are dynamic and you could adopt the code?

**Comment by rwaaren** [comment]
@steph10200   

> Maybe it would be interesting to make this selection dynamic, or configurable.

Hope you are not offended by my  PR #3851 for the same issue.

**Comment by steph10200** [comment]
> 
> 
> @steph10200
> 
> > Maybe it would be interesting to make this selection dynamic, or configurable.
> 
> Hope you are not offended by my PR #3851 for the same issue.

Indeed, I had not seen your patch. 
yours is better.

**Comment by gizmocuz** [comment]
@StefanPuntNL , thank you for this PR !! Much appreciated!
I do prefer the dynamic solution, but please continue to submit feature PR's !

**Pull request closed without merging**
