### PR TITLE
Detect Python boost library

### PR DESCRIPTION
**Pull request by Infern1**
Boost Python library wasn't detected. Based on the example from here:
https://github.com/TNG/boost-python-examples
more exactly
https://github.com/TNG/boost-python-examples/blob/master/CMakeLists.txt

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the PR !!
As far as i know, there is no dependency on boost_python needed, are you sure about this ?
This because all build scripts also do not 'build' the boost-python library, and python is still working

**Comment by Infern1** [comment]
> As far as i know, there is no dependency on boost_python needed, are you sure about this ?
> This because all build scripts also do not 'build' the boost-python library, and python is still working

Yes python is working, since this is detected elsewhere.
The reason for this PR is that in the [install manual ](https://www.domoticz.com/wiki/Mac_OSX) for MacOS is mentioned:
```
brew install cmake
brew install boost --with-python
brew install boost-python
.....
```

So when I need to install boost-python I suppose it need to be detected by cmake. So this is why I made the PR. If it is really need for functionality I don't know.

**Comment by gizmocuz** [comment]
Could you have a look at the Travis build script here:

https://github.com/domoticz/domoticz/blob/development/.travis.yml

I do not see a reference to it, maybe it is not needed (anymore)

**Comment by gizmocuz** [comment]
Then again... the travis OSX build is not working...

**Comment by gizmocuz** [comment]
No response for a long time.. maybe the setup page for osx on the wiki needs updates?
Closing issue for now

**Pull request closed without merging**
