### PR TITLE
somewhat fixed white slider in rgbw popup in dark-element skin

### PR DESCRIPTION
**Pull request by xztraz**
Before
rgbw_before

After
rgbw_after

### CODE REVIEW

**Comment by gizmocuz** [comment]
And the light as well ? Maybe this needs a global css change ?

**Comment by xztraz** [comment]
probably a global one(it's a mess to change skins). could not get it better than that in decent time. looks like a bunch of rowbreaks in html between sliders too.

**Comment by gizmocuz** [comment]
Should be done globally and not for this specific theme

**Comment by gizmocuz** [comment]
This should solve it globally i hope:

https://github.com/domoticz/domoticz/commit/7d890a97fb14ac489bedb0fb0b4bdabf9351ba0d

**Pull request closed without merging**
