### PR TITLE
Gui work

### PR DESCRIPTION
**Pull request by flatsiedatsie**
Let's, for now, just merge the basic version. 

Theme settings can be added later.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could it be that this was intended to be pushed to the GuiWork branch instead of the master?

**Comment by flatsiedatsie** [comment]
I wanted to propose merging the GuiWork into the main. I hope I did that correctly..

**Comment by gmaslowski** [comment]
@flatsiedatsie This branch contains conflicts, you'd need to merge 'master' branch into 'GuiWork' branch.

**Comment by gizmocuz** [comment]
best to merge the branch soon instead of a pull request to the master branch
going to publish a new stable first

**Comment by flatsiedatsie** [comment]
A new stable Domoticz has been released. Time to re-open this request?

**Comment by flatsiedatsie** [comment]
Anything I can do to help this along?

**Comment by gizmocuz** [comment]
Yes, there are some conflicts in the base html files.
If needed please create a separate pull request for base file changes
The new theme could be a separate zip file (excluding base images for the file size)
Maybe we can create a repository for themes so users can download the themes from there.
(With some screenshots in a wiki page)

**Comment by gizmocuz** [comment]
I think all needed changes are already in domoticz and this pull request can be closed ?

**Comment by gizmocuz** [comment]
Closing pull request as most work has been integrated.
If needed, please submit additional pull requests for more functionality
New themes should be done in a separate repository, and maybe we could create an option in Domoticz to download/enable/preview them

**Pull request closed without merging**
