### PR TITLE
#3918 #3922 Handle websocket messages by device table itself

### PR DESCRIPTION
**Pull request by stas-demydiuk**
Should address #3922 and probably #3918 issues as well as issue posted on the [forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31379) with resetting current page

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!!

**Comment by gizmocuz** [comment]
@stas-demydiuk , i seem to have a minor issue (maybe unrelated), when I add a new device to the system (green arrow) it is added, but the list is not refreshed and it 'seems' the device was not added
refreshing the browser solves it

**Comment by stas-demydiuk** [comment]
That's because there is no websocket event from server side about device update after you add or remove device

**Comment by rwaaren** [comment]
Same is true when you rename a device

**Comment by gizmocuz** [comment]
Maybe do a complete refresh of the list ?

**Pull request merged**
