### PR TITLE
SBFspot import data fix

### PR DESCRIPTION
**Pull request by novorum**
Archieved data is saved as Wh while domoticz uses kWh.
kWh = Wh * 1000

### CODE REVIEW

**Comment by gizmocuz** [comment]
What is your kWh divider in the settings ?

**Comment by novorum** [comment]
Default setting: 1000

**Comment by gizmocuz** [comment]
Okey, as i suspect a lot of users are using SBFSpot with domoticz, could you create a forum post to ask if users are having issues like you have ?
(Maybe it is a SBFSpot configuration ?)

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
