### PR TITLE
Adding RF structures that can be serialized.

### PR DESCRIPTION
**Pull request by rkluwen**
This pull request includes the file HardwareCereal.h which is able to cerealize the RFBUF union.
For the rest, no code makes use of it as of yet.
I *think* the types in Hardwaretypes.h will need to be included in the _tRDomoticz union (at the end of HardwareCereal.h) as well. Am I right, Gizmocuz?

== Rene

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR! Lot of work !

Yes that sound about right !
Question, do we need a copy constructor ?

_tR_LIGHTING1 v1;
LIGHTING1 vOrg;

v1 = vOrg

Or will the above work without it ?

**Comment by rkluwen** [comment]
It's a structure, not a class. So I figure it doesn't need a separate copy constructor.

**Comment by gizmocuz** [comment]
Thanks ! we do have a few compile errors (see our build system):

```
/home/travis/build/domoticz/domoticz/hardware/DomoticzHardware.cpp: In member function ‘void CDomoticzHardwareBase::SendTempSensor(int, int, float, const string&, int)’:
/home/travis/build/domoticz/domoticz/hardware/DomoticzHardware.cpp:180:27: error: ‘Serialize’ was not declared in this scope
  std::string serialized = Serialize<_tTempBaro>(deleteme);
                           ^~~~~~~~~
/home/travis/build/domoticz/domoticz/hardware/DomoticzHardware.cpp:180:47: error: expected primary-expression before ‘>’ token
  std::string serialized = Serialize<_tTempBaro>(deleteme);
                                               ^
/home/travis/build/domoticz/domoticz/hardware/DomoticzHardware.cpp:181:13: error: ‘Deserialize’ was not declared in this scope
  deleteme = Deserialize<_tTempBaro>(serialized);
             ^~~~~~~~~~~
/home/travis/build/domoticz/domoticz/hardware/DomoticzHardware.cpp:181:35: error: expected primary-expression before ‘>’ token
  deleteme = Deserialize<_tTempBaro>(serialized);
                                   ^
make[2]: *** [CMakeFiles/domoticz.dir/hardware/DomoticzHardware.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2

```

**Comment by rkluwen** [comment]
Sorry. Had to hunt some typo's first.
But as far as I am concerned, this PR can now be merged.

**Comment by gizmocuz** [comment]
Thanks!!!

**Pull request merged**
