### PR TITLE
Fix for RFLink version reading using TCP connection

### PR DESCRIPTION
**Pull request by bilbolodz**
Fix for RFLink version reading using TCP connection.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR! If this a normal RFLink that is serial and you use (for example) ser2net to make it available over TCP ?
Please have a look in the code here:
RFLinkBase.cpp , line 679:

`if ((Name_ID.find("Nodo RadioFrequencyLink") != std::string::npos) || (Name_ID.find("RFLink Gateway") != std::string::npos))
`

This should request the version.

Maybe your Name_ID is different ?

I think the patch should be made in the base class ?

**Comment by bilbolodz** [comment]
My RFlink is "normal RFLink" with connected ESP8266 module with  "serial bridge" software. I've described it in these issue: https://github.com/domoticz/domoticz/issues/4207
Problem occurs ONLY for TCP: when connection is made over USB Arduino is automatically reset and at start it presents firmware revision. When connection is over TCP NO Arduino reset is done so RFLink doesn't know nothing about "new connection" and NOT present version. Solution is a) modify Serial Bridge to reset Arduino on every incoming new TCP connection (require hardware modification) b) add to request version at start. So I think modification is in right place.

**Comment by gizmocuz** [comment]
Yes in this case there is no other option... Got a link to the sketch ? Always interested in this ;)

**Comment by bilbolodz** [comment]
I'm using ESPeasy with Ser2Net module: https://www.letscontrolit.com/wiki/index.php/Ser2Net
In case you have more RFLinks (for other frequencies) you can use ESP32 with 3 serial ports and these sketch: https://github.com/AlphaLima/ESP32-Serial-Bridge (Not yet tested by me).

**Comment by gizmocuz** [comment]
Thanks ! Going to look at the ESP32-Serial-Bridge as the first link displays that it can not work with large data (like a P1 meter)

**Comment by bilbolodz** [comment]
Yes my friend said that ESP-01 as serial server for RFLink sometimes is loosing some data (in case of some massive data flow). I'm going to build new version of my RFLink devices and integrate 3 RFLink (315,432,868MHz) on separate Arduino Mega 2560 modules into one using 3x Arduino Mega 2560 mini and ESP32 as serial bridge.

**Pull request merged**
