### PR TITLE
Add workaround to support additional Xiaomi devices like the relais (#3577, #3769, #4029)

### PR DESCRIPTION
**Pull request by Huupke**
Workaround for devices that do not report a model via the gateways API. For now this only works for the Xiaomi Aqara relais LLKZMK11LM (lumi.relay.c2acn01 or relay.c2acn01).

For usage you can either add some hardcoded values in the DeviceSupport but probably easier is to add a user variable named 'XiaomiDeviceSupportRelais'. You can add a single device ID like '158d00045c25cf' or comma separated for multiple like this: '158d00045c25cf,158d0003cbe6e8'. Notice always the prefix of '158d00' with respect to what you see in the 'Devices' overview UI.

This PR could fix/close (#3577, #3769, #4029)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Please have a look at the windows build system (error)

**Comment by gizmocuz** [comment]
Thank you for this PR!!

**Comment by waltervl** [comment]
@Huupke Can you update the Wiki for this? I suppose page https://www.domoticz.com/wiki/Xiaomi_Gateway_(Aqara) has to be updated?

**Comment by fielux** [comment]
Hi guys, not sure I understood what I'm supposed to do... my apologies. Assuming I downloaded a domoticz release that contains this fix, what else I'm supposed to do in order to make the Aqara wireless relay work? Do I have to modify some files? In which folder are they and what's their name? Thx in advance for your patience and support

**Comment by Huupke** [comment]
Add a user variable named 'XiaomiDeviceSupportRelais'. You can add a single
device ID like '158d00045c25cf' or comma separated for multiple like this:
'158d00045c25cf,158d0003cbe6e8'. Notice always the prefix of '158d00' with
respect to what you see in the 'Devices' overview UI.
Are also the updated wiki page.

Op za 6 nov. 2021 16:49 schreef fielux ***@***.***>:

**Comment by fielux** [comment]
Thx for your kind reply. For some reason I thought i was supposed to write something in a file… but it’s just adding a variable as properly written… my bad. Thx again

**Pull request merged**
