### PR TITLE
Chart changes

### PR DESCRIPTION
**Pull request by michahagg**
This PR contains the following:
- fix for Computed kWh-devices where the power value was never updated and the energy was computed from a constant and incorrect power value
- fix for the Compare chart to calculate the trend using the value in the same period of the previous year instead of the value in the previous period of the same year (#5025 )
- fix for the Compare chart to ignore negative counter values
- fix for Short Log Chart to show zoom buttons for 1d and 3d only when relevant in according to the range of the chart (#5024)
- fix for Counter Incremental to calculate the usage of the day with the first value of the day instead of the lowest value
- removed the ability to delete points on the Compare Chart
- a fix to prevent text selection when panning a chart on a mobile device (still not completely fixed)
- update for Highcharts library
- removed each Javascript .map-file and the reference to it from the .js-file, plus gzipped all .js-files in /js

### CODE REVIEW

**Comment by michahagg** [comment]
Hi @gizmocuz, I'm sorry but I introduced a nasty bug on 3 Oct this year. For computed kWh-devices the power value was updated with the current value instead of the new value, hence the power value was never updated at all. Each time a new update would occur, the energy value was calculated with the stuck power value. This PR contains a fix for this issue. My apologies for causing this issue.

The commit causing the error was part of PR #4958 which was merged on 7 Oct.

**Comment by gizmocuz** [comment]
No worries, great you solved it !! Thank you again for your support!

**Comment by gizmocuz** [comment]
Happy to merge this, but is it correct that the current month has no up/down icon ?

image

**Comment by michahagg** [comment]
In your situation, this is correct indeed. The trend for a period is determined by comparing its value with the value of the same period in the previous year. In your situation, the previous year for 2021 is 2020. For this year no value is given, hence no comparison can be made. It is quite unlikely for this to occur. It means, no counter value was recorded in Dec 2020. Is that correct? Could you check that?

**Comment by kiddigital** [comment]
> Hi @gizmocuz, I'm sorry but I introduced a nasty bug on 3 Oct this year. For computed kWh-devices the power value was updated with the current value instead of the new value, hence the power value was never updated at all. Each time a new update would occur, the energy value was calculated with the stuck power value. This PR contains a fix for this issue. My apologies for causing this issue.
> 
> The commit causing the error was part of PR #4958 which was merged on 7 Oct.

That is why we have Beta versions :) Thanks to Beta testing, the problem has not made it into the Stable.


> No worries, great you solved it !! Thank you again for your support!

🥇

**Comment by gizmocuz** [comment]
Your correct! In this domoticz instance there was no data in december 2020, there was for the other months.
Tested the PR and works perfectly, thanks!

**Pull request merged**
