### PR TITLE
Added Evohome DATE_TIME message decoding

### PR DESCRIPTION
**Pull request by Evsdd**
Hi,
A small update to add 0x313F (DATE_TIME) to the list of decoded Evohome messages.
Dan

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR.
It seems the new function 'DecodeDTime' is not used and currently only outputs some logging ?

**Comment by Evsdd** [comment]
Hi,

Yes, this is a really small update to simply add the decoding of this command to the log.  I'm gradually expanding the list of Evohome commands that are successfully decoded (to reduce/remove the UNKNOWN COMMAND flagging) and this helps with Evohome system monitoring and troubleshooting by identifying true corrupt messages caused by weak signal due to device positioning.

Let me know if would be better to group the updates to reduce the number of pull requests rather than submit small updates such as this one.

Dan

**Comment by gizmocuz** [comment]
@Evsdd , it might be better to submit a PR when the code is being called/implemented.
I understand you are working on this (Great!!), but currently the new function is not called, so there are no new changes for domoticz (for the end-user)

**Comment by Evsdd** [comment]
No problem.  I'll close this pull request and re-submit in a few weeks when I can combine it with additional functionality using the additional decoded commands.

Regards,

Dan

**Pull request closed without merging**
