### PR TITLE
Add Telegram Notification

### PR DESCRIPTION
**Pull request by chatainsim**
Here my new pull request for Telegram Notification.
Removed Setup.html and language files from my previous pull request.

Hope it's ok now :)

Thanks

Regarding language, my need are:
"Telegram": "Telegram",
"Chat ID": "Chat ID",

API Key is already defined.

### CODE REVIEW

**Comment by gizmocuz** [comment]
I think we do miss some setup form stuff in setup.html
The thing was in your previous pull request you changed much more in setup.html that was not related to this pull request.
Please submit/commit new changes to this pull request

**Comment by chatainsim** [comment]
Yes, sorry, I forgot this.
I'm on it.
That's the first time I do a multiple file commit to a project so I'm a little lost :)

**Comment by chatainsim** [comment]
Done !
I hope all is fine now.

**Comment by gizmocuz** [comment]
Thanks for your great work !!

**Comment by chatainsim** [comment]
No problem, thanks to you for having made Domoticz!

**Pull request merged**
