### PR TITLE
USBtin & Multibloc improvement / Bloc 9 now supported 

### PR DESCRIPTION
**Pull request by ghost**
This pull request contains many feature for USBtin and USBtin_MultiblocV8 improvement.

    Increase CAN buffer size receiver to avoid loss of frames.
    Increase Max number of blocs supported
    Add Bloc 9 management (like SFSP Bloc)
    Improve the auto release key code generation method when a user clicked on a virtual device who send his code on CAN bus. The old method was hazardous if more than one client clicked on 2 different virtual switch, the release keycode could not be send on CAN.
    About that, I would like to know if there is a way with some switch, to detect a "press" state (who could send the "press" state) and detect the release of the switch (who could idealy send the release keycode) which would be idealy because a real EnOcean switch send a push key code and a release key code, this means that we could dim a light when we push the switch without release them.

[recreated following advice from gizmocuz , thanks to him]

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR !!
One question, could you replace the log calls from

_log.Log(....

to

Log(...

**Comment by ghost** [comment]
Yes !

**Comment by gizmocuz** [comment]
If you make the changes and commit they will automatically appear in this PR

**Comment by gizmocuz** [comment]
Thank you for your PR and time!!

**Comment by ghost** [comment]
with pleasure :-)

**Pull request merged**
