### PR TITLE
add support for pushsafer.com notification service

### PR DESCRIPTION
**Pull request by appzer**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for this great piece of work !!

**Comment by appzer** [comment]
Thank you for merging.
what do you think the new version with Pushsafer published

**Comment by appzer** [comment]
Hi gizmocuz,

i installed the new beta, but in the notification setting the pushsafer header is missing!

**Pushsafer (iOS/Android/Windows10/Chrome/Firefox)**

zwischenablage01

Kevin

**Comment by gizmocuz** [comment]
that is because you only added the data-i18n, and not put the text also in the span
But i will add it to the translation system in the next commit

**Comment by gizmocuz** [comment]
Nope.. this text does not need translation, i removed the data-i18n, code is committed

**Comment by appzer** [comment]
Hi,

now in the latest beta (Windows 3.5687 2016-09-22 13,27 MB) the pushsafer plugin will not appear at all

Kevin

**Comment by gizmocuz** [comment]
Dont know why this is .... if you look at my latest change i can not imagine its broken, but i will have a look asap

**Comment by appzer** [comment]
i reinstalled 3.5687 after that all is fine.

Thanks Kevin

**Pull request merged**
