### PR TITLE
unique_ptr conversions

### PR DESCRIPTION
**Pull request by neheb**
This is C++14. new can be replaced with make_unique.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
@neheb , I do thank you for your efforts to contribute to this project, but your recent merged PR's are causing Domoticz too crash. This has happened multiple times before as well.
Either the changes are incorrect or not tested good enough. This could be because you have limited hardware to test with (No RF 433/868/zwave/ZigBee/MQTT) or not many realtime devices.
Please have a look at the latest commits where 4 of your PR's have been reverted to resolve a crash that happened in minutes after running.
Maybe you can review them again.
For now I find it to risky to accept any of your patches.

**Comment by neheb** [comment]
Most likely the unique_ptr commit was faulty. The rest should be fine.

**Comment by gizmocuz** [comment]
Thank you for this PR. I needed to remove the duplicate FILE_SEND_BUFFER_SIZE define. Did you not get a compile warning during testing ?

**Comment by neheb** [comment]
I believe I did but ignored it IIRC.

**Comment by gizmocuz** [comment]
Not a good thing to ignore compile warnings ;)

**Comment by neheb** [comment]
Sure. OTOH the codebase is full of them ;).

**Comment by kiddigital** [comment]
> Sure. OTOH the codebase is full of them ;).

Interesting, as when I compile under Linux (Ubuntu 21 gcc 10 at the moment) I don't see any on my clean environment.

If I encounter one or more, I fix them asap, so it stays clean (for me at least).

What warnings do you get in your environment? What (additional?) settings do you give the compiler that could generate these warnings?

I agree with @gizmocuz that we should not ignore warnings as they are there often for a reason.

**Comment by gizmocuz** [comment]
I don't see them as well... only when I compile under Windows with a 64bit platform...

**Comment by neheb** [comment]
Probably need to enable Wextra with gcc.

**Pull request merged**
