### PR TITLE
Fixed Anna to work with both firmwares

### PR DESCRIPTION
**Pull request by jgaalen**
Fixed Anna to work with both firmwares
Added different boiler state switches
Improved log messages

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR
Is it possible to let every log message start with "AnnaTherm: " ?

**Comment by jgaalen** [comment]
There you go

**Comment by p-hagen** [comment]
Tested the code for 3.1.4
Result: Fail
Reason: The new switches do not update Domoticz as the code to implement switches other then the setpoint was never completed in the Anna plugin.
Recommendation : Change them to sensors for now  as that will allow this patch to function

New Switches:     Fail
Delete hardware : Ok
Add hardware :     Ok
Delete devices:     Ok
Auto add devices: Ok
Disable/Enable:     Ok
Set Setpoint:         Ok


Result: The new switches do not update as the code to implement switches other then the setpoint was never completed in the Anna plugin.

**Comment by jgaalen** [comment]
It seemed that 'domestic_hot_water_state' doesn't update, its a fixed setting in the Anna Therm. But boiler_state updates (on and off) at least at 1.8.20 once the boiler starts heating. Perhaps we only need this switch. flame_state seemed to be a new state for 3.1.x version (not available on the 1.8.20).

Can you test the switch for 'boiler_state' only for 3.1.4? Then we can leave that switch in there. It works on my end for 1.8.20 and with a static xml file of 3.1.4

**Comment by p-hagen** [comment]
@Jgaalen  I've tested the boiler state  and it gets an update.
 
However it is implemented as a switch that the user could update. this causes an error messagebox to appear if they click on the switch : Problem sending switch command 
using a text sensor for example is a quick solution:
` 
else if (sname == "flame_state")
            {

                tmpstr = GetPeriodMeasurement(pElem);
                if (!tmpstr.empty())
                {
                    if(strcmp(tmpstr.c_str(), "on") == 0)
                    {
			SendTextSensor(10, 1, 255, "On",sname);
                    }
                    else
                    {
                        SendTextSensor(10, 1, 255, "Off", sname);
                    }
                }
            }
`

**Comment by jgaalen** [comment]
@p-hagen Thanks for your response. I see what you mean now, and yes the switch shouldn't be user-controllable, so text sensor seems the way to go.
I've updated the fix and also removed the domestic_hot_water_state as thats a config from Anna, not a state that switches when you turn on/off the hot water.

**Comment by p-hagen** [comment]
Tested on 3.1.4 and no issues found.  Ok to merge

**Comment by gizmocuz** [comment]
Thanks!!

**Comment by jgaalen** [comment]
I'm not happy by how the text sensor works for the state. It always adds a new line 'On' or 'Off' and overwriting the time. Therefor you can't see for how long the state 'On' is on that state for which time. We need a simple switch that cannot by controlled from the interface. Not sure how to do that, but there are many switches like that, like motion sensor, door switch, those are switches which cannot be controlled from the interface. Any idea how to change the text sensor to an actual switch?

**Comment by gizmocuz** [comment]
like a 'contact' type of switch ?

**Comment by gizmocuz** [comment]
Instead of a text sensor, the code needs to change to use a general switch for On/Off

**Comment by jgaalen** [comment]
@gizmocuz That's what it was before `SendSwitch` , but that seems to be a user controllable switch from the user interface, which should be possible. Any function available to set a switch on/off which can only be controlled from the code?

**Comment by jgaalen** [comment]
I've thought about it and think the `SendSwitch` command is the better way to go compared to `TextSensor`.  It's a on/off switch, which users can't control. If they somehow try to turn on the boiler by using the switch, they get an error and that is actually good, because they cannot switch it which is nicely shown in the interface. The TextSensor is a worse implementation in my opinion. 
What do you think?

**Comment by gizmocuz** [comment]
Yes better use the switch. Users can set it to a contact type

**Comment by ivooovi** [comment]
I have noticed one strange behaviour with Anna 1.8.20 I get battery low on my return water temperature from Anna. 

See this notification:
status problems 
2019-02-08 18:03:03.040  Status: dzVents: Error (2.4.13): Low battery warning: device temp - water (retour) low battery level : 56

**Pull request merged**
