### PR TITLE
Fix a wrong starting value issue for ZWave kWh devices

### PR DESCRIPTION
**Pull request by gaudryc**

### CODE REVIEW

**Comment by gizmocuz** [comment]
I think we need to divide instead of multiply
see the zwavebase.cpp's usage

`SendKwhMeter(pDevice->nodeID, pDevice->instanceID, BatLevel, pPowerDevice->floatValue, pDevice->floatValue / pDevice->scaleMultiply, "kWh Meter");
`

does this change, also goes for line 1888 (searching for "kwh") ?

**Comment by gaudryc** [comment]
Device value should contain Wh, openzwave sends kWh so we have to multiple.
I've changed it because I saw there was an issue after adding some logs.

**Comment by gaudryc** [comment]
It is invisible for everybody because updatevalue came shortly after addvalue. But because I had some strange values in Kwh logs (in meter table) when I was restarting domoticz, I have decided to add some logs then I saw these bad starting values.
This patch makes things coherent between addvalue and updatevalue.

**Comment by gizmocuz** [comment]
Okey, but it needs to be applied in 2 places then ?

**Comment by gaudryc** [comment]
Did I miss something ?

**Comment by gizmocuz** [comment]
Maybe one place

If you search for "kwh", you will see two occurrences... you patched one, i was wondering if this needed to be patched on two places
About line 1888 is the second occurrence

**Comment by gaudryc** [comment]
Ok I will see it this evening.
Thank you

**Comment by gaudryc** [comment]
You're absolutely right, I had to correct my problem without thinking that it could be elsewhere.

**Comment by gizmocuz** [comment]
Well you could not have known all code ;)

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
