### PR TITLE
Logging,  added optional parm level to addlogmessage JSON

### PR DESCRIPTION
**Pull request by rwaaren**

### CODE REVIEW

**Comment by gizmocuz** [comment]
I am not sure if this should be part of the Domoticz code or part of some script/system
Because this is just to log a message, maybe this needs to done upstream somewhere ?

**Comment by rwaaren** [comment]
> I am not sure if this should be part of the Domoticz code or part of some script/system
> Because this is just to log a message, maybe this needs to done upstream somewhere ?

It is a [Feature request](https://www.domoticz.com/forum/viewtopic.php?f=28&t=32670) and my thinking was that we already provide the option to use this to log a message but now only as status.
This PR only adds the option to choose the type of the logmessage which makes it easier to filter.

**Comment by Tsjippy** [comment]
I need this as I have a python script running which posts sensor data to domoticz using json. If the script catches an error I want to sent that error to domoticz as an error not as an status

**Comment by gizmocuz** [comment]
That's perfectly fine. Just before you call this function add your status text.

**Comment by rwaaren** [comment]
@gizmocuz  Do you have enough information to either merge or reject (close) this PR?

**Comment by gizmocuz** [comment]
@rwaaren , yes, I think it is up to the caller to build the string to be logged

**Comment by Tsjippy** [comment]
I don’t understand, do you mean this is already possible? how does this work?

**Comment by gizmocuz** [comment]
@Tsjippy , easy, the JSON addlogmessage JSON call expects one parameter, a string that needs to be added in the log.
Whatever you put in the string is up to you, you have to create/format the string, then call this function

**Comment by MrHobbes74** [comment]
I guess the point is that this function currently logs everything as level ‘status’ while he wants to log an ‘error’.

**Comment by gizmocuz** [comment]
Oeps sorry, totally missed that one indeed ! I implemented it here:

https://github.com/domoticz/domoticz/commit/a29cc48a20c9e5ba49f0b0ba802a939341f9c214
(and just added the missing OK status)

**Comment by Tsjippy** [comment]
Thanks!

**Comment by rwaaren** [comment]
> Oeps sorry, totally missed that one indeed ! I implemented it here:
> 
> [a29cc48](https://github.com/domoticz/domoticz/commit/a29cc48a20c9e5ba49f0b0ba802a939341f9c214)
> (and just added the missing OK status)

Thx!

**Pull request closed without merging**
