### PR TITLE
Rework of Nest plugin / NestOAuthAPI (#2)

### PR DESCRIPTION
**Pull request by dotms**
Followup of https://github.com/domoticz/domoticz/pull/2026 but now based on development branch as requested.

This pull request is the result of reworking the Nest thermostat plugin as described in [this Domoticz Forum thread](http://www.domoticz.com/forum/viewtopic.php?f=34&t=17370). This is intended as a replacement for the current Nest plugin (eventually) but it differs too much from the current one to be a drop-in replacement.

Please consider this one experimental since it should work, fine, but needs additional testing by others. I for example do not have 2FA enabled on my Nest account so I cannot reliably tell if it works on those kind of accounts, although I do not see any reason why it wouldn't.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this great addition!
One request, please increase the version number in the appcache file (needed when you make changes in the www folder)

**Comment by dotms** [comment]
I don't exactly know what you mean by that. Do you mean incrementing the "# ref 1475" statement in the appache file?

edit: judging from some explanation on [here](https://www.sitepoint.com/html5-application-cache/) that should be it.

**Comment by gizmocuz** [comment]
Thanks!

**Comment by mDieli** [comment]
Hi @dotms @gizmocuz 
Could it be there is something wrong here? (Or is it just my instance?)
As soon as I enable it with filled in Product ID, Product secret and oAuth PIN, Domoticz is crashing:
2018-01-31 17:18:56.723  NestOAuthAPI: No API key available.
2018-01-31 17:18:56.723  NestOAuthAPI: Will request an API key based on Product Id, Product Secret and PIN code.
*** Error in `./domoticz': free(): invalid pointer: 0x00007f36f801c020 ***

**Comment by sweetpants** [comment]
This commit is generating a lot of warnings during make
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable
cc1plus: warning: ./stdafx.h.gch/.c++: created by a different GCC executable

and a lot of other warnings

/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp: In member function ‘bool CNestOAuthAPI::Login()’:
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp:177:110: warning: format not a string literal and no format arguments [-Wformat-security]
     _log.Log(LOG_NORM, ("NestOAuthAPI: Received an API key to use for future requests: " + sTmpToken).c_str());
                                                                                                              ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp: In member function ‘void CNestOAuthAPI::GetMeterDetails()’:
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp:519:118: warning: format not a string literal and no format arguments [-Wformat-security]
     _log.Log(LOG_ERROR, ("NestOAuthAPI: Structure referenced thermostat " + devID + " but it was not found.").c_str());
                                                                                                                      ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp: In member function ‘std::__cxx11::string CNestOAuthAPI::FetchNestApiAccessToken(const string&, const string&, const string&)’:
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp:716:92: warning: format not a string literal and no format arguments [-Wformat-security]
  _log.Log(LOG_NORM, ("NestOAuthAPI: Fetched access token: " + sReceivedAccessToken).c_str());
                                                                                            ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp: In member function ‘bool CNestOAuthAPI::SetOAuthAccessToken(unsigned int, std::__cxx11::string&)’:
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/NestOAuthAPI.cpp:722:133: warning: format not a string literal and no format arguments [-Wformat-security]
  _log.Log(LOG_NORM, ("NestOAuthAPI: Storing received access token " + newToken + " and clearing token request information.").c_str());

**Comment by dotms** [comment]
Thanks both for testing. 

@mDieli I'll take a look and report back. Is it a Windows or Linux build you're experiencing this on?

@sweetpants Didn't look into Linux build logs very deeply on the CI part (only checked if they passed). Windows build does not mention these things. I'll look into it.

**Comment by mDieli** [comment]
@dotms It is Linux environment (Ubuntu Server 16.04.3)

**Comment by dotms** [comment]
@mDieli I can't seem to reproduce the crash myself. However I added some additional logging to the part of the code that you got the last output from, so it should be easier to narrow things down. 

Can you please do a test compiling https://github.com/dotms/domoticz/tree/development-nestoauth and providing me with the log from that one?

**Comment by mDieli** [comment]
@dotms I'm totally unknown to the use of git and branches. However, I came as far as merging from your development-nestoauth branch.
However, I receive a error:
"Automatic merge failed; fix conflicts and then commit the result."

When I check the terminal, it says:
"CONFLICT (content): Merge conflict in hardware/Rtl433.cpp"

**Comment by dotms** [comment]
You'd probably better do a fresh clone:

`git clone -b development-nestoauth https://github.com/dotms/domoticz.git `

And then do the regular building.

**Comment by mDieli** [comment]
I managed to compile it from your branch. (Huray!)
I lso did a fresh test compile of the official Domoticz git and did saw some errors there, however there were no errors with your branch. 

Unfortunate, I'm affraid my crashes are related to my live environment. In both my test-domoticz git and your branch, I had 0 crashes. 
However, I was also not able to manually set the setpoint. 
I tested to use the Nest app to change it, and that worked. Also after that, the temp setpoint changed in Domoticz. (So there is connection, but for some reason only to view in my case, not to set a setpoint)

**Comment by dotms** [comment]
@mDieli Since several months I do not have a Nest thermostat any more (only a Protect) so troubleshooting this will be a challenge. Back when I wrote the code it all worked fine so in basis it should be fine. I'll have a look this week. In the meantime, can you please check if you see any errors or other information in the logs when trying to adjust the setpoint?

**Comment by mDieli** [comment]
@dotms I tried my best to issolate the problem or try to get at least a reference. 
Unfortunate, I didn't find much.
I tried to set it to 24 degrees.
-With debug logging, It looks like the json call is ok:
"json.htm?type=command&param=setsetpoint&idx=2&setpoint=24"
When I do this call in the browser, the reply is `{
   "status" : "OK",
   "title" : "SetSetpoint"
}`
Looks OK to me, right ?

I issolated the rows that are logged when I do that json call. Unfortunate, I don't see that "24" degrees value comming by in the log.


2018-02-05 08:02:05.950  [7faa9564e700] Incoming connection from: 192.168.1.126
2018-02-05 08:02:05.954  [7faa9564e700] WEBH : Host:192.168.1.126 Uri;/json.htm?type=command&param=setsetpoint&idx=2&setpoint=24
2018-02-05 08:02:05.954  [7faa9564e700] WEBS GetJSon :setsetpoint :/json.htm?type=command&param=setsetpoint&idx=2&setpoint=24 
2018-02-05 08:02:05.954  [7faa9564e700] SQLQ query : SELECT HardwareID, DeviceID,Unit,Type,SubType,SwitchType,StrParam1,ID FROM DeviceStatus WHERE (ID == '2')
2018-02-05 08:02:05.954  [7faa9564e700] SQLR result: 2;0000001;0;242;1;0;;2;
2018-02-05 08:02:08.768  [7faa9564e700] SQLQ query : SELECT Name,nValue,sValue FROM DeviceStatus WHERE (HardwareID==2) AND (DeviceID=='0000003') AND (Unit == 1) AND (Type==17) AND (Subtype==0)
2018-02-05 08:02:08.769  [7faa9564e700] SQLR result: Thuis Away;0;0;
2018-02-05 08:02:08.769  [7faa92e49700] MAIN ProcessRX Msg 1FF2010000000100FF40649500008C4100000000000000000000000000000000
2018-02-05 08:02:08.769  [7faa92e49700] SQLQ query : SELECT ID,Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='0000001' AND Unit=0 AND Type=242 AND SubType=1)
2018-02-05 08:02:08.769  [7faa92e49700] SQLR result: 2;Thuis Family Room Setpoint;1;0;0;17.50;2018-02-05 08:01:59;;
2018-02-05 08:02:08.770  [7faa92e49700] SQLQ query : UPDATE DeviceStatus SET SignalLevel=12, BatteryLevel=255, nValue=0, sValue='17.50', LastUpdate='2018-02-05 08:02:08' WHERE (ID = 2)
2018-02-05 08:02:08.770  [7faa92e49700] SQLH UpdateValueInt Thuis Family Room Setpoint HwID:2  DevID:0000001 Type:242  sType:1 nValue:0 sValue:17.50 
2018-02-05 08:02:08.770  [7faa92e49700] SQLQ query : SELECT ID, SwitchType, LastUpdate, LastLevel, Options FROM DeviceStatus WHERE (Name == 'Thuis Family Room Setpoint')
2018-02-05 08:02:08.770  [7faa92e49700] SQLR result: 2;0;2018-02-05 08:02:08;0;;
2018-02-05 08:02:08.771  [7faa92e49700] RFXN : GetLightStatus Typ:242 STyp: 1 nVal:0 sVal:17.50 llvl: 0 isDim:0 maxDim: 0 GrpCmd:0 lstat:
2018-02-05 08:02:08.771  [7faa92e49700] SQLQ query : SELECT nValue, sValue FROM Preferences WHERE (Key='SensorTimeout')
2018-02-05 08:02:08.771  [7faa92e49700] SQLR result: 60;;
2018-02-05 08:02:08.771  [7faa92e49700] SQLQ query : SELECT ID, Name, Enabled, Type FROM Hardware
2018-02-05 08:02:08.771  [7faa92e49700] SQLR result: 1;Domoticz Internal;1;67;
2018-02-05 08:02:08.771  [7faa92e49700] SQLR result: 2;Nest;1;112;
2018-02-05 08:02:08.772  [7faa92e49700] SQLQ query : SELECT A.ID, A.DeviceID, A.Unit, A.Name, A.Used, A.Type, A.SubType, A.SignalLevel, A.BatteryLevel, A.nValue, A.sValue, A.LastUpdate, A.Favorite, A.SwitchType, A.HardwareID, A.AddjValue, A.AddjMulti, A.AddjValue2, A.AddjMulti2, A.LastLevel, A.CustomImage, A.StrParam1, A.StrParam2, A.Protected, IFNULL(B.XOffset,0), IFNULL(B.YOffset,0), IFNULL(B.PlanID,0), A.Description, A.Options FROM DeviceStatus A LEFT OUTER JOIN DeviceToPlansMap as B ON (B.DeviceRowID==a.ID) WHERE (A.ID=='2')
2018-02-05 08:02:08.772  [7faa92e49700] SQLR result: 2;0000001;0;Thuis Family Room Setpoint;1;242;1;12;255;0;17.50;2018-02-05 08:02:08;1;0;2;0.0;1.0;0.0;1.0;0;0;;;0;0;0;0;;;
2018-02-05 08:02:08.773  [7faa92e49700] SQLQ query : SELECT COUNT(*) FROM Timers WHERE (DeviceRowID==2) AND (TimerPlan==0)
2018-02-05 08:02:08.773  [7faa92e49700] SQLR result: 0;
2018-02-05 08:02:08.773  [7faa92e49700] SQLQ query : SELECT COUNT(*) FROM SetpointTimers WHERE (DeviceRowID==2) AND (TimerPlan==0)
2018-02-05 08:02:08.773  [7faa92e49700] SQLR result: 0;
2018-02-05 08:02:08.774  [7faa92e49700] subtype       = SetPoint
Temp = 17.50
2018-02-05 08:02:08.774  [7faa92e49700] SQLQ query : UPDATE DeviceStatus SET BatteryLevel=255 WHERE (ID==2)
2018-02-05 08:02:08.774  [7faa92e49700] (Nest) Thermostat (Thuis Family Room Setpoint)
2018-02-05 08:02:08.775  [7faa9564e700] SQLQ query : SELECT Name,nValue,sValue FROM DeviceStatus WHERE (HardwareID==2) AND (Type==17) AND (SubType==0) AND (DeviceID=='0000071')
2018-02-05 08:02:08.775  [7faa9564e700] SQLR result: Thuis Family Room HeatingOn;0;0;
2018-02-05 08:02:08.776  [7faa92e49700] MAIN ProcessRX Msg 0A520500000200B92D01CF
2018-02-05 08:02:08.776  [7faa92e49700] SQLQ query : SELECT AddjValue,AddjMulti FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='2' AND Unit=0 AND Type=82 AND SubType=5)
2018-02-05 08:02:08.776  [7faa92e49700] SQLR result: 0.0;1.0;
2018-02-05 08:02:08.776  [7faa92e49700] SQLQ query : SELECT ID,Name, Used, SwitchType, nValue, sValue, LastUpdate, Options FROM DeviceStatus WHERE (HardwareID=2 AND DeviceID='2' AND Unit=0 AND Type=82 AND SubType=5)
2018-02-05 08:02:08.777  [7faa92e49700] SQLR result: 3;Thuis Family Room TempHum;1;0;0;18.5;45;1;2018-02-05 08:01:59;;
2018-02-05 08:02:08.777  [7faa92e49700] SQLQ query : UPDATE DeviceStatus SET SignalLevel=12, BatteryLevel=100, nValue=0, sValue='18.5;45;1', LastUpdate='2018-02-05 08:02:08' WHERE (ID = 3)
2018-02-05 08:02:08.777  [7faa92e49700] SQLH UpdateValueInt Thuis Family Room TempHum HwID:2  DevID:2 Type:82  sType:5 nValue:0 sValue:18.5;45;1 
2018-02-05 08:02:08.777  [7faa92e49700] SQLQ query : SELECT ID, SwitchType, LastUpdate, LastLevel, Options FROM DeviceStatus WHERE (Name == 'Thuis Family Room TempHum')
2018-02-05 08:02:08.777  [7faa92e49700] SQLR result: 3;0;2018-02-05 08:02:08;0;;
2018-02-05 08:02:08.777  [7faa92e49700] RFXN : GetLightStatus Typ:82 STyp: 5 nVal:0 sVal:18.5;45;1 llvl: 0 isDim:0 maxDim: 0 GrpCmd:0 lstat:
2018-02-05 08:02:08.778  [7faa92e49700] SQLQ query : SELECT nValue, sValue FROM Preferences WHERE (Key='SensorTimeout')
2018-02-05 08:02:08.778  [7faa92e49700] SQLR result: 60;;
2018-02-05 08:02:08.778  [7faa92e49700] SQLQ query : SELECT ID, Name, Enabled, Type FROM Hardware
2018-02-05 08:02:08.778  [7faa92e49700] SQLR result: 1;Domoticz Internal;1;67;
2018-02-05 08:02:08.778  [7faa92e49700] SQLR result: 2;Nest;1;112;
2018-02-05 08:02:08.778  [7faa92e49700] SQLQ query : SELECT A.ID, A.DeviceID, A.Unit, A.Name, A.Used, A.Type, A.SubType, A.SignalLevel, A.BatteryLevel, A.nValue, A.sValue, A.LastUpdate, A.Favorite, A.SwitchType, A.HardwareID, A.AddjValue, A.AddjMulti, A.AddjValue2, A.AddjMulti2, A.LastLevel, A.CustomImage, A.StrParam1, A.StrParam2, A.Protected, IFNULL(B.XOffset,0), IFNULL(B.YOffset,0), IFNULL(B.PlanID,0), A.Description, A.Options FROM DeviceStatus A LEFT OUTER JOIN DeviceToPlansMap as B ON (B.DeviceRowID==a.ID) WHERE (A.ID=='3')
2018-02-05 08:02:08.779  [7faa92e49700] SQLR result: 3;2;0;Thuis Family Room TempHum;1;82;5;12;100;0;18.5;45;1;2018-02-05 08:02:08;0;0;2;0.0;1.0;0.0;1.0;0;0;;;0;0;0;0;;;
2018-02-05 08:02:08.779  [7faa92e49700] subtype       = TH5 - WTGR800
Sequence nbr  = 0
ID            = 2
Temperature   = 18.5 C
Humidity      = 45 %
Status        = Comfortable
Signal level  = 12
Battery       = OK
2018-02-05 08:02:08.779  [7faa92e49700] SQLQ query : UPDATE DeviceStatus SET BatteryLevel=255 WHERE (ID==3)
2018-02-05 08:02:08.779  [7faa92e49700] (Nest) Temp + Humidity (Thuis Family Room TempHum)

**Comment by dotms** [comment]
Found out there is a Nest simulator which I can test API interaction against. This makes it easier to troubleshoot. Once I tested against this one I'll follow up.

For clarification: during development last year I still had a physical Nest (that I developed and tested against). Now I don't anymore.

**Pull request merged**
