### PR TITLE
Improved robustness of processing Settings update

### PR DESCRIPTION
**Pull request by kiddigital**
This PR made changes to the cmd_PostSettings to make the processing of updated settings more robust.

Some users (see forum topics and issue #4936 for example) report that they have crashes when trying to save Settings.

Although it is not really clear why these crashes occur, it makes sense that the Domoticz back-end handles wrong data more gracefully.

The code has been refactored, cleaned-up and re-arranged to be more readable and better error handling is added including some extra information in case of caught exceptions.

And a (Linux) compiler warning has been tackled.

### CODE REVIEW

**Comment by gizmocuz** [comment]
The settings are applied but it seems to crash after it. When restarting the settings are applied.
So maybe it's not inside this function ?

**Comment by kiddigital** [comment]
If you are just referring to the mentioned example issue, it is partly true.

During the process of storing the settings, for a number of settings not only the DB update is done but also one or more specific setting related function calls are executed from within this command. In this example issue it is likely that one of these calls (reload Python plugins I guess) is crashing.

But as the initiative to perform this call is from the PostSettings command and the change of the settings requires another function to be executed, it makes sense to consider the PostSettings call as failed (although most or even all DB updates have been done).

More in general this call should not crash and handle the data better. Also telling the User that if something failed, the state of the system is in limbo (what is stored and what not, what parts/modules have adapted to the new settings and what not, etc).

And from security perspective handling the data better makes abuse a little harder.

**Comment by gizmocuz** [comment]
I don't think when the application is crashing it will return true/false to the user....
But restarting python plugins could indeed be the issue... If it is still crashing as some user, maybe we could remark this code and do some testing.
I will merge the PR, thank you!

**Comment by kiddigital** [comment]
Thx..

With this change, the end-user will get a message 'Problem saving settings!' (See SetupController.js line 743) because the back-end will now return status 'ERR' instead of crashing 😁.

(And there is some additional information in an MSG field that could contain a clue on where/why it crashed. At least a starting point 😉)

**Pull request merged**
