### PR TITLE
Update Event editor

### PR DESCRIPTION
**Pull request by stas-demydiuk**
-- Get rid of events iframe
-- Add tabs support
-- Add ability to edit couple scripts at the same time
-- Extract app routes to own module
-- Update blockly to fix known issues

localhost_3000_ 2

localhost_3000_

### CODE REVIEW

**Comment by stas-demydiuk** [comment]
Any feedback or suggestions are appreciated

**Comment by dannybloe** [comment]
Looks good. I will try to look into this this weekend. (And please do normal checkboxes instead of those ugly slider switches, fine for the general UI but not in a script IDE environment if you ask me).

**Comment by gizmocuz** [comment]
@dannybloe , we should keep everything in the same style. Later in a theme you can override the checkbox styles to look whatever you would like it to be

**Comment by twpeltenburg** [comment]
I would love the tab feature! No more switching back and forth between events! I also agree about the checkboxes. Use those and not those sliders.

**Comment by dannybloe** [comment]
> @dannybloe , we should keep everything in the same style. Later in a theme you can override the checkbox styles to look whatever you would like it to be

They are horrible and a pain to my eye. Takes way too much space, especially in a list. When looking for the proper file in the list I have to constantly jump over those gruesome slide-switches. 
But who am I anyway... sigh... ;-)

**Comment by gizmocuz** [comment]
I actually have no idea what i am looking at...'Automation Scripts' ? Are those scripts you already stored ?
If so, why not have a list without checkboxes? Make the scripts grayed (in font color) when they are disabled ? (or red like it is now), where can we rename/edit/active them ?

**Comment by stas-demydiuk** [comment]
@gizmocuz could you please explain a little bit what do you mean, the idea is to make it behave as any editor in IDE. Checkboxes are used to enable or disable selected script

**Comment by gizmocuz** [comment]
@stas-demydiuk , what do you mean by 'enable or disable' selected script ?
As my question above, are these scripts you made and saved ? these scripts can be enabled/disabled and have a name, and can be deleted correct ?
Like the current behavior:

image

**Comment by stas-demydiuk** [comment]
Yes, correct. The list contains all events you've created and saved before. If you click on the item in the list, it will open selected event in new tab, where you will be able to edit it and save or delete. When you edit the event, special "*" mark will be added to the tab title till you click "Save". If you want to create new event you need to click "+" button near the tabs. 

Checkboxes make event active or not like in your screenshot.

**Comment by gizmocuz** [comment]
@stas-demydiuk , okey then i understood correctly. So instead of checkboxes you can display the active/disabled state with a font color. If you select an event, you should have the option to change it's name, enable/disable it, (press the update button), or delete the event.
So there is only one checkbox needed, which could be the default checkbox style in domoticz.
This will also give 50/60 more pixels for the editor

**Comment by stas-demydiuk** [comment]
Yes I could do it this way and at the same time it will require to make couple more clicks, my intention was to make it a little bit simpler, as currently you just can click on checkbox in the list to enable/disable event and in another case you would need to open event each required event and after that be able to enable/disable it

**Comment by dannybloe** [comment]
> @stas-demydiuk , okey then i understood correctly. So instead of checkboxes you can display the active/disabled state with a font color. If you select an event, you should have the option to change it's name, enable/disable it, (press the update button), or delete the event.
> So there is only one checkbox needed, which could be the default checkbox style in domoticz.
> This will also give 50/60 more pixels for the editor

Indeed a much better approach!

**Comment by gizmocuz** [comment]
@stas-demydiuk , i think it is much easier if you add the checkbox (plus label) at the top where you have now the editbox for the name, the save and delete buttons.
You just select the event, make your changes, and press save.
It is not common you disable and enable events, and using three mouse clicks (selecting the event, enable the event and press save), is not much more work then 'press the checkbox, and get a messagebox that asks if you really want to do this, because you might have accidentally clicked the wrong event, and press YES)  so it is 3 clicks vs 2 clicks, and you get a cleaner gui in return ;)

**Comment by gizmocuz** [comment]
@stas-demydiuk , you might wish to add a 'new or clear' button. This could clear the internal selected eventID so you know there is no name-change/(enable/disable change), and it could clear the name, set the state to enabled and clear the event code
Also please do not forget to add a tab (or similar) where you can quickly see all current device states

**Comment by gizmocuz** [comment]
Question, when we use blockly for the event (which is still the easiest way...for me *g*), there is always the issue that your screen is not large enough.
Do we need to have a list of all events (with the active/disable state) on the screen ?
We could make it in a panel that you can dock/hide (sidebar) ?

https://www.w3schools.com/w3css/w3css_sidebar.asp

http://jsfiddle.net/rionmonster/J8U25/

**Comment by chatainsim** [comment]
This is really nice !
Love tabs for script editing.

**Comment by stas-demydiuk** [comment]
PR has been updated to address existed feedback:
- Move control to enable/disable script to its tab
- Add ability to Import/Export Blockly script
- Add ability to show/hide script list
- Add static tab with devices current states

localhost_3000_ 3

localhost_3000_ 4

localhost_3000_ 5

localhost_3000_ 6

**Comment by sweetpants** [comment]
looking slick

**Comment by gizmocuz** [comment]
Looking great ! Whats the small icon in front of the script name ? do you have different icons for lua/dzVents and blockly ?

**Comment by dannybloe** [comment]
I love it! 
Already asked on Slack: would it be possible to add dzVents specific code-completions? Woud be awesome that if you type `domoticz.` you will get a list of all methods and constants of the `domoticz` object. Of course the editor isn't aware (I guess) of the types of variables (like knowing if your variable is a device object or a time object) but we could make it semi-smart by at least trigger based on the name `domoticz` or `dz`. If that's not possible then I will just create a long list of all dzVents keywords (all methods of all kinds of objects in the dzVents object tree).

Another question: Search and replace. Is it possible to at least have a couple of buttons in the 'toolbar' for search/replace (and perhaps some others like copy/past, undo/redo)?

And finally: is there a shortcut to save the current file? like cmd-s on mac or ctrl-s on windows. I know it is possible to overrule the default browser behaviour for ctr/cmd-s. It would be a huge benefit in here. If so, make sure there's a tooltip on the save button telling the user there's a short-cut for saving.

**Comment by stas-demydiuk** [comment]
@gizmocuz small icon is the own tab with table of devices current statuses.

@dannybloe great suggestions. I would love to have all of them
1. Code-completion should eventually be possible as Ace editor (which we use for code editing) looks like supports such extensions: https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor. Need to allocate some time to dig into how to implement it

2. Search and replace also looks like could be added by native extension (searchbox)
https://github.com/ajaxorg/ace/wiki/Extensions

3. Currently there is no such implementation but I guess it could be added relatively easy, will take a look on that

**Comment by landaisbenj** [comment]
Really really nice. 
Would not it be possible to have an import / export files (download ?) for lua / dzvent / python etc ... like the blockly, instead of copy past?

**Comment by stas-demydiuk** [comment]
@landaisbenj I guess it is possible but what's the difference as in import/export modal you still need to copy/paste and why don't just do it directly into editor?

**Comment by landaisbenj** [comment]
@stas-demydiuk If i want to make a backup of domoticz, i can do it with all backup. But if i just want to make a save of all my script, for reinstall by blank (or share or just make a back up) i must to copy/past all event in another editor. i think if it's possible on blockly, why not on other ... I can't acces my domoticz at work. So i pull all my script on cloud and i can edit by the way ...

**Comment by stas-demydiuk** [comment]
@landaisbenj probably I misunderstood what are you looking for in import/export functionality. Could you please explain how would you expect it work?

**Comment by landaisbenj** [comment]
Yes. by clicking on the export button, a file would be created with type extension (name.lua, name.py or .dz etc...) that could be downloaded. And on import maybe same thing to upload. And maybe all for multiple files!? Just an idea.

**Comment by gizmocuz** [comment]
If the Lua/dzVents scripts are stored inside the database (like the Blockly), then making a backup is just pressing the backup button in the settings.

**Comment by landaisbenj** [comment]
Yes. But if i want reinstall without backup (to make a blank install) i must to save all event one by one. If i want to make change on script without access to domoticz, i can't... But it's just an idea.

**Comment by gizmocuz** [comment]
@landaisbenj , who wants to start with a clean database when you have all those great historic values ?
Anyways, you can always open the database in a SQLite editor and copy/paste, and you can copy/paste them now in 'notepad'

@stas-demydiuk, looking great !, Tell me when you think it should be merged!

**Comment by landaisbenj** [comment]
Easy. I do. I don't care historic because my home's life is present. But like I said, it's just an idea after import/export were already implemented for blockly.

**Comment by devrosx** [comment]
@stas-demydiuk 
Really like your work. I have idea to improve the editor. Dunno if its simply possible, or should fit in own theme panel? What about add support to add js/jquery support (next to python, blocky and lua) for own gui modification. This way it could be easy to manage / disable / enable small pieces of js code. :)

**Comment by freemann** [comment]
What's needed to get this PR accepted?

**Comment by freemann** [comment]
What's needed to get this PR accepted?

**Comment by gizmocuz** [comment]
@freemann , not much but i know stas is busy currently and can't give support when something goes/is wrong. That's why i'm waiting for his word.
This is also a cosmetic change and you can use the current implementation

**Comment by stas-demydiuk** [comment]
@gizmocuz It should be ok for merging now

**Comment by gizmocuz** [comment]
Thanks!!

**Comment by freemann** [comment]
Just updated my Beta install with the new editor and seeing strange things;
screenshot - 24_10_2018 16_45_58

Also after selecting an event the code panel isn't showing;
screenshot - 24_10_2018 16_48_06

It this enough for reporting this problem or should I create a issue on git or the forum?

**Comment by gizmocuz** [comment]
@freeman, no issue here, can you try in a 'private' browser? (in chrome control-shift-n), it could be a browser cache and/or appcache issue (two different things!)

**Comment by freemann** [comment]
Tried clearing the Appcache (chrome://appcache-internals/#) and clear local chrome cache.
After that it shows the code panel, but still the script names are overlaying. 
Tried disabling some css stuff and disabling the "display:flex" on the "</li>" elements make the text visible.
But when I scroll the left panel, the icon stay on there place and the text scrolls vertical.
screenshot - 24_10_2018 19_23_16

**Comment by stas-demydiuk** [comment]
@freemann was able to reproduce your issue (requires to have scrolling in the scripts list), will create a PR with fix

**Comment by stas-demydiuk** [comment]
#2798 PR with the fix

**Comment by gizmocuz** [comment]
merged in beta 10098

**Pull request merged**
