### PR TITLE
Tado Smart Thermostat device support

### PR DESCRIPTION
**Pull request by dotms**
Device support for the Tado Smart Thermostat. Data source is the _my.tado.com_ web application API. Some measures have been taken to make it as robust as possible but since the API is unofficial it may change in the future require code changes.

Provides the following sensors:

**Home**
- Presence (home/away)

**Zone**
- Setpoint
- Temperature/humidity
- Heating power %
- Heating enabled (can thermostat turn on heating if required)
- Setpoint override in effect
- Heating On (is thermostat currently heating)

Please hold this PR until I have tested it for about a week. Will follow up with confirmation.

Related feature request: https://github.com/domoticz/domoticz/issues/1294

### CODE REVIEW

**Comment by dannybloe** [comment]
Can you also test if the api also supports this device and if you can control this from Lua and/or dzVents? Coz I can already see the questions in the forum: how can I control this device from script?

**Comment by dotms** [comment]
The thermostat will be a regular device in Domoticz, so I don't think any special measures should be taken. I'll do some tests from Lua but I don't expect any problems in any of the 3 areas that you mentioned.

**Comment by dotms** [comment]
Quick update: build with this patch seems stable and functional for the past week now. I however did see some unexpected behaviour regarding the setting and cancelling of setpoints so I'll need to do some additional testing on that.

Edit: false alarm, everything is working just fine (except my head >< ). Please merge this PR into development.

**Comment by gizmocuz** [comment]
Thanks for this great addition!

**Comment by Jumbotroll** [comment]
Synology cross compile error.

[ 72%] Building CXX object CMakeFiles/domoticz.dir/hardware/Tado.cpp.o
In file included from /home/dahl/spksrc-master/toolchains/syno-x86-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/include/c++/4.9.3/regex:35:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:25:
/home/dahl/spksrc-master/toolchains/syno-x86-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/include/c++/4.9.3/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp: In member function ‘bool CTado::MatchValueFromJSKey(std::string, std::string, std::string&)’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:2: error: ‘match_results’ is not a member of ‘std’
  std::match_results<std::string::const_iterator> _Matches;
  ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:2: note: suggested alternative:
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/read_until.hpp:26:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio.hpp:91,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPClient.h:3,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPServer.h:4,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/mainworker.h:11,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:21:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/detail/regex_fwd.hpp:29:7: note:   ‘boost::match_results’
 class match_results;
       ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:48: error: expected primary-expression before ‘>’ token
  std::match_results<std::string::const_iterator> _Matches;
                                                ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:578:50: error: ‘_Matches’ was not declared in this scope
  std::match_results<std::string::const_iterator> _Matches;
                                                  ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:581:2: error: ‘regex’ is not a member of ‘std’
  std::regex _reSearch(sKeyName + ": '(.*?)'");
  ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:581:2: note: suggested alternative:
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/regex_fwd.hpp:27:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/detail/regex_fwd.hpp:20,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/read_until.hpp:26,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio.hpp:91,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPClient.h:3,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPServer.h:4,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/mainworker.h:11,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:21:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/regex/v4/regex_fwd.hpp:60:48: note:   ‘boost::regex’
 typedef basic_regex<char, regex_traits<char> > regex;
                                                ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:582:7: error: ‘regex_search’ is not a member of ‘std’
  if (!std::regex_search(sJavascriptData, _Matches, _reSearch)) {
       ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:582:52: error: ‘_reSearch’ was not declared in this scope
  if (!std::regex_search(sJavascriptData, _Matches, _reSearch)) {
                                                    ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp: In member function ‘bool CTado::GetTadoApiEnvironment(std::string)’:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:2: error: ‘match_results’ is not a member of ‘std’
  std::match_results<std::string::const_iterator> _Matches;
  ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:2: note: suggested alternative:
In file included from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/read_until.hpp:26:0,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio.hpp:91,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPClient.h:3,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/../tcpserver/TCPServer.h:4,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/../main/mainworker.h:11,
                 from /home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:21:
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/install//usr/local/domoticz/include/boost/asio/detail/regex_fwd.hpp:29:7: note:   ‘boost::match_results’
 class match_results;
       ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:48: error: expected primary-expression before ‘>’ token
  std::match_results<std::string::const_iterator> _Matches;
                                                ^
/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268/hardware/Tado.cpp:607:50: error: ‘_Matches’ was not declared in this scope
  std::match_results<std::string::const_iterator> _Matches;
                                                  ^
make[5]: *** [CMakeFiles/domoticz.dir/hardware/Tado.cpp.o] Error 1
make[5]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268'
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz/work-x86-6.1/domoticz-r9268'
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory `/home/dahl/spksrc-master/cross/domoticz'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/home/dahl/spksrc-master/spk/domoticz'
make: [arch-x86] Error 2 (ignored)

**Comment by emontnemery** [comment]
@Jumbotroll it's due to using c+11 feature std::regex, some compilers allow this even though c+11 is not enabled by Domoticz build environment. I opened #2334 to change to boost:regex instead.

**Comment by dotms** [comment]
@Jumbotroll Thanks for reporting. 
@emontnemery Thanks for the fix.

**Comment by Jumbotroll** [comment]
Trying to cross compile with the changes from @dotms 

CMake Error at /usr/local/share/cmake-3.2/Modules/FindBoost.cmake:1182 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.64.0

  Boost include path:
  /home/dahl/spksrc-master/spk/domoticz/work-armadaxp-6.1/install/usr/local/domoticz/include


  Could not find the following static Boost libraries:

          boost_regex

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:541 (find_package)

**Comment by dotms** [comment]
@Jumbotroll I don't know if I can be much of help in deciphering these environment-specific errors. The only thing that comes to mind is checking if the boost library was compiled/installed/set up using the `--with-regex` parameter.

**Comment by emontnemery** [comment]
You need to install/apt-get boost-regex for your cross environment

**Comment by Jumbotroll** [comment]
@dotms Solved with the right settings (regex) in cross compiler for boost 😃

**Comment by dotms** [comment]
@Jumbotroll Happy to hear that. For future reference, can you describe what you changed in your cross compile settings? I managed to reproduce this error using gcc 4.8.5 on x86_64 platform. When using gcc 6.3.0 it compiles fine.

**Comment by Jumbotroll** [comment]
@dotms 
I partly use the spksrc framework from synocommunity and my own script to compile for Synology NASes and use many different versions of toolchains. What happened was that the spksrc framework did not include regex in the compilation, so this had to be added to cross domoticz Makefile.

BOOST_LIBRARIES = system thread date_time **regex**

**Pull request merged**
