### PR TITLE
JSON: Added PlanID and PlanIDs to output for Groups/Scenes

### PR DESCRIPTION
**Pull request by EddyK69**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Sorry to tell, but this goes wrong when you do not have scenes in a plan, and request with planid=0

```
                        //result = m_sql.safe_query(
                        //  "SELECT A.ID, A.Name, A.nValue, A.LastUpdate, A.Favorite, A.SceneType,"
                        //  " A.Protected, B.XOffset, B.YOffset, B.PlanID, A.Description"
                        //  " FROM Scenes as A, DeviceToPlansMap as B, Plans as C"
                        //  " WHERE (C.ID==B.PlanID) AND (B.DeviceRowID==a.ID) AND (B.DevSceneType==1)"
                        //  " ORDER BY %s",
                        //  szOrderBy);
``

changing back to:

```

```
                    result = m_sql.safe_query(
                        "SELECT A.ID, A.Name, A.nValue, A.LastUpdate, A.Favorite, A.SceneType,"
                        " A.Protected, 0 as XOffset, 0 as YOffset, 0 as PlanID, A.Description"
                        " FROM Scenes as A"
                        " ORDER BY %s",
                        szOrderBy);
```

```
```

**Comment by EddyK69** [comment]
o ok, i will try to fix this in and do a new PR

**Comment by gizmocuz** [comment]
there are some forum threads about this issue

**Comment by EddyK69** [comment]
yep, i noticed ;(

**Comment by gizmocuz** [comment]
when a scene is in a plan/floor, i think it still works ?
The problem was when it was not in a plan (as per default)

**Comment by EddyK69** [comment]
Applied fix in PR #357

**Pull request merged**
