### PR TITLE
Fixed #4072  without breaking single rocker

### LINKED ISSUE #4072: Xiaomi Aqara WXKG02LM bug with 2020.1
Hi
I used Version: 2020.1 (build 11930) Build Hash: 423448b7e Compile Date: 2020-04-10 06:53:38 dzVents Version: 3.0.2 Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
It's Beta distribution.

I have a problem with the WXKG02LM double aqara buttons since the last Domoticz updates 
normally I had this:
Left button click = 10
Right button click = 20
Button L and R click = 30
Left button double click = 40
Right button double click = 50
L and R button double click = 60
Left button long click = 70
Right button long click = 80
L and R button long click = 90

Now I have this:
Left button click = 10
Right button click = 20
Button L and D click = 30
Left button double click = **20** (Normally 40)
Right button double click = 50
L and R button double click = 60
Left button long click = **30**(Normally 70)
Right button long click = 80
L and R button long click = 90

(Text physical action on the button = return level of the button in Domoticz)

I opened a post on easydomoticz.com and I am not the only one with this problem, you would make a lot of joy to all users of aqara with domoticz.

By that Domoticz is really cool, good job.
Thanks

### PR DESCRIPTION
**Pull request by Huupke**
Hotfix for #4072

### CODE REVIEW

**Comment by rwaaren** [comment]
Please change this PR to point the development branch. 
I don't know for 100% but my understanding is that @gizmocuz does not allow hotfixes to the master branch so all commits / PR's should be applied to development

**Comment by gizmocuz** [comment]
Sorry, No we do not accept PR against the master branch, you need to make it against the 'default' branch (development)

**Comment by gizmocuz** [comment]
Not sure what happened, when you press 'Create new Pull Request' everything is filled in correctly by default
I created a new PR against the dev branch

**Comment by Huupke** [comment]
I know, I made one PR for master and one for development. This one was for master.
I think the #4074 is now redundant but still slightly different. You can abort that one.

**Pull request closed without merging**
