### PR TITLE
Implemented: Extended schedules for SetPoints

### PR DESCRIPTION
**Pull request by EddyK69**
**Added extended schedules for SetPoints:**
- Odd day numbers
- Even day numbers
- Odd week numbers
- Even week numbers
- Monthly (like: every day 5 of month)
- Monthly (weekday) (like: every second sunday of month)
- Yearly (like: every december 5)
- Yearly (weekday) (like: every third tuesday in september)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Question, why another web implementation to get the timerlist of the setpoints ?
This function already exists

json.htm?type=setpointtimers&idx=xxxx

Could this be used?

**Comment by EddyK69** [comment]
No, this ones shows **all** the setpointtimers just like the existing gettimerlist & getscenetimerlist.

**Comment by gizmocuz** [comment]
Where/When is this used?
If it is for debugging, it would be better to extern the RType_Schedules function ?

**Comment by EddyK69** [comment]
It is used in custom templates to show an overview of all the timer-schedules (ligthts/scenes/setpoints).
I will revert the getsetpointtimerlist method in this PR, and will rethink your suggestion on using the RType_Schedules function.

**Comment by gizmocuz** [comment]
I think it is best to use the RType_Schedules for this, if you also made a command like this for lights/scenes, it would be better to use the above command as well

**Comment by EddyK69** [comment]
The only problem is, that the RType_Schedules doesn't show the disabled schedules; in the existing gettimerlist & getscenetimerlist i get an overview of **all** schedules, both _**enabled & disabled**_ :)
So i would like to keep those and would like to add one for the setpoints as well...

**Comment by gizmocuz** [comment]
Hmmm why you want disabled timers ?

**Pull request merged**
