### PR TITLE
Update XiaomiHardware.h

### PR DESCRIPTION
**Pull request by EvgenaNet**
Adding new switch Aqara D1: https://aliexpress.ru/af/QBKG26LM.html

### CODE REVIEW

**Comment by gizmocuz** [comment]
@EvgenaNet , thank you for the PR.
Could you move all defines from the header to the top of the c++ file (underneath the last includes)
Do we miss some changes in the c++ file ?

**Comment by EvgenaNet** [comment]
> Could you move all defines from the header to the top of the c++ file (underneath the last includes)
> Do we miss some changes in the c++ file ?

Don't understood question... We just adding one line to the code.

**Comment by gizmocuz** [comment]
Okey Now I understand...
In the Visual Studio project this header file is not included in the project and therefor I have not noticed this
Could you put everything from this header file at the top of XiaomiGateway.cpp and remove the include, and delete this header file ?

**Comment by EvgenaNet** [comment]
> Okey Now I understand...
> In the Visual Studio project this header file is not included in the project and therefor I have not noticed this
> Could you put everything from this header file at the top of XiaomiGateway.cpp and remove the include, and delete this header file ?

You want to move content of file XiaomiHardware.h to file XiaomiGateway.cpp and then delete file XiaomiHardware.h? Is it right?

**Comment by gizmocuz** [comment]
Yes please, if you could do that, that would be great. Otherwise I will accept your two PR's and will do this

**Comment by EvgenaNet** [comment]
> Yes please, if you could do that, that would be great. Otherwise I will accept your two PR's and will do this

Please, check it: https://github.com/domoticz/domoticz/pull/4514

**Pull request closed without merging**
