### PR TITLE
Changes for new IHC hardware, using Serial/RS485 protocol

### PR DESCRIPTION
**Pull request by pilfos**
This new hardware plugin is for the IHC home automation system, originally from Lauritz Knudsen (LK), now owned by Schneider Electric.

This plugin is based in the Serial/RS485 protocol used by the first version of the IHC controller. Newer versions of the IHC controller uses a SOAP protocol (OpenHAB has an implementation this SOAP version of the IHC protocol), but in my case, I have a re-branded version of the first IHC version, for the Spanish market, known as "Simon VIS", and this is why I wanted to build this plug-in for Domoticz.

https://en.wikipedia.org/wiki/Intelligent_Home_Control

### CODE REVIEW

**Comment by gizmocuz** [comment]
Hi, thanks for your hard and great work !
Does this mean it is only for the spanish market then ? that would be not so great for the rest of the world.
Your device does not speak soap ?
Could you add links to the hardware in the .cpp file ?

Your logging of On/Off is a bit over the top, and is also done by domoticz:
_log.Log(LOG_STATUS, "ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON ON");

You also need to include the .cpp file in CMakeList.xt

Did you try to compile under linux/raspberry as well ?

**Comment by pilfos** [comment]
Hi, 

No, this code should be compatible with all the IHC devices that can speak with Serial/RS485, so mainly people from Denmark, but also people from other countries like Finland, UK, Spain, Portugal can take advantage of it. I'll try to contact people from a Danish forum to see if they can test it.

I have the first version of the IHC controller that only supports Serial/RS485 protocol.

About the logging, yes, I'll clean the code a bit to remove those "small" logs :-), add the links, and yes, I forgot to add the change to CMakeList.txt. 

Now, this plugin it's working in my Windows10 laptop, but my intention is to have Domoticz running in a Rasp, and once I have a new Raspberry 3,  I can compile it. I see in "travis ci" that the linux version is not compiling. Which linux version and config should I use to try to compile in the same conditions as the "travis ci" job?

**Comment by pilfos** [comment]
Abut the linux version, I can see it in the "system info" of the job:

https://travis-ci.org/domoticz/domoticz/jobs/178135262

**Comment by pilfos** [comment]
Hi,

I'm trying to compile under Ubuntu 14.04 LTS, and GCC 4.6, but I'm getting another different errors that the travis linux job:

what can I check?

In the other hand, I can see that the Xcode job is compiling fine.


/home/pilfos/git/domoticz/main/mainworker.cpp:10309:27: error: ‘CIHCSerial::ihcCmd_t’ is not a class or namespace
       OnOff = CIHCSerial::ihcCmd_t::OFF;
                           ^
/home/pilfos/git/domoticz/main/mainworker.cpp:10312:27: error: ‘CIHCSerial::ihcCmd_t’ is not a class or namespace
       OnOff = CIHCSerial::ihcCmd_t::ON;
                           ^
make[2]: *** [CMakeFiles/domoticz.dir/main/mainworker.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
make: *** [all] Error 2

**Comment by gizmocuz** [comment]
Maybe it's best to create a python/bash script for this, as there are not many people using this

**Comment by pilfos** [comment]
how? could you give me more details or where I can see some examples?

**Pull request closed without merging**
