### PR TITLE
Proxycereal

### PR DESCRIPTION
**Pull request by rkluwen**
Finally ready. It took some time to hunt an ssl bug that only appeared on some platforms, i.e. hard to debug.

### CODE REVIEW

**Comment by rkluwen** [comment]
This pull request contains an update AsyncTCP client with lots of fixes.
Also MyDomoticz is being communicatied with by means of "cereal" packed structures and now makes use ot the AsyncTCP client class at the same time.

**Comment by gizmocuz** [comment]
!! THANKS !! for your work again !!! I know this was a lot of work and testing !!!
Question, in the commited files, the last file can be deleted ? (if you click here on github on "Files Changed" you can also press the delete button)

**Comment by gizmocuz** [comment]
Thanks!!

**Comment by TheReptile** [comment]
@rkluwen @gizmocuz This PR seems to break the latest beta (4.10525), see the following topics in the forum:

https://www.domoticz.com/forum/viewtopic.php?f=6&t=27134
https://www.domoticz.com/forum/viewtopic.php?f=6&t=27146
https://www.domoticz.com/forum/viewtopic.php?f=6&t=27151

And the related issue here: https://github.com/domoticz/domoticz/issues/3071

All crashdumps contain boost::asio related lines.

**Comment by gizmocuz** [comment]
@TheReptile , please continue in #3071

**Pull request merged**
