### PR TITLE
Update VisualCrossing.cpp

### PR DESCRIPTION
**Pull request by Olifant1990**
Added used URL to get more info why it is failing on win10 with error "Bad API Request:Invalid location parameter value"

https://github.com/domoticz/domoticz/issues/6176

### CODE REVIEW

**Comment by gizmocuz** [comment]
Sorry, there is a hardcoded number in your PR (location)
And as there is only one call, you know the complete URL i suppose?

**Comment by Olifant1990** [comment]
Whoops, fixed!
Yes, I should know the URL, but Windows 10 is making it a bit different somewhere I guess...

**Comment by gizmocuz** [comment]
I don't think it is wise to log the complete url/api key.
Everyone can read the log if it is written to disk, or via the GUI
So you can add a deeper log message via DEBUG_HARDWARE if you wish, but as mentioned, you already know the complete URL, it is only one URL, so it seems not needed to log this?

**Comment by Olifant1990** [comment]
Yeah right again, still trying to get a finger on the problem xD.
Indeed I want to know what my PC is making of that URL, but not wise to do this for everyone in the log sorry!
Will have another look on how to debug this further

**Comment by gizmocuz** [comment]
Hope you will find the issue! Thanks for looking!

**Pull request closed without merging**
