### PR TITLE
Update domoticzdevices.js - fix dimmer switch on Floorplan

### PR DESCRIPTION
**Pull request by martin-g-it**
Fix dimmer switch on Floorplan

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could you display here how it looks with your patch?

Here, using a dimmer on a floorplan without your patch it looks like:

image

Which seems OK

The popup looks like:
image

**Comment by martin-g-it** [comment]
Thats because it has the **default** Icon I guess... try it with a custom one.

**Comment by martin-g-it** [comment]
Hmm, the P1 meter (with your setting on smallStatus) is still looking odd once there is delivery:
image

**Comment by gizmocuz** [comment]
Gotha... Why is that last change on line 1540 needed in your PR?

**Comment by martin-g-it** [comment]
To show the status/value of a Custom sensor on the popup when you hover over it.

Type = General, SubType  = Custom Sensor

Before:
image

After:
image

**Comment by gizmocuz** [comment]
Ahh okey, because this PR is about "fix dimmer switch on Floorplan"

Thanks for the PR

**Pull request merged**
