### PR TITLE
Only require libudev if USE_STATIC_OPENZWAVE is set

### PR DESCRIPTION
**Pull request by dwmw2**
When we have a dynamic libopenzwave.so, we don't need to explicitly link
against libudev — and *shouldn't* link against libudev, because some
systems (like OpenWRT) don't have it and build OpenZWave not to use it.

It's only needed when we're linking against a static libopenzwave.a,
which doesn't encode the other libraries that it depends on. (Actually
this *ought* to work too via pkg-config but OpenZWave doesn't correctly
put them into its Libs.private, and we support building against OpenZWave
from its build dir without using pkg-config anyway.)

### CODE REVIEW

**Comment by dwmw2** [comment]
For ease of review, here's what the patch looks like with `-w` to ignore indentation:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -638,7 +638,8 @@ IF(OpenZWave)
   target_link_libraries(domoticz ${OpenZWave})
   include_directories(${CMAKE_SOURCE_DIR}/hardware/openzwave)
   add_definitions(-DWITH_OPENZWAVE)
-  # open-zwave needs libudev
+  # open-zwave needs libudev if statically linked
+  IF(USE_STATIC_OPENZWAVE)
     IF(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
       set(IOKIT_LIBRARY "-framework IOKit -framework CoreFoundation" CACHE FILEPATH "IOKit framework" FORCE)
       target_link_libraries(domoticz ${IOKIT_LIBRARY})
@@ -671,6 +672,7 @@ IF(OpenZWave)
         ENDIF(UDEV)
       ENDIF(UDEV)
     ENDIF()
+  ENDIF(USE_STATIC_OPENZWAVE)
 ELSE()
   MESSAGE(STATUS "==== OpenZWave not found, support disabled!")
 ENDIF(OpenZWave)

```

**Comment by gizmocuz** [comment]
Those build systems use a patch, like we use for the Synology at the moment.
I was working on a PR for openzwave to make it possible to disable HID support (udev)

https://github.com/OpenZWave/open-zwave/issues/1316

But it seems i totally forgot about that ! Sorry, maybe we could team up to submit a PR ? I remember i was struggling with the make files

**Comment by dwmw2** [comment]
Yeah, fixing openzwave seems simple enough. I'll do a PR later. In the meantime we're going to need this on the Domoticz side too (and maybe later we can drop the explicit linking of udev completely, even for the static linking).

**Comment by dwmw2** [comment]
https://github.com/OpenZWave/open-zwave/pull/1516

**Comment by gizmocuz** [comment]
Thanks for this ! Hope it gets accepted, that will safe a lot of people some patching work!

**Comment by dwmw2** [comment]
NP. We need this PR in Domoticz either way though; please could you merge it?

Thanks.

**Comment by gizmocuz** [comment]
Maybe it is better to wait a bit , maybe the PR in openzwave gets merged and we need another patch in the make file as we do not have to depend on udev

**Comment by dwmw2** [comment]
Surely it's not a problem to stop adding `-ludev` for the dynamic builds today, and then potentially rip it out for the static builds too, later?

In fact, maybe we can already remove it completely? We only ever need to add `-ludev` if linking against a static `libopenzwave.a` which *does* include the HID support. Did you say that the Domoticz builds with a static OpenZWave were already building that without HID support anyway?

**Comment by gizmocuz** [comment]
no no ... only the Synology builds as far as i know.
Domoticz is building OZW (dev, with some additional PR patches) 'as-is', so also using udev

**Comment by dwmw2** [comment]
OK, not yet for the static libopenzwave then. But it would be nice if we could merge this part to fix dynamic linking for those who are doing distro packages of Domoticz, so they don't all have to apply the same patch. There's no real harm in that, is there?

**Comment by gizmocuz** [comment]
Nope, thanks ;) but we shall not forget to remove it if the PR is accepted on OZW

**Comment by sweetpants** [comment]
This gives a bunch of errors during linking
[ 20%] Linking CXX executable domoticz
/home/harrys/MyProjects/Cpp/Domoticz/open-zwave-read-only/libopenzwave.a(hid.o): In function `hid_enumerate':
hid.c:(.text+0x22e): undefined reference to `udev_new'
hid.c:(.text+0x242): undefined reference to `udev_enumerate_new'
hid.c:(.text+0x259): undefined reference to `udev_enumerate_add_match_subsystem'
hid.c:(.text+0x261): undefined reference to `udev_enumerate_scan_devices'
hid.c:(.text+0x269): undefined reference to `udev_enumerate_get_list_entry'
hid.c:(.text+0x2c6): undefined reference to `udev_list_entry_get_name'
hid.c:(.text+0x2d1): undefined reference to `udev_device_new_from_syspath'
hid.c:(.text+0x2dc): undefined reference to `udev_device_get_devnode'
hid.c:(.text+0x2f0): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0x304): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0x368): undefined reference to `udev_device_unref'
hid.c:(.text+0x370): undefined reference to `udev_list_entry_get_next'
hid.c:(.text+0x386): undefined reference to `udev_enumerate_unref'
hid.c:(.text+0x38e): undefined reference to `udev_unref'
hid.c:(.text+0x56a): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0x588): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0x607): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0x682): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0x6b5): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0x6d2): undefined reference to `udev_device_get_sysattr_value'
/home/harrys/MyProjects/Cpp/Domoticz/open-zwave-read-only/libopenzwave.a(hid.o): In function `hid_get_manufacturer_string':
hid.c:(.text+0xd7e): undefined reference to `udev_new'
hid.c:(.text+0xdae): undefined reference to `udev_device_new_from_devnum'
hid.c:(.text+0xdc7): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0xddb): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0xe46): undefined reference to `udev_device_unref'
hid.c:(.text+0xe4e): undefined reference to `udev_unref'
hid.c:(.text+0xe92): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0xea9): undefined reference to `udev_device_get_sysattr_value'
/home/harrys/MyProjects/Cpp/Domoticz/open-zwave-read-only/libopenzwave.a(hid.o): In function `hid_get_product_string':
hid.c:(.text+0xf3e): undefined reference to `udev_new'
hid.c:(.text+0xf6e): undefined reference to `udev_device_new_from_devnum'
hid.c:(.text+0xf87): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0xf9b): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0x100e): undefined reference to `udev_device_unref'
hid.c:(.text+0x1016): undefined reference to `udev_unref'
hid.c:(.text+0x1052): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0x106a): undefined reference to `udev_device_get_sysattr_value'
/home/harrys/MyProjects/Cpp/Domoticz/open-zwave-read-only/libopenzwave.a(hid.o): In function `hid_get_serial_number_string':
hid.c:(.text+0x10de): undefined reference to `udev_new'
hid.c:(.text+0x110e): undefined reference to `udev_device_new_from_devnum'
hid.c:(.text+0x1127): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0x113b): undefined reference to `udev_device_get_sysattr_value'
hid.c:(.text+0x11ae): undefined reference to `udev_device_unref'
hid.c:(.text+0x11b6): undefined reference to `udev_unref'
hid.c:(.text+0x11f2): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
hid.c:(.text+0x120a): undefined reference to `udev_device_get_sysattr_value'
collect2: error: ld returned 1 exit status
CMakeFiles/domoticz.dir/build.make:6089: recipe for target 'domoticz' failed
make[2]: *** [domoticz] Error 1
CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gizmocuz** [comment]
Seems udev is not linked after building...

**Comment by dwmw2** [comment]
Hm... that was supposed to still be using udev for the static build.

@sweetpants what environment is this and what definitions do you pass to cmake? Did you set `-DUSE_STATIC_OPENZWAVE`?

**Comment by dwmw2** [comment]
I'll attempt a local static build and check...

**Comment by gizmocuz** [comment]
@sweetpants : No issue on my build systems (multiple) did not touch a thing

**Comment by gizmocuz** [comment]
did you specify use -dUSE_STATIC_OPENZWAVE=NO perhaps ?

**Comment by sweetpants** [comment]
yes i did, compiling again without

**Comment by gizmocuz** [comment]
@sweetpants , okey, perhaps you did build openzwave yourself before ? could you remove the openzwave build folder, in the domoticz build folder issue
make clean
and also remove the CMakeCache.txt and CMakeFiles folder and build again ?

**Comment by sweetpants** [comment]
Ok, i try

**Comment by gizmocuz** [comment]
@sweetpants , make sure the dynamic openzwave library exists on your system else it is build without zwave support

**Comment by dwmw2** [comment]
It shouldn't be looking at `open-zwave-read-only/libopenzwave.a` if you set `-DUSE_STATIC_OPENZWAVE=NO`

**Comment by sweetpants** [comment]
@dwmw2, well it still did. That was my idea too, but when i removed the folder a few weeks ago it still would not compile/link without this folder being present.

In fact I don't use Zwave anymore (too expensive) so it's fine for me if it builds without Zwave support anyway. I'm using:

cmake -DCMAKE_BUILD_TYPE="Release" -DUSE_STATIC_BOOST=no -DINCLUDE_SPI=no -DUSE_STATIC_OPENZWAVE=no -DUSE_OPENSSL_STATIC=no -DUSE_STATIC_LIBSTDCXX=no .

Removed the complete openzwave folder, removed CMakeCache.txt and CMakeFiles folder and now it compiles/links ok, thanks

**Comment by dwmw2** [comment]
Right. I managed to reproduce this here, and I think it's just that the `OpenZWave` setting is cached, so when you switch to `-DUSE_STATIC_OPENZWAVE=no` it doesn't force it to go and find the library again.

**Comment by dwmw2** [comment]
Hm, testing with dynamic libopenzwave on Fedora shows a completely separate issue. We seem to have a bunch of the openzwave headers present in the Domoticz source tree and we use those *instead* of the ones that match the system library. And since Fedora for some reason has a snapshot of libopenzwave 1.5, it ends up failing to link because of the header mismatch.

Is there a reason those headers are copied into the Domoticz source tree? Shouldn't they be used from the libopenzwave directory? Either `../open-zwave-read-only/cpp/src/` or whatever `pkg-config` gives us in `CFLAGS`?

**Comment by dwmw2** [comment]
I'm willing to blame Fedora 28 for having an unreleased version of the library for now. But the day is coming when that isn't just a _Don't Do That Then_.

**Comment by gizmocuz** [comment]
We also use the beta branch

**Comment by dwmw2** [comment]
How do you build against the Dev branch of openzwave? Don't the v1.4 headers in Domoticz's `hardware/openzwave` directory cause it to fail to build? Or am I missing a trick that makes it use the updated headers?

**Comment by gizmocuz** [comment]
@dwmw2 , see the travis/appveyor scripts

**Comment by dwmw2** [comment]
Ah, that's using the head of the `master` branch. But the fun stuff for OpenZWave 1.5 seems to be on the `Dev` branch. They're using branches the wrong _(or at least unconventional)_ way round.

So you're effectively using the tip of the 1.4.x stable branch, not the 1.5.x development branch.

**Comment by gizmocuz** [comment]
Yes thats correct with a important patch for scene controllers

**Pull request merged**
