### PR TITLE
Added Nest Heating/Cooling logging in a "switch" device.

### PR DESCRIPTION
**Pull request by Delaroyas**
Simple implementation for Nest Heating/Cooling logging in a "switch" device. 
Supports only basic heating/cooling.
Tested on a minimal linux compilation (no OpenZwave) with a real heating thermostat, and a  heating/cooling virtual thermostat.

### CODE REVIEW

**Comment by Delaroyas** [comment]
Mmm it compiled on my side... I'll investigate..

**Comment by gizmocuz** [comment]
That is strange, because 'and' is not c++, it should be &&

**Comment by Delaroyas** [comment]
That's what I figured, but it seems my compiler (gcc) didn't mind...

Anyway, let's try with actual c++ this time.

**Comment by gizmocuz** [comment]
Not sure i should trust your coding skills now....

**Comment by Delaroyas** [comment]
I dont blame you. I havent coded in c++ for a long time. 
Between matlab, php, javascript, mysql and lua keywords and syntax gets mixup sometimes.
But I did compile and test the code under 64bit linux before submitting the first time.
Anyway, you can always revise my code before accepting.

**Comment by Delaroyas** [comment]
FYI:  C++ defines keywords to act as aliases for a number of operators: and (&&), bitand (&), and_eq (&=), or (||), bitor (|), or_eq (|=), xor (^), xor_eq (^=), not (!), not_eq (!=), and compl (~). For compatibility with C, C++ provides the header ciso646.  The latter file has no effect, being empty. Notwithstanding some compilers, such as Microsoft Visual C++, do require the header to be included in order to use these identifiers.
https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#C.2B.2B_operator_synonyms
https://en.wikipedia.org/w/index.php?title=Ciso646

**Comment by Delaroyas** [comment]
Merged changes from domoticz.
Rebuild and tested locally, everything is sill working as expected.

**Comment by gizmocuz** [comment]
Thanks !

**Pull request merged**
