### PR TITLE
EUROtronic spirit radiator valve implemetation

### PR DESCRIPTION
**Pull request by TacticalLeader**
I added EUROtronic Spirit radiator valve to OZW. After you added the new valve to your zwave network, you should change the update limit of the "Measured Temperature report" from factory default 5 to 1 to make the new temp sensor appear.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this. But you have to submit this to the openzwave team. We sync from time-to-time the configuration files from their repository

**Comment by TacticalLeader** [comment]
Ok, then I'll submit to openzwave repo.

**Comment by gizmocuz** [comment]
Thanks!, I will close this, but please let us know if it's merged...

**Comment by TacticalLeader** [comment]
I will, but merging to openzwave is a bit slow nowadays..

**Pull request closed without merging**
