### PR TITLE
Update eHouse to new version of Domoticz

### PR DESCRIPTION
**Pull request by ehousepro**
- device discovery failure after code cleanup
- unlimited selectable fields (programs, scenes, zones)
- suggested naming prefix m_

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR, i reverted the changes in .gitignore and the visual studio project files.
If you use the visual studio git toolbar or tortuisesvn, you can uncheck those when doing a commit
Waiting for our build system to complete now before merging

**Comment by ehousepro** [comment]
Hi, It's only modified eHouse files I think you can replace them safely. 
Please be careful while cleaning our files on your side because some of your modification stop its work (DB updates). It worked under first issue of integration and than stop somewhere in this year .

**Comment by gizmocuz** [comment]
I can't see anything related in this PR which fixes a possible cleanup error, but i always try to be carefull ;)
And specifically this change (unwanted git ignore and visual studio version changes), can't do any harm.

**Comment by gizmocuz** [comment]
Thanks!

**Comment by ehousepro** [comment]
thanks for you!

If you supply email for communication I can give you more specific data (I send it to global email i....@domoticz.*) what was changed and stop working.

Most important things :
please look @ line 271 eHouseTCP.cpp
InsertDevice parameters seemes to be ok but don't set used field to 1 !!!

please look @ line 285 eHouseTCP.cpp
It don't set plan ID at once we must do workaround.

I'll try to test after weekend.

**Comment by gizmocuz** [comment]
Thanks! Okey, and the email address is mine

**Pull request merged**
