### PR TITLE
Review all supported EEP according to current specifications

### PR DESCRIPTION
**Pull request by efdeb**
Continuing my work, I reviewed and checked all supported ESP2/ESP3 EEP according to current specification : EnOcean Equipment Profiles (EEP) 2.6.8 - Dec 31, 2017 or from EnOcean website when newer/missing.

Because I do not have all devices to test, I also implemented DEBUG test cases for all those EEP. They are based on EnOcean EEP test files XX-XX-XX_test.xml taken from EnOcean website. They only aim to verify ESP3 telegrams data is correctly parsed, so, please note they do not check how data is converted/transmitted to Domotics.

Of course, testers are welcome.

**EnOceanESP2 / EnOceanESP3**

1/ Review all existing ESP2/ESP3 devices EEP, according to current specifications and add DEBUG test cases

1BS
D5-00-01, Single Input Contact

4BS
A5-02-01..30, Temperature sensor
A5-04-01..03, Temperature and Humidity Sensor
A5-06-01, Light Sensor
A5-07-01, Occupancy sensor with optional Supply voltage monitor
A5-07-02, Occupancy sensor with Supply voltage monitor
A5-07-03, Occupancy sensor with Supply voltage monitor and 10-bit illumination measurement
A5-09-04, CO2 Gas Sensor with Temp and Humidity
A5-10-01..0D, RoomOperatingPanel
A5-12-00..03, Automated Meter Reading

RPS (ESP3 only)
F6-01-01, Push button
F6-02-01, 2 Rocker (Light and blind control, Application style 1)
F6-02-02, 2 Rocker (Light and blind control, Application style 2)
F6-05-00, Wind speed threshold detector
F6-05-01, Liquid Leakage Sensor (mechanic harvester)
F6-05-02, Smoke detector

VLD (ESP3 only)
D2-01-XX, Electronic Switches and Dimmers with Local Control
D2-03-0A, Push Button, Single Button

2/ Add support according to current specifications and add DEBUG test cases

4BS (ESP2/ESP3)
A5-04-04, Temperature and Humidity Sensor

VLD (ESP3 only)
D2-14-30, Sensor for Smoke, Air quality, Hygrothermal comfort, Temperature and Humidity
(Fix issue domoticz#3036 opened 10/02/19)
DONE : Smoke alarm, Temperature, Humidity & Battery level
TODO : Hygrothermal Comfort Index, Indoor Air Quality Analysis, Maintenance condition

**EnOceanEEP**

Add two missing EEP :
D2-01-17, SwitchesDimmers, Type 0x17
D2-06-11, Intrusion detection system for windows with tilt detection and PIR sensitivity adjustment

**Cosmetics / code readability**

Review comments / log messages / indentation

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks! Let us know if this can be merged
Could you remove the SQLHelper.cpp changes as they are not part of this PR.
Not sure if we want this, there is also no need to display version numbers, it's just not possible to downgrade domoticz and use whatever database version number...
You can of course make a separate PR for this

**Comment by efdeb** [comment]
@gizmocuz

Hello,

I reverted SQLHelper.cpp changes, so you can merge this PR right now.

I am quite new to github, but once I open a PR, each and every change I push to my own Domoticz repository (forked from Domoticz/Domoticz) isl added to my PR. Maybe I forgot doing someting ?

Concerning SQLHelper.cpp changes : the purpose is only to make it clearer in the logs if a database is created or reused or upgraded from v1 to v2. This last case is not obvious otherwise as you may upgrade from an old Domoticz setup to the last and need that information to debug the changes made to the database. If not displayed, you need to 'SQLite3 edit' the database to get its version. I shall propose it in a separate PR, but of course it is up to you to decide if usefull ! ;^)

Thanks !

**Comment by gizmocuz** [comment]
Thank you again for this PR!

Yes I experience this issue also sometimes... I think this can be solved by creating a branch for each different PR

**Comment by waltervl** [comment]
@efdeb I see you are doing a very good job in implementing and enhancing the Enocean integration! Could you please update The wiki page https://www.domoticz.com/wiki/EnOcean as I think it is really outdated and Enocean user cannot find the proper instructions or cannot appreciate the extensive implementation. In the wiki page please make a separation in functionality in Stable and Beta release.
A Wiki account can be requested at gizmocuz on slack.

**Comment by efdeb** [comment]
hi @waltervl, @gizmocuz,
OK, I can do that.
A Wiki account can be requested at gizmocuz on slack. => is there an how-to for that somewhere ?
Thanks

**Comment by gizmocuz** [comment]
@efdeb , please send me a PM on the forum with your forum username ;)

**Comment by efdeb** [comment]
@gizmocuz, newbie on the forum, it seems I cannot send PM...
;^)
However, my username on the forum is efdeb
Thanks

**Comment by gizmocuz** [comment]
No worries. You should by now have received a email with a username/password for our wiki

**Comment by efdeb** [comment]
It's working for the wiki, many thanks.

Still interrested being able to join you on slack !
;^)

**Comment by gizmocuz** [comment]
https://join.slack.com/t/domoticz/shared_invite/zt-v59e0d7p-WyEFkNwAsIt2u1_FmI53zA

**Pull request merged**
