### PR TITLE
Have textfiles in VCS instead of gzipped versions

### PR DESCRIPTION
**Pull request by sjoerdmulder**
According to #552 all files are compressed at buildtime (and this makes sense). However some files in the repository where still compressed. This change gunzips them to allow better maintainablility

### CODE REVIEW

**Comment by gizmocuz** [comment]
217 changed files, can't be right ;)
From my current location i am not even able to look at the changes

The i18n files do NOT have to be unzipped, because we translate them at transifex online

If an HTML developer which to tweak/edit the html/javascript code, it should be not so difficult to unzip them and delete the .gz file right ?

**Comment by gaeljw** [comment]
I don't know the Domoticz build process very well but I agree it's not helping maintainability to have these HTML and JS files compressed because we don't have any history on these files.

**Comment by gizmocuz** [comment]
That will only be needed for the web(gui) part, not for the translations, you can see the versioning at the transifex website, and not for the html/javascript files, if there is a modification for lets say.... highcharts, that means, a new library has been used.
Also there is a very good reason for having these files compressed... we are also running on arm systems

**Comment by gaeljw** [comment]
Indeed, I only know about the web gui part in Domoticz. And as you said it should only be for proper domoticz code, not for external libraries nor for translations which are managed by transifex (by the way, is there any info about that somewhere ? how can we help translating ?).

Actually, this sums up to only 4 files : `www/js/domoticz*.js.gz`, everything else is either not compressed or an external library, right ?

**Comment by rkluwen** [comment]
Sure, info about the Domoticz Transifex project is here: https://www.transifex.com/domoticz/domoticz/dashboard/.

You can just sign up for free and join the project and start translating.

**Comment by sjoerdmulder** [comment]
Didn't know about the transifex, will revert the i18n files.

Still i believe all javascript should be uncompressed in the repository, and compressed during the build. Even better would be to introduce a tool like bower.io to manage the dependencies.

Currently there are a gazzilion dependencies just dropped (and zipped) in the libs folder, without knowing which file is actually used (because IDE's don't search in the binary files). If performance was really a concern focus should be on cleaning up these dependencies and removing unused ones.

But then again it's only a issue when refreshing the 'browser cache' feature (manifest) and then the transfering of the files might be taking a longer time. Otherwise they are all cached by the browsers and not refetched every request.

**Comment by sjoerdmulder** [comment]
Example of the importance: Search for the `copy_csv_xls_pdf` SWF (60KB flash file) in the project. It's not referenced anywhere in the project so save to remove?

Now search for the same file in the PR, you will see that it is used by the `dataTables.tableTools.min.js` file, since it's unzipped your editor will find it.

Actually the `dataTables.tableTools.min` contains the `ZeroClipboard 1.0.4` but there is also a separate `ZeroClipboard.js` so these are duplicate?

**Comment by gizmocuz** [comment]
Sure you can use "total commander" and search also in archives.. ? (or another app)

**Comment by ldrolez** [comment]
Yes at least having domoticz*.js.gz files uncompressed would make patching easier :)

**Pull request closed without merging**
