### PR TITLE
Feature/selector switch level action

### PR DESCRIPTION
**Pull request by gaudryc**
- add "Hide Off level" and "Selector Actions" to Selector editing form ;
- fix character encoding issue while saving level names containing characters with accent ;
- fix Selector style alignment.

### CODE REVIEW

**Comment by ghost** [comment]
Can you also add dimmer... that user can select mixed button and slider dimmer. With this config users can build device to control AV Reciver with setup  volume. Now i have create dimmer and have set lua script and can control volume and on off DENON.

**Comment by gaudryc** [comment]
Hi @gizmocuz !

Could you please add the following strings to language files :

"Hide Off level": "Hide Off level",
"Selector actions": "Selector actions",
"Edit level action": "Edit level action"

**Comment by ghost** [comment]
is any chance to add dimmer ?

**Comment by gizmocuz** [comment]
@gaudryc 
Sure no problem
Before i merge, what are you doing here?

if (dbversion < 92) {

Dropping the whole table, and recreate, .... something todo with the options field, but could you not change this with a normal query ?

**Comment by gaudryc** [comment]
It is needed to change the options field datatype. This procédure is documented in sqlite API. There is no other choice.

**Comment by gizmocuz** [comment]
Thanks again for the patch!

**Comment by ghost** [comment]
Hi
I update my Domoticz to 4088 and i dont see new function... Dont see hide Off and add action to other levels... Also not see tooltip for button edit, delete. Where is it ?

**Pull request merged**
