### PR TITLE
RFLINK MQTT gateway multi domoticz node sync become configurable

### LINKED ISSUE #5239: Domoticz sends SYNCID after RFLink string
Hi all,

I'm using the RFLink gateway MQTT of Domoticz 2022.1 together with the espRFLinkMQTT software on a Nodemcu.
Receiving 433Mhz sensors works great but switching a switch doesn't seem to work.

I used the mosquitto client to subscribe to rflink/out to see what Domoticz is sending when a switch was switched ON.
What I expected to see is for example: 10;NewKaku;1234567;1;ON;
What was sent by Domoticz is: 10;NewKaku;1234567;1;ON;SYNCID=65fdd29e;

When 10;NewKaku;1234567;1;ON;  is published to the rflink/out topic the switch switches to ON.
So it is definitely the SYNCID part that shouldn't be there. 

The RFLink doesn't respond to the string received because of the SYNCID=65fdd29e; part, so the switch is not switched to ON.

What is that SYNCID=65fdd29e; part doing there? Why is Domoticz sending it?
I use Domoticz in a docker pulled from docker hub from LinuxServer.io

Is there something wrong with my Domoticz docker or is espRFLinkMQTT missing something that should filter the SYNCID part?

Best regards

### PR DESCRIPTION
**Pull request by pagocs**
Based on this issue https://github.com/domoticz/domoticz/issues/5239 I made the snycid to be configurable. Thanks for this modification the Domoticz hardware is become compatible with this https://github.com/seb821/espRFLinkMQTT gateway also.

### CODE REVIEW

**Comment by kiddigital** [comment]
Thank you for the PR. Have a look at the comments.

Please rebase the PR and squash the merge commits, so only the real changes remain.

**Comment by pagocs** [comment]
> Thank you for the PR. Have a look at the comments.
> 
> Please rebase the PR and squash the merge commits, so only the real changes remain.

Sorry for the mistake.

**Comment by kiddigital** [comment]
> > Thank you for the PR. Have a look at the comments.
> 
> > 
> 
> > Please rebase the PR and squash the merge commits, so only the real changes remain.
> 
> 
> 
> Sorry for the mistake.

No problem.. it is not a mistake, it is just more clear in the gitlog 😁 And fine if it is more than one commit.

Please take a look at the code comments.

**Comment by gizmocuz** [comment]
Thank you for your PR!
Is it possible to have a second look at your indenting (code and html)

**Comment by acca84** [comment]
> Based on this issue #5239 I made the snycid to be configurable. Thanks for this modification the Domoticz hardware is become compatible with this https://github.com/seb821/espRFLinkMQTT gateway also.

Hello, i'm interested in this improvement, i'm using Seb821 gateway, but i dont know how to use this change (i'm using latest beta of domoticz)

**Comment by gizmocuz** [comment]
Thank you for this PR and time!

**Pull request merged**
