### PR TITLE
Set brightness percentage after switching hue light to on

### PR DESCRIPTION
**Pull request by arjanwaard**
Fixes issue https://github.com/domoticz/domoticz/issues/542

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the patch!

**Comment by gizmocuz** [comment]
We have some build errors

\hardware\PhilipsHue.cpp(392): error C2146: syntax error: missing ')' before identifier 'and' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(392): error C3861: 'and': identifier not found [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(392): error C2059: syntax error: ')' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(393): error C2146: syntax error: missing ';' before identifier 'cmd' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(498): error C2146: syntax error: missing ')' before identifier 'and' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(498): error C3861: 'and': identifier not found [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(498): error C2059: syntax error: ')' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
..\hardware\PhilipsHue.cpp(499): error C2146: syntax error: missing ';' before identifier 'cmd' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
  PiFace.cpp
  Pinger.cpp

**Comment by arjanwaard** [comment]
Should be fixed by https://github.com/arjanwaard/domoticz/commit/9aee25b3b90f6d563184de7b98c649e9c020ed77

**Comment by gizmocuz** [comment]
Perfect, thanks!

**Pull request merged**
