### PR TITLE
basic support for x509 sso

### PR DESCRIPTION
**Pull request by nayrnet**
I tested this and it works fine with no further implementation, and no interference with other auth mechanisms.

In Nginx I have the following config:

``` nginx
    # Domoticz
        location / {
        proxy_pass          http://localhost:8080/;
        proxy_set_header    Authorization $ssl_client_s_dn;
        proxy_hide_header   Authorization;
    }
```

it passes the Client Certificate DN to Domoticz in the auth header, Domoticz parses this DN and extracts a username (commonName) and password (emailAddress), then checks the user database for a match and signs them in.

At the same time nginx suppresses any Authorization headers coming from Domoticz requesting a password.

Ideally the password would not be verified for x509 users, so they can fall back onto a more secure password if they bypass the proxy.. however I am afraid of introducing security flaws so simple = better.

See Wiki for more details: http://www.domoticz.com/wiki/Secure_Nginx_Proxy_Setup
See Forums for my brain chatter: https://www.domoticz.com/forum/viewtopic.php?f=21&t=9799

### CODE REVIEW

**Comment by nayrnet** [comment]
ignore my initial message, i managed to get this operational through a better nginx configuration, no configuration is nessicary for Domoticz other than setting up users and enabling basic-auth

This method is preferred because you can fall back to basic auth without the x509-proxy, for example allowing json requests to come through on localhost without x509. The -nowwwpwd run flag works fine along with x509 if you lock your self out.

**Comment by gizmocuz** [comment]
Okey, so we do not this patch/pull request?

**Comment by nayrnet** [comment]
this is ready to go

**Comment by gizmocuz** [comment]
Your nginx implementation or this patch ?

**Comment by nayrnet** [comment]
This patch is good to be merged, it adds support via Nginx.. 

I had an issue originally and was looking for a bit of help, but I found the fix on the proxy side.. edited the original post.. you'll see a PM from me thats nonsencial.

**Comment by nayrnet** [comment]
I had an issue originally with the password prompt being displayed when Auth-Basic was configured, was looking for some help making a config option to bypass it..

in the end I found I could just block the header with nginx and the prompt would not display, the original submission was perfectly fine with a bit of additional configuration on the auth-proxy side.

**Pull request merged**
