### PR TITLE
dzVents version 3.0.0: system-events and custom-events

### PR DESCRIPTION
**Pull request by MrHobbes74**
- Add system-events triggers as option to the on = { ... } section. Scripts can now be triggered based on these system-events. Supported system-events:
`start, stop, manualBackupFinished, dailyBackupFinished, hourlyBackupFinished, monthlyBackupFinished,`
- Add custom-events triggers as option to the on = { ... } section. You can now send an event trigger to start subscribed dzVents scripts.
	customEvents can be triggered by:

```
	dzVents: domoticz.emitEvent(name, data ) command  (data = optional)
	JSON: json.htm?type=command&param=customevent&event=MyEvent&data=myData   
                   ( data = optional )
	MQTT: {"command" : "customevent", "event" : "MyEvent" , "data" : "myData" }  
                   ( data = opional )
```
- Add method  domoticz.emitEvent()
- Add attribute `mode` to Evohome controller
- Add option to dumpTable() and ([device][uservariable][scene][group].dump() to os file

```
========= domoticz V4.11xxx, dzVents V3.0.0 =======+========================== Tests ==============================+
  time  | test-script                              | expected | tests | result  | successful |  failed  | seconds  |
===================================================+===============================================================+
00:00:02  Device                                        1        113      OK            113         0      0.2660
00:00:02  Domoticz                                      1         71      OK             71         0      0.2676
00:00:02  EventHelpers                                  1         32      OK             32         0      0.2463
00:00:03  EventHelpersStorage                           1         50      OK             50         0      0.2376
00:00:03  HTTPResponse                                  1          6      OK              6         0      0.0134
00:00:03  Lodash                                        1        100      OK            100         0      0.1628
00:00:03  ScriptdzVentsDispatching                      1          2      OK              2         0      0.0671
00:00:03  TimedCommand                                  1         42      OK             42         0      0.0944
00:00:03  Time                                          3        340      OK            340         0      0.6534
00:00:04  Utils                                         1         25      OK             25         0      0.0439
00:00:04  Variable                                      1         15      OK             15         0      0.0324
00:00:04  ContactDoorLockInvertedSwitch                 3          2      OK              2         0      3.0666
00:00:08  DelayedVariableScene                          8          2      OK              2         0      7.0649
00:00:15  EventState                                   19          2      OK              2         0     18.0780
00:00:33  Integration                                  33        217      OK            217         0     28.6416
00:01:02  SelectorSwitch                               10          2      OK              2         0      9.2073
00:01:16  SystemAndCustomEvents                         1          7      OK              7         0      0.0351

Total tests: 1028
Mon 10 Feb 2020 11:16:13 AM CET; dzVents version 3.0.0 tested without erors after 00:01:16
```

### CODE REVIEW

**Comment by MrHobbes74** [comment]
Note: this PR is developed in close cooperation and together with @dannybloe and @rwaaren.

**Review by rwaaren — APPROVED** [review]
Added a new test module for this update. All existing and new features successfully tested against latest beta's.

**Review by dannybloe — APPROVED** [review]
All tested. Initial ground work was done by jvandenbroek and me and MrHobbes74 continued and refactored it from there.

**Comment by rwaaren** [comment]
Redid tests after replacing general pointer with JSON string and type remapping fix.
 
```
========= domoticz V4.11678, dzVents V3.0.0 =======+========================== Tests ==============================+
  time  | test-script                              | expected | tests | result  | successful |  failed  | seconds  |
===================================================+===============================================================+
00:00:02  Device                                        1        113      OK            113         0      0.2596
00:00:02  Domoticz                                      1         71      OK             71         0      0.2630
00:00:03  EventHelpers                                  1         32      OK             32         0      0.2498
00:00:03  EventHelpersStorage                           1         50      OK             50         0      0.2340
00:00:03  HTTPResponse                                  1          6      OK              6         0      0.0132
00:00:03  Lodash                                        1        100      OK            100         0      0.1479
00:00:03  ScriptdzVentsDispatching                      1          2      OK              2         0      0.0648
00:00:04  TimedCommand                                  1         42      OK             42         0      0.0914
00:00:04  Time                                          3        340      OK            340         0      0.6820
00:00:04  Utils                                         1         25      OK             25         0      0.0431
00:00:05  Variable                                      1         15      OK             15         0      0.0312
00:00:05  ContactDoorLockInvertedSwitch                 3          2      OK              2         0      3.0640
00:00:08  DelayedVariableScene                          8          2      OK              2         0      7.0695
00:00:15  EventState                                   19          2      OK              2         0     18.0789
00:00:33  Integration                                  33        217      OK            217         0     28.6125
00:01:02  SelectorSwitch                               10          2      OK              2         0      9.2276
00:01:16  SystemAndCustomEvents                         1          7      OK              7         0      0.0353


Total tests: 1028
Thu 13 Feb 2020 08:17:33 AM CET; dzVents version 3.0.0 tested without errors after 00:01:16

```

**Review by gizmocuz — APPROVED** [review]

**Pull request merged**
