### PR TITLE
Serial port in FreeBSD

### PR DESCRIPTION
**Pull request by dschoorisse**
In FreeBSD/FreeNAS serial devices are accessible under /dev/ttyU*

### CODE REVIEW

**Comment by gizmocuz** [comment]
Will be added in next svn commit, thanks for reporting!

**Comment by dschoorisse** [comment]
Not sure if I have to create a new pull request... but I have made some extra changes to the CMakeList.txt file.

When building on FreeBSD there should be no check if libudev is available, in FreeBSD OpenZWave relies on libiconv.

Before I made this change I pulled the latest version from the SVN repo (r2259).

This CMakeFile.txt works on FreeBSD, however it's not tested on any other OS/platform.

**Comment by gizmocuz** [comment]
Thanks, CMakeList patch included

**Comment by dschoorisse** [comment]
Thank you! A guide on installing on FreeNAS is coming up.

**Pull request closed without merging**
