### PR TITLE
MQTT capture scripts to facilitate AD debugging.

### PR DESCRIPTION
**Pull request by jvanderzande**
MQTT capture scripts to facilitate AD debugging.
Located in subdirectory hardware/mqtt_ad.
README.md included for usage options.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you!!

**Comment by mcmellow** [comment]
Downloaded this file to my PC and Uploaded it with WinSCP to my Raspberry Pi.
Checked this file to see what it does and get an error after the first run.

pi@mcmellow-pi:~/domoticz $ bash  mqtt_ad_record.sh "692E91"
mqtt_ad_record.sh: line 7: syntax error near unexpected token `newline'
mqtt_ad_record.sh: line 7: `<!DOCTYPE html>'

Did I missed something?

**Comment by jvanderzande** [comment]
> Downloaded this file to my PC and Uploaded it with WinSCP to my Raspberry Pi. Checked this file to see what it does and get an error after the first run.
> 
> pi@mcmellow-pi:~/domoticz $ bash mqtt_ad_record.sh "692E91" mqtt_ad_record.sh: line 7: syntax error near unexpected token `newline' mqtt_ad_record.sh: line 7: `'
> 
> Did I missed something?

Did you do an ALT+Click in CHROME on the RAW button to download the script or just a Windows GIT PULL and use that file?
The latter will give issues as WINDOWS uses CRLF as line endings where Debian(unix) needs LFs only for scripts to work.

**Comment by mcmellow** [comment]
In windows right click on the file name and the Save link as ..
I will try a RAW download

**Comment by jvanderzande** [comment]
> In windows right click on the file name and the Save link as 

Have you looked at its content at all as I guess you downloaded the HTML version?
Either way: Download the RAW version by going to : https://github.com/domoticz/domoticz/blob/development/hardware/mqtt_ad/mqtt_ad_record.sh
and Alt+Click the RAW button on the right hand side.

**Comment by mcmellow** [comment]
Thanks I did this. it looks more plain text now.  After issued the command I have the following output.

pi@mcmellow-pi:~/domoticz $ bash mqtt_ad_record.sh -s '692E91'
mqtt_ad_record.sh: line 32: $'\r': command not found
mqtt_ad_record.sh: line 37: $'\r': command not found
: invalid shell option name shopt: nocasematch
mqtt_ad_record.sh: line 40: $'\r': command not found
mqtt_ad_record.sh: line 54: syntax error near unexpected token `$'in\r''
'qtt_ad_record.sh: line 54: `    case "${flag}" in
pi@mcmellow-pi:~/domoticz $
 
This a copy of putty sesion, don't know why there is strike through

**Comment by mcmellow** [comment]
> @mcmellow Please mind your language.

Not aware of anything wrong language, please can you explain?

**Comment by jvanderzande** [comment]
Think this one I explained in my first post: You can't have CRLF (windows type) line endings.... did you check those whether they are there?

**Comment by jvanderzande** [comment]
> > @mcmellow Please mind your language.
> 
> Not aware of anything wrong language, please can you explain?

It a BOT...  so just think: What does that bot know? ;)

**Comment by mcmellow** [comment]
Changed the file to just LF line ends. It works OK now.  Only my mqtt uses a User/Password combination. How can I add this? This user is not a RPi user, just for mqtt

pi@mcmellow-pi:~/domoticz $ bash mqtt_ad_record.sh -s '692E91'
MQTT_IP: 127.0.0.1
MQTT_PORT: 1883
Recordtime: 600
Search For: '692E91'
Start Capture for 600 seconds of MQTT messages containing 692E91 to Console and file: 692E91.log
Connection Refused: not authorised.
Capture ended, check file: mqtt_ad_record_692E91.log

**Comment by jvanderzande** [comment]
> Changed the file to just LF line ends. It works OK now. Only my mqtt uses a User/Password combination. How can I add this? This user is not a RPi user, just for mqtt
> 
> pi@mcmellow-pi:~/domoticz $ bash mqtt_ad_record.sh -s '692E91' MQTT_IP: 127.0.0.1 MQTT_PORT: 1883 Recordtime: 600 Search For: '692E91' Start Capture for 600 seconds of MQTT messages containing 692E91 to Console and file: 692E91.log Connection Refused: not authorised. Capture ended, check file: mqtt_ad_record_692E91.log

Good one ...   will make a modification for that and post an new PR.
We can in the background test it first when you are ok with that....  
Contact me when you like to assist testing. :)

**Comment by mcmellow** [comment]
Done in Slack

**Pull request merged**
