### PR TITLE
OpenWebNet: bug fix and burglar alarm battery, network and maintenance status. 

### PR DESCRIPTION
**Pull request by Spugna85**
Fix wrong automatic creation of auxiliary device and update status of dry contact, introduced with the development of CEN PLUS commands.

'Unit' must be left free for the interface, so the alarm zone is used as the 'where' and not as 'interface' in UpdateAlarm function.
After this update, the alarm device will have a different ID.
Adding devices to the battery status, network status and alarm maintenance.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
Is it possible to check the compile warnings on our travis build system ?
https://travis-ci.org/domoticz/domoticz/jobs/208561512

like

/Users/travis/build/domoticz/domoticz/hardware/OpenWebNetTCP.cpp:365:27: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                            if(m_pStatusSocket = connectGwOwn(OPENWEBNET_EVENT_SESSION))
                               ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/travis/build/domoticz/domoticz/hardware/OpenWebNetTCP.cpp:365:27: note: place parentheses around the assignment to silence this warning
                            if(m_pStatusSocket = connectGwOwn(OPENWEBNET_EVENT_SESSION))
                                               ^
                               (                                                       )
/Users/travis/build/domoticz/domoticz/hardware/OpenWebNetTCP.cpp:365:27: note: use '==' to turn this assignment into an equality comparison
                            if(m_pStatusSocket = connectGwOwn(OPENWEBNET_EVENT_SESSION))
                                               ^
                                               ==
1 warning generated.
[ 57%] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenWebNetUSB.cpp.o
[ 57%] Building CXX object CMakeFiles/domoticz.dir/hardware/openwebnet/bt_openwebnet.cpp.o
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1307:16: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "OFF <96> Heating Mode";
                                    ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1310:16: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "OFF <96> Conditioning Mode";
                                    ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1316:37: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "manual - adjustment Mode <96> Heating";
                                                         ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1319:37: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "manual - adjustment Mode <96> Conditioning";
                                                         ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1325:29: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "programming Mode <96> Heating";
                                                 ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1334:31: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "holiday daily plan <96> Heating Mode";
                                                   ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1337:31: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "holiday daily plan <96> Conditioning Mode";
                                                   ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1409:19: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        sstr << " days <96> Heating mode";
                                       ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1417:19: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        sstr << " days <96> Conditioning mode";
                                       ^~~~
/Users/travis/build/domoticz/domoticz/hardware/openwebnet/bt_openwebnet.cpp:1661:21: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                        return "sleep on <93>base band<94>";
                                         ^~~~         ~~~~
10 warnings generated.

**Comment by Spugna85** [comment]
These warnings have already solved with the pull request #1302 , right?

**Comment by Spugna85** [comment]
I do not understand, with github client I did the 'update from domoticz/master' to my 'master' and now I have lost the changes made by the pull request #1302  and #1303  ..
What happened?

**Comment by Spugna85** [comment]
I opened the pull request #1310  to restore the code that I did in #1303 and fix compilation warning that you have reported (#1302 )

**Pull request merged**
