### PR TITLE
Implemented: Extended schedules (Odd/Even week numbers, Monthly & Yearly)

### PR DESCRIPTION
**Pull request by EddyK69**
**Added extended schedules:**
- Odd week numbers
- Even week numbers
- Monthly (like: every day 5 of month)
- Monthly (weekday) (like: every second sunday of month)
- Yearly (like: every december 5)
- Yearly (weekday) (like: every third tuesday in september)

**Note: Updated language-file**

### CODE REVIEW

**Comment by nayrnet** [comment]
Can you also add odd/even days? Many localities will implement watering restrictions to even/odd days when under drought conditions.

The lack of advanced scheduling such as this proposal extends was the only thing preventing me from coding up a decent interface for my OpenSprinkler system in Domoticz.

**Comment by EddyK69** [comment]
That is possible maybe in future releases. For now i want see if this version is accepted first ;)

**Comment by PiterEL** [comment]
Pleaase add strings to translation...i want start translate.

**Comment by gizmocuz** [comment]
Thanks for this great patch!

**Comment by EddyK69** [comment]
:D 
One remark: i added the list First, Second, Third etc. in the translation-file as 2nd, 3rd, 4th because the word Second already exist as in time. I saw it was changed to Second...
Please use 2nd, 3rd & 4th in the translation-files. Or can i change them myself in Transifex?

**Comment by gizmocuz** [comment]
Done...
The master file can not me changed on transifex...

**Comment by PiterEL** [comment]
EddyK69 can you tell me where your schedule is avaible ? Bacuse when i go to TIMERS i see old scheduler.

**Pull request merged**
