### PR TITLE
Adding current values to P1 Meter Hardware

### PR DESCRIPTION
**Pull request by fjgalesloot**
The DSMR telegram contains current values for all phases L1, L2, L3. The current P1MeterBase code does not parse those values. 

This PR adds code to read those values and output them to a current sensor.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the patch ! There are merging conflicts probably caused by using an old source code as start point. Is it possible you can make a patch against the latest development code ?

**Comment by fjgalesloot** [comment]
I'm glad to finally give something back to domoticz! 

I did my changes in the development branch now and commited. 
As this is my first PR, I'm a bit of a n00b with this. Should I create a new PR or can I change this one.

**Comment by gizmocuz** [comment]
You can try to commit and push again to your fork.. that should update this PR
Wise feel free to close this and make a new one

**Comment by fjgalesloot** [comment]
I'll close this and create new one. Thanks.

**Comment by fjgalesloot** [comment]
New PR:#2851

**Pull request closed without merging**
