### PR TITLE
Energy counter now can decrease, when production power is greater tha…

### PR DESCRIPTION
**Pull request by CreasolTech**
…n usage power

### CODE REVIEW

**Comment by Oleg-Sob** [comment]
If the values are negative, the "today" counter is reset to zero every 5 minutes.

**Comment by Oleg-Sob** [comment]
Blue bars are displayed correctly.

**Comment by CreasolTech** [comment]
> If the values are negative, the "today" counter is reset to zero every 5 minutes.

Hi.
I remember to have solved this trouble. 
I'm looking for this pull request be committed into the developement sources, then if there's any problem I'll fix it.
Thanks for your feedback.
Paolo

**Comment by Oleg-Sob** [comment]
Correct it please.

**Comment by CreasolTech** [comment]
> Correct it please
Fixed!

**Comment by Oleg-Sob** [comment]
Thanks, I'm testing.

**Comment by Oleg-Sob** [comment]
Great, everything works, thanks!

**Comment by gizmocuz** [comment]
Thank you for this PR!

**Comment by CreasolTech** [comment]
> Thank you for this PR!

Thanks to you, Oleg-Sob for testing and other people involved in this very nice project.
I'm happy for this little contribution.

May I ask a question?
I've developed some modules for Domoticz (inputs, outputs, sensors) that should be connected by RS485 bus.
These devices are working since almost 2 years in my house, and now I'd like to start producing and selling them.
Actually, the plugin is written in python, and consists of 1 directory within 2 python files.
How can I get the plugin be available by default in Domoticz?
Should I rewrite it in C, or is it sufficient to put it in the Domoticz source tree?

This is the repository for the hardware plugin in python:
https://github.com/CreasolTech/CreasolDomBus

This is a page with description of 2 modules for Domoticz (another 2 modules are almost ready, and will be available in January).
https://www.creasol.it/products/domotics

Thanks a lot.
Paolo

**Pull request merged**
