### PR TITLE
dzVents 2.5.0 ( to be used with Lua version 5.3 or newer )

### PR DESCRIPTION
**Pull request by rwaaren**
This PR must only be merged into development together with implementation of Lua 5.3 in domoticz !! 

        modified:   History.txt
	modified:   dzVents/documentation/README.md
	modified:   dzVents/documentation/README.wiki
	modified:   dzVents/documentation/history.md
	modified:   dzVents/runtime/Camera.lua
	modified:   dzVents/runtime/Device.lua
	modified:   dzVents/runtime/Time.lua
	modified:   dzVents/runtime/Utils.lua
	modified:   dzVents/runtime/Variable.lua
	modified:   dzVents/runtime/device-adapters/evohome_device.lua
	modified:   dzVents/runtime/device-adapters/generic_device.lua
	modified:   dzVents/runtime/device-adapters/rgbw_device.lua
	modified:   dzVents/runtime/device-adapters/switch_device.lua
	modified:   dzVents/runtime/integration-tests/README.md
	modified:   dzVents/runtime/integration-tests/scriptTestRename.lua
	modified:   dzVents/runtime/integration-tests/stage2.lua
	modified:   dzVents/runtime/misc/testdzVents.sh
	modified:   dzVents/runtime/tests/README.md
	modified:   dzVents/runtime/tests/testDomoticz.lua
	modified:   main/EventSystem.cpp
	modified:   main/dzVents.cpp

### CODE REVIEW

**Review by gizmocuz — APPROVED** [review]
All looking fine! Thanks again!

**Review by dannybloe — APPROVED** [review]
Looks great. Let's go for it.

**Comment by freemann** [comment]
Great work! 

When will there be a stable again?
This is atleast the second major(with breaking) change(s) for the next stable release.

I'm still on the may 2019 unstable, just before the OZW change, this because I didn't want to break my zwave stuff and all other stuff behind it. 
As i'm correct, it will be a lot of work to get Z-Wave working again with the new OZW. Now next is the LUA/dzVents change. 
When there is a new stable it will be, in worst case scenario, a lot of big (breaking) changes on my system... With the question if its a LUA/dzVents or OZW issue!? 

Why nog releasing these big changes in seperate new stable changes so people can migrate in fases?

**Comment by dannybloe** [comment]
Dunno about a new stable. For me current beta doesn't work at all with all my 30+ zwave devices so I guess there's still some work to be done in this field.

**Comment by gizmocuz** [comment]
Thank you !! All merged as well as Lua 5.3

**Pull request merged**
