### PR TITLE
Allow remote proxy

### PR DESCRIPTION
**Pull request by gordonb3**
In response to issue #1823: AreWeInLocalNetwork and Nginx

This update allows users to specify a list of IPs that are allowed to act as a proxy. The additional logging patch will show the originating (proxied) IP when a new session is started rather than just once for each unique IP.

### CODE REVIEW

**Comment by gordonb3** [comment]
Hold on... session expiration does not appear to update without logon

**Comment by gordonb3** [comment]
Looks like something is f*ed up with session management. I can see the session refreshing every 5 minutes but it still starts a new session every 15 minutes...

Edit: 
Okay, that is weird. Has nobody else had issues with this before? There is in fact a mixup with two time values: `timeout` and `expires`. The latter one gets refreshed while the session is kept alive by the remote user, but the first one is only set at creation time and subsequently used in a periodic cleaning routine that will kill any session that was created more than 10 minutes ago, regardless of the value of `expires`.

Edit 2:
Right... This behaviour appears to be related to issue #172 and I need to reload the session info from store. Verifying solution right now.

**Comment by gordonb3** [comment]
All working now. Good to go

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
