### PR TITLE
XiaomiGateway: fixing door sensors

### PR DESCRIPTION
**Pull request by corbinmunce**
Broke this previously sorry.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by marcotini** [comment]
It does not work even with this change, when the log shows a heartbeat occasionally by a false signal on for the doors and for the motion sensor.

**Comment by corbinmunce** [comment]
@marcotini, this was for a different problem than what you are experiencing.  Can you setup a test environment for me to look at? PM me the details on the forum if so.

**Comment by marcotini** [comment]
@corbinmunce I already have solved https://github.com/marcotini/domoticz/commit/254c29b97516da937ae36614e252e3560104fecf

**Pull request merged**
