### PR TITLE
New attempt to enable C++11 build and fix build errors

### PR DESCRIPTION
**Pull request by emontnemery**
Enable c++11 support, builds on:
  - Ubuntu Trusty (through Travis)
  - OSX + XCode 8.3 (Through Travis)
  - VS2017 (Through appveyor)
  - Debian Jessie (x64, but needs CMake from Jessie backports)
  - Raspbian Stretch (RPi 3)
  - Ubuntu WSL (x64)

CMake minimum version stepped, CMake 3.1.0 was first version to include support for CMAKE_CXX_STANDARD

### CODE REVIEW

**Comment by correa** [comment]
Hi emontnemery. I'm also working on CPP11 again. I see we both found some different places to replace the SSTR macro. Please check my cpp11 branch, I think my current CMakeLists.txt is a better solution, and will build with Pi's older cmake.

I'm build testing on Pi at the moment, the build takes around 12 hours to complete :(

https://github.com/correa/domoticz/blob/cpp11/CMakeLists.txt

Perhaps we can merge our changes into one pull request.

**Comment by emontnemery** [comment]
Hi correa!
Yes, I agree your `macro(use_cxx11)` CMakeLists.txt is a better solution.
Sure, let's merge into one PR. Do you prefer I close this one, or I should I merge in your changes here?

Please note when using set(CMAKE_CXX_STANDARD 11), the needed flags were not present when making the combined header:
COMMAND ${CMAKE_CXX_COMPILER} ${CMAKE_CXX_COMPILER_ARG1} ${_compiler_FLAGS} -x c++-header -o ${_output} ${_source}
This is why I added it manually, maybe you can find a better way?

**Comment by correa** [comment]
I have added a workaround for the issue with CXX_STANDARD you mention in the PCH. Also cherry-picked your commit as well. Going to make a pull request with both our changes, but I don't have a ready machine available with g++ and cmake > 3.1, can you check the PCH fix?

**Comment by emontnemery** [comment]
Sure, closing this and I'll try to build #2081.

**Pull request closed without merging**
