### PR TITLE
Replace all special chars for safe HTML.

### PR DESCRIPTION
**Pull request by Jarthianur**
There is actually such a function, called MakeHtml, but CRLF should not be replaced with br-tags in SafeHtml.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Do we need to change the & sign ? I assume people have names like Garden&Pool or similar

**Comment by dannybloe** [comment]
Isn't everything utf8 already? Then you don't need this relic from the past.

**Comment by Jarthianur** [comment]
No, replacing the ampersand is not really necessary, at least not for security reasons.
I've just compared this to the list of characters beeing replaced by php's htmlspecialchars function.

If the page is built with utf8 encoding, there is also no need to replace it for encoding reasons.
But it would be displayed as `&` either way, as this just effects the representation in the DOM.

I will adjust this.

**Comment by gizmocuz** [comment]
Thanks!

**Comment by dwmw2** [comment]
Now my son's bedroom temperature is reported as `Ned&apos;s room`.
nedaposroom

**Comment by sweetpants** [comment]
@dwmw2, already upgrade toe latest beta?

**Comment by dwmw2** [comment]
@sweetpants This is the latest development branch; I saw it when I updated. Looks like it's already reported as #2138

**Pull request merged**
