### PR TITLE
New Version UBStin / Multibloc_V8 (SFSP)

### PR DESCRIPTION
**Pull request by ghost**
New functionality : 
- manual creation up to 127 virtual switch in domoticz, ability to learn eatch switch to any blocks output. Virtual switch works like EnOcean. (Usefull if we want to control the 6 outputs with a global virtual switch).
- now possibility to Enter/Exit Learn mode Or Clear Mode for all SFSP Blocks. (each blocks detected automatically creates 3 associated buttons for Learn / Exit Learn and Clear, usefull if the blocks is not accessible ).

### CODE REVIEW

**Comment by ghost** [comment]
For information, on my Ubuntu server I've change the 2 first log line of the GetScript function in the EcoCompteur.cpp hardware because they return "undefine" elements so Makefile failed (after linking). quite strange to have this trouble with the main developpement checked-out, no ?

**Comment by ghost** [comment]
don't validate right away, have some changes to do ;-)

**Comment by ghost** [comment]
finally everything is ok for me.

**Comment by gizmocuz** [comment]
Thank you for your patch!

Some questions:
- i see a new class 'CDenkoviSmartdenIPIn' that probably should not be in this patch, we also have already a 'CDenkoviSmartdenIPInOut' class that should work ? Or maybe needs some adjustments but a new denkovi class is maybe not needed (and needs another pull request)

You included a WebServer.cpp.bak file in your pull request

**Comment by ghost** [comment]
I think the "CDenkoviSmartdenIPIn" is an error, I was pretty annoyed to update my repository because I'was at an old revision.

**Comment by ghost** [comment]
I've deleted CDenkoviSmartdenIPIn files and .bak files.

**Comment by gizmocuz** [comment]
Thank you for this, just two more please:

- could you undo the formatting changes in "EcoCompteur.cpp", so no changes in this class please
- could you rename all your member variables in your class(es) , and make them start with m_ and if possible in 'PascalCase' style, like m_HelloWorld

**Comment by ghost** [comment]
Can you tell me more about this appveyor error ? don't understand...

**Comment by gizmocuz** [comment]
Dont think this is an error with your PR, but just with Appveyor... happens now and then...
I am forcing a rebuild now

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
