### PR TITLE
Fix issue #538

### PR DESCRIPTION
**Pull request by gaudryc**
This patch consists of :
- Handle OnDelay and OffDelay the same way for all devices ;
- Fix Selector switch OnDelay and OffDelay management.

**I've tested it with a button (On/Off), a Selector switch, a Scene and a Blockly script to control a button but I don't know if it covers all cases.**

### CODE REVIEW

**Comment by gizmocuz** [comment]
The off delay is handled in SQLHelper.cpp, line 3218

if (AddjValue!=0) //Off Delay
...

When i use the current system, and make a virtual dummy switch, with an on delay of 5 seconds, and an off delay of 10 seconds, and press the switch, in the log i see

after 5 seconds, ON
after 5+10 seconds, OFF

this is the expected behaviour

**Comment by gaudryc** [comment]
Do the OffDelay have to be handled in CSQLHelper::UpdateValueInt only ?
What is the reason to make this difference between OnDelay and OffDelay management (i.e. different places) ?

**Comment by gizmocuz** [comment]
When a switch command is send, then we only need to check for the ON delay, because it might need to be scheduled after xxx seconds
Then when the actual switch command is performed, and the database is updated with the current state (ON), we check if that switch had an OFF delay, and if so, we schedule a switch-off command
(not for motion sensors)

**Comment by gaudryc** [comment]
OK, now I understand that On delay and Off delay usage is very confusing.
For me :
- On delay produces a delay to be switch on ;
- Off delay produces a delay to be switch off ;
  What you are saying is that the device will be switch on after OnDelay and then switch off after OnDelay + OffDelay.

I don't blame you but I think it needs some help label in the edit form.

Anyway, I thank you for these informations.
So I will change my pull request to only handle Selector device in the three places it would be.

**Comment by gaudryc** [comment]
Ok, it works as you want now.

**Comment by gizmocuz** [comment]
Thanks, well yes, might need a bit clearing up... hope it is in the manual.. (that is 1.1 year old now _g_)

**Pull request merged**
