### PR TITLE
P1 Smart Meter suppress spikes

### PR DESCRIPTION
**Pull request by jvandenbroek**
I think this should prevent spikes on meters without CRC check enabled/possible: http://www.domoticz.com/forum/viewtopic.php?f=6&t=18099

### CODE REVIEW

**Comment by gordonb3** [comment]
I see what you attempt to do here, but could you include the meter version in those conditional updates? This should not affect meters that have m_p1version >=4

**Comment by jvandenbroek** [comment]
~~Now also check for CRC is disabled, guess that's even better than just relying on the version right?~~
Edit: Wait, that doesn't work :) Thought disable_crc was global..

Ok, now indeed check the meter version as you suggested..

**Comment by gordonb3** [comment]
My vote would be against that. If one deliberately disables error checking we should not replace it with a different error defeating (or rather: masking) mechanism. Except of course errors that may crash dz

**Comment by jvandenbroek** [comment]
I already updated it, because it didn't work ;)

**Comment by gordonb3** [comment]
Noticed the third commit just as I commented.

Don't really know why the call to ParseData is done this way. `disable_crc` is in fact loaded from the Class variable `m_bDisableCRC`. May want to note that the logic on this variable is reverted, i.e. `true` means that there is no CRC checking.

**Comment by Pigloox** [comment]
I have never had strange values ​​with the CRC verification and I do not know how this patch will behave with a "peak consumption"

**Comment by jvandenbroek** [comment]
@Pigloox I'm sorry, but you should really check my edits and the current code before commenting. I reverted the (non) working disable CRC check and implemented the suggestion of @gordonb3 to check on >= v4

**Comment by gizmocuz** [comment]
Should we merge this ?

**Comment by jvandenbroek** [comment]
I say yes ;) I doesn't harm ppl with version >= 4 and helps others without CRC possibility. I kept the numbers high (way higher than needed) so no worries about missing peak values or something.

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
