### PR TITLE
Line endings supported in text log

### PR DESCRIPTION
**Pull request by Olifant1990**
\r \n line endings are parsed to <br \> for line endings in log. As continuation of commit https://github.com/domoticz/domoticz/pull/1942

### CODE REVIEW

**Comment by Olifant1990** [comment]
afbeelding
Line endings are supported now

**Comment by gizmocuz** [comment]
Thanks! Could you undo the change in WebServer.cpp, the previous code was OK and the date field is later then sValue in the database as well

**Comment by Olifant1990** [comment]
Yes I can, but is it an alternative to change the order of the rows

root["result"][ii]["idx"] = sd[0];
root["result"][ii]["Date"] = sd[2];
root["result"][ii]["Data"] = sd[1];

to

root["result"][ii]["idx"] = sd[0];
root["result"][ii]["Data"] = sd[1];
root["result"][ii]["Date"] = sd[2];
?

It is less a risc to make a mistake. Same order you select, same order in code you work with.
I was debugging here, so I came upon this.
Otherwise, will undo it maybe tonight

**Comment by gizmocuz** [comment]
Yes just revert the changes in that file

**Comment by Olifant1990** [comment]
Done!

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
