### PR TITLE
Removed ) witch should fix the hardware page

### PR DESCRIPTION
**Pull request by Sneezydevil**

### CODE REVIEW

**Comment by ducseb** [comment]
Sorry my mistake.

**Comment by Sneezydevil** [comment]
Found another one, don't have my test setup handy, so might have missed more.

**Comment by CyberClwn** [comment]
i tested with the extra ones removed from line 1007 and 5075. it worked then.

**Comment by ducseb** [comment]
I tested to, no more error.
Sorry for the bug :(

**Comment by gizmocuz** [comment]
No worries, already fixed it

**Pull request closed without merging**
