### PR TITLE
Add support to the eurotronics spirtiz Radiator Valves

### PR DESCRIPTION
**Pull request by pipiche38**
Add support to the eurotronics spirtiz Radiator Valves

Will require update of the manufacturer_specific.xml

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this, but you have to submit this to the openzwave team.
We we merge from time 2 time their repo

**Comment by pipiche38** [comment]
Got it and sorry for the mistake.
These are already on their repo, so it would be great to merge their repo prior release 4.

**Comment by gizmocuz** [comment]
Can see it
https://github.com/OpenZWave/open-zwave/tree/master/config/eurotronic

**Comment by pipiche38** [comment]
You right, it is still on their Dev branch.

**Comment by gizmocuz** [comment]
i think most configuration patches are made against the master branch

**Pull request closed without merging**
