### PR TITLE
Domoticz Weekly Planning Selector

### LINKED ISSUE #3361: Weekly programming
Hello, is it possible to record this in Domoticz?

http://www.domoticz.com/forum/viewtopic.php?f=31&t=20868&start=100&sid=bc3aa7601e87a1c0a8a7eeed35c2db71

### PR DESCRIPTION
**Pull request by xbeaudouin**
This Pull Request is the portage of the following patch : https://github.com/syrhus/domoticz-weekly-planning

Idea is to have choice on the weekly planning to allow for example heating to be easily set.
Author didn't made a PR, so I made it for him since I really think this should be a nice addition to Domoticz.
Some Screenshots : (but the original project has some more as well)

Capture d’écran 2021-12-13 à 18 04 21
Capture d’écran 2021-12-13 à 18 04 09

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR. Looking great!

Question (My French is not that good), View vs Table ...  ::

Table is the default behaviour correct? What we have at the moment ?
Could you make this the first item in the 'tab' ?

View, nut sure how to interpretate this, maybe **Grid** is a better label ? If you aggree , could you rename this ?
Could you post a screenshot with the default theme ? I am looking at the above theme and have issues with all the black text ... shouldn't that be white for better reading ?

**Comment by xbeaudouin** [comment]
Maybe the label are not really the best one. I agree the View should be renamed as Grid.

Well table is not the default.

Here is some screen shots. Unfortunatly "Table" is not yet the default. And... I have to understand how to make this per default.

Empty Timers : 
Capture d’écran 2021-12-14 à 18 10 16
Capture d’écran 2021-12-14 à 18 10 22

Adding some random stuff there :  
Capture d’écran 2021-12-14 à 18 10 43
Capture d’écran 2021-12-14 à 18 10 50

Odd and pairs weeks : 
Capture d’écran 2021-12-14 à 18 11 26
Capture d’écran 2021-12-14 à 18 11 37

French translation (for the fun) :  
Capture d’écran 2021-12-14 à 18 05 39

Maybe we have to add some translation for the "Grid" keyword ?

**Comment by gizmocuz** [comment]
Maybe I can change this once it is merged.... I will try to test this PR soon, thanks!

**Comment by gizmocuz** [comment]
A few comments:

- The checkboxes for the day names are broken with this PR (See the original theme screenshots above)
- It seems that the Scene/Group timers is broke
- The table top/left entry (amount of items) is broke (black text), see below image
image

Is it possible to fix this ? It would be great if you could swap table/grid so existing users are still seeing the normal editor.
(We can change this in a next-next stable)

**Comment by xbeaudouin** [comment]
I'll have a look.

**Comment by gizmocuz** [comment]
Were you successful ?

**Comment by xbeaudouin** [comment]
Well I didn't had the time yet... Try to find some free time as soon as I can.

**Comment by xbeaudouin** [comment]
About "The table top/left entry (amount of items) is broke (black text), see below image
image", on lastest domoticz I still have the 25 entries... So I am not sure about what to fix. See the screen shot :
Capture d’écran 2022-01-09 à 14 53 09

Still working on other stuff..

**Comment by gizmocuz** [comment]
Thanks for working on this.
This is my view of the latest version with the default theme (and cache cleared)

image

**Comment by xbeaudouin** [comment]
Yeah I confirm the text is black instead of white.
The issue is maybe in the following code :  
```
<div id="ds-timers-table">
(... old timers.html code)
</div>

```
Since there is no class=<something> it takes the defauts values.
Problems is I dunno what kind of class I can use to fix that (this will fix, I think issues with the checkboxes a well).

**Comment by gizmocuz** [comment]
Thanks, yes the default seems fine. Domoticz is using a lot of tables, for instance the devices view. There the dropdown displays normally
Maybe it's in the CSS file of this PR

**Comment by xbeaudouin** [comment]
Well I have no clue. Maybe if some JS / CSS guru can help. :/

**Comment by waltervl** [comment]
Sound interesting! The color of the text is black is a minor issue and can perhaps easily been fixed by someone else if merged and build into test.

**Comment by gizmocuz** [comment]
Maybe, maybe not. Is the Table view already the default view? Because that's what people are used now.
And at least a new stable release before we merge problems into the beta

**Comment by kiddigital** [comment]
@xbeaudouin , could you `git rebase` your PR with the latest development branch to resolve any merge-conflicts? And you can remove the app-cache update as app-cache has been removed completely.

Is the 'problem' of the dark/black number (instead of light/white) still an issue or has it been resolved? If not, once re-based, I might take a look although I am not a front-end wizard myself. Maybe @michahagg can have a look?

**Comment by gizmocuz** [comment]
It's still an issue, and I think we should swap the table and grid for a first release.
There are also other options then on/off, on/off with random, sunrise, sunset etc

**Comment by michahagg** [comment]
> Is the 'problem' of the dark/black number (instead of light/white) still an issue or has it been resolved? If not, once re-based, I might take a look although I am not a front-end wizard myself. Maybe @michahagg can have a look?

@kiddigital I'm sorry but I have not been able and I'm still not able to spend much time on domoticz unfortunately. :-( I'll let you know when I have more time.

**Comment by xbeaudouin** [comment]
@kiddigital I have done the merging to remove any merge conflcts. About dark/black issue, this are still there... Since I am not really a JS wizard I have tried on my side to find a way to fix that, but I am out of luck on this part !

**Comment by soif** [comment]
Following @gizmocuz  comments in #5433 :

> I like the design! But for example the look of the timers should initially be the table view we have now
> 
>   -   In the PR it is a grid as default, and you can switch to a table view
>   -  The checkboxes for the day names are broken with this PR (See the original theme screenshots above)
>   -  It seems that the Scene/Group timers is broke
>   -  The table top/left entry (amount of items) is broke (black text)

I've quickly tried to merge it, but here are some quirks and remarks:
- Merge conflicts: I cant really figure out what is right/wrong to fixes the conflicts... If ever @xbeaudouin could fix it, It would be easier to review...
- the Grid/Table tabs, is not really pretty/compliant to the current UI design, IMO --> might be certainly easily fixed, by  just using basics Bootstrap Tabs, or maybe better, just displaying the Grid view, BELLOW the table view, instead of relying on 2 separate views.
- In "Grid" view the buttons ( levels) above the planning view are both clickable, but also have an input field when you click on the color?? What is the use of this? absolutely not obvious IMHO.
- the bellow buttons : "Clear", "Update", "Activate all", "deactivate all", are also not obvious? What are they supposed to do?

I also like ❤️ this PR  and I might help to fix some CSS/JS bugs, but only once all of these things have been previously decided/coded/fixed..

**Comment by soif** [comment]
BTW , since this PR, @syrhus (original author) has just pushed some commits (Nov 2022) to his own repo at:
https://github.com/syrhus/domoticz-weekly-planning

Maybe worth a look, or better @syrhus could push a PR himself.....

**Comment by brjhaverkamp** [comment]
Hi soif, 

By chance, last week  I stumbled upon syrhus weekly planning patch. I want to use it in a program/thermostat to control my Aduro wood-pellet stove. I'm creating a plugin for this atm. So it is great to see there is traction to include it in mainline domoticz right now.
I only wanted to comment on your point:
"the Grid/Table tabs, is not really pretty/compliant to the current UI design, IMO --> might be certainly easily fixed, by just using basics Bootstrap Tabs, or maybe better, just displaying the Grid view, BELLOW the table view, instead of relying on 2 separate views."
I want to be able to use the weekly planner on a small 8 inch tablet with dashticz. I fear it would be too big to show both together. and the functionality is complementary, so showing both doesn't add much. I expect in my case, I will only use the  grid view to change timer settings, for instance.

So I hope the two tabs stay as designed by syrhus. Just my 2ct.

Regards,

Bert

**Comment by gizmocuz** [comment]
@brjhaverkamp , the reason for the tabs to switch has multiple reasons:
- current users can work as they are used too and get used to the new grid method
- the current grid method is not complete, but when we can merge this it is a very good start (for example blinds open/close commands are not available)

**Comment by gizmocuz** [comment]
Closed by #5542

**Pull request closed without merging**
