### PR TITLE
Websocket added subscribe/unsubscribe

### PR DESCRIPTION
**Pull request by gizmocuz**
Cleaned up websocket code
Added subscribe/unsubscribe feature
Rebuild Log controller as demonstration (made it real-time)

### CODE REVIEW

**Comment by Smanar** [comment]
Hello, thx, but there is few documentation about the websocket, I think there is usefull stuff for me in this PR but idk the impact of the "subscribe/unsubscribe feature" compared to the old version.

**Comment by gizmocuz** [comment]
@Smanar , at the moment subscription is only implemented for the 'log' and log controller.
It can be extended, like which devices do I want to receive, or if you are on the groups/scene page, you only want update for them
(Same for the other tabs)
Anyway, the log page is now blazing fast (real-time) and that was my goal.
Not sure if this is interesting (at the moment...) for Deconz

**Comment by Smanar** [comment]
>like which devices do I want to receive

Nice, It's exactly what I need.
And it's not for Deconz, but for another project https://github.com/Smanar/CYD-Domoticz-Remote
And I have problem because websocket can be realy talkative, not good for those kind of devices, and more If I need only websocket for 12 devices on 200 in domoticz.

**Comment by gizmocuz** [comment]
It is currently possible to make a device status query for specific devices with

`json.htm?type=command&param=getdevices&rid=10,20,30,40`

This returns all info for devices 10,20,30,40

You can use this in a timer already, or as initial query for the websocket

New beta: 16073

When you now issue this with the websocket, internally only these 4 devices are being send to the client

Could you verify if that's working? I have tested it with the new energy dashboard and all seems to work great

**Comment by Smanar** [comment]
It works fine with REST request, have a single json with all datas, perfect, so usefull too. I have problem to get "complete device list" using for exemple `json.htm?type=command&param=getdevices&filter=light&used=true&order=Name` esp32 don't have enought memory for too hudge json, this new feature will be usefull to make "custom list"


>When you now issue this with the websocket

It's possible too directly with the Websocket ? How ? ATM I m connecting to websocket using `ws://IP:PORT/json/` with protocol "domoticz"

**Comment by gizmocuz** [comment]
yes, see the EnergyDashboard controller
It builds a list of needed devices, request it via the websocket (with a list of rid's) and handles the websocket receive
It will only receive those devices that are initially requested

**Comment by Smanar** [comment]
I don't see the magic, or I miss something

`livesocket.getJson("json.htm?type=command&param=getdevices&rid=" + devArray.toString(), function (data) {`

So need to make a classic websocket connexion then send the message 

`{"event":"request","query":"type=command&param=getdevices&rid=1,2,3,4,5"}`

Edit:

So it works finnaly.

But now I have some problem on the Domoticz dashboard, even with a restart `sudo service domoticz restart` some widget are not updated.
It's random, but need to press F5 to update them

The action is memorised ?

**Comment by gizmocuz** [comment]
@Smanar , that first query should have done the trick as well, but there was an issue with an internal filter generation
This is fixed in beta 16078

**Comment by Smanar** [comment]
Yep have see https://www.domoticz.com/forum/viewtopic.php?t=42430
And BTW thx again for this feature, using the websocket as connection is perfect for me, native, portable, fast, simple, I prefer that as MQTT for exemple, the only problem was the amount of data transfered, even if hardware are able to support it in 2024.

But this feature decrease it a lot.

I will start to use it this Week end.

**Pull request merged**
