### PR TITLE
Add step to trigger Docker build

### PR DESCRIPTION
**Pull request by stas-demydiuk**
Add a step to automatically trigger [Docker build](https://hub.docker.com/repository/docker/demydiuk/domoticz) after successful deployment

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR. Looks good!
I would personally put this below the deploy section above the ngrok part.
Is that something you can change?

**Comment by stas-demydiuk** [comment]
Sure, will update

**Comment by stas-demydiuk** [comment]
Done! Hopefully, would be able to finally remove my cron script that triggers the Docker build every 4 hours :)

**Comment by gizmocuz** [comment]
Thanks! Fingers crossed😁

**Pull request merged**
