### PR TITLE
Fix missing sys/time.h include

### LINKED ISSUE #2583: Build broken with GCC 6.4.0 on Alpine
When updating my Domoticz image (alpine:latest) it doesn't build anymore and I get an error somewhat similar to #2576 but not identical.

The build is done using alpine docker image (latest) and it use the current GCC of alpine which looks like 6.4.0.

build log:
```
-- The C compiler identification is GNU 6.4.0                                                                                                                     
-- The CXX compiler identification is GNU 6.4.0
[...]
[ 23%] Building CXX object CMakeFiles/domoticz.dir/main/EventsPythonDevice.cpp.o                                                                                  
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/Helper.cpp.o
[ 24%] Building CXX object CMakeFiles/domoticz.dir/main/IFTTT.cpp.o
In file included from /src/domoticz/main/IFTTT.cpp:3:0:
/src/domoticz/main/SQLHelper.h:74:10: error: field '_DelayTimeBegin' has incomplete type 'timeval'                                                                
  timeval _DelayTimeBegin;                                                                                                                                        
          ^~~~~~~~~~~~~~~                                                                                                                                         
In file included from /src/domoticz/main/SQLHelper.h:6:0,                                                                                                         
                 from /src/domoticz/main/IFTTT.cpp:3:                                                                                                             
/src/domoticz/main/Helper.h:71:21: note: forward declaration of 'struct timeval'                                                                                  
 int getclock(struct timeval *tv);                                                                                                                                
                     ^~~~~~~                                                                                                                                      
make[2]: *** [CMakeFiles/domoticz.dir/build.make:279: CMakeFiles/domoticz.dir/main/IFTTT.cpp.o] Error 1                                                           
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/domoticz.dir/all] Error 2                                                                                      
make: *** [Makefile:152: all] Error 2                                                                                                                             
```

### PR DESCRIPTION
**Pull request by rhaamo**
Partly fixes #2583

### CODE REVIEW

**Comment by rhaamo** [comment]
Can't build with GCC 6.4.0 on Alpine (edge), unless I add sys/time.h, (and replace u_short by unsigned short).

**Comment by pipiche38** [comment]
cannot be specific to this platform GCC 6.4.0 / Alpine ? So maybe putting the corresponding #ifdef in order to avoid impacting other platforms which don't have the issue.

**Comment by rhaamo** [comment]
I don't have anything else with a GCC 6.4.0 to test.
And I don't think it's possible to detect alpine from an ifdef.
Travis seems to use a 6.4.0 on trusty and builds with this fix so I don't know.

**Comment by gizmocuz** [comment]
Don't think this needs to be in SQLHelper.h
It should be added to the classes needed it, or in the precompiled header.
How about gcc 7 ?

**Comment by rhaamo** [comment]
There is an issue with timeval in at least ```main/IFTTT.cpp```, ```main/LuaCommon.cpp```, ```main/Scheduler.cpp``` and also ```main/SQLHelper.cpp```
So putting the include in ```main/SQLHelper.h``` which is included by previous mentioned files looked a good fix for me.

No GCC 7 or 8 in Alpine yet, ```6.4.0-r8``` is the latest available, even on ```edge```.

**Comment by gizmocuz** [comment]
True, that looks like a good spot, same as in the precompiled header, but did you know that a lot of classes might include that file, but do not need this header file?
Also if somehow later the IFTTT class is not using SQLHelper.h anymore, you still get a compile error

But this project exists for years now, and this is the first time this is reported, it compiles fine under various unix/linux distributions. Maybe this should be solved elsewhere ?

**Comment by rhaamo** [comment]
I don't know the domoticz codebase enough, but I could add to each associated ```.h``` too to avoid issue if removing ```SQLHelper.h``` include.

The use of ```timeval``` might be recent, it built for a long time without issue on Alpine, I think the root issue may be related to the use of a different libc (musl IIRC) which may not implicitely internally declare stuff about timeval.
That's the only explanation I think of since the CI have the same GCC version but runs on Debian (so it's a glibc).

**Comment by gizmocuz** [comment]
this depends, if the timeval structure is used only in the CPP file, then the header should be included in the CPP file rather then in the header file

**Comment by rhaamo** [comment]
ok, I will do it that way and retry building

**Comment by gizmocuz** [comment]
Is it working correctly for you now?

**Comment by rhaamo** [comment]
Sorry I made some tests the other day and forgot to report.

I wasn't able to do something "good", the first error is:
```
In file included from /src/domoticz/main/IFTTT.cpp:3:0:
/src/domoticz/main/SQLHelper.h:74:10: error: field '_DelayTimeBegin' has incomplete type 'timeval'                                                                
  timeval _DelayTimeBegin;                                                                                                                                        
          ^~~~~~~~~~~~~~~                                                                                                                                         
In file included from /src/domoticz/main/SQLHelper.h:6:0,                                                                                                         
                 from /src/domoticz/main/IFTTT.cpp:3:                                                                                                             
/src/domoticz/main/Helper.h:71:21: note: forward declaration of 'struct timeval'                                                                                  
 int getclock(struct timeval *tv);                                                                                                                                
                     ^~~~~~~                                                                                                                                      
```

And adding the include in Helper.h fix for every other errors because of includes last time I tested.

Now It fails elesewhere because of "pthread_getname_np" and I can't test further so I think I'm gonna give up building on alpine and just switch the base to debian.

**Comment by kofec** [comment]
I have the same issue on Openwrt:
[ 18%] Building CXX object CMakeFiles/domoticz.dir/main/IFTTT.cpp.o
In file included from /mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/main/IFTTT.cpp:3:0:
/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/main/SQLHelper.h:74:10: error: field '_DelayTimeBegin' has incomplete type 'timeval'
  timeval _DelayTimeBegin;
          ^~~~~~~~~~~~~~~
In file included from /mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/main/SQLHelper.h:6:0,
                 from /mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/main/IFTTT.cpp:3:
/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/main/Helper.h:71:21: note: forward declaration of 'struct timeval'
 int getclock(struct timeval *tv);
                     ^~~~~~~
CMakeFiles/domoticz.dir/build.make:192: recipe for target 'CMakeFiles/domoticz.dir/main/IFTTT.cpp.o' failed
make[5]: *** [CMakeFiles/domoticz.dir/main/IFTTT.cpp.o] Error 1
make[5]: Leaving directory '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87'
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[4]: *** [CMakeFiles/domoticz.dir/all] Error 2
make[4]: Leaving directory '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87'
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87'
Makefile:136: recipe for target '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/.built' failed
make[2]: *** [/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/domoticz-0737c6ad8dbb96dfa9eae02a03906d599296fd87/.built] Error 2
make[2]: Leaving directory '/mnt/openwrt/OpenwrtNSA310/feeds/packages/utils/domoticz'
time: package/feeds/packages/domoticz/compile#51.41#7.30#92.37
package/Makefile:107: recipe for target 'package/feeds/packages/domoticz/compile' failed
make[1]: *** [package/feeds/packages/domoticz/compile] Error 2

**Comment by stas-demydiuk** [comment]
Guys any thoughts how to compile domoticz on alpine again?

**Comment by rhaamo** [comment]
@stas-demydiuk see preview comments or the file changes tab, but you will hit others problems like : u_short which needs to be "unsigned short" and issues with ```pthread_getname_np``` but I haven't looked to resolve this one.

**Comment by gizmocuz** [comment]
Please create a github issue for the discussion or use the forum.
Closing the PR as this is not the correct way

**Pull request closed without merging**
