### PR TITLE
Update XiaomiGateway.cpp

### PR DESCRIPTION
**Pull request by EvgenaNet**
I just want to help add "Xiaomi Wireless Single Wall Switch" and "Xiaomi Wired Dual Wall Switch". I do not know what write to string 667 - i have not double switch.

### CODE REVIEW

**Comment by kovainfo** [comment]
Please, remove your PR! You deleted the processing of the switch and did not add anything to handle it, and if this PR is released, this switch will stop working for everyone!

**Comment by EvgenaNet** [comment]
> Please, remove your PR! You deleted the processing of the switch and did not add anything to handle it, and if this PR is released, this switch will stop working for everyone!

Did you see good? Pls, write me number of strings, which i was deleted??? I just replaced some strings by category and add some strings by analogy from there was.
What is the problem?

**Comment by kovainfo** [comment]
I can’t tell you the line numbers you deleted. This is a great ability to do GITHUB. Here it is necessary to do not by analogy, but with understanding.

**Comment by EvgenaNet** [comment]
> I can’t tell you the line numbers you deleted. This is a great ability to do GITHUB. Here it is necessary to do not by analogy, but with understanding.

So why you thinking, that i deleted the processing of the switch? I nothing deleted. Nothing! Just added.
Nobody else said not that my PR will be crashed your switch...

**Comment by kovainfo** [comment]
> So why you thinking, that i deleted the processing of the switch? I nothing deleted. Nothing! Just added.
> Nobody else said not that my PR will be crashed your switch...

Do you want to arrange a vote for your PR? The third time I tell you, you deleted the description for "Xiaomi Wireless Dual Wall Switch", added the comment "need to write" and posted the PR.

**Comment by EvgenaNet** [comment]
> > So why you thinking, that i deleted the processing of the switch? I nothing deleted. Nothing! Just added.
> > Nobody else said not that my PR will be crashed your switch...
> 
> Do you want to arrange a vote for your PR? The third time I tell you, you deleted the description for "Xiaomi Wireless Dual Wall Switch", added the comment "need to write" and posted the PR.

You are right.... Sorry!! I mistaked and make change. This stupid mistake...

**Pull request closed without merging**
