### PR TITLE
dzVents 3.1

### PR DESCRIPTION
**Pull request by akamming**
dzVents 3.1, developed together with @rwaaren 

 - Added shell command event triggers to be used in combination with executeShellCommand. You can now execute shell commands and handle the response in your dzVents scripts ASYNCHRONICALLY. See the documentation. No more json parsing needed or complex popen() or ‘system()’ shizzle.
  - add inActive attribute to devices

### CODE REVIEW

**Comment by rwaaren** [comment]
This PR require some additional Boost headers to compile for Windows.  @gizmocuz. can these be added please?

**Comment by gizmocuz** [comment]
Best to remove the boost dependency with native calls
Trying to minimize boost

**Comment by akamming** [comment]
> Best to remove the boost dependency with native calls
> Trying to minimize boost

Willing to ofcourse, but can you give me a bit of help? 

what i then would need is a native call 
- to start a process 
- to be able  to capture the output, exitcode and errortext  
- and to get the pid so i can kill it if it runs too long.
- which does not block other threads

system() and popen() are the as far as i know the potential candidates, but are unusable because on both 
- i don't get the pid 
- they block other threads (seen this in testing)

do you have a sugggestion?

**Comment by gizmocuz** [comment]
@akamming , yes those are the onces... we even have a helper function for this in helper.h/cpp "ExecuteCommandAndReturn"
I think you should be able to use this (see the motherboard class for usage)

**Comment by akamming** [comment]
> 
> 
> @akamming , yes those are the onces... we even have a helper function for this in helper.h/cpp "ExecuteCommandAndReturn"
> I think you should be able to use this (see the motherboard class for usage)

that's not gonna work. it turns out the popen statement statement should be avoided in a multithreaded environment. cause the pipes are handled sequentially if one or more are called in parallel. and when lots of scripts are fired in parallel race conditions can occur, blocking all threads. (seen this in testing, that's why i switched to boost::process)

anyway: i had a good brainwave last night. on unix i now have a working solution using fork/exec. Now trying to get a solution for windows with CreateProcess. unfortunately a difficult API for me as novice developer, so will take some time...

**Comment by gizmocuz** [comment]
Yes that will work!

**Comment by dannybloe** [comment]
Nice work!

**Comment by akamming** [comment]
just pushed  a commit which should decouple from boost. Pls don't merge yet. 

requires more testing, i just want to be sure it compiles correctly now.

**Comment by akamming** [comment]
it's working now. As far as i'm concerned this one can be merged

**Comment by rwaaren** [comment]
Testreport  OK

ready for merge 

```
======== domoticz V2020.2 (12767), dzVents V3.1.0 +========================== Tests ==============================+
  time  | test-script                              | expected | tests | result  | successful |  failed  | seconds  |
===================================================+===============================================================+
00:00:02  Device                                        1        118      OK            118         0      0.6199
00:00:03  Domoticz                                      1         82      OK             82         0      0.6006
00:00:05  EventHelpers                                  1         32      OK             32         0      0.6705
00:00:07  EventHelpersStorage                           1         50      OK             50         0      0.4937
00:00:08  HTTPResponse                                  1          6      OK              6         0      0.0287
00:00:08  Lodash                                        1        100      OK            100         0      0.2900
00:00:09  ScriptdzVentsDispatching                      1          2      OK              2         0      0.1700
00:00:09  Time                                          3        369      OK            369         0      1.4543
00:00:13  TimedCommand                                  1         46      OK             46         0      0.1885
00:00:13  Utils                                         1         36      OK             36         0      0.1427
00:00:14  Variable                                      1         15      OK             15         0      0.0612
00:00:14  ContactDoorLockInvertedSwitch                 3          2      OK              2         0      3.1358
00:00:21  DelayedVariableScene                          8          2      OK              2         0      7.3625
00:00:36  EventState                                   19          2      OK              2         0     18.1470
00:01:12  Integration                                  34        222      OK            222         0     31.4681
00:02:17  SelectorSwitch                               10          2      OK              2         0      9.1217
00:02:42  SystemAndCustomEvents                         1          7      OK              7         0      0.0779

Total tests: 1093
Mon Dec 28 17:27:58 CET 2020; dzVents version 3.1.0 tested without errors after 00:02:42

```

**Review by rwaaren — APPROVED** [review]
Tested and OK for merge

**Review by gizmocuz — APPROVED** [review]
Thank you all again for this addon and changes !

**Pull request merged**
