### PR TITLE
Legrand EcoCompteur plugin

### PR DESCRIPTION
**Pull request by DenisMartin0**
I've written a hardware plugin for Legrand EcoCompteur 4 120 000 : a multizone kWh meter
https://www.amazon.fr/Legrand-LEG412000-Compteur-110-230-modules/dp/B016BBSEWC

It's currently supporting the 5 electrical channels from Current Transformers.
It's getting instantaneous power from inst.json and overall power consumption for each chanel from log2.csv

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the great work!

**Comment by sweetpants** [comment]
When compiling, i get errors on this commit
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp: In member function ‘void CEcoCompteur::GetScript()’:
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:139:72: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 1, 255, root["data1"].asFloat(), stod(fields[7]), "Conso 1");
                                                                        ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:144:72: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 2, 255, root["data2"].asFloat(), stod(fields[9]), "Conso 2");
                                                                        ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:149:73: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 3, 255, root["data3"].asFloat(), stod(fields[11]), "Conso 3");
                                                                         ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:154:73: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 4, 255, root["data4"].asFloat(), stod(fields[13]), "Conso 4");
                                                                         ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:159:73: error: ‘stod’ was not declared in this scope
   SendKwhMeter(m_HwdID, 5, 255, root["data5"].asFloat(), stod(fields[15]), "Conso 5");
                                                                         ^
CMakeFiles/domoticz.dir/build.make:1454: recipe for target 'CMakeFiles/domoticz.dir/hardware/EcoCompteur.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/hardware/EcoCompteur.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DenisMartin0** [comment]
I'm sorry guys, everything was ok here on my Win10 & VS2017, and the CI tests were also ok.
I've found some info on stackoverflow : 
https://stackoverflow.com/questions/20145488/cygwin-g-stdstoi-error-stoi-is-not-a-member-of-std
https://stackoverflow.com/questions/37138744/g-stod-was-not-declared-in-this-scope
https://stackoverflow.com/questions/20437984/error-stod-was-not-declared-in-this-scope?lq=1

Could you try to replace stod() by std::stod() ?
If there is still an issue, I'll try to replace this function.

**Comment by DenisMartin0** [comment]
I'll replace stod by strtod, I'm quite sure it will solve the issue because there is some calls to strtod in the project (and there is no stod )

**Comment by gizmocuz** [comment]
This has now been solved

**Pull request merged**
