### PR TITLE
[Satel Integra] optimization of the number of queries to hardware

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by szczukot** [comment]
Please check changes on www and HardwareController

**Comment by gizmocuz** [comment]
thanks for the patches, i review them tomorrow, did you test with windows/linux ?

**Comment by szczukot** [comment]
Under Win10 and Ubuntu

How can I may debugging domoticz under Raspberry PI ?

**Comment by gizmocuz** [comment]
those two will be OK.... for the raspberry pi, you need a raspberry pi, and compile on this

I review the changes tomorrow!
/Rob

**Comment by szczukot** [comment]
But how debugging (not compiling) on Raspberry PI ? Using logs ? Whats better ?

**Comment by gizmocuz** [comment]
I made the modifications locally

**Pull request closed without merging**
