### PR TITLE
If dimmer has value > 100%, set value to 100%

### PR DESCRIPTION
**Pull request by nayrnet**
Z-Wave dimmers @ 100% Brightness should report 100% and not 255%

### CODE REVIEW

**Comment by nayrnet** [comment]
with this patch when you pull a ZWave slider to 100% it stays there and status eventually changes from **100%** to **On**, the expected behavior.

**Comment by pp1984** [comment]
But why change from 100% to ON ? I Think that should 100% ON.

**Comment by gizmocuz** [comment]
That is correct, when you set a dimmer to 25%, then turn it off, then drag the slider to 255 (it will now send ON), it goes back to 25%

**Comment by nayrnet** [comment]
I think this is a bit cleaner of a fix, hopefully ready to merge.. testing on my end all weekend has been fine, no ill effects.

**Comment by nayrnet** [comment]
screen shot 2016-01-25 at 12 52 05 am

Would this be a problem? Shouldn't that say **On** instead of **Set Level 100%**

**Comment by nayrnet** [comment]
oops, I messed that cleaner fix up.. fixed my mistake
screen shot 2016-01-25 at 1 04 58 am
now everything works as should, bug squashed.

screen shot 2016-01-25 at 1 06 26 am

also found this closed issue related to this bug, going to mention it so its pinged. https://github.com/domoticz/domoticz/issues/324

**Comment by gizmocuz** [comment]
Thanks for the patch !

**Pull request merged**
