### PR TITLE
Small improvements of philips hue integration

### PR DESCRIPTION
**Pull request by emontnemery**
Fixes:
Optionally block new groups and scenes for Philips Hue (#2314)
Turn off when setting color with brightness 0 (#2332)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the changes !!
One (small) request, could you add two '#defines' in the .cpp file

```
#define USE_GROUPS 0x01
#define USE_SCENES 0x02
```

And then in the constructor use these for 'AddGroupsScenes' like:

```
m_add_groups = (AddGroupsScenes & USE_GROUPS) != 0;
m_add_scenes = (AddGroupsScenes & USE_SCENES) != 0;
```

Maybe change 'AddGroupsScenes' to a better name like 'iOptions' ?

**Comment by emontnemery** [comment]
@gizmocuz Thanks for reviewing! Your comments should now be fixed.

**Comment by gizmocuz** [comment]
Thanks! Are you sure this works:

m_add_groups = (Options & HUE_NOT_ADD_GROUPS) == 0

Should this not be != 0 ?

if (1 & 1) == 0 --> add groups ?

**Comment by gizmocuz** [comment]
Hmmm you are using reversed options... thats not so great... could you make it a bit enabled option field ? We might need more settings in the feature

**Comment by emontnemery** [comment]
Yes, the reason is to be backwards compatible, Mode2 is set to 0 by default.
Otherwise, a new database version + update code is needed to set Mode2 = HUE_ADD_GROUPS | HUE_ADD_SCENES.

**Comment by gizmocuz** [comment]
But you can change the value of mode2 ... even if it is 0, you could say, okey enable everything.
Or you can make a database patch (See SQLHelper) to set the default mode2 value to 0x03 ?

**Comment by emontnemery** [comment]
Exactly, I'll make the database patch to update default mode2 value.

**Comment by emontnemery** [comment]
@gizmocuz The options are now changed to be non-inverted

**Comment by gizmocuz** [comment]
Thanks!!!

**Comment by jonferreira** [comment]
Bit confuse wether this was publised to beta or not. I'm on 3.9398 and can't see any new options?

**Comment by emontnemery** [comment]
Yeah, should be in beta. Can you try in incognito tab to make sure it's not hidden due to browser cache not being refreshed?

**Comment by jonferreira** [comment]
I'll be damned, stupid cache!

Had to manually flush the cache and remove all application data for the thing to show up - simple ctrl + f5 wasn't enough!

Thanks

**Comment by Wob76** [comment]
Hi,

Update (solved?): I switched between a few of the standard themes, It options don't show on default or elemental themes (or non-standard ThinkTheme), but it they do show on element-dark, so ticked and working. Theme issue??

I have just installed a Hue Bridge, running Domoticz 3.9476. I don't see any scenes or groups being imported, I can see the settings, but no check boxes.

I restored the default theme, completed a full browser flush and tried incognito mode all without success. Any idea?

image

**Comment by emontnemery** [comment]
@Wob76 Yeah, @gizmocuz usually states only one theme is supported in beta (not sure which one that is though).

**Comment by gizmocuz** [comment]
@emontnemery , that is the default theme for now

**Comment by Wob76** [comment]
@gizmocuz "default" or "element-dark"? as I see the above issue with the "default" theme.

**Comment by gizmocuz** [comment]
@Wob76 , default theme
Scenes/Groups being imported does not have something to do with the theme ?

**Comment by jonferreira** [comment]
@gizmocuz think his problem is he doesn't see the options to enable Scenes / Groups...
@Wob76 you need to flush your browser application cache...In Firefox for example you do that on the settings page. After that when you open Domoticz you should see the usual "refreshing browser cache" message and you should see those options I reckon...

**Comment by gizmocuz** [comment]
In the settings you can hide/show the scene/groups

**Comment by jonferreira** [comment]
@gizmocuz exactly my point, he doesn't have that option (checkbox is missing) as per the above screenshot ... could be cache or something off on the theme

**Comment by gizmocuz** [comment]
The above screenshot is not from the settings page, but from the hardware setup

**Comment by jonferreira** [comment]
ah my bad @gizmocuz didn't realised that. I'm running 9462 and the options to show / hide Hue Scenes / Groups are in the Hardware setup

image

**Comment by gizmocuz** [comment]
I see, they are also gone here ;)
The solution is simple... moment

**Comment by gizmocuz** [comment]
Fixed, will be solved in an hour (or two)

**Comment by jonferreira** [comment]
nice! thanks @gizmocuz

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/commit/56688ba670547be76f756cfb552d01f51d27fbb6

**Pull request merged**
