### PR TITLE
Add sunscreen example script

### PR DESCRIPTION
**Pull request by bramstroker**
I've created a dzVents implementation of the sunscreen automation script found on the [wiki](https://www.domoticz.com/wiki/Smart_Lua_Scripts). Running it happily for a few days now at my home, so I'm glad to share it with the community. More example scripts will follow when they are stable.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks! I have not looked at the script code yet, but could you rename all dutch to english ?

**Comment by bramstroker** [comment]
Done

**Comment by gizmocuz** [comment]
I see in this screen that it is based on an UV sensor... could make sense indeed if it is placed in front of the window ;)
There is a small typo in the script (Check temerature sensor)

**Comment by bramstroker** [comment]
Yes, you could use your own UV sensor mounted on the outside. However I am using an UV sensor from a Weather Underground station 100 meter away from my home. It's working perfectly fine for me this way. When you don't want to control your sunscreen using UV measurements you can of course remove the conditional statement for the UV sensor.

Type is fixed

**Comment by remb0** [comment]
Wat (dutch volgende keer doe ik het EN, maar kan je geen pm of mail sturen:( )feedback (uit mijn script)  wat kan helpen je script nog beter te maken dan het al is.
hopelijk heb je er wat aan, anders pak ik jouw script als basis en vul ik hem aan.

1: lux binnen? (zodat bank niet verkleurd)

2: Scherm niet naar binnen als hij xx min eerder naar boven is gegaan.

3:
als iemand een switch heeft "iemand_thuis" op basis van presence detection,
dan ook ander gedrag.  aangezien je als je zelf in de tuin zit misschien zelf beter de regie in handen kan hebben.

4:
knop: zonwering_manual
zelfde doel als punt 3.

5:
op basis van buienradar kan je zien of het binnen 10 min gaat regenen.
anders alvast naar binnen of niet eens omhoog.
zodat je nooit telaat bent.

6:
binnentemp en jaargetijde meenemen?
in de winter kan het heel zonnig zijn maar wil je misschien liever niet dat hij uit gaat?

7:
als het scherm weer ingaat, wil je in de logging of notificatie misschien de reden zien.
waarschijnlijk bij iedere check reden opslaan. zodat in het daadwerkelijk open/dicht de reden(en) vermeld kunnen worden, ipv condities wel/niet voldaan.
op die manier kun je checken waarom een scherm beweegt en je tijdens een testfase kunt beoordelen of dit daadwerkelijk nodig was.

8:
wat als WU even geen actuele data heeft ?

9:
overige checks zoals NILL data's

**Comment by gizmocuz** [comment]
Yep... maybe you two can create one awesome dzEvent script... but you should be able to find each other on the forum ;)

**Comment by bramstroker** [comment]
@remb0 Thanks for your comments, definitely some good ideas here. I don't have much spare time on hand to implement all these wishes but will add them to my "domoticz todo list" :-). I want this initial script approved and merged so it can be used by the community. Than we can implement new features as new commits/PR's. 
Also it would be a good idea to implement some configuration flags in the script because not everyone needs these features. Than you can tweak the script to your wishes without the need to modify the script body.
About point 8. You definitely need to monitor that outside of the sunscreen scripting, or have your own sensors. It's not this script's responsibility to monitor for stable sensor data.

**Comment by gizmocuz** [comment]
Well it is a good idea to check if a sensor does not have a timeout (nothing is received) otherwise you will be working with wrong information
Point 2 is indeed a good idea.. imagine a change every minute... pfff
Point 3 that is a very smart idea and i think maybe a must have, you can create a switch that when switched it will go auto-off in lets say xx hours, when it is on, do bypass this script

**Comment by bramstroker** [comment]
@gizmocuz Ok will have a look into 2 and 3 soon. Maybe I have some time friday night or in the weekend.

**Comment by gizmocuz** [comment]
Great! Appreciated ;)

**Comment by remb0** [comment]
bramstroker I can't find you on the forum,  what your username?
We also working on a nice alarm script that would be very good customizable by users,  the trick is to make one script to rule them all,  and the hard part is that it's easy to read and configure.

I will help you, because I have already a very good script (in old lua style)  but with the posibilities of dzvents it can be much better.

**Comment by bramstroker** [comment]
@remb0 My username on the forum is bramski.
I can give you write access to my domoticz fork if you want than we can work on improving the sunscreen script, when it is production ready we can make a new PR to the domoticz develop branch.

**Comment by bramstroker** [comment]
Ok found some time and did a major rewrite of the script. It will be better maintainable now and introducing new features easier. Hope you like it.

**Comment by gizmocuz** [comment]
looking good, please test it a few days ;) (hoping for some sun... rain is nu issue here)

**Comment by bramstroker** [comment]
@gizmocuz I will be testing the script for a few days. Found a blocking bug and solved it, also improved some more code. I will give you a notice when everything works as expected. For now we can just leave the PR open if you like. Or close it and I will make another one when fully tested. What do you want?

**Comment by bramstroker** [comment]
@remb0 Can you also do some testing with this script? I have fixed some small issues today. When it is also working correctly for you we can get it merged asap.

**Comment by dannybloe** [comment]
Code looks good 😄

**Comment by bramstroker** [comment]
@dannybloe Thanks to your amazing work with the dzVents library of course ;-)

**Comment by gizmocuz** [comment]
Thanks! Give me a head-up when you want this merged

**Comment by remb0** [comment]
bramstroker:

Nice work!! I have setup all my parameters and got:
2017-08-13 11:51:00.525 dzVents: Info: Sunscreen: ------ Start internal script: Sunscreen:, trigger: every minute
2017-08-13 11:51:00.526 dzVents: Debug: Sunscreen: Device-adapter found for Sunscreen: Switch device adapter
2017-08-13 11:51:00.526 dzVents: Debug: Sunscreen: Processing device-adapter for Sunscreen: Switch device adapter
2017-08-13 11:51:00.527 dzVents: Debug: Sunscreen: Device-adapter found for Wu Uv: UV device adapter
2017-08-13 11:51:00.527 dzVents: Debug: Sunscreen: Processing device-adapter for Wu Uv: UV device adapter
2017-08-13 11:51:00.527 dzVents: Debug: Sunscreen: Checking sensor: uv
2017-08-13 11:51:00.527 dzVents: Debug: Sunscreen: Sensor not active skipping: lux
2017-08-13 11:51:00.528 dzVents: Debug: Sunscreen: Device-adapter found for Wu Wind: Wind device adapter
2017-08-13 11:51:00.528 dzVents: Debug: Sunscreen: Processing device-adapter for Wu Wind: Wind device adapter
2017-08-13 11:51:00.528 dzVents: Debug: Sunscreen: Checking sensor: wind
2017-08-13 11:51:00.529 dzVents: Debug: Sunscreen: Device-adapter found for Wu Rain: Rain device
2017-08-13 11:51:00.529 dzVents: Debug: Sunscreen: Processing device-adapter for Wu Rain: Rain device
2017-08-13 11:51:00.529 dzVents: Debug: Sunscreen: Checking sensor: rain
2017-08-13 11:51:00.530 dzVents: Debug: Sunscreen: Device-adapter found for IsItGonnaRain: Humidty device adapter
2017-08-13 11:51:00.530 dzVents: Debug: Sunscreen: Processing device-adapter for IsItGonnaRain: Humidty device adapter
2017-08-13 11:51:00.530 dzVents: Debug: Sunscreen: Checking sensor: rainExpected
2017-08-13 11:51:00.530 Error: dzVents: Error: Sunscreen: An error occured when calling event handler Sunscreen
2017-08-13 11:51:00.530 Error: dzVents: Error: Sunscreen: ...domoticz/scripts/dzVents/generated_scripts/Sunscreen.lua:28: attempt to compare number with nil
2017-08-13 11:51:00.530 dzVents: Info: Sunscreen: ------ Finished Sunscreen

The pushmessage tells me that UV treshold exceeded,   but line 28 is  return device.percentage > 15
And actual data on that sensor is:   Humidity 0 %

**Comment by remb0** [comment]
maybe it's handy to debug the value's?  

2017-08-13 12:26:00.242 dzVents: Debug: Sunscreen: : Device-adapter found for Daikin buitentemperatuur: Temperature device adapter
2017-08-13 12:26:00.242 dzVents: Debug: Sunscreen: : Processing device-adapter for Daikin buitentemperatuur: Temperature device adapter
2017-08-13 12:26:00.242 dzVents: Debug: Sunscreen: : Checking sensor: temperature

Only thing in debug now is that some sensors are not active.  But my screen isn't moving while I think all conditions are correct, no thresholds exceeded.  so it would be helpful that when running in test/debug  those values would be printed.

**Comment by bramstroker** [comment]
@remb0 Apparently you are using a humidity device for "rainExpected" sensor. It's kind of a strange devicetype to have for that as humidity doesn't have much to do with rainfaill. I have set it up to expect a percentage device. My rain expected device is setup as described in [this](https://www.domoticz.com/forum/viewtopic.php?t=13938) forum post. 

- You can set rainExpected sensor to active = false to test if everything else is working correctly.
- Than you can change your rainExpected to a percentage device or change the closeRule function to adapt to your device type and tresholds you want.

I am not sure why you get the push message UV treshold exceeded. Whenever you get this push message the same message is also added to the log with a log level INFO, maybe you can dig through your logs to find that record.

**Comment by remb0** [comment]
you are right about that sensors, I had it beforce percentage sensors where available:P

It looked that screenOn or Off function never called. But it was because my screen was already lowered.
Maybe some extra debug lines:
domoticz.log('Sunscreen is already down' , domoticz.LOG_INFO)
After checking device, show the current value. This value is also handy in notifications so you can adjust easier the tresholds.

Automatic sunscreen script is manually disabled      works fine!

maybe an extra feature: overrideManual.  when there is no presence (nobody home) and the screen is lowered and manual activated,  maybe after xxx Minutes this switch can be deactivated, so the system takes control again.

**Comment by bramstroker** [comment]
@gizmocuz Got this script running for a few weeks now and it's working perfectly fine for me. You can merge it.

**Comment by gizmocuz** [comment]
Great! Thanks (And all others) for the great work!

**Pull request merged**
