### PR TITLE
revert to using boost::bind instead of std::bind

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation issues with earlier versions of boost where the
placeholders are "ambiguous".

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
@neheb , I think this might be caused by the definition of (for example) webem_include_function in cWebem.h (as it is using boost::function)
Maybe if this was changed to non-boost, it will work/compile directly ? Would be a shame if we need to depend on boost for this...

**Comment by neheb** [comment]
Weird. In this PR: https://github.com/domoticz/domoticz/pull/4620 , I also have a similar commit as it wouldn't build. One of the commits there changes boost::function to std::function but same problem.

I'll look some more...

**Comment by gizmocuz** [comment]
Maybe if you also change the declaration in cWebem.h (replace the boost::function) it will work ?

**Comment by neheb** [comment]
No. The actual problem was fixed with boost 1.73. Internally in many boost headers, there's a using namespace boost::placeholders.

**Comment by neheb** [comment]
Yeah, the problem is in the asio headers, which cannot simply be removed: https://www.boost.org/users/history/version_1_73_0.html

**Comment by gizmocuz** [comment]
True, but if we could remove the boost bind dependency, we do not need this...

**Comment by neheb** [comment]
I can convert to lambdas. My original reasoning for not doing so is the size increase. But that can be offset by other changes.

**Comment by neheb** [comment]
Removed bind. These changes were done automatically.

**Comment by neheb** [comment]
Closing in favor of https://github.com/domoticz/domoticz/pull/4646

**Pull request closed without merging**
