### PR TITLE
HTTP/HTTPS client with the use of a lua parser

### PR DESCRIPTION
**Pull request by sbouchex**
HTTP/HTTPS client implementation:

Some details: The hardware is a HTTP/HTTPS client with several parameters: url, login, password, refresh rate and script name (command). The refresh rate defines how often the url is polled and the script is a lua script to which the polled data will be passed.

The user must create the virtual devices in order to have the ids and use these ids in the lua script.

The lua script is a lua parsers using the same lua functions as already implemented to parse using xpath (see #351) or json (see #347)

A complete example is provided in the example_owm.lua file (under script/lua_parsers)

see #614

### CODE REVIEW

**Comment by sbouchex** [comment]
Wait before merging, the use of the domoticz_createVirtualDevice is not nice. I will go to the same menu item as the virtual device where the user defines the device prior starting the script

**Comment by gizmocuz** [comment]
Thanks for the great patch !
Could you rename the class CHttp to something else (also the hardware type), as it is confusing
Make HTTPPoller ? (If thats a good name)

**Comment by sbouchex** [comment]
@gizmocuz, done ! I still have to write an article for the Wiki

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
Do you know if this could be related to your patch ?

http://www.domoticz.com/forum/viewtopic.php?f=6&t=11794

I can not find this sentence in domoticz (Cannot find the device) so i dont think so.. but just wanting to be sure ;)

**Comment by sbouchex** [comment]
No, it is not related to this patch

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gerard33** [comment]
@sbouchex thanks for this nice feature.
Is it possible to check the status of the virtual device in the lua parser?
I am using the http poller to check which song is playing on the Sonos, but would only like to update the virtual switch if the value differs from the value being polled.

**Comment by sbouchex** [comment]
@gerard33 I don't know if the lua call already exists in the API, but you may probably implement this by using "Blockly" or "Lua" events (Events in the "More options" section)

**Comment by gerard33** [comment]
@sbouchex I indeed use LUA scripts from where it is possible to check the status of a device in Domoticz (using for example ` targetvolume = otherdevices_svalues['Sonos kantoor volume']` to check the value of that switch).
But the LUA scripts from the LUA parser (in the directory domoticz/scripts/lua_parsers) can't use this information. I also tried to use the JSON interface to get the status (using curl), but that isn't working either.

The LUA parser contains for example the following code to update a device
`domoticz_updateDevice(484,'',s)`

My question is if there is a possibility to first check the value of that device in the LUA parser script (for example something like `domoticz_statusDevice(484)`?
So you only have to update the device if the new value differs from the current value.

**Comment by sbouchex** [comment]
@gerard33 It should be doable, I will add otherdevices, otherdevices_lastupdate, otherdevices_svalues, otherdevices_idx
@gizmocuz any objections or comments ?

**Comment by gizmocuz** [comment]
no objections, but i think all values should be available to poll from lua/python scripts, maybe there is something broke here?
I'm not the original author of the lua implementation, this was not the best design, i only extended things here
Also we are going more forward with the python implementation

**Comment by sbouchex** [comment]
@gizmocuz, In fact I'm the author of this and I did not export all variables in CLuaHandler::executeLuaScript so that's why it is requested.

**Comment by gizmocuz** [comment]
prefect

**Comment by sbouchex** [comment]
@gerard33 I have implemented your request, it's a branch called 'http_lua' in my 'domoticz' repository. If you can build & test it for me, tell me if it's working fine and I will send the PR.

**Comment by gerard33** [comment]
@sbouchex, thanks! I have build that version and it is working great!
Tested the following in the LUA parser:
- otherdevices
- otherdevices_svalues
- otherdevices_lastupdate

and those are all getting the right data from the device in Domoticz. So ready for PR :-)

Example of my LUA parser code:
```
--Sonos information
--{"kantoor":{"playing":"Uit"},"keuken":{"playing":"Uit"}}

--Retrieve the request content
s = request['content'];

--Update sonos (kantoor,1 and keuken 2) with playing information
local s_1 = domoticz_applyJsonPath(s,'.kantoor.playing')
local s_2 = domoticz_applyJsonPath(s,'.keuken.playing')

--Check the current value in Domoticz
s_3 = otherdevices['Sonos']
s_4 = otherdevices['Sonos 2']
--print('1: '..s_3)
--print('2: '..s_4)

if (tostring(s_1) == tostring(s_3)) then
	print('no update needed')
else
	domoticz_updateDevice(1,'',s_1)
end

if (tostring(s_2) == tostring(s_4)) then
	print('no update needed')
else
	domoticz_updateDevice(2,'',s_2)
end
```


P.S.
I got an error when running make on Ubuntu server 14.04. I have fixed this by copying an old version of HEOS.cpp and HEOS.h.
Has nothing to do with your changes, so just FYI.

`[ 48%] Building CXX object CMakeFiles/domoticz.dir/hardware/HEOS.cpp.o
In file included from /usr/include/boost/preprocessor/iteration/detail/iter/forw                          ard1.hpp:52:0,
                 from /usr/include/boost/signals2/preprocessed_signal.hpp:28,
                 from /usr/include/boost/signals2/signal.hpp:36,
                 from /usr/include/boost/signals2.hpp:19,
                 from /home/gerard/domoticz-test/hardware/DomoticzHardware.h:3,
                 from /home/gerard/domoticz-test/hardware/HEOS.h:3,
                 from /home/gerard/domoticz-test/hardware/HEOS.cpp:2:
/usr/include/boost/signals2/detail/signal_template.hpp:160:79: internal compiler                           error: Segmentation fault
         connection connect(const slot_type &slot, connect_position position = a                          t_back)
                                                                               ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
make[2]: *** [CMakeFiles/domoticz.dir/hardware/HEOS.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by gerard33** [comment]
@sbouchex 
Also did some regression testing with the built-in LUA editor (saw you made a small change to the event system as well).
That is also working fine.

```
commandArray = {}

s_1 = otherdevices['Sonos']
s_2 = otherdevices['Sonos 2']
print('1: '..s_1)
print('2: '..s_2)

s_3 = otherdevices_svalues['Sonos']
s_4 = otherdevices_svalues['Sonos 2']
print('3: '..s_3)
print('4: '..s_4)

s_5 = otherdevices_lastupdate['Sonos']
s_6 = otherdevices_lastupdate['Sonos 2']
print('5: '..s_5)
print('6: '..s_6)

return commandArray

```

Output:
```
2016-12-17 16:19:00.247 LUA: 1: Uit
2016-12-17 16:19:00.247 LUA: 2: Lyves - Visions
2016-12-17 16:19:00.247 LUA: 3: Uit
2016-12-17 16:19:00.247 LUA: 4: Lyves - Visions
2016-12-17 16:19:00.247 LUA: 5: 2016-12-17 16:07:37
2016-12-17 16:19:00.247 LUA: 6: 2016-12-17 16:17:09
```

**Pull request merged**
