### PR TITLE
[BleBox] support for tempSensor

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by szczukot** [comment]
I have a big problem. Where can I save IP address for temp sensor ? 
In method CDomoticzHardwareBase::SendTempSensor i see:
	tsen.TEMP.id1 = (NodeID & 0xFF00) >> 8;
	tsen.TEMP.id2 = NodeID & 0xFF;
That only 2 bytes used :(
This same problem exist for example for 1wire: 
https://www.domoticz.com/forum/viewtopic.php?t=10808

**Comment by gizmocuz** [comment]
@szczukot , 1wire is kind of the same problem, but not quite
You have the option for 65K ID's, that should be enough, i won't expect one BleBox user to have a conflict?
You can use the 'WOLNodes' table, table needs to be renamed, but hardware is using this as helper table.
Is it possible you could undo the formatting changes ? The formatting was just find (switch/case for example)
If you are in visual studio, and press in your document control-k then control-d it will format it back
(Depending on the Visual Studio options)

**Comment by gizmocuz** [comment]
Question, why do you need to save IP address ?
If you use the last two numbers as ID, should that not be clear enough ?

**Comment by szczukot** [comment]
All devices used different IP.
Ok - i check WOLNodes table.

Formatting: I used always CTRL+K+D. But sometimes You have different formating (https://github.com/domoticz/domoticz/commit/b60437c400656aa96f08019a83d32b4bd1bf2b2d)

**Comment by gizmocuz** [comment]
The above commit just makes clear code, is not about indent spacing (tabs/spaces)
(Sorry i meant indent/spacing before)

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
