### PR TITLE
Updated History-file

### PR DESCRIPTION
**Pull request by EddyK69**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks, i probably going to walk though all commits and update the history file before making a stable release

**Comment by EddyK69** [comment]
Ah, was hoping you should do that :D

**Comment by gizmocuz** [comment]
New stable milestone is set on 29th feb

**Comment by EddyK69** [comment]
Good to know. Thumbs up!

**Comment by gizmocuz** [comment]
Did you see
https://github.com/domoticz/domoticz/issues/418

**Comment by EddyK69** [comment]
I just did. Nice!

**Pull request merged**
