### PR TITLE
Refactor webserver server class

### PR DESCRIPTION
**Pull request by gaudryc**
What it is changing :
- Refactor the webserver server class to separate the HTTP and HTTPS implementation, and gather all server settings in the new server_settings and ssl_server_settings classes.
- Add -sslmethod, -ssloptions and -ssldhparam arguments to domoticz executable.
- Fix the webserver not stopping and not restarting issue after an exception occurred.
- Fix multiple session cleaner start after restarting webserver.
- Define webserver default settings in one place (mainworker).
- Manage enabled/disabled server in one place (server_settings::is_enabled()).

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks !!!

**Comment by gizmocuz** [comment]
Got some build errors

> In file included from /home/travis/build/domoticz/domoticz/main/../tcpserver/../webserver/server.hpp:14:0,
>                  from /home/travis/build/domoticz/domoticz/main/../tcpserver/../webserver/cWebem.h:6,
>                  from /home/travis/build/domoticz/domoticz/main/../tcpserver/../webserver/proxyclient.h:12,
>                  from /home/travis/build/domoticz/domoticz/main/../tcpserver/TCPClient.h:7,
>                  from /home/travis/build/domoticz/domoticz/main/../tcpserver/TCPServer.h:4,
>                  from /home/travis/build/domoticz/domoticz/main/mainworker.h:11,
>                  from /home/travis/build/domoticz/domoticz/main/Camera.cpp:7:
> /home/travis/build/domoticz/domoticz/main/../tcpserver/../webserver/server_settings.hpp: In member function ‘boost::asio::ssl::context_base::options http::server::ssl_server_settings::get_ssl_options() const’:
> /home/travis/build/domoticz/domoticz/main/../tcpserver/../webserver/server_settings.hpp:180:26: error: ‘no_tlsv1_1’ is not a member of ‘boost::asio::ssl::context’
> /home/travis/build/domoticz/domoticz/main/../tcpserver/../webserver/server_settings.hpp:182:26: error: ‘no_tlsv1_2’ is not a member of ‘boost::asio::ssl::context’

**Comment by gizmocuz** [comment]
fixed
https://github.com/domoticz/domoticz/commit/8bc90d1d005e6f84a5846bb304a34edfed80fa3f

**Comment by gizmocuz** [comment]
Could there be an issue ?
http://www.domoticz.com/forum/viewtopic.php?f=6&t=10704

https://www.domoticz.com/forum/viewtopic.php?f=6&t=10705&start=20

https://github.com/domoticz/domoticz/commit/bac78dd637f194e2046230716b6490e3e1186155#commitcomment-16250929

**Comment by rkluwen** [comment]
The first issue seems unrelated and not a bug, just informational for something that is intended to be.
The second one does seem to be an issue. I tested on Windows and it works. Right now compiling on the pi to see what happens there.

**Comment by gizmocuz** [comment]
I have it running on my cubietruck , http works, https does not

```
2016-02-23 08:54:48.372  Webserver(HTTP) started on port: 8080
2016-02-23 08:54:48.379  Webserver(SSL) started on port: 443
2016-02-23 08:54:48.383  Error: [web:443] missing SSL certificate chain file parameter !
2016-02-23 08:54:48.384  Proxymanager started.
2016-02-23 08:54:48.386  Error: [web:443] missing SSL private key file parameter !
2016-02-23 08:54:48.387  Error: [web:443] missing SSL DH file parameter
2016-02-23 08:54:48.389  Error: WebServer(SSL) exception occurred : 'bind: Permission denied'
2016-02-23 08:54:48.390  WebServer(SSL) restart server in 5 seconds
2016-02-23 08:54:48.391  Starting shared server on: :::3201
```

it does not crash here...

**Comment by gizmocuz** [comment]
On my raspberry pi it is crashing too, it runs, but cant access the web server

it keeps restarting the web server in 5 seconds

2016-02-23 08:59:45.182  Webserver(HTTP) started on port: 8080
2016-02-23 08:59:45.186  Error: WebServer(HTTP) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-23 08:59:45.186  WebServer(HTTP) restart server in 5 seconds
2016-02-23 08:59:45.188  Webserver(SSL) started on port: 443
2016-02-23 08:59:45.190  Error: [web:443] missing SSL certificate chain file parameter !
2016-02-23 08:59:45.191  Proxymanager started.
2016-02-23 08:59:45.193  Error: [web:443] missing SSL private key file parameter !
2016-02-23 08:59:45.193  Error: [web:443] missing SSL DH file parameter
2016-02-23 08:59:45.193  Error: WebServer(SSL) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-23 08:59:45.194  WebServer(SSL) restart server in 5 seconds
2016-02-23 08:59:45.196  Starting shared server on: 0.0.0.0:6144
2016-02-23 08:59:45.196  TCPServer: shared server started...
2016-02-23 08:59:45.197  RxQueue: queue worker started...
2016-02-23 08:59:47.197  Hardware Monitor: Started
2016-02-23 08:59:47.198  EventSystem: reset all events...
2016-02-23 08:59:47.199  EventSystem: reset all device statuses...
2016-02-23 08:59:47.202  EventSystem: Started
2016-02-23 08:59:50.187  Error: WebServer(HTTP) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-23 08:59:50.187  WebServer(HTTP) restart server in 5 seconds
2016-02-23 08:59:50.195  Error: WebServer(SSL) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-23 08:59:50.195  WebServer(SSL) restart server in 5 seconds

**Comment by gizmocuz** [comment]
I am reverting, we can always go back with

git reset --hard commitid
git reset --soft HEAD@{1}
git commit -m "..."
git push

**Comment by gaudryc** [comment]
Could you give me your command line arguments (-www... and -sss...) ?

**Comment by gaudryc** [comment]
OK I know where the problem is (in the server_settings::set method)

**Comment by gizmocuz** [comment]
the commandline arguments where the defaults like -www 8080 -wwwssl 443

**Comment by gaudryc** [comment]
I don't understand how you got "Error: WebServer(HTTP) exception occurred : 'resolve: Host not found (authoritative)'" without setting something wrong in the argument -wwwbind.

**Comment by gizmocuz** [comment]
It is the default Domoticz.sh file in the repo

**Comment by gaudryc** [comment]
I'm in trouble with git :-)

**Comment by gaudryc** [comment]
I lost everything

**Comment by gizmocuz** [comment]
no problem, you can always checkout a specific commit

**Comment by gaudryc** [comment]
I tried almost everything yesterday without success.
I didn't found the magic command to apply my commits to the last master checkout.

**Comment by gizmocuz** [comment]
I think you could have checked out the commit from the master where your pull request was merged
What i did to revert was check out the commit before this pull request, made this actual and pushed it (see the above commands)
Hope that was the right way...

**Pull request merged**
