### PR TITLE
Prepare for integration of evohome client

### PR DESCRIPTION
**Pull request by gordonb3**
I'm planning to integrate Evohome client ([see project here](https://github.com/gordonb3/evohomeclient)) into Domoticz. This requires separating the HGI80 specific workers from the current all-in-1 code.

Note: this is work in progress. There are no real changes in this commit yet. It only splits the current evohome.cpp and evohome.h in two and corrects the static references in mainworker and RFXNames.

### CODE REVIEW

**Comment by gordonb3** [comment]
Scripted evohome now moved to its own class. Obsolete lines in evohome serial deleted and references in mainworker revised.

**Comment by gordonb3** [comment]
AppVeyor seems to fail because the msbuild files are not synched?

**Comment by gizmocuz** [comment]
Yes, if you add/delete files, you also need to do this in the visual studio project files

**Comment by gordonb3** [comment]
Unsure how to do that. Only reference to the old file appears to be in `msbuild/domoticz.vcxproj.filters` which I did alter and include in this push. AppVeyor still references the old file though, likely because it respects the gitignore on msbuild.

**Comment by gizmocuz** [comment]
No, its not only in the filters, just search the whole domoticz source/msbuild folder for files containing the .cpp file
It should be in 'domoticz.vcxproj' also

**Comment by gordonb3** [comment]
Now how did I miss that?

**Comment by gordonb3** [comment]
Right. That got fubarred because of changes to the deleted file.

Resuming [here](1532)

**Pull request closed without merging**
