### PR TITLE
correct for broken lua pkg-config

### PR DESCRIPTION
**Pull request by gordonb3**
Standard Lua 5.2 pkg-config does not correctly return the include path and library name. If the distro did not create links to provide backward compatibility with older Lua (if the API itself wasn't changed as well) then we need to find these ourselves.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gordonb3** [comment]
Sloppy....

On line 67 the ENDIF argument does not match the IF argument (~NOT~ LUA_INCLUDE_DIRS) causing a cmake warning at build time. Can you add the missing `NOT`?

**Comment by gizmocuz** [comment]
Sure, done in this commit
https://github.com/domoticz/domoticz/commit/af1acd4a0024dee986622846221660d85a9506fa

**Comment by gordonb3** [comment]
Thanks

**Pull request merged**
