### PR TITLE
MySensors groupID with verbose log

### PR DESCRIPTION
**Pull request by BmdOnline**
I have improved groupID detection (checking nodeID, just in case).
I have added verbose log, for debugging purpose :
✔️ Inform groupID assignment at startup (LoadDevicesFromDatabase)
✔️ Inform of groupID usage when trying to group childs (FindChildWithValueType)

### CODE REVIEW

**Comment by gizmocuz** [comment]
I can't except all that logging, but can you place them in #ifdef _DEBUG lines ?
Then everyone building in debug mode can see the log messages

**Comment by gizmocuz** [comment]
I can't except all that logging, but can you place them in #ifdef _DEBUG lines ?
Then everyone building in debug mode can see the log messages

**Comment by gizmocuz** [comment]
I can't accept all that logging, but can you place them in '#ifdef _DEBUG' lines ?
Then everyone building in debug mode can see the log messages

**Comment by BmdOnline** [comment]
I suspected it.
For now, I don't know how to debug users who don't know how to compile by themselves.

I'm looking for another method...
Do you have a way, for example, to share user's database, extract some table contents, or something else ?

**Comment by gizmocuz** [comment]
Unfortunately not, you could ask the user to go to the settings page, and export the database
If he/she does not trust this, because there is some personal information in this, he/she can open the exported database with for example 'SQLite Expert Personal Edition' and clear/delete the preferences table

**Pull request closed without merging**
