### PR TITLE
Fixes for the Nest OAuth plugin

### PR DESCRIPTION
**Pull request by dotms**
This pull request is a followup on the Nest OAuth plugin pull request (#2095, #2026).

Changes:
- Did some cleanup
- Expanded on error handling
- Improved logging
- Implemented manual eco mode for a thermostat
- Fixed away mode which was entirely broken

Should be fully functional with no known broken features.
Reference: (http://www.domoticz.com/forum/viewtopic.php?f=34&t=17370)

Putting in this pull request now to prevent build issues later on. I think it's best not to pull this one right away, let's wait for some test results.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Let us know when you would like this to be merged... Unfortunately I can't verify the changes..

**Comment by dotms** [comment]
Thanks. Since it's difficult to get people to actually test it, I'll leave it running this week in my own test environment. If I don't run into any problems it will probably be decent enough for testing in an official development build :)  I'll follow up then.

**Comment by dotms** [comment]
During this week I have not discovered any irregularities in the plugin. This pull request can be merged :)

**Comment by gizmocuz** [comment]
Thanks for the great patch!

**Pull request merged**
