### PR TITLE
Update EnOceanESP2.cpp

### PR DESCRIPTION
**Pull request by stephaneguillard**
Added NodOn and Ewattch manufacturer codes

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!, Does this also need in EnOceanESP3.cpp ?

**Comment by stephaneguillard** [comment]
No, there is a single manufacturer table for the two files, EnOceanESP3.cpp uses Get_EnoceanManufacturer() from EnOceanESP2.cpp

**Comment by stephaneguillard** [comment]
(cool, my 1st ever github stuff, and 1st ever domoticz public change :)

**Comment by gizmocuz** [comment]
Thanks for the patch !

**Pull request merged**
