### PR TITLE
Fix </a> tags for DashboardController.js

### PR DESCRIPTION
**Pull request by kovainfo**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could you show us a screenshot of before and after ? Seems the name needs to be in the <a> {name} </a> tag, you removed this

**Comment by kovainfo** [comment]
previously (before #2729) the name was out of the tag. after #2729 the name of some devices became in the tag. it's not beautiful. It should be monotonous.

**Comment by gizmocuz** [comment]
Ahhh this clears things up! Thanks for the patch, will merge this!

**Comment by gizmocuz** [comment]
need to revert this as PR 2729 needs to be reverted

**Pull request merged**
