### PR TITLE
Lots of fixes and improvements on Teleinfo support thanks to forum feedback

### PR DESCRIPTION
**Pull request by DebugBill**
- Peak/OffPeak indexes swaped in P1 meters
- Update rate greatly reduced to avoid clogging database
- IMAX information now ignored
- PPOT (triphasé only) now handled
- Messages in alerts are now properly handled and will not cause crashes. Problem was with object lifetime being to short to be consumed by asynchronous thread
- Texts are (I hope) more explicit
- Wiki is updated
and more....

### CODE REVIEW

**Comment by szczukot** [comment]
Repair you bugs you made in other modules !
https://www.domoticz.com/forum/viewtopic.php?f=6&t=16727

**Comment by DebugBill** [comment]
Good morning.

I did not see your message in the other merge. I guess GitHub does not send alerts for new messages in a closed merge.

I don't have Multifun or Satel hardware so I can't test for side effects. I can only do my best to avoid them.
There was definitely a race condition between threads that explains those crashes. It is now fixed I think (but not merged yet. If you're in a hurry you can clone my fork directly)

Beta versions and beta testers are meant exactly for this purpose: spoting such issues and fix them before they go to general public

Have a nice day

**Comment by gizmocuz** [comment]
Thanks, but i will limit the text string to 64, as it is also send over the internet, should be enough for a clean and simple message ?

**Comment by gizmocuz** [comment]
Done here
https://github.com/domoticz/domoticz/commit/06c84bf2aa3e25ab4c24970127db84fa9f3e3672

**Comment by gizmocuz** [comment]
@szczukot, please try to stays nice, we all get frustrated some times

**Comment by DebugBill** [comment]
I used 200 because that's the size of the database record it goes to, but 64 is definitely enough

**Comment by gizmocuz** [comment]
Seems there was a change from one file not committed
https://github.com/domoticz/domoticz/commit/613cd0e70fcef358dee732591b30a84f2f3c21d1
(now the limitis 64)

**Comment by gizmocuz** [comment]
Is it possible to have a quick look in this forum thread? It could be it is not working for all users:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=18606

**Comment by lstep** [comment]
About "IMAX information now ignored", I don't think it works. On my EDF meter, using Domoticz v3.8153, I get continuous errors about the IMAX info:

```
2017-07-30 21:28:51.339 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:28:53.432 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:28:55.526 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:28:57.620 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:28:59.729 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:01.823 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:03.915 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:06.009 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:08.102 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:10.211 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:12.303 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
2017-07-30 21:29:14.397 Error: Frame #PMAX 17480:# passed the checksum test but failed analysis
```

I also get these messages (not sure it's related):

```
2017-07-30 21:28:51.452 (edf) Teleinfo CRC check mode set to 1
2017-07-30 21:28:53.432 (edf) TeleinfoCRC check mode set to 2
2017-07-30 21:28:53.544 (edf) Teleinfo CRC check mode set to 1
2017-07-30 21:28:55.526 (edf) TeleinfoCRC check mode set to 2
2017-07-30 21:28:55.653 (edf) Teleinfo CRC check mode set to 1
2017-07-30 21:28:57.620 (edf) TeleinfoCRC check mode set to 2
2017-07-30 21:28:57.747 (edf) Teleinfo CRC check mode set to 1
2017-07-30 21:28:59.729 (edf) TeleinfoCRC check mode set to 2
2017-07-30 21:28:59.841 (edf) Teleinfo CRC check mode set to 1
2017-07-30 21:29:01.823 (edf) TeleinfoCRC check mode set to 2
2017-07-30 21:29:01.934 (edf) Teleinfo CRC check mode set to 1
2017-07-30 21:29:03.915 (edf) TeleinfoCRC check mode set to 2
2017-07-30 21:29:04.027 (edf) Teleinfo CRC check mode set to 1
```

**Pull request merged**
