### PR TITLE
Temporary - for testing Satel Integra

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by gizmocuz** [comment]
please make a private repo, and build domoticz locally instead of pushing debug changes in the main repo
setting up the build environment in windows is pretty easy, and you can set breakpoints

**Comment by szczukot** [comment]
Bur when i compiling on my hardware (Raspberry PI and Ubuntu) this code is working !
Only compiled package from You dont'work :(
How can I find bug without changing mainworker.cpp ??

**Comment by szczukot** [comment]
Hmmm. I downloaded latest version and reporting zones working again.
Last time on log i have only :
2015-09-20 09:01:41.234 Satel Integra: Report Zone 31 = 1
and nothing else. This is last line in my code, when i sending signal.
Now i have :
2015-09-26 09:23:49.191 Satel Integra: Report Zone 31 = 1
and from your code :
subtype = Alert
Alert = 1
2015-09-26 09:23:49.191 (Satel) General/Alert (Zone:pokoj parter pir)
Its work now ?!?

**Comment by gizmocuz** [comment]
i dont know.... you have to test
also remember my above message, it could be that your changes where not in the latest beta version

**Pull request closed without merging**
