### PR TITLE
EnOcean setup screen cosmetics

### PR DESCRIPTION
**Pull request by efdeb**
Minor PR.
Some cosmetics adjustments to the new EnOcean setup screen.
No functional changes.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR!
You can not add translation files here. If you have new words/sentences please mention them here so I can add them to the list and translators can translate them on Transifex

**Comment by efdeb** [comment]
Here are the new strings that need to be added to the translation system.
For these I suggested appropriate french translations (ans also small fixes of existing translations).

**New text, with suggested french translation :**
"Generic": "Générique",
"Teached-in": "Associé",
"Virtual": "Virtuel",
"Manufacturer": "Fabriquant",
"Hardware controller": "Contrôleur matériel",
"EnOcean Profile": "Profil EnOcean",
"EnOcean learn mode": "Mode apprentissage EnOcean",
"Problem enabling learn mode!": "Echec de l'activation du mode apprentissage !",
"Learn mode timed out!": "Expiration du délai d'apprentissage !",
"Problem teachin-in node!": "Echec de l'apprentissage du nœud !",
"Teach-in your EnOcean node according to it's documentation...": "Enregistrer le nœud EnOcean, selon sa documentation...",
"New EnOcean node teached-in": "Nouveau nœud EnOcean enregistré",
"No new EnOcean node teached-in!": "Aucun nœud EnOcean enregistré !",
"Resetting EnOcean controller...": "Réinitialisation du contrôleur EnOcean...",
"Problem resetting EnOcean controller!": "Echec de la réinitialisation du contrôleur EnOcean !",
"Please enter a node name!": "Veuillez saisir le nom du nœud !",
"Please select a manufacturer!": "Veuillez selectionner le fabriquant du nœud !",
"Please select an EnOcean Profile (EEP)!": "Veuillez selectionner un profil EnOcean (EEP) !",
"Are you sure you want to update node": "Confirmez-vous la mise à jour du nœud",
"Are you sure you want to delete node": "Confirmez-vous la suppression du nœud",
"and all it's devices?": "et des dispositifs associés ?",
"Problem deleting node": "Echec de la suppression du nœud",

Updated french translations (better translations, I think -I am french-)
"Node management": "Gestion des nœuds",
"Status": "Etat",
"Include node": "Inclure le nœud",
"NodeID": "ID Nœud",

**Comment by gizmocuz** [comment]
I will have to add them to the English file and upload it to transifex so everyone can translate them

Do these two need a question mark at the end ?

"Are you sure you want to update node": "Confirmez-vous la mise à jour du nœud",
"Are you sure you want to delete node": "Confirmez-vous la suppression du nœud",

**Comment by efdeb** [comment]
I have the question mark hard coded in the js file, so we don't need it in the translation.
But I can change this if preferred.

**Comment by gizmocuz** [comment]
If this is the whole sentense yes then please

**Comment by efdeb** [comment]
After checking, I have to left it as is, because the strings in js file include a dynamic nodeID: 
$.t("Are you sure you want to update node") + " \'"+ nodeidStr + "\'?"
$.t("Are you sure you want to delete node") + " \'" + nodeidStr + "\' " + $.t("and all it's devices?")

OK for you ?

**Comment by gizmocuz** [comment]
Sure, I will add the translation to the English file and upload it to Transifex

**Comment by gizmocuz** [comment]
I updated the translations in the development branch. (And translated it for Dutch)
If possible, please also translate them to French

https://www.transifex.com/domoticz/domoticz/dashboard/

**Comment by efdeb** [comment]
OK thanks.
I created an account on transifex, but I think I nees somme approval before I can translate to french ?

**Comment by efdeb** [comment]
OK thanks.

I created an account on transifex, but I think I need somme approval before I can translate to french ?
=>
Found how it works. Will look after it quickly !
=>
Done for french !

Anyway, you can merge the pull request now limited to the cosmetics part, and the translation shall come later on.

**Comment by gizmocuz** [comment]
Thank you!!

**Pull request merged**
