### PR TITLE
Fix inverted door lock status

### PR DESCRIPTION
**Pull request by david81**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Sorry, this is not a fix.
- It might work for you, surely not for me, as mine is correct. You need a new type, or a flag
- I also don't think the icon state will be correct? (Maybe it is ?)

**Comment by david81** [comment]
Ok. There were multiple forum threads regarding this issue with no one stating that it was correct for them, so I assumed it as incorrect for everyone.

**Comment by david81** [comment]
How are the options for each switch type defined (different switch types have different options that can be set)? Perhaps adding a flag to invert status here would be the "proper" fix to allow the current switch type to work for everyone?

**Comment by gizmocuz** [comment]
A code fix has to be made on multiple places in the c++ code and html code

**Pull request closed without merging**
