### PR TITLE
Security related translations and Info icon

### PR DESCRIPTION
**Pull request by kiddigital**
Updated some translations in EN file
Added Info icon on Security tab with link to Wiki Security page

### CODE REVIEW

**Comment by gizmocuz** [comment]
Maybe change the translation of SecuritySetup to 'Visit <this> page for more information about Security Setup' ?

**Comment by kiddigital** [comment]
> Maybe change the translation of SecuritySetup to 'Visit page for more information about Security Setup' ?

Do you mean the the name of the Tab to this long sentence?

Make sense if it would be a mouse-over help text, but I do not know how to do that :(

**Comment by gizmocuz** [comment]
No sorry, just in the settings page underneath the Security section where you have the Trustred Networks

**Comment by kiddigital** [comment]
Done, looks as followed now
image
So both at the top (i) and at the bottom are both links to the [Security page](https://www.domoticz.com/wiki/Security) at the Wiki.

**Comment by gizmocuz** [comment]
Looking good! I will update transifex after merging and do the Dutch translation

**Pull request merged**
