### PR TITLE
Teleinfo: Basic support for standard mode (Linky)

### PR DESCRIPTION
**Pull request by mce35**
Add basic support for standard mode (Linky) for the Teleinfo plugin
Only "Base" has been tested, HC/HP and triphase may work, no support for EJP.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR. Could you please use the trim functions in our helper class? (helper.h/cpp)

**Comment by mce35** [comment]
> Thank you for this PR. Could you please use the trim functions in our helper class? (helper.h/cpp)

sorry, I did not see these functions, fixed.

**Comment by gizmocuz** [comment]
Thank you for the PR and the changes!

**Comment by gizmocuz** [comment]
I need to revert this PR at it seems to brake the current implementation see issue

https://github.com/domoticz/domoticz/issues/5066

**Comment by gizmocuz** [comment]
Maybe it is not related as there still seems to be an issue ?

**Comment by knasson** [comment]
did not work when using both historic and Standard
"2022-08-16 07:47:50.317 Error: Production_solaire: CRC check failed on Teleinfo line 'EASD03 0000000000 #' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:50.353 Error: Production_solaire: CRC check failed on Teleinfo line 'EAIT' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:50.513 Error: Production_solaire: CRC check failed on Teleinfo line 'RQ ^ ' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:50.663 Error: Production_solaire: CRC check failed on Teleinfo line 'SISTS 00000 F' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:50.727 Error: Production_solaire: CRC check failed on Teleinfo line 'SM' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:50.765 Error: Production_solaire: CRC check failed on Teleinfo line 'SMAXS-1 E220' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:50.864 Error: Production_solaire: CRC check failed on Teleinfo line 'SMAXIN.' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.060 Error: Production_solaire: CRC check failed on Teleinfo line 'M MESSAGE <' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.108 Error: Production_solaire: CRC check failed on Teleinfo line 'PM 1<' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.203 Error: Production_solaire: CRC check failed on Teleinfo line 'RELAIS 000' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.235 Error: Production_solaire: CRC check failed on Teleinfo line 'NJOURF+1 00 ' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.379 Error: Production_solaire: CRC check failed on Teleinfo line 'PJOURF+1 00008001 NONUTILE ONUTIL' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.537 Error: Production_solaire: CRC check failed on Teleinfo line 'VTIC 02 J747 NUR .' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.617 Error: Production_solaire: CRC check failed on Teleinfo line 'LTARF INDEX NON CON00000394 _' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:51.778 Error: Production_solaire: CRC check failed on Teleinfo line 'E4 20 #0000000 %' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:52.026 Error: Production_solaire: CRC check failed on Teleinfo line 'EAF09 000000000 * "' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:52.058 Error: Production_solaire: CRC check failed on Teleinfo line 'ASD01 000000394 0' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:52.534 Error: Production_solaire: CRC check failed on Teleinfo line 'SISTS 00000 F' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:52.673 Error: Production_solaire: CRC check failed on Teleinfo line 'SMAXSN E220816064133 00020 05071652 00020 Q' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:52.729 Error: Production_solaire: CRC check failed on Teleinfo line 'SMAXIN.' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:52.867 Error: Production_solaire: CRC check failed on Teleinfo line 'MOY1.=' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:53.073 radiateursalon2kw(Inv): onHeartbeat called
2022-08-16 07:47:53.000 Error: Production_solaire: CRC check failed on Teleinfo line 'MSG1 MESSAGE <527 <' using both modes 1 and 2. Line skipped.
2022-08-16 07:47:53.032 Error: Production_solaire: CRC check failed on Teleinfo line 'NARF' using both modes 1 and 2. Line skipped.

**Comment by mce35** [comment]
@knasson it seems that you are having communication issues, some characters are missing in some lines, some lines have non printable charaters, ...
How are you connecting the linky to your serial port?

**Comment by knasson** [comment]
The linky is connected via a tindie USB interface.
https://www.tindie.com/products/hallard/pitinfo/
On ttyUSB0.
I am trying to shorten the cable between the linky and the interface.
More than the errors log i observe no creation of "dispositifs" in domoticz.
Please notice that the plugin is working perfectly with the "historic" mode
of the linky.
 Have you any positive feedbacks on the standard mode?

Regards

jean-Claude Gaubertier

**Comment by mce35** [comment]
I don't know this specific device, but the description mentions:
```
Product back in stock, now release V1.3a, it's the same than V1.3, **just resistors changes**, see History section below

Still compatible with Linky Standard (9600BPS) and Historique (1200BPS) modes
```
I have a homemade circuit (same principle as this one) to connect my Linky, and when I switched to standard mode I had to change some resistors as well (lower values). This is because the signal in standard mode is weaker than in "Historique" mode. You can try to decrease the cable length. According to your logs it could work has most of the data seems correct.
If you do not have v1.3a of this board this may explain why it is not working properly (I guess v1.3 should also work but maybe not the others).

The plugin only creates devices in Domoticz when it is able to decode the lines containing actual data. If nothing can be decoded then no devices are created. Also note that if you were previously using "Historique" mode the plugin will re-use the existing devices and not create new ones (except for the new devices that were not available in "Historique" mode).

**Comment by knasson** [comment]
Thank you for Lightening me about the new devices creation in standard mode En historic mode i have 5 devices created :Teleinfo kWh Heures CreusesTeleinfo kWh Heures PleinesTeleinfo kWh TotalTeleinfo  CourantTeleinfo Pourcentage de Charge What will be the new eventual devices created in stand ard mode ?The link for the USB dongle i gave you previously  was wrong the good one here http://hallard.me/utinfo/Some resistance had already been changed.The test with picocom as explained in the description is OK.I tested to day a shorter cable (about 20 cm) and the plug of my dongle on a USB cable in order to push away the dongle from the Raspberry.The result is the same CRC errors. De : mce35Envoyé le :mercredi 17 août 2022 23:39À : domoticz/domoticzCc : knasson; MentionObjet :Re: [domoticz/domoticz] Teleinfo: Basic support for standard mode (Linky) (PR #5045) I don't know this specific device, but the description mentions:Product back in stock, now release V1.3a, it's the same than V1.3, **just resistors changes**, see History section below Still compatible with Linky Standard (9600BPS) and Historique (1200BPS) modesI have a homemade circuit (same principle as this one) to connect my Linky, and when I switched to standard mode I had to change some resistors as well (lower values). This is because the signal in standard mode is weaker than in "Historique" mode. You can try to decrease the cable length. According to your logs it could work has most of the data seems correct.The plugin only creates devices in Domoticz when it is able to decode the lines containing actual data. If nothing can be decoded then no devices are created. Also note that if you were previously using "Historique" mode the plugin will re-use the existing devices and not create new ones (except for the new devices that were not available in "Historique" mode).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by mce35** [comment]
Here are my teleinfo devices, new devices are in the red box:
image

I have made the previous version of this adapter (i.e. without the MOSFET), but it was not working with the resistors value given (10K and 4.7K), I don't have access to my schema right now, I will get back to you later today with the values I have.

**Comment by knasson** [comment]
Very clear, but i don’t see the injected Energy instant and total (SINSTI,EAIT) ?I will be very pleased to see you schema. Regardsknasson De : mce35Envoyé le :jeudi 18 août 2022 13:55À : domoticz/domoticzCc : knasson; MentionObjet :Re: [domoticz/domoticz] Teleinfo: Basic support for standard mode (Linky) (PR #5045) Here are my teleinfo devices, new devices are in the red box:I have made the previous version of this adapter (i.e. without the MOSFET), but it was not working with the resistors value given (10K and 4.7K), I don't have access to my schema right now, I will get back to you later today with the values I have.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by mce35** [comment]
Injected power is displayed in the same device as the power usage:
(Apparent power is negative when power is sent to the grid)
image

image
(Injected power is in green)

Here is my schema:
image

Notes:
 - D1 is here because I used a different optocoupler which doesn't have it integrated (SFH620 is not so easy to find)
 - Original value of R2 is 3K3, I replaced it with 470R. This is the most important resistor.
 - Original value of R1 is 10K, I replaced it with 4K7
 - Pin 1 and pin 2 of the optocoupler are reversed only for simplifying the board design
 - Do not pay attention to the CNY70 and related components, it is for a water meter using a CNY70 reflective sensor
 - I am connecting this directly to the serial port of the raspberry on the RX pin, so Vcc is 3.3V in my case

**Pull request merged**
