### PR TITLE
Update hardware module Daikin cpp

### PR DESCRIPTION
**Pull request by spiderjn**
tested on windows and my controlers.
need review and help for cleaning code (cause it's my first C++ experience)

### CODE REVIEW

**Comment by spiderjn** [comment]
image20180107282

new device to standard daikin hardware plugin.
- Led (on/off)
- Power (On/Off)
- Ventallation (Auto, Silence, Lev 1 to 5)
- Winds (Stop/Vertical/Horizontal/Both)
- Target  temperature ( Set target)
- mode (Auto, Dehumidificator, Cold, Hot, Fan)

**Comment by spiderjn** [comment]
minor change on mode status

**Comment by spiderjn** [comment]
wait commit

**Comment by gizmocuz** [comment]
Is this patch ready to be reviewed? Please change the log functionality, there is no need to sprintf before calling the log functions, there is the possibility to add parameters, see other class implementations

**Comment by spiderjn** [comment]
Yes it can be reviewed, this code (sprintf) in not mine, but i can change it.

**Comment by spiderjn** [comment]
review done

**Comment by gizmocuz** [comment]
Thanks!

**Comment by spiderjn** [comment]
Hi, when i can test this commit on beta version ?

**Comment by spiderjn** [comment]
ok done in  3.8825

**Comment by gizmocuz** [comment]
@spiderjn , there are some strange code lines, hope you can help with them:

~ line 931

	if (NewLevel == 10)
		szURL << "&f_dir=0";
	else if (NewLevel == 20)
		szURL << "&f_dir=1";
	else if (NewLevel == 20)
		szURL << "&f_dir=2";
	else if (NewLevel == 20)
		szURL << "&f_dir=3";

3 times there is checked if the NewLevel = 20, should that be 30 and 40 ?

**Comment by gizmocuz** [comment]
And line 731

```
	_eSwitchType switchtype;
	switchtype = STYPE_Selector;

	if (switchtype == STYPE_Selector) {
		xcmd.subtype = sSwitchTypeSelector;
		if (level > 0) {
			xcmd.level = level;
		}
	}

```

it is always STYPE_Selector type

**Comment by pipiche38** [comment]
When I did the update on Daikkin I was also wondering about this if (switchtype == STYPE_Selector) as indeed it is always STYPE_Selector.
But didn't spend much time on it.

I have some needs to do some update on the code in order to behave as the Daikkin remote control. I'll have a look if we don't have answer from @spiderjn

**Comment by gizmocuz** [comment]
@pipiche38 , thank you ! If possible, also run cppcheck (http://cppcheck.sourceforge.net/) over the code

**Comment by pipiche38** [comment]
I'll do.

Quick question, how can I enable DEBUG_HARDWARE ? 
_log.Debug(DEBUG_HARDWARE, "Daikin: Set Point...");

**Comment by spiderjn** [comment]
You have to set configuration in command line for debugging:

My configuration, found when reverse code :

-debug -verbose 2 -wwwroot "C:\**************\domoticz-development\www" -log "C:\ \**************\domoticz-development\domoticz.log" -loglevel 0

Best regards

**Comment by pipiche38** [comment]
Line 931 is definitively a bug as you pointed out :-(

**Comment by gizmocuz** [comment]
@pipiche38 , we have new command line parameters for logging and debug level

-loglevel (combination of: normal,status,error,debug)
-debuglevel (combination of: normal,hardware,received,webserver,eventsystem,python,thread_id)

for example:
- loglevel normal,status,error,debug -debuglevel normal,hardware

**Comment by gizmocuz** [comment]
(or you can use the new configuration file, best to start domoticz with --help or /?)

**Comment by spiderjn** [comment]
i've reinstall a new dev env for make test and complete plugin, i think we need create a test plan and update Wiki page (https://www.domoticz.com/wiki/Daikin_wifi ) for comunity
we have also to cover mulitsplit configuration (like in my case) cause we need to have same mode on all split for one group.

**Comment by gizmocuz** [comment]
Please go ahead and update the wiki
We might need to remove the old plugin ?

**Pull request merged**
