### PR TITLE
Added pushbullet notifications

### PR DESCRIPTION
**Pull request by tofra**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Please don't modify the cmakelist.txt other then adding the file
Sqlhelper.cpp you do not have to increase the database version,
And it should not be enabled per defaut

**Comment by gizmocuz** [comment]
Thanks, and many thanks for the patch as well !

**Comment by tofra** [comment]
BTW: don't forget adding it to History :-)

**Comment by gizmocuz** [comment]
i fill push a updated history file soon! You could have added it ;)

**Pull request merged**
