### PR TITLE
NestOAuth: Fix for travis ci compile warnings.

### PR DESCRIPTION
**Pull request by dotms**
I noticed that there were some warnings spit out while compiling the OSX version. This PR consists of a few minor code changes to fix that.

Example warning: /Users/travis/build/domoticz/domoticz/hardware/NestOAuthAPI.cpp:175:9: warning: address of 'sResult' will always evaluate to 'true' [-Wpointer-bool-conversion]

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for noticing.

Could you make a few changes, instead of size() == 0 or >0 please use empty like:

if (sResult.size() == 0)

to

if (sResult.empty())

vHeaderData.size() > 0

to

!vHeaderData.empty()

(mind the ! (not))

**Comment by dotms** [comment]
Still need to test functionality after building it on Linux. Please hold this one.

**Comment by dotms** [comment]
While at it I also changed the description in the hardware configuration page. Testing was ok, ready for merging :)

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
