### PR TITLE
[1wire] write wiper value to DS2890

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by oohlaf** [comment]
No need to change <python.h> to "python.h", a proper fix is already in master, please merge it here to get it to compile again on OSX.

**Comment by gizmocuz** [comment]
Thanks, Maybe you want to check the result of GetWiper before reporting it in (1Wire.cpp, ~ line 439)

**Comment by szczukot** [comment]
I have check in ReportWiper:
if ((wiper < 0) || (wiper > 255))
 		return;

**Comment by gizmocuz** [comment]
True, and i think it was already changed with the clang patches

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
