### PR TITLE
Add Telegram Notification

### PR DESCRIPTION
**Pull request by chatainsim**
I've added Telegram notification.
I'm not a dev so maybe I've made some mistake but it's working.

Thanks :)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for this! Integration looks good but:
- could you remove all language file changes, and post here the needed changes ? (or only add them for English). The rest is done in our transifex system
- Could you undo all setup changes , only add the relevant parts for the new notification. Maybe later create one for the setup changes you propose if they are needed

**Comment by chatainsim** [comment]
Hum, I'm sorry, I don't know how can I do that.
I've tried some but nothing work.
Do I have to delete my pull request than create a new one ?

Edit: I will create a new pull request for this but regarding the setup change, what do you mean by that ?

**Comment by gizmocuz** [comment]
I mean all changes in setup.html which do not belong to this specific new feature

**Comment by chatainsim** [comment]
Closing this pull request and I'll recreate a new one.

**Pull request closed without merging**
