### PR TITLE
#2279 Fix url for device log page

### PR DESCRIPTION
**Pull request by stas-demydiuk**
- Extract domoticzblocks.js, domoticzdevices.js from gzip
- Fix url for device log page from floor plan

### CODE REVIEW

**Comment by gizmocuz** [comment]
Was there a change needed in the domoticzblocks ? (blockly part) ?

**Comment by stas-demydiuk** [comment]
No, just unzipped both files because they contain domoticz related code as it would be useful to start having version history for them and I hope help to avoid such issues.

**Comment by gizmocuz** [comment]
I understand, but then only for changed files please. If both are not changed, please undo this change

**Comment by stas-demydiuk** [comment]
@gizmocuz I hope got your idea right: removed domoticzblocks.js.gz from pull-request.
But still don't completely understand what is the benefit of having this file compressed in the repository (except of RPI performance issue I guess)  as it doesn't allow us to have its history in git log

**Comment by gizmocuz** [comment]
Its been explained quite some times, but basically in short, it saves a lot of CPU cycles on slow systems
Later we will make the compression realtime (for changes files) or during packaging .

**Comment by gizmocuz** [comment]
Its been explained quite some times, but basically in short, it saves a lot of CPU cycles on slow systems
Later we will make the compression realtime (for changes files) or during packaging .

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
