### PR TITLE
RoomPlan page update

### PR DESCRIPTION
**Pull request by stas-demydiuk**
- rewrite to use angular controllers and components
- extract new device selection into modal with ability to filter by hardware and by device name
- update checking permissions flow
- update uiBootstrap to fix issue with modal
- update modal styles

image

image

### CODE REVIEW

**Comment by dannybloe** [comment]
Can't you get rid of those horrible up/down buttons or add drag-drop to reorder as well? 🙂

**Comment by stas-demydiuk** [comment]
@dannybloe, basically do you know, why do we need this reorder at all?

**Comment by stas-demydiuk** [comment]
@gizmocuz any chances to have that merged?

**Comment by gizmocuz** [comment]
Thanks for this,  but i miss the idx in here... is it possible to prefix the device name with this?

**Comment by gizmocuz** [comment]
@stas-demydiuk , the reorder is there because it's the order it will present itself on the page
For the IDX, i mean in the popup to select the device

**Comment by stas-demydiuk** [comment]
image

**Comment by stas-demydiuk** [comment]
image

**Comment by gizmocuz** [comment]
Thanks!!

**Pull request merged**
