### PR TITLE
manual conversion to use std::make_unique

### PR DESCRIPTION
**Pull request by neheb**
Simpler.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you again for the work !!

**Comment by gizmocuz** [comment]
@neheb , could you try to fix this, or revert this PR ?

**Comment by neheb** [comment]
Just revert.

**Comment by gizmocuz** [comment]
@neheb , sorry I could not. Because I fixed some compile warning issues yesterday, I was unable to revert.
The only solution was a hard reset/push

The serial issue was inside "AsyncSerial::writeEnd", but there could be others as well.

**Pull request merged**
