### PR TITLE
First version of python3 event-scripts.

### PR DESCRIPTION
**Pull request by moroen**
Updated python event-script handling to python3. Dependent on python plugins for shared python library and python initialization.

Creates DomoticzEvents python module, to replace the domoticz.py module-file for python2. Mayor changes from previous version:
1. Everything handled from one module
2. Command doesn't (yet) support named parameters, and only two params needed (name, action)
3. Devices-dictionary changed from devices to Devices
4. Log changed from log, and accepts (currently) only one string as parameter
5. Most of the old module-dictionary is supported
6. Added script_device_test.py and script_time_test.py to test and describe API.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks! 
We have some build errors see below
What has changed in Domoticz.js?

**Comment by moroen** [comment]
Build-checks now passing, I don't have access to a windows environment at the moment, so have no way of checking if this commit will compile with python plugins and scripts on windows,but compiling without python at least passes the test.

I haven't made any changes to Domoticz.js.

M

**Comment by gizmocuz** [comment]
If you look at this pull request you see there are 245 changed files?

**Comment by moroen** [comment]
My mistake, I must confess I'm a bit of a noob when it comes to git, and contributing to large projects...

I created the pull request against the Python-Plugins-branch, but I've managed to merge in the master-branch before my one of my latest commits, so the pull-request has 245 files changed against python-plugins, but only 17 against the master-branch, and those 17 files are files I have changed...

Not quite sure what's the preferred branch to create a pull-request against? I have assumed Python-Plugins, so if that's the preferred branch, I'll revert the merge of master, so only files I have changes differs from the Python-Plugins-branch.

I'm canceling the pull-request, and issue a new one after fixing a bug I just discovered.

M

**Pull request closed without merging**
