### PR TITLE
open-zwave accepted version of TagReader500.xml

### PR DESCRIPTION
**Pull request by hvbommel**
This version of the BeNext TagReader500.xml was accepted by open-zwave. Note: I first did submit a version simular to the current one in Domoticz. I got a change request, to use lists, for that one. After I made those changes it was accepted and is now part of the open-zwave Dev branch.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Is this in the normal branch ? If yes, then this file is soon overwritten when we update the configuration files

**Comment by hvbommel** [comment]
A few questions from my side to better understand how open-zwave config files get into domoticz.
 ... So do you copy the open-zwave config files from time to time ? from the master branch or the Dev branch? Is that manually done by you ? If this is done already from time to time then this PR is not needed of course and it can be closed.

**Comment by gizmocuz** [comment]
Yes, once upon a time i update ozw here, and move all configuration related stuff (settings/manufactorer) to the domoticz folder
Everything will be overwritten
We are not using the dev branch of OZW (yet)

**Comment by gizmocuz** [comment]
(for this we need to patch the make scripts, and the travis/appveyor scripts)

**Comment by hvbommel** [comment]
Ok, understood, I will close this PR. Thanks.

**Pull request closed without merging**
