### PR TITLE
Use boost regex instead of c++11 std::regex

### PR DESCRIPTION
**Pull request by emontnemery**
Fix compile error introduced by #2306 due to use of c++11 feature std::regex
Closes #2334.

### CODE REVIEW

**Comment by emontnemery** [comment]
@dotms Please review

**Review by dotms — APPROVED** [review]
Looks fine to me, thanks for this fix!

@gizmocuz Is there any particular reason why c++11 extensions are not enabled/specified when building on Linux using gcc 4.x, while on more recent gcc versions this feature is enabled by default?

**Comment by emontnemery** [comment]
@dotms it was discussed in #2081. My take is that c++11 unfortunately has to remain off until we can assume most users are on stretch or newer, so maybe next year, or until someone makes domoticz fully statically linked.

**Comment by gordonb3** [comment]
Yeah... The problem is that in between gcc versions 4.7 and 5.1 the symbol naming of c++11 objects is not properly defined. As a result any revison or upgrade that has either its source or destination within this range will cause applications using it to break.

I'm unsure where Microsoft Visual Studio stands in this.

**Comment by gizmocuz** [comment]
Could you try to avoid boost as well ? (or the regex, try a different method ?)

**Comment by dotms** [comment]
Do you object against the use of regular expressions (whether it comes from std or boost)? Or boost altogether? I'm unsure what you mean.

**Comment by gizmocuz** [comment]
I opt to limit boost usage as much as possible as we need to add this to the build systems
Sure when we could finally use c++x11, that would solve a lot of problems.
As this is not possible, you can therefore also not use the c++x11 regex function (unfortunately)

**Comment by dotms** [comment]
I can work around it since I only need a few specific bits of information, although it will probably look a bit silly.

**Comment by emontnemery** [comment]
@dotms OK, then I close this PR?

**Comment by gizmocuz** [comment]
@dotms , or maybe update this pull request with other code ?

**Comment by dotms** [comment]
@gizmocuz By the looks of it I cannot change much on this PR (makes sense since it's emontnemery's PR) nor the original one (most likely since it's already merged). 

I have a few changes ready to publish. If it's ok with you and @emontnemery close this PR and I will create a new one with the updated code. Code is ready, just test compiling it on gcc 4.8 now.

**Comment by gizmocuz** [comment]
That would be great! Thanks in advance!

**Pull request closed without merging**
