### PR TITLE
EventSystem fix high load with dzVents enabled

### PR DESCRIPTION
**Pull request by jvandenbroek**
This should fix the high load issues users have with dzVents enabled

### CODE REVIEW

**Comment by jvandenbroek** [comment]
Wait before merge, seems not to do (fix) what I intended... Need to review some more code.

**Comment by scottydj2** [comment]
Looks good to merge.

**Comment by jvandenbroek** [comment]
This will completely disable executing dzVents Lua code if dzVents is enabled (default) but no scripts are active / available, so users without dzVents scripts won't notice any slowdown anymore.

**Comment by dannybloe** [comment]
I tested this on various systems and seems good to go.
Merging... 
Thanks guys.. 
One more optimization to go...

**Pull request merged**
