### PR TITLE
Improved IP address checking function (used in Proxy header processing)

### PR DESCRIPTION
**Pull request by kiddigital**
This PR adds the `bool IsValidIP(std::string &ip)` function which first validates _AND_ reformats the IP address if needed.

It works for both IPv4 and IPv6 addresses.

This new function is used to validate IP addresses seen in Proxy headers.

### CODE REVIEW

**Comment by gizmocuz** [comment]
We have some build issues under win32:

> C:\projects\domoticz\main\Helper.cpp(662,7): error C3861: 'inet_aton': identifier not found C:\projects\domoticz\main\Helper.cpp(664,12): error C2065: 'INET_ADDRSTRLEN': undeclared identifier C:\projects\domoticz\main\Helper.cpp(665,38): error C2065: 'INET_ADDRSTRLEN': undeclared identifier C:\projects\domoticz\main\Helper.cpp(665,7): error C3861: 'inet_ntop': identifier not found C:\projects\domoticz\main\Helper.cpp(670,6): error C3861: 'inet_pton': identifier not found C:\projects\domoticz\main\Helper.cpp(673,12): error C2065: 'INET6_ADDRSTRLEN': undeclared identifier C:\projects\domoticz\main\Helper.cpp(674,62): error C2065: 'INET6_ADDRSTRLEN': undeclared identifier C:\projects\domoticz\main\Helper.cpp(674,7): error C3861: 'inet_ntop': identifier not found

**Comment by kiddigital** [comment]
hm... some WIN32 specific includes missing it seems. These functions are used at other parts like 'hardware/csocket.cpp' and 'webserver/cWebem.cpp'

Maybe add to 'helper.cpp'?
```
#ifdef WIN32
...
#include <winsock2.h>
#include <Ws2tcpip.h>
#else
...
```

Unfortunately I am not able to test this quickly myself.
Otherwise I might have to _abuse_ the Windows build system to fix it by trail/error :(

**Comment by gizmocuz** [comment]
You are only using the **isValidIP** function in cWebem, please put the function in this class
If you need to test this... make it a static function so you can call it from your testing helper

**Comment by gizmocuz** [comment]
You could also use inet_pton
But still please make this a (static) function of cWebEm as it's only used in this class

**Comment by kiddigital** [comment]
Agree that it is currently only used in the cWebEm class.

Reason to put in into the Helper is because it is intended to be used wider as I see that other hardware modules also do IP checking (some with `inet_pton`, some with `inet_addr` and some even fully custom build) but all in limited form, most IPv4 only (and also only _dotted decimal_, no _numbers and dots_) and no/bad support for IPv6.

I did not undertake any refactoring of those other pieces as I don't have the time and/or ability to test them properly (knowing it compiles is not enough).

**Comment by gizmocuz** [comment]
Yes, that is why i suggested to make the function static so you can use/call it everywhere

**Comment by gizmocuz** [comment]
Could you move the 'bool isValidIP(std::string &ip)' out of the helper header/cpp and into cWebem and make it static so you can use it in your test code if you want to?

**Comment by kiddigital** [comment]
@gizmocuz , moved to cWebem as static function and removed from tester

**Comment by gizmocuz** [comment]
> @gizmocuz , moved to cWebem as static function and removed from tester

Thanks for this. This works (actually it does not have to be static anymore now), but what I actually meant was declare it as static in the header (cWebem.h) inside the class cWebem

then you can access it anywhere you like with

cWebem::IsValidIP(....)

As long as you include cWebem.h

Going to merge, thanks once again!!

**Pull request merged**
