### PR TITLE
build: Detect and allow external tinyxpath library usage

### PR DESCRIPTION
**Pull request by mooninite**
Combines all previous work from PR 1731 into one clean commit.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
Unfortunately this is not working with the current cmake version on raspberry and other systems (for example my pine64)

CMake Error at CMakeLists.txt:528 (target_sources):
  Unknown CMake command "target_sources".

Current cmake version 3.0.2

https://packages.debian.org/jessie/cmake

**Comment by gizmocuz** [comment]
I reverted it partly, most is still there, but at least it now compiles on these arm systems

**Comment by mooninite** [comment]
The target_sources command first appeared in CMake 3.1 3 years ago. The most important part of this pull request were the CMake changes.

Version 3.6.2 is available in backports to you. I'd highly recommend upgrading to a newer CMake. It will prevent future development more often the longer you stay on an ancient version.

**Pull request merged**
