### PR TITLE
Fix segfault on python plugin stop

### PR DESCRIPTION
**Pull request by hamshiva**

### CODE REVIEW

**Comment by hamshiva** [comment]
Well it seems that the build fails due to a Boost download issue. Could someone fix this ?

**Comment by gizmocuz** [comment]
It will fix itself, sometimes their server is in maintenance

**Comment by hamshiva** [comment]
Is there something to do for the checks to run again ?

**Comment by rwaaren** [comment]
> Is there something to do for the checks to run again ?

did you try `git commit –allow-empty -m “Force rebuild”` ? (from [TiKalk)](https://www.tikalk.com/posts/2016/04/04/empty-commit-is-a-useful-commit/)

**Comment by gizmocuz** [comment]
We used to have a rebuild option in Travis... that is gone unfortunately

**Comment by gizmocuz** [comment]
The issue is probably because you made a PR against the master branch instead of the default development
Could you do so ?

**Pull request closed without merging**
