### PR TITLE
Fix 'SubType' when device change with enum

### PR DESCRIPTION
**Pull request by DT27**
When change the type between normal switch and selector switch, the SubType won't change, and the switch can not edit again.
This can fit it.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks, but do you agree a patch that stops being able to change a switch in a selector switch ?
You are trying to change a non-selector-switch to a selector-switch ?

**Comment by DT27** [comment]
@gizmocuz Sometimes need to change on both sides, like the BroadlinkRM2 plugin. Please do not cut this function, it's useful. 

_Sent from my Samsung SM-G9550 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gizmocuz** [comment]
No worries ;) Thanks for the patch!

**Comment by hvbommel** [comment]
See PR #1680
DT27;  FYI above PR was requested to revert your change.

**Comment by DT27** [comment]
@hvbommel thanks, I will test and fix the problem.

**Pull request merged**
