### PR TITLE
Line endings

### PR DESCRIPTION
**Pull request by deece**
Amend line endings of checked in text files to their native format.

Addresses #644

### CODE REVIEW

**Comment by gizmocuz** [comment]
That goes a bit wrong i think.... 712 patched files
Next, the files in the Config folder (Openzwave configuration files) are also patched
They will be overwritten

If people set the correct global configuration option for this, there will be no need for this patch ?

**Comment by deece** [comment]
Unfortunately not :( The repo currently contains hard CR-LFs. I suspect files that contained CRLFs might have been checked in under unix, so git added them to the repo as-is.

Subsequently, other have edited it under unix, with some editors preserving CRLFs, and others adding altered lines as just LF, with the result that some files have both types of line-endings in them.

re the Config folder, replacements should be fine, as further edits will be marked with native line endings now that there is a .gitattributes in place, and converted as appropriate for the platform it is checked out on.

The conversion is going to be an issue for any pending merges (although I don't see any active pull requests other than mine atm), as the entire file will be conflicted. The merges can be resolved by accepting the new version and running dos2unix on them before committing the files.

**Comment by gizmocuz** [comment]
We never had problems with pull requests before.
No problem that they are all ending with crlf, thats find my be, but i think your git should resolve this with pulling/pushing ?

**Comment by gizmocuz** [comment]
(i am quite new to git... 2 years now.., never ever got a request for this... but i like to learn ;))

**Comment by deece** [comment]
On unix, git will check out the files in whatever is hardcoded in the files (currently crlf), but when checking in, git will convert the whole file to LF, causing changes on every line (and making the merge quite difficult). This pull request gets all that out of the way up front, the only pain would be from merging pull requests from before the gitattributes file went in.

Windows developers will continue to check out as CRLF, and should not see any change as a result of this pull request.

**Comment by deece** [comment]
As it stands at the moment, this is what happens under Unix with a fresh checkout and no changes:

```
deece@localhost tmp]$ git clone git@github.com:domoticz/domoticz.git
Cloning into 'domoticz'...
remote: Counting objects: 28133, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 28133 (delta 9), reused 0 (delta 0), pack-reused 28095
Receiving objects: 100% (28133/28133), 135.94 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (19723/19723), done.
Checking connectivity... done.
[deece@localhost tmp]$ cd domoticz/
[deece@localhost domoticz]$ git diff HEAD
warning: CRLF will be replaced by LF in Config/2gig/ct100.xml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Config/2gig/ct101.xml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Config/2gig/ct30.xml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Config/BeNext/1poleswitch.xml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Config/BeNext/2poleswitch.xml.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in Config/BeNext/AlarmSound.xml.
...<snip>
diff --git a/Config/2gig/ct100.xml b/Config/2gig/ct100.xml
index 017d8d1..e5aa2ba 100644
--- a/Config/2gig/ct100.xml
+++ b/Config/2gig/ct100.xml
@@ -1,7 +1,7 @@
-<?xml version="1.0" encoding="utf-8"?>
-
-<Product xmlns='http://code.google.com/p/open-zwave/'>
-  <!-- This thermostat's setpoint descriptions are 0 based, not 1 -->
-  <CommandClass id="67" base="0" />
-
-</Product>
+<?xml version="1.0" encoding="utf-8"?>
+
+<Product xmlns='http://code.google.com/p/open-zwave/'>
+  <!-- This thermostat's setpoint descriptions are 0 based, not 1 -->
+  <CommandClass id="67" base="0" />
+
+</Product>
diff --git a/Config/2gig/ct101.xml b/Config/2gig/ct101.xml
index 017d8d1..e5aa2ba 100644
--- a/Config/2gig/ct101.xml
+++ b/Config/2gig/ct101.xml
@@ -1,7 +1,7 @@
-<?xml version="1.0" encoding="utf-8"?>
-
-<Product xmlns='http://code.google.com/p/open-zwave/'>
-  <!-- This thermostat's setpoint descriptions are 0 based, not 1 -->
-  <CommandClass id="67" base="0" />
-
-</Product>
+<?xml version="1.0" encoding="utf-8"?>
+
+<Product xmlns='http://code.google.com/p/open-zwave/'>
+  <!-- This thermostat's setpoint descriptions are 0 based, not 1 -->
+  <CommandClass id="67" base="0" />
+
+</Product>
```

**Comment by deece** [comment]
These change have been done directly by @gizmocuz , closing this request.

**Pull request closed without merging**
