### PR TITLE
Remove MQTT mutex

### PR DESCRIPTION
**Pull request by emontnemery**
Remove MQTT mutex which filled no purpose and was causing deadlocks (#2384)

### CODE REVIEW

**Comment by emontnemery** [comment]
@gizmocuz It looks like the windows libraries need an update.

**Comment by gizmocuz** [comment]
@emontnemery, thanks for the hard work testing this !!! (And all others of course, specially Miloslav !)

Could you explain a bit more what windows library needs an update ?

**Comment by emontnemery** [comment]
@gizmocuz Not related to this PR, I was just referring to Appveyor builds failing since a couple of days:
`LINK : fatal error C1047: The object or library file '.\Windows Libraries\Lua\Release\LuaMSVS.lib' was created with an older compiler than other objects; rebuild old objects and libraries [C:\projects\domoticz\msbuild\domoticz.vcxproj]`

**Comment by gizmocuz** [comment]
Thanks for sharing, i will update this asap! (now)

**Comment by jonferreira** [comment]
just to clarify @emontnemery does that mean the build I'm using on #2364 has been merged and so it's "safe" to update to the latest beta?

**Comment by emontnemery** [comment]
@jonferreira Yeah, it's included in beta 3.9453

**Comment by jonferreira** [comment]
OK just installed 9462, lets see how it goes.

Thanks for all the hard work!

**Comment by MiloshCZ** [comment]
Installed 9462, 40 hours online, under my "stress test". No problem yet.

**Comment by jonferreira** [comment]
yes same here, really sound slike @emontnemery nailed it again :)

**Comment by Avton524** [comment]
48 hours, all right too. Thanks)))

**Pull request merged**
