### PR TITLE
Update domoticzdevices.js - show current value as status for custom sensor

### PR DESCRIPTION
**Pull request by martin-g-it**
To show current value as status on custom sensor (while hovering over the icon)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could you try beta 15653?

**Comment by martin-g-it** [comment]
oeh, no, this makes the P1 meter looks terrible on the floorplan:
image

**Comment by gizmocuz** [comment]
Why is your P1 meter looking so much different than mine?
Besides the P1 meter, everything else is OK?
You are using the default theme right?

Without delivery:
image

With return delivery:
image

**Comment by gizmocuz** [comment]
I don't think you are using the default theme looking at your screenshots

**Comment by gizmocuz** [comment]
Ahhh I am looking at the popup when you hover your mouse above it... you are looking at the text underneath it... 
The popup's seems fine now

**Comment by gizmocuz** [comment]
Seems the text beneath is an option as I don't have this here... have to dig into this

image

Anyway, the popups are now correct... that's part 1

**Comment by gizmocuz** [comment]
Could you test beta 15654, it should now be correctly display the values as well

**Comment by martin-g-it** [comment]
> I don't think you are using the default theme looking at your screenshots

It's the Elemental theme with a different background (some carbon look)..

**Comment by martin-g-it** [comment]
> Could you test beta 15654, it should now be correctly display the values as well

Will check tomorrow; busy day and plans tonight

**Comment by martin-g-it** [comment]
Partially fixed..

The P1 icon shows the current usage (instead of CounterToday)
image
Not sure if this is better, since you also have a dedicated device for the actual usage..

The Current icon seems OK now:
image

Although for the popup when you hoover over it becomes unreadable when the device name is longer than 18 characters.
image
Would be better to show it like this:
image

Which can be achieved by adding below case in the `switch (this.type) {:`
```
>             case "Current":
>                 this.LogLink = this.onClick = "ShowCurrentLog('#" + Device.contentTag + "','" + Device.backFunction + "','" + this.index + "','" + this.name + "', '" + this.switchTypeVal + "');";
>                 this.smallStatus = this.data;
>                 this.status = this.data;
>                 this.data = '';
>                 break;
```

**Comment by gizmocuz** [comment]
Thank you for your feedback. I consider this fixed. (And fixed for you as well as you rename your device)

**Comment by martin-g-it** [comment]
Hmm, let me create a new PR, because the P1 device is now even worse when power is being delivered:
image

Really better to show the CounterToday..

**Comment by gizmocuz** [comment]
What do I see above? What is your current usage, don't you want to see your house usage? Like it is using 1000 W, or it is delivering 300 Watt (-300 W)?

**Comment by martin-g-it** [comment]
delivering 300 Watt... I got it all sorted out now (incl. some more fixes w/o impacting others), will make a PR in a few

**Comment by martin-g-it** [comment]
see https://github.com/domoticz/domoticz/pull/5878

**Pull request closed without merging**
