### PR TITLE
Make CustomImage of Utility devices visible to javascript and use it …

### PR DESCRIPTION
**Pull request by ultrasuperpingu**
…in javascript

### CODE REVIEW

**Comment by gizmocuz** [comment]
@ultrasuperpingu , thank you for this PR!
Quick comment, and this has nothing todo with your code, but could maybe be great to apply as well...
In the javascript code there is currently a lot of duplicate code like

```
if(item.CustomImage == 0)
      imagehtml = '<a href="#/Devices/' + item.idx + '/Log"><img src="images/Gas48.png" class="lcursor" height="40" width="40"></a></td>\n';
else
      imagehtml = '<a href="#/Devices/' + item.idx + '/Log"><img src="images/' + item.Image +'48_On.png" class="lcursor" height="40" width="40"></a></td>\n';
```

Could you do instead a short if/then like: (pseudo code, hope it's error free!)

```
item.Image = (item.CustomImage == 0)  ? 'Gas48.png' : item.Image + '48_On.png';
imagehtml = '<a href="#/Devices/' + item.idx + '/Log"><img src="images/' + item.Image +'" class="lcursor" height="40" width="40"></a></td>\n';

```

**Comment by ultrasuperpingu** [comment]
Ok, it's done

**Comment by gizmocuz** [comment]
You're fast ! Hope to test this PR shortly !

**Comment by gizmocuz** [comment]
@ultrasuperpingu , Is it correct that I don't see the code where a user can select a custom image ? (Like you can when you edit a Switch)

**Comment by ultrasuperpingu** [comment]
Yes, it's correct. The idea is to allow plugins to change the image of their devices. Users still can't.

**Comment by ultrasuperpingu** [comment]
Do you want me to modify something ? Or to provide you something to be able to test it easyly ? (in fact, to test, I just added on a dummy db file all the utility sensors availables in Dummy hardware and added and removed CustomImage in db via sql)

**Comment by gizmocuz** [comment]
@ultrasuperpingu , no I just need to test this. The only pity here is that this is only for plugin developers and a normal user is not able to change to a custom image.
Hope to test this soon

**Comment by ultrasuperpingu** [comment]
You're right, it should be easy to add the UI to be able to change the custom image. But this commit is part of the job. I guess I'll do it later, it shouldn't be a huge work (just some ui and update the ajax request).

**Comment by jeroenkl** [comment]
> You're right, it should be easy to add the UI to be able to change the custom image. But this commit is part of the job. I guess I'll do it later, it shouldn't be a huge work (just some ui and update the ajax request).

@ultrasuperpingu, many users will like this feature, if you have time, could you add it also?
thxs!

**Comment by ultrasuperpingu** [comment]
@jeroenkl, yes, as I said, I'll probably do it later, when I'll have some time and motivation. But this could be done in another PR and if possible, I'd like this PR to be reviewed before I do it.

**Comment by gizmocuz** [comment]
Sorry about the delay! Thanks for the PR all looking good!

**Pull request merged**
