### PR TITLE
Ignore Serial_ID_Button devices in 1wire

### PR DESCRIPTION
**Pull request by sbouchex**
Ignore Serial_ID_Button devices in 1wire as it does not contain usefull data and generate useless activity

### CODE REVIEW

**Comment by gizmocuz** [comment]
Shall this also be ignored ByKernel or ForWindows ?

**Comment by sbouchex** [comment]
I would say yes as well (even if I can't test it)

**Comment by gizmocuz** [comment]
then maybe it should be ignored in 1Wire.cpp

void C1Wire::BuildSensorList() {

or

void C1Wire::PollSensors()

or

void C1Wire::BuildSwitchList() {

or

void C1Wire::PollSwitches()

But as far as i can see, only these sensors are supported:

```
    case high_precision_digital_thermometer:
    case Thermachron:
    case Econo_Digital_Thermometer:
    case Temperature_memory:
    case programmable_resolution_digital_thermometer:
    case Temperature_IO:
    case Environmental_Monitors:
    case _4k_ram_with_counter:
    case quad_ad_converter:
    case smart_battery_monitor:
```

**Comment by sbouchex** [comment]
problem looks different, new PR :-)

**Pull request closed without merging**
