### PR TITLE
[USBtin/Multibloc V8] - Add support of Bloc 7 + some fixes

### PR DESCRIPTION
**Pull request by reivax85**
Fixed a bad sID used to write to supply voltage information on bloc 9/ bloc sfsp
Add support of Bloc 7 which allows users to be able to read analog and digital inputs coming from this block (and IBS information to, because bloc 7 has a LIN input like block 9 so we can connect 6x IBS on it !)
Stack upgraded to V04.00

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for your PR. Is it possible to not include any other files? (From the extern folder)

**Comment by reivax85** [comment]
yes I will exclude the external folder.

**Comment by kiddigital** [comment]
> yes I will exclude the external folder.

@Xav-Scheiber  They are still there unfortunately

**Comment by reivax85** [comment]
Think it's now ok (sometimes I make mistakes with git command arf...)

**Comment by kiddigital** [comment]
> Think it's now ok (sometimes I make mistakes with git command arf...)

Still there :(

**Comment by reivax85** [comment]
I see that here : 
image

And no extern folder on my repos...
image

Don't understand...

**Comment by kiddigital** [comment]
@Xav-Scheiber , easiest way is to to copy the 2 relevant files to a temp location. Throw away your local repo, do a new git pull and copy the temp files back to your local development branch... now check with `git status` that these 2 files are the only changes.. now commit again and push... you can commit also only the 2 files...

you should end up with a local branch with only 1 commit containing the 2 files...

good luck :)

**Comment by reivax85** [comment]
should I close this pull request to recreate a new one ? (I made a git clone from my repository and I no longer see the extern folder since my last push, I think I'm going to fork again the dev branch from domoticz, this is a very strange behaviour...)

**Pull request closed without merging**
