### PR TITLE
Sqlhelper locks and cWebem isnew connection

### PR DESCRIPTION
**Pull request by Krzysztof1234534**
Added more locks to sqlhelper and fixed problem with multiple incomming connection in cWebem.

Changes to fix issue: https://github.com/domoticz/domoticz/issues/5630 are in SQLHelper. I used recursive_mutex for simplicity to not care about multiple locks from the same thread, I've didn't spot any performance issue. It is possible to use mutex, but it will require much more code refactoring, so my proposition as simple fix is to use recursive_mutex. 

I've also fixed problem with multiple logs "Status: [web:80] Incoming connection from: ...". This was in specific case: when AreWeInTrustedNetwork returns true and browsers cookie is expired (for example first opening the browser in the day). In some cases browsers sends a lot of requests to domoticz in parallel (browser has cached html page and all resources, but if this is first using of domoticz that day it assumes that resources needs to be refreshed, so this is why there is a lot of requests). Because we are in trusted network, the code in CheckAuthentication (if (AreWeInTrustedNetwork... sets session.rights = 2). At the end of the CheckAuthentication there is:
if ((session.rights == URIGHTS_ADMIN) && (session.id.empty()))
This is the place where session.isnew = true; 
Code goes to this place, because there are no cookie, so parse_cookie returns false. And there is a lot of requests without cookie (something around 60 - this is the number of icons, pages and so on). In handle_request after executing CheckAuthentication  there is:
if ((session.isnew == true) &&
				(session.rights == URIGHTS_ADMIN) &&
				(req.uri.find("json.htm") != std::string::npos) &&
				(req.uri.find("logincheck") == std::string::npos)
				)
I've removed this json.htm check, because we also want to go there in all cases in Trusted Network (except logincheck, but if will probably not be used in trusted network). Note that code "session.isnew = true" is in 3 places:
- logincheck (this is excluded)
- in CheckAuthentication at the end (this is Trusted Network)
- in CheckAuthentication when parse_cookie returns true and session.rights == 2 - if rights == 2 it means that it is trusted network, but if there is cookie (parse_cookie return true), it means that it is not expired yet. This case looks like some fallback, it is not used frequently. I've removed private method authorize, because it was not used and there was "session.isnew = true".

Note also that I'm not sure if handle_request is synchronous or async method (probably it is async). Because there is incorrect lock mechanism in cWebem. "std::unique_lock<std::mutex> lock(m_sessionsMutex);" is in GetSession, AddSession, RemoveSession, CountSessions, GetExpiredSessions, but for example look at code:

```
WebEmSession* memSession = myWebem->GetSession(session.id);
if (memSession != nullptr)
{
  time_t now = mytime(nullptr);
  // Renew session expiration date if half of session duration has been exceeded ("dont remember me" sessions, 10 minutes)
  if (memSession->expires - (SHORT_SESSION_TIMEOUT / 2) < now)
  {
    memSession->expires = now + SHORT_SESSION_TIMEOUT;
    memSession->auth_token = generateAuthToken(*memSession, req); // do it after expires to save it also
    send_cookie(rep, *memSession);
  }
  // Renew session expiration date if half of session duration has been exceeded ("remember me" sessions, 30 days)
  else if ((memSession->expires > SHORT_SESSION_TIMEOUT + now) && (memSession->expires - (LONG_SESSION_TIMEOUT / 2) < now))
  {
    memSession->expires = now + LONG_SESSION_TIMEOUT;
    memSession->auth_token = generateAuthToken(*memSession, req); // do it after expires to save it also
    send_cookie(rep, *memSession);
  }
}
```
memSession is edited outside of lock guard (it means that this modification is not protected by lock). Also there is a lot of GetSession and after that RemoveSession - this also should be atomic operation. But I've didn't observe any problems with incorrect locks behaviour, so my fix for now should be enough.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR!

I am not sure why you need to use **recursive_mutex** if there is a double lock somewhere, that should be fixed

Can you tell me make a callstack that goes wrong?

**Comment by Krzysztof1234534** [comment]
Look at execute_sql method:
```
int CSQLHelper::execute_sql(const std::string &sSQL, std::vector<std::string> *pValues, bool bLogError)
{
	std::lock_guard<std::recursive_mutex> l(m_sqlQueryMutex);
	CSQLStatement sqlStatement(m_dbase, sSQL);
	std::vector<std::vector<std::string>> result;
	for (unsigned int i = 0; (i < pValues->size()) && (!sqlStatement.Error()); i++)
	{
		sqlStatement.AddParameter((*pValues)[i]);
	}

	if (!sqlStatement.Error())
	{
		sqlStatement.Execute();
	}

	if (!sqlStatement.Error())
	{
		result = safe_query("SELECT changes();");
	}
	else
	{
		if (bLogError)
		{
			_log.Log(LOG_ERROR, "Error performing operation: '%s'", sqlStatement.ErrorText());
		}
	}

	if (result.empty() || result[0][0] == "0")
		return 0;
	else
		return atoi(result[0][0].c_str());
}
```
First look at "**sqlStatement.Execute();**" (this is **CSQLStatement::Execute()**) there is no lock, but it doing sqlite3_step (this is operation on database). 
Next look at **safe_query**, it using **query** and there is lock in **query**. 
Note also that we cannot add lock only in: "**sqlStatement.Execute();**" this is because when there will be some another sql operation between "**sqlStatement.Execute();**" and "**safe_query("SELECT changes();");**" than SELECT changes(); will return not our changes, but some another thread's changes, so both sql operations needs to be locked. 
As alternate way we can write second query method (for example **query_nolock**), and second safe_query (for example **safe_query_nolock**), but it will complicate code even more (note that current SQLHelper contains 10k lines, it would be better to extract data access to some another class, extract thread safe to another and keep only public methods in SQLHelper, but this is very big task).

**Comment by gizmocuz** [comment]
Okey and who is calling this function 'execute_sql' ?
Ahhh someone implemented this for Python

Python should call 'safe_query', like is done everywhere else in the code

That same person also added something like 'CSQLStatement' .... That should also be moved to the python code
It is also only used in the python code.
(No idea what this class is for and why it should be needed... just saying that 100 other classes just use m_sql.safe_query)

Could you try to move this and change the python code to call m_sql.safe_query like everywhere else?

**Comment by gizmocuz** [comment]
I had a look at the python code that calls execute_sql....
Pfffff

I know it is not your or mine code, (PythonObjectEx.cpp , line 625). this has to be changed m_sql.safe_query, there is no need for stacking values and passing that....this is exactly why safe_query was made

I will make the modification right now....

There is a large section of remarked code that could be removed (line 898), I made some changes some time ago, those are working, and forgot about this...

**Comment by gizmocuz** [comment]
I made the patch in the commit above. This should solve the problem. Beta 15619, will take some time before available.

**Comment by gizmocuz** [comment]
Is it possible you could make a separate PR for issue #5630 ?

**Comment by Krzysztof1234534** [comment]
Thanks for fixing Sqlhelper, I've didn't test it yet, but I hope that it solve the problems. 
Regarding cWebem, I've created another PR: https://github.com/domoticz/domoticz/pull/5853

**Pull request closed without merging**
