### PR TITLE
Hardware buttons fix

### PR DESCRIPTION
**Pull request by LoukKamp**
Make update and delete buttons on hardware page really disabled, not only gray

### CODE REVIEW

**Comment by LoukKamp** [comment]
Note: The first commit is white space changes only: checked with:

`git diff -w --ignore-blank-lines www/app/hardware/Hardware.js`

**Comment by gizmocuz** [comment]
Thank you for this PR and your time!!

**Comment by LoukKamp** [comment]
Question: Who is responsible for maintaining the history file; Am I supposed to add a line to it to describe this patch?

**Comment by gizmocuz** [comment]
Yes, if you could do that... Before a new stable release I also check the complete commit history and add missing lines when needed

**Comment by LoukKamp** [comment]
I will also use this fork to update the Netatmo oAuth2 patch, I think...
Is it OK when I make the change in the history file in the new PR for the NetAtmooAuth2 update, or should I do this in a separate PR?

**Comment by gizmocuz** [comment]
Thats OK... but please create a new local branch

**Pull request merged**
