### PR TITLE
Add GCM in configurable notification subsystems.

### PR DESCRIPTION
**Pull request by ultratoto14**
For unknown reasons, GCM was not selectable as a notification subsystem.
I just reenable it, put a configuration parameter in the notifications.

Some people complains about not being able to send through GCM unless all the systems are enabled (all is sending to GCM).

That should fix it.
Best regards,
U.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could you undo all formatting changes and specially the language file changes ?

**Comment by ultratoto14** [comment]
Hi Gizmocuz, I'll look at the formatting changes on the code, what do you mean on the languages files ?

Also, quick question, is there a kind of coding rules or coding guides for domoticz, like space for tabs sizes, how to add a translated text and so on ?

Another quick question as we are not able to trace the changes on the gz files, why do not put them as plain text in the repo and add a script to zip them for releasing ?
Best regards,
U.

**Comment by gizmocuz** [comment]
All good questions:

- if you need to add a translation, please state it in your pull request comment, i will add it in our translation system on transifex
- code formatting, just the normal formatting, tabs, no spaces

"Another quick question as we are not able to trace the changes on the gz files, why do not put them as plain text in the repo and add a script to zip them for releasing ?"

Yes, that would be great... if we can do this in the makebeta/release scripts, that would be great

Like when making a new beta/release/package, create a new www folder with all compressed js files

**Comment by ultratoto14** [comment]
So just a last question to be sure (i do not want to break something)
I added Google Cloud  Messaging in all the qzip files. So i modified them (i ensured that i do not have any conflict before pulling this request).
So it seems that it's the good way but another commit changed that ? No formatting problem on the json files or there is a problem still ?

**Comment by ultratoto14** [comment]
Removed unneeded formatting, merge translation changes, i added:
"Google Cloud Messaging" that need to be translated.
Best regards,
U.

**Comment by gizmocuz** [comment]
At the moment you have a commit with 37! changes
You need to revert all i18n files
and undo all formatting changes
just change/add the lines you want to change/add please

if you use <span data-i18n="aaaa">aaaa</span> then there will be no language problem as the second aaaa will then always be plot

**Comment by ultratoto14** [comment]
I'm truly sorry, but there's still something i do not understand.
I changed the setup.html following the other configuration. Each configuration use data-i18n even for the titles, so i added Google Cloud Messaging in the new section in i18n. If i do not add it into the i18n GZ files, there's a blank space instead. If i add only in the en file, it's blank in french (i'm french).

I saw that there was still formatting problems in my merge, i'm fixing that but it's still not clear for me about the translation. I'm truly sorry, i do not want to bother you, just want to understand.

**Comment by gizmocuz** [comment]
Maybe best to start from a fresh fork ? (Don't forget to save your work)

**Comment by ultratoto14** [comment]
Ok, we can close that one, i will take in another pull request to be clearer. 
As I added this "Google Cloud Messaging" term in the i18n can you confirm me that i can update all the GZ to put them in the pull request ?
U.

**Comment by ultratoto14** [comment]
Closing that pull request, will open a new one, clearer.

**Pull request closed without merging**
