### PR TITLE
Similar code from Ecodevices.cpp and Teleinfo.cpp merged into TeleinfoBase.cpp

### PR DESCRIPTION
**Pull request by DebugBill**
First release of Teleinfo related classes being reorganised

CTeleinfoBase now contains the core and common Teleinfo protocol processing
CEcoDevices and CTeleinfoSerial inherit from it, decode the raw data and delegate further processing

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks !!!

**Comment by gizmocuz** [comment]
There are some possible issues reported on the forum, maybe you could have a look there?
https://www.domoticz.com/forum/viewtopic.php?p=124451#p124451

**Comment by Pigloox** [comment]
Hello, thanks for the job.
But I've this error message :
`Error: Teleinfo: label 'DEMAIN' not handled!`

And, My EDF subscription was a TEMPO contract, 
I would like to find the 3 old P1 Smart Metter, (each HP/HC for each tariff) 
thanks

**Comment by Pigloox** [comment]
Please Revert. 
So many bugs and changes, all my teleinfo's scripts are down since this update

**Comment by DebugBill** [comment]
Hi,

I posted and answer on the forum and will make the old P1's come back along with the new features. 
Can you be more specific about the "bugs" though? DEMAIN is definitely one and fixed (but not yet published). What else?

**Pull request merged**
