### PR TITLE
std::bind, lambda, and GCC6 fixes

### PR DESCRIPTION
**Pull request by neheb**
GCC6 has a bug with lambdas and captured pointers. Work around it by being explicit.

### CODE REVIEW

**Comment by neheb** [comment]
Fixes: https://github.com/domoticz/domoticz/issues/4644

**Comment by gizmocuz** [comment]
@neheb, thank you for this PR. It looked better previously without the 'this' pointer of course...

Question, there are a few 'this' pointers with classes in them:

void ssl_server::init_connection() {
	new_connection_.reset(new connection(io_service_, connection_manager_, request_handler_, timeout_, context_));
	// the following line gets the passphrase for protected private server keys
	context_.set_password_callback([this](auto &&...) { return this->ssl_server::get_passphrase(); });

Could/Should this be 

	context_.set_password_callback([this](auto &&...) { return this->get_passphrase(); }); 

without the 'ssl_server' ?

**Comment by neheb** [comment]
Done.

Although that was the only example I found.

**Comment by gizmocuz** [comment]
Thanks! One thing I find strange (and should not be needed) is using 'this' in a class/function.
Sure this is valid, but should not be needed, it is already 'this'
I think you added this because of another issue reported, but it seems that is solved by installing clang 6, so I don't think this is needed

**Comment by neheb** [comment]
It is as long as CMake does not error on GCC6,

**Comment by neheb** [comment]
Eh removed the GCC6 stuff. It's old at this point.

**Comment by gizmocuz** [comment]
Thank you for this ! One request (when you want to, otherwise I will do this after the merge),
Specially in the WebServer.cpp class

Use the real variable names:

RegisterCommandCode("zwaveisnodeincluded", [this](auto &&PH1, auto &&PH2, auto &&PH3) { Cmd_ZWaveIsNodeIncluded(PH1, PH2, PH3); });

to:

RegisterCommandCode("zwaveisnodeincluded", [this](auto &&session, auto &&req, auto &&root) { Cmd_ZWaveIsNodeIncluded(session, req, root); });

It will make it a bit more readable as well

**Comment by neheb** [comment]
Main reason I didn't do that is that it's time consuming. The other is that it would force clang-tidy to break it up to multiple lines. It's better to merge now I think.

**Comment by gizmocuz** [comment]
Okey I will merged this but will do the time consuming job myself
Clang tidy could be modified to not break it

**Comment by gizmocuz** [comment]
Thank you for all the work again!!

**Pull request merged**
