### PR TITLE
Add =, !=, <= and >= to notification conditions

### PR DESCRIPTION
**Pull request by DebugBill**
Now that I use Alerts to pass messages associated to various levels, I needed to send a notification based on some precise level. The "=" operator was missing. 
While at it, I also added a few others.....

What do you think? Is that usefull? I am still testing it but it seems to work fine. It was also an opportunity to factorise some code in NotificationHelper while adding functionality

If we keep it, news translations are needed for
Lower
Lower or Equal
Equal
Not Equal
More 
More or Equal

### CODE REVIEW

**Comment by gizmocuz** [comment]
Is it an option to change all texts to the 'signs' (=, !=, <= and >=,...) this way we do not need any translation anymore

**Comment by DebugBill** [comment]
Done. No need for translation anymore. I used "<>" rather than "!=" as I think it is less "geeky"... but this is really a question of taste.

**Comment by gizmocuz** [comment]
Thanks, could you also remove the data-i18n fields for the options ?
Could you post a screenshot how the dropdown looks ?

**Comment by DebugBill** [comment]
Done.

Here is a screenshot of the new conditions


notifications

**Comment by gizmocuz** [comment]
Great thank you !
What do you think prefer ... text or symbols ? Maybe you where correct adding the new translations ?
If you also think so, please add the text labels again and i will add the translations asap...

**Comment by DebugBill** [comment]
Really your call. I like both, and it is true that symbols are a way to avoid the translation phase.

**Comment by gizmocuz** [comment]
Okey, then sorry for the double work, but please place back the textual notations... i think it is easier for users without a math background ...

**Comment by DebugBill** [comment]
Done, you can merge

**Comment by gizmocuz** [comment]
Thanks!!

**Pull request merged**
