### PR TITLE
[BleBox] add shutterbox support

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks

**Comment by Intellium** [comment]
After this I'm getting 

``` bash
[ 38%] Building CXX object CMakeFiles/domoticz.dir/hardware/BleBox.cpp.o
/src/domoticz/hardware/BleBox.cpp: In member function 'std::__cxx11::string BleBox::IPToHex(const string&)':
/src/domoticz/hardware/BleBox.cpp:171:10: error: could not convert 'false' from 'bool' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
   return false;
          ^~~~~
CMakeFiles/domoticz.dir/build.make:854: recipe for target 'CMakeFiles/domoticz.dir/hardware/BleBox.cpp.o' failed
make[2]: *** [CMakeFiles/domoticz.dir/hardware/BleBox.cpp.o] Error 1
make[1]: *** [CMakeFiles/domoticz.dir/all] Error 2
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make: *** [all] Error 2
Makefile:149: recipe for target 'all' failed
```

**Comment by gizmocuz** [comment]
fixed by
https://github.com/domoticz/domoticz/commit/dd7d799033a546a1df49f6a32838e10e07dc0534

**Comment by szczukot** [comment]
thanks

**Pull request merged**
