### PR TITLE
Update WebServer.cpp

### PR DESCRIPTION
**Pull request by Olifant1990**
Added extradata as param to sendnotification json command, so you can send a notification to a specific device for example

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you!

**Comment by waltervl** [comment]
@Olifant1990 Can you give some examples of json commands with this new feature (for documentation purposes)
Edit: See also wiki https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Use_Notification_Subsystem

**Comment by Olifant1990** [comment]
@waltervl I don't know the ins and outs for every subsystem, but for FCM I use it this way:

/json.htm?type=command&param=sendnotification&subject=SUBJECT&body=THEBODY&subsystem=fcm&extradata=midx_7

You can enter multiple Idx values like extradata=midx_7;8;9
And you can find the Idx values of the devices on the mobile devices page: Setup -> More Options -> Mobile Devices

I think pushover has some options too, but again, I don't know for other subsystems

**Comment by waltervl** [comment]
Thanks, added to the wiki!

**Pull request merged**
