### PR TITLE
Openzwave full version logging

### PR DESCRIPTION
**Pull request by ikkemaniac**
log the OZW full version, including the git hash compiled from!

### CODE REVIEW

**Comment by ikkemaniac** [comment]
I don't get what you are seeing. This is my debug log:
```
2015-05-31 12:57:39.932  argv:  -loglevel 2 -nocache
2015-05-31 12:57:39.932  Log level: 2
2015-05-31 12:57:39.932  Domoticz V2.g911fa98 (c)2012-2015 GizMoCuz
2015-05-31 12:57:39.932  Startup Path: /opt/domoticz/code/
2015-05-31 12:57:39.933  Inside MainWorker::Start, line 737
...
2015-05-31 12:57:40.003  Inside WebServer::CWebServer, line 98
2015-05-31 12:57:40.003  Inside COpenZWave::COpenZWave, line 270
2015-05-31 12:57:40.003  Inside COpenZWave::GetVersionLong, line 3211
2015-05-31 12:57:40.003  OpenZWave versionLong: 1.3-260-g71d196f-dirty
2015-05-31 12:57:40.003  Inside COpenZWave::GetVersion, line 3204
2015-05-31 12:57:40.003  OpenZWave version: 1.3.260
2015-05-31 12:57:40.003  Inside COpenZWave::~COpenZWave, line 287
...
```

with this in WebServer.cpp
``` c++
//~ log the OpenZWave version
COpenZWave myVar( 1, "OZWversion");
_log.Log(LOG_STATUS, "OpenZWave versionLong: %s", myVar.GetVersionLong().c_str());
_log.Log(LOG_STATUS, "OpenZWave version: %s", myVar.GetVersion().c_str());
```

**Comment by gizmocuz** [comment]
Again, this version number is weird.

If it was something like V2.2666 (also in the web interface), but at 
startup it displays

V2.2666.g911fa98

it would make  more sense

no need to display openzwave version if not used, it should only be 
displayed when starting, or in the hardware page

**Comment by ikkemaniac** [comment]
You're looking in the wrong pull request i think. This is about the OpenZWave version thus not the domoticz version.
OpenZWave is not on version 2 nor 2666, those numbers are from the domoticz svn repo.

This pull is about getting the OZW library version. This would have saved me a lot of trouble if the OZW version is printed to the log.
Domoticz is using the beta (master) branch from OZW. This complicates versioning since OZW does NOT update the minor revision for each commit. Printing the long version will show the git hash and make debugging user problems much easier since you know exactly which commit OZW was build from.

For instance: you switched to the Issue branch a few week back. This threw some users since they tired to build domoticz against an older OZW lib. It wasn't an older version actually but they were still using the master branch. When you show the OZW version including hash this type of issue is potted easily.

**Comment by ikkemaniac** [comment]
ps, in my debug log you can even see the text 'dirty' appended to the OZW version. This means i actually have made changes to the source files without commiting then, giving me a 'dirty' working tree the OZW lib was build from. This kind of info is worth a lot to me when debugging.

**Comment by gizmocuz** [comment]
Yeah, got things mixed up....
I will add the long version number to domoticz, but not just like the way you implemented it
This i will implement now (will be pushed on SVN until i got the migration to github right
until then, this repo is still in test fase and should not be used for merging requests

**Comment by gizmocuz** [comment]
I'll implement it like

bool COpenZWave::OpenSerialConnector()
{
	_log.Log(LOG_STATUS, "OpenZWave: Starting...");
	_log.Log(LOG_STATUS, "OpenZWave: Version: %s", GetVersionLong().c_str());

**Comment by gizmocuz** [comment]
Its committed (also in github)
the long openzwave version is also visible in the web interface

**Comment by ikkemaniac** [comment]
ok tnx!

**Pull request closed without merging**
