### PR TITLE
Added SelectorState (LevelStr) in JSON-calls Schedules & Devices

### PR DESCRIPTION
**Pull request by EddyK69**
Added SelectorState (LevelStr) in JSON-calls Schedules & Devices
- http://<ip>:<port>/json.htm?type=schedules
- http://<ip>:<port>/json.htm?type=devices&filter=all&used=true&order=Name

### CODE REVIEW

**Comment by gizmocuz** [comment]
What will this do ?

**Comment by gizmocuz** [comment]
Where is this used ?

**Comment by EddyK69** [comment]
I use both JSON-calls in custom html-templates to show all my devices and their scheduled timers. For Selectors the state in 'devices' and the switchcmd in 'schedules' is showing only the level% (as if it was a dimmer). I added the level as a string in both JSON-calls now with an extra field 'LevelStr'.

For instance a selector in state 2 will show:
**LevelStr: "Level 02"**

**Comment by gizmocuz** [comment]
How does the domoticz user interface knows which one/state is active ?

**Comment by EddyK69** [comment]
It just translates the levelint (used as index to an array) to a string based on the levelnames of the device

**Comment by gizmocuz** [comment]
Okey, but this will make the json output larger, can you translate them in your javascript ?
(for me, if it's not needed by the native domoticz gui, i would rather not make it larger, and also the dbase query not larger)

**Comment by EddyK69** [comment]
Yeah, but that means a json-call for every timer-row to catch the levelnames of a selector :(

**Comment by gizmocuz** [comment]
Okey, maybe i do not understand

If you have an index (A) and you create a small lookup table with the strings (B)

B={ "Level 01", "Level 02", "Level 03", "..." }

then plotting the Label (C) = B[A]

**Comment by EddyK69** [comment]
I know, but if i have 30 schedules planned for a selector, i have to get the levelnames for this selector for every item in de schedules-json. 

An other solutions would be (if you do not want to enlarge the json-output) to put the levelname in the existing **status** field instead of an extra field.

**Comment by gizmocuz** [comment]
I think indeed that would be best... also for people not knowing index values ;)

**Pull request closed without merging**
