### PR TITLE
Ignore eclipse project in git

### PR DESCRIPTION
**Pull request by sbouchex**
For those using Eclipse (like me)

### CODE REVIEW

**Comment by sbouchex** [comment]
Should be done locally (i.e. on the client side)

**Comment by gizmocuz** [comment]
Maybe you could add the Eclipse project to Domoticz?
Have you looked at 'codelite' ?

**Comment by sbouchex** [comment]
I'm just using Eclipse to manage git and doing a fill Eclipse project would be useless. I don't know codelite, but could be interesting.

**Comment by gizmocuz** [comment]
ahhh okey, bummer... so you could have as well build it from the command line instead of using eclipse?

**Pull request closed without merging**
