### PR TITLE
Dynamic libstdc++/libsqlite

### PR DESCRIPTION
**Pull request by dwmw2**
As discussed in Issue #201 here is a further pull request. It contains the basic fixes I already submitted which should be uncontroversial, and also it makes it **possible** _(but not mandatory, and not the default)_ to link dynamically against libstdc++/libgcc_s/libsqlite.

If this is acceptable, I'll make it work for lua and possible MQTT too.

### CODE REVIEW

**Comment by gizmocuz** [comment]
How small is your storage footprint ? i mean lua/sqlite/mqtt these are small..
boost/gcc/stdc i can imagine
I have to review this, as i am not good with cmake and it took me quite a while to build the script

**Comment by dwmw2** [comment]
OpenWRT covers a lot of devices, many of them _extremely_ limited. Each library might only be a few hundred KiB but that's a few hundred KiB of RAM _and_ flash, for _every_ application that statically links just a few 'small' things...

In the case of Fedora packaging, the motivation is different — there, it's not about size. The packaging guidelines require that we do not ship static copies of libraries which are provided by the system, so that we can have more confidence that (especially security) bug-fixes in libraries will actually be effective everywhere.

**Comment by dwmw2** [comment]
Note that the lua one needs lua 5.2 or greater, while OpenWRT has 5.1 _(and would be hard to upgrade)_. Looking at  the things which actually break in CEventSystem::CreateBlocklyLuaState() I'm a little confused about what's going on.

In that function we call luaL_openlibs() which initialises _all_ the standard modules, by _(internally)_ calling luaL_requiref() for them all. But before that, for some reason we call the 5.2-only luaL_requiref() function for just the "os" module. Which was going to be initalised anyway. And we call the init function of various others but _not_ through luaL_requiref(), which does something _different_ and it's not clear it isn't wrong.

Is there a reason that the call to luaL_openlibs() isn't sufficient? If I was going to play with cleaning that up, what specifically should I be testing to ensure I haven't broken stuff?

**Comment by gizmocuz** [comment]
All with all, why wont you consider a raspberry pi 2 ? Its not expensive and can be used for domoticz only ?
And does not use much energy as well !

**Comment by dwmw2** [comment]
Yeah, there's plenty of such hardware lying around already in fact. But there is a Geode box running OpenWRT already sitting in the cupboard under the stairs where the Honeywell HGI80 gets decent coverage of all the evohome traffic, and on a UPS. Adding yet another box to the system is not really my ideal solution. After all, domoticz on OpenWRT is basically already working; I'm just trying to clean it up a bit and package it properly — for others, and for my own sanity because it should Just Work on future upgrades.

**Comment by gizmocuz** [comment]
Okey Fair _g_
I did not implemented Lua, and the original implementer is not active anymore as a developer.

I think you have to test is 'os' calls are still working, i also see you can use a #define 
http://lua-users.org/lists/lua-l/2012-07/msg00111.html

**Comment by dwmw2** [comment]
Thanks. I've now submitted a package for inclusion in OpenWRT: https://github.com/openwrt/packages/pull/2007

I haven't fully investigated the LUA 5.1 compatibility issues so I've stuck with a static 5.2 for now.

I've also disabled the automatic updates in a local patch, since we'd need to make those a little more careful about precisely which system they're running on — the information from uname() isn't sufficient. Different distributions running on the same sysname/machine may be wildly different, including completely different C libraries and ABIs, etc.

**Comment by gizmocuz** [comment]
Great! Hope all works out fine

**Pull request merged**
