### PR TITLE
fixing blinds open close behaviors

### PR DESCRIPTION
**Pull request by CyrilB1531**
fixing Issue with blinds (DC106 and RFY) since beta 14414 and 14420 #5282

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you very much for this PR and your time!
If you want, you can make 'switchcmd' not const, so you do not have to declare it in a new variable

**Comment by CyrilB1531** [comment]
@gizmocuz Thank you for your feed back. There are too much changes if I remove const in signature. I'd let it as is if you don't mind

**Comment by gizmocuz** [comment]
Thank you for this PR!!

**Comment by kipusoep** [comment]
I'm sorry, but how can a piece of code like this get merged?

```
if (switchCommand == "On")
	switchCommand = "Off";
else if (switchCommand == "Off")
	switchCommand = "On";
```

**Comment by kiddigital** [comment]
> I'm sorry, but how can a piece of code like this get merged?
> 
> 
> 
> ```
> 
> if (switchCommand == "On")
> 
> 	switchCommand = "Off";
> 
> else if (switchCommand == "Off")
> 
> 	switchCommand = "On";
> 
> ```

Valid code in its context.

**Comment by kipusoep** [comment]
Well apparently not as it's messing up all other zigbee devices.

**Pull request merged**
