### PR TITLE
Update to dzVents 2.4.23

### PR DESCRIPTION
**Pull request by rwaaren**
Update to dzVents 2.4.23
- Add setMode for evoHome controller
- Add incrementCounter for counter incremental
- Prepared for fcm (Firebase Cloud Messaging)
- Fixed small typo's 
- Prevent use of method switchSelector for devices other then selectors.

	modified:   History.txt
	modified:   dzVents/documentation/README.md
	modified:   dzVents/documentation/README.wiki
	modified:   dzVents/documentation/history.md
	modified:   dzVents/runtime/Domoticz.lua
	modified:   dzVents/runtime/EventHelpers.lua
	modified:   dzVents/runtime/Utils.lua
	modified:   dzVents/runtime/device-adapters/counter_device.lua
	modified:   dzVents/runtime/device-adapters/evohome_device.lua
	modified:   dzVents/runtime/device-adapters/switch_device.lua
	new file:   dzVents/runtime/integration-tests/scriptTestUpdatedDocumentation.lua
	modified:   dzVents/runtime/integration-tests/stage1.lua
	modified:   dzVents/runtime/integration-tests/stage2.lua
	modified:   dzVents/runtime/integration-tests/testIntegration.lua
	modified:   dzVents/runtime/tests/testDevice.lua
	modified:   main/dzVents.cpp

### CODE REVIEW

**Comment by Olifant1990** [comment]
@rwaaren 
The GCM subsystem will still be the same in Domoticz. See https://github.com/domoticz/domoticz/issues/3292 We did not rename the GCM to FCM at the end. Only the URL has been changed.

**Comment by rwaaren** [comment]
> @rwaaren
> The GCM subsystem will still be the same in Domoticz. See #3292 We did not rename the GCM to FCM at the end. Only the URL has been changed.


Thx updated the PR accordingly

**Comment by RunnicFusion** [comment]
When will this fix (#3292) be released into the stable version of Domoticz?

**Comment by gizmocuz** [comment]
When OZW 1.6 is stable enough so we can create a new stable version.
Until then no new stable release...

**Comment by RunnicFusion** [comment]
> When OZW 1.6 is stable enough so we can create a new stable version.
> Until then no new stable release...

In what form is this related to each other? Do you know when 1.6 is stable enough, are we talking about days, weeks, months?

**Comment by gizmocuz** [comment]
@RunnicFusion , stables are made from beta's that have been marked as pre-stable
I can not tell you when something get's stable, that depends on developers, if you could help debug/test the OZW 1.6 code/integration that could help

**Pull request merged**
