### PR TITLE
Propagate device deletes to *Link tables

### PR DESCRIPTION
**Pull request by rwaaren**
Add delete device from 

PushLink
HttpLink
FibaroLink
GooglePubSubLink

tables when device is deleted.

### CODE REVIEW

**Comment by rwaaren** [comment]
Fix for #4036

**Comment by gizmocuz** [comment]
Thank you for this ! Maybe it is a idea to migrate them all to one database in the feature
They seem all the same except the PushLink as an additional 'PushType' field which we could set to 0 as default
No idea why it is now in different tables ... it has been so since quite some time
We could use the 'PushType' for the type of pusher, like Fibaro, Influx etc..
Currently it is always set to 1
Let me create a quick PR for this and maybe you could share your idea about this...

**Comment by rwaaren** [comment]
If you are going to merge these tables into one new, could you please also change the field deviceID to deviceRowID to make it consistent with all other tables.
(That is; if there is no specific reason to have a different name in the *Link tables)

**Comment by gizmocuz** [comment]
Pff that was not an easy patch... verified all database table migrations .. Should be OK

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/pull/4042

**Comment by gizmocuz** [comment]
Thanks for the PR, closing it because it's inside PR 4042

**Pull request closed without merging**
