### PR TITLE
Daikin multiple bug corrections

### PR DESCRIPTION
**Pull request by dgrostoto**
see issue https://github.com/domoticz/domoticz/issues/4007 for complete documentation

### CODE REVIEW

**Comment by dgrostoto** [comment]
PR finished.

**Comment by dgrostoto** [comment]
waiting for review

**Comment by dgrostoto** [comment]
updated done

**Comment by gizmocuz** [comment]
Thank you!

**Comment by dgrostoto** [comment]
I'll keep it for the moment if anything goes wrong (something i did not anticipate)

**Pull request merged**
