### PR TITLE
Fix difference between domoticz.time object and trigger

### PR DESCRIPTION
**Pull request by trandbert37**
Fix problem for when "at sunrise" is triggered, this script logs "night" instead of "day":
```
return {
    on = {
        timer = {
            'at sunrise',
            'at sunset'
        }

    },
    execute = function(domoticz)
        if (domoticz.time.isNightTime)) then
                domoticz.log('Night', domoticz.LOG_INFO)
        elseif (domoticz.time.isDayTime) then
                domoticz.log('Day', domoticz.LOG_INFO)
        end
    end
}
```

### CODE REVIEW

**Comment by dannybloe** [comment]
Ah.. great. But this seems more like a bug in Domoticz then dzVents so perhaps the dzVents version didn't have to be udpated?

**Comment by gizmocuz** [comment]
Yep, seems only a patch for "EventSystem.cpp" is needed, could you undo the other changes ?

**Comment by trandbert37** [comment]
You are right ;-) done

**Comment by gizmocuz** [comment]
Thanks for the PR!

**Pull request merged**
