### PR TITLE
Update hardware.html for a minor spell error

### PR DESCRIPTION
**Pull request by steljwagh**
Update hardware.html for a very minor spell check error. The instruction is confusing when a capital 'U' implies a new sentence.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Seems this is the beginning of a new sentence ? And that should start with a capital letter

**Comment by steljwagh** [comment]
No, believe me. It is part of the instruction:
To quickly force ....<removed> use the tamper switch on the back to wake up the device.

I experienced to confusion while needing this instruction. And the 'To quickly....' sentence doesn't even close with a '.'. I also asked for a second opinion in my surroundings to verify ;).

**Comment by raymck** [comment]
As a native English speaker, I can verify that letter U in this commit is indeed in the middle of a sentence and should not be capitalized. :)

**Comment by gizmocuz** [comment]
Thanks all!

**Pull request merged**
