### PR TITLE
Icon for P1 Meter Gas, added json functions for enable/disable (scene)timers

### PR DESCRIPTION
**Pull request by EddyK69**

### CODE REVIEW

**Comment by EddyK69** [comment]
What about the extra json-functions?  I would be very happy is you implement there. (i don't know yet how to make separate pull-requests for different commits ;(

**Comment by gizmocuz** [comment]
Yes, and i dont know how to merge separate commits from one pull request

**Comment by EddyK69** [comment]
ok, i will try to cancel this pull-request and make separate requests per commit...

**Comment by gizmocuz** [comment]
that would be great!

**Pull request closed without merging**
