### PR TITLE
Added netatmo thermostat support

### PR DESCRIPTION
**Pull request by sbebrone**
I've added basic hardware support for Netatmo's thermostat. 
The code has been heavily inspired by the weather station and the Nest thermostat.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks a lot !
Could you verify that you can use the same m_clientId and m_clientSecret as in the original netatmo class as we already are registrated by Netatmo (and on the support list)

As both classes are almost identical, i think i will merge them into one

Is it possible to send me a PM on the forum?

**Comment by sbebrone** [comment]
I confirm that it works with existing keys, updated the PR with the commit.

Btw, it seems that I cannot send PM on the forum yet: "We are sorry, but you are not authorised to use this feature. You may have just registered here and may need to participate more to be able to use this feature."

**Comment by gizmocuz** [comment]
Send you by accident an empty email..but you have my email now 😀

**Comment by fredleroy** [comment]
Hi, I'm also very interested in this feature. If I can do anything to help...

**Comment by gizmocuz** [comment]
Send me a PM on the forum with the login credentials

**Comment by fredleroy** [comment]
I'd like to... But forum says I cannot send PMs cause I haven't been active enough...

**Comment by jbfenris** [comment]
Hi, Thanks for the implementation !
Why do you have integrated your own Netatmo Client-Id and Client-Secret directly in the code ?
Do you  think it could be possible to put it as a parameters to set when we declare a new hardware ?

**Comment by gizmocuz** [comment]
This is a domoticz wide clientid/secret, and is registrated @ netatmo, we are also in the official support list
So to answer your question, no this will not be allowed

**Comment by gizmocuz** [comment]
Implemented, thanks for the support

**Pull request closed without merging**
