### PR TITLE
MQTT prevent loop on updating Thermostat devicetypes

### PR DESCRIPTION
**Pull request by rwaaren**
Fix for the MQTT loop prevention part of issue #4282

### CODE REVIEW

**Comment by rwaaren** [comment]
@gizmocuz Any chance that this quick fix is going to be merged or should I close it ?

**Comment by gizmocuz** [comment]
@rwaaren , I need to test it. It might very well be that the problem is caused upstream

**Comment by Eddie-BS** [comment]
Any idea when this will be merged ?

**Comment by gizmocuz** [comment]
@Eddie-BS , see the comment above

**Comment by rwaaren** [comment]
Root cause of this issue has been solved by @gizmocuz with  https://github.com/domoticz/domoticz/commit/01784e66e439f92a4ae87022490e072eb8f495ac

**Pull request closed without merging**
