### PR TITLE
Build failure with python 3.9

### PR DESCRIPTION
**Pull request by jzapater**
Signed-off-by: Jose Zapater <jzapater@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the patch !

**Comment by jzapater** [comment]
Great software, used for many years;)

**Comment by kofec** [comment]
Remaber also about: 

if (!shared_lib_) shared_lib_ = LoadLibrary("python38_d.dll"); 
add for version 3.9

The same issue was in openwrt version

**Comment by jzapater** [comment]
@kofec Corrected in #4436 Thanks.

**Pull request merged**
