### PR TITLE
Add support for Remeha Calenta 40C

### PR DESCRIPTION
**Pull request by TheLizard**
Added support for the Remeha Calenta 40C

Currently it is just a single device, when there is demand, it is possible to create device recognition and automatically support all the other devices as well (all config files from the remeha recom software have been added)

For now only the temperature and percentage valued devices are added as devices.

### CODE REVIEW

**Comment by TheLizard** [comment]
Unfortunately it took a whole lot of commits, because I don't have a working VS win32 build environment. Please let me know if anything else is required

**Comment by gizmocuz** [comment]
Maybe easier to get yourself an opentherm gateway ? (or a thermostat that you can control from domoticz?)

**Comment by TheLizard** [comment]
This didn't cost me anything and it was fun to build, 
also the opentherm gateway has to be placed next to the Remeha as I can't access the cable anywhere else, and still uses the raspberry pi to retrieve the data.

**Comment by gizmocuz** [comment]
I agree, and it was a lot of work !
It is only that maybe one or two people will use this, over the larger and easier available thermostat support.

**Comment by gizmocuz** [comment]
Hardware to specific, not maybe will use this.

**Pull request closed without merging**
