### PR TITLE
Aircon with me

### PR DESCRIPTION
**Pull request by LarsenDX**
Clean up AirconWithMe, see PR #4357

### CODE REVIEW

**Comment by gizmocuz** [comment]
@LarsenDX , thank you for the PR.

Is it possible to:

- declare the Poll interval as a '#define' in the source file
- remove the poll interval in Hardware.html (this will also resolve the merge conflict, just replace the Hardware.html file with the current file from the repository)
- remove the poll interval code in Hardware.js (related to AirconWithMe of course)

**Comment by LarsenDX** [comment]
> @LarsenDX , thank you for the PR.
> 
> Is it possible to:
> 
>     * declare the Poll interval as a '#define' in the source file
> 
>     * remove the poll interval in Hardware.html (this will also resolve the merge conflict, just replace the Hardware.html file with the current file from the repository)
> 
>     * remove the poll interval code in Hardware.js (related to AirconWithMe of course)

@gizmocuz, poll interval code replaced with #define . Thank you for the Hardware.html tip, saved me some work. The AirconWithMe hardware should now be good to go.

**Comment by gizmocuz** [comment]
@LarsenDX , thank you (and @RDols ) very much for all the work and PR!

**Comment by mcmikev** [comment]
Hi, Thanks for this great addon. I use it with my Airco and can create schedules and triggers (windows open etc)

But there is one thing that is an issue for me. When I change the IP of the airconwithme module, and change that in domoticz then the worker stops but fails to start after that.
 2020-11-06 18:44:58.003 Error: AirconWithMe: Login failed : request failed!
2020-11-06 18:44:58.003 Error: AirconWithMe: GetAvailableDataPoints failed : 

Only possible fix then is to remove hardware completly in domoticz and re-add it with new ip. That is some sort of a hassle to do so maybe this bug/error can be fixed?

And yes, the username and password are 100% correct.

**Comment by RDols** [comment]
Hmmm. Im able to reproduce the error. I will look into this.

**Comment by mcmikev** [comment]
> 
> 
> Hmmm. Im able to reproduce the error. I will look into this.

Great that it is reproducable.. Hope that It's a quick and simpel fix for you

**Comment by RDols** [comment]
@mcmikev I tried to reproduce the error again. The only way i can reproduce this as you described is with a wrong username/password combination. Since you 100% confident you had entered the correct username and password, three additional questions.

1. Did this happen more then once?
2. Does the error persist after you restarted domoticz?
3. do you use the default username password (operator / operator) ?

**Comment by LarsenDX** [comment]
Hi, I have 3 AirconWithMe modules in my house. I ran some tests and can confirm the behaviour as follows:
* In the hardware list click on the AirconWithMe hardware (already configured and enabled)
* Don't change any value, click Update
* or re-enter operator/operator in the Username/Password fields, click Update

It throws the errors in the log:

2020-11-09 13:26:25.987 Error: AirconWithMe: Login failed : request failed!
2020-11-09 13:26:25.988 Error: AirconWithMe: GetAvailableDataPoints failed

**Comment by LarsenDX** [comment]
If I had to guess I'd say there's something wrong with the Update code. If I look at the DB following a click on Update, I see that the password is not set for the hardware. Instead, it reads "undefined".
Screenshot 2020-11-09 at 14 13 45

**Comment by LarsenDX** [comment]
Found it! hardware.js is missing 
 				var password = encodeURIComponent($("#hardwarecontent #divlogin #password").val()); 
I dropped the line when I was cleaning up the code for the PR. Mea culpa.

**Pull request merged**
