### PR TITLE
Added support for Libre Hardware Monitor

### PR DESCRIPTION
**Pull request by Eegee**
On Windows, added support for Libre Hardware Monitor, with a fallback to Open Hardware Monitor, as the latter hasn't been maintained recently.

### CODE REVIEW

**Comment by kiddigital** [comment]
Thx, seems useful.

As I don't run Windows, did you test with both Open and Libre?

Which versions (and which Windows version).

**Comment by gizmocuz** [comment]
@Eegee , I had a look at your PR and looks perfect! Still support for both monitors so current users won't have issues, but main set to Libre.
Great job, thanks for the PR!

**Comment by Eegee** [comment]
I am very sorry, I made a mistake. The fallback does not seem to work properly: open hardware monitor is still not detected even if it is running. I will investigate further and will try to come up with a proper solution. @gizmocuz

**Comment by gizmocuz** [comment]
No problem. I will take it out the release version for now. But might be better to switch to Libre 100% if you can't get it working

**Pull request merged**
