### PR TITLE
dzVents Shell Command: Removed some more logging

### PR DESCRIPTION
**Pull request by akamming**
This logging should be visibile when debugging only

### CODE REVIEW

**Comment by kiddigital** [comment]
@akamming , why use compiletime debug (#ifdef) and not runtime debug (_log.Debug)? Makes it much easier to just (re)start domoticz with Debug flags enabled.

**Comment by gizmocuz** [comment]
Yep, I agree with that, It's what it is designed for ;)

**Comment by akamming** [comment]
ok... corrected...

**Comment by gizmocuz** [comment]
Thank you!

**Pull request merged**
