### PR TITLE
Added Netatmo Thermostat status as Utility/GeneralPercent

### PR DESCRIPTION
**Pull request by olivierberthomme**
Match the feature request #3039 Netatmo 'boiler_status' binary switch

Use the Netatmo public API to parse the actual "boiler status" and push it to Domoticz to new device "Status" true==100% ; false == 0%

### CODE REVIEW

**Comment by olivierberthomme** [comment]
Commit log is not clear as I did not merge my dev to a "staging" branch. Anyway, the goal is write the current Netatmo Thermostat state. 
The current Netatmo Thermostat state should help my to log my convector's costs.

I first tried with a switch but as the Netatmo API do not allow to overide the thermostat so the switch should be "read only". I also faced issue retriving which switch is pressed from Domoticz interface (I was tring to identify Away switch from Status switch by their ChildID but did not found how to). Then I rewrited my dev and coded the state into a PercentageSensor (which is read-only by design).

Please advise if something's unclear / badly coded.

**Comment by gizmocuz** [comment]
As this is a on/off status, please use a switch
You can later change the switch type in the user interface or set you own icon
It will also be much easier to use a switch in scripting

**Comment by olivierberthomme** [comment]
> As this is a on/off status, please use a switch
> You can later change the switch type in the user interface or set you own icon
> It will also be much easier to use a switch in scripting

OK Thanks for you answer.
I agree to use a basic switch but I did not find a way to identify the pressed switch from WriteToHardware function... As the hardware will get 2 switches (Away + Status) how could I know the switch pressed from interface ?
Tried: pCmd->LIGHTING2.packettype ; pCmd->LIGHTING2.subtype

Could you help me?

**Comment by gizmocuz** [comment]
@olivierberthomme , you give the ID/Unit to the switch, so it should be easy to find out what switch is pressed i think ?
The ID is in LIGHTING2.id1 till LIGHTING2.id4

**Comment by olivierberthomme** [comment]
I finally managed to make it works with a On/Off switch. Many thanks for your help.
Played with bitwise and bit shift operand.

Sorry again for the messy commit log... forget to squash commit while merging. If it's an issue; let me know.

**Comment by gizmocuz** [comment]
Thanks!!

**Pull request merged**
