### PR TITLE
#3666 ASyncTCP fix for hanging in destructor

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you very much for all work and this PR !!! Much appreciated, and hope to test this very soon!

Is it possible to change normal member variable initialization to look like

bool m_bMyBool = true;

instead of

bool m_bMyBool ( true };

This makes it more uniform throughout the application.

I would only use "uniform" initialization for structs/classes/arrays and so

**Comment by ghost** [comment]
Yes no problem, i will do so.

**Comment by ghost** [comment]
I pushed the changes for both the PR. 

Be critical at the code style. I think its important for readability to have the same style.

**Comment by gizmocuz** [comment]
Thanks!!

**Pull request merged**
