### PR TITLE
[LUA] Ability to disable recurring logging

### PR DESCRIPTION
**Pull request by YcKe**
Add the ability to disable recurring logging when a LUA script is
executed. This can be specified in the LUA script by adding `_donotlog_`
to the script name. E.g.: script_time_donotlog_MyScriptName

### CODE REVIEW

**Comment by gizmocuz** [comment]
It would be much nicer to let the user specify this in the script.. is that possible ?
This is a quick hack ;)

**Comment by gizmocuz** [comment]
Pff lot of changes.. how does this work now ? Do you have a small lua example ?

**Comment by YcKe** [comment]
The recurring logging is disabled when the user adds the following statement to the Lua script:
commandArray['DoNotPerformLogging'] = "1"

Incase the value is 0 or the value is not added to the commandarray, the recurrent log is shown as it was originally. This way existing scripts are not impacted.

Thanks for your time!

**Comment by gizmocuz** [comment]
Dont know what kind of patch this is... but something must have gone wrong

**Pull request closed without merging**
