### PR TITLE
Compress translation files at build time

### PR DESCRIPTION
**Pull request by deece**
We can't merge or review changes to binary files, so keeping the translation files as text is preferable.

With this patch, compressed versions are created at build time instead of being checked in. Tested on Linux, needs to be verified on Windows.

### CODE REVIEW

**Comment by deece** [comment]
Hmm, Travis is using an ancient cmake - do you mind if I update it?

Also, the Windows build does not appear to be using cmake, should it?

**Comment by gizmocuz** [comment]
Thats correct, and you can not make changes to the translation files directly
You have to use transifex for this, as this is our translation system

**Comment by deece** [comment]
Can Transifex work with the uncompressed json files? If so, there is still value in this change, if not, I'll close this pull request and refactor the consistency checking script to work with the compressed files instead.

**Comment by gizmocuz** [comment]
If you make changes on transifex, they will get merged in domoticz eventually
I already have a script that updates the translation files... in fact, it is also in the repo (in the tools folder)

**Comment by gizmocuz** [comment]
Any changes directly made in the translation files are overwritten when there is an update

**Comment by deece** [comment]
This should now compress the json files at build time on both Windows & Unix, and provides developers more visibility into the changes that occur in the translation files (even if they can't edit them).

This also adds a tools to report missing and unused translations, allowing better planning of future translation work.

A minor change to the Transifex config is required, that is to pull the updated json files to the top level i18n directory, where they can be immediately added to the repository. (I couldn't test this as I don't have a Transifex account).

During the build, the raw json files are compressed and emitted into www/i18n.

**Comment by gizmocuz** [comment]
Raspberry is using CMake 2.8.9

**Comment by deece** [comment]
Is your machine up to date? If so, what distribution are you running?

root@homeautomation:~# cat /etc/os-release
PRETTY_NAME="**Raspbian GNU/Linux 8 (jessie)**"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

aroot@homeautomation:~# apt-get install cmake
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  cmake-data
Suggested packages:
  codeblocks eclipse ninja-build
The following NEW packages will be installed:
  cmake cmake-data
0 upgraded, 2 newly installed, 0 to remove and 8 not upgraded.
Need to get 2,799 kB of archives.
After this operation, 14.3 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main cmake-data all 3.0.2-1 [929 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main cmake armhf 3.0.2-1 [1,870 kB]
Fetched 2,799 kB in 2s (1,110 kB/s)
Selecting previously unselected package cmake-data.
(Reading database ... 124653 files and directories currently installed.)
Preparing to unpack .../cmake-data_3.0.2-1_all.deb ...
Unpacking cmake-data (3.0.2-1) ...
Selecting previously unselected package cmake.
Preparing to unpack .../cmake_3.0.2-1_armhf.deb ...
Unpacking cmake (3.0.2-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up cmake-data (3.0.2-1) ...
Setting up cmake (3.0.2-1) ...
root@homeautomation:~# cmake --version
**cmake version 3.0.2**

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by gizmocuz** [comment]
to many changed files, can't be true, can't accept this patch
Happy to look at another patch if you like

**Comment by deece** [comment]
The majority of the changes come from replacing the compressed translation files with uncompressed ones (commit 45004252ccc0228e35e2e3de7e40c0cb58b80a29).

**Comment by gizmocuz** [comment]
That's already done I thought...

**Comment by gizmocuz** [comment]
And a lot of white space changes

**Comment by szczukot** [comment]
I have RPI and i have installed cmake 2.8.9

**Pull request closed without merging**
