### PR TITLE
add clang-format file

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Note that this will replace tabs with spaces. The codebase currently uses a mix of tabs and spaces.

This is basically just clang-tidy --dump-config with column limit bumped to 100.

### CODE REVIEW

**Comment by gizmocuz** [comment]
I think (hope) dat 99,9% the code is using tabs instead of spaces.
Could you adjust this ?

**Comment by neheb** [comment]
Do you mean to change https://github.com/domoticz/domoticz/pull/4418/commits/8679c58078b821ee116605b4c549a30e8311551c#diff-1026e0038b722990204a42bed8a6f7c0ec2302aa79e3fad1959d62ba968edfa2R135 ?

**Comment by gizmocuz** [comment]
@neheb , Yes I think thank field would do the trick. I do have to get myself some clang-format lessons

**Comment by neheb** [comment]
Reworked the file so that it's closer to the style used here.

**Comment by gizmocuz** [comment]
Thank you !!

**Pull request merged**
