### PR TITLE
P1 Smart meter update logic (again)

### PR DESCRIPTION
**Pull request by jvandenbroek**
Make sure that the meter is updated at least once a minute.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by adgoudsmit** [comment]
Guys, this fails when you have solar panels. Then "usagecurrent" is 0 during the day, hence only every minute an update from my smart meter.

**Comment by gizmocuz** [comment]
Ehhh you are talking about the >40 ? This was already there a long time
this is also not for delivery
if you want this for delivery to, you could make a patch so it will be an OR ||
if ((usage_difference>40)||(delivery_difference>40)))

**Comment by adgoudsmit** [comment]
Ok, this might have been there since some time, but with the latest changes this causes a one minute update for me now. So this is an issue for everybody who has solar panels. I also added some comments on 2f1cb58.

**Pull request merged**
