### PR TITLE
cWebem isnew connection problem

### PR DESCRIPTION
**Pull request by Krzysztof1234534**
Extracted cWebem changes from https://github.com/domoticz/domoticz/pull/5849 pull request as SQLHelper problem was fixed different way.

### CODE REVIEW

**Comment by kiddigital** [comment]
I will have a look as I am unsure if removing the check to see if it is not an API call is correct. I think it was the main reason for the code block.

And I think you are right that the `authorize` function can be removed as the 'auth basic' method is now only available for API consumption.

Will take a little time but I will get back.

**Comment by gizmocuz** [comment]
Yes, I think the API call check could stay as well.

**Comment by Krzysztof1234534** [comment]
json.htm is API call, but web page in browser also calls json.htm. Not everything was moved to web sockets, you for example if you go to Log page, you will see in developer window that json.htm is called every 5 seconds. So if this is check for unauthorized API calls, it means that is bad check. 

Moreover json.htm check is in code since 5 years, but I've observed this multiple "Status: [web:80] Incoming connection from: ..." recently. So I've checked code what cause it. I know that in 2022.2 there was no such problem, and I thing that I found reason why. This is the code from 2022.2:
```
// Check authentication on each page or action, if it exists.
bool bCheckAuthentication = false;
if (isPage || isAction)
{
	bCheckAuthentication = true;
}

...

// Check user authentication on each page or action, if it exists.
if ((isPage || isAction || bCheckAuthentication) && !CheckAuthentication(session, req, rep))
{
	return;
}
```
As you can see at this days if something was page or action, there was enabled CheckAuthentication. But if something was not page (for example css resources), then probably CheckAuthentication was not executed (probably because I've didn't analyse what IsPageOverride function doing). Note that CheckAuthentication sets "session.isnew = true;" and this cause that we have multiple log messages.

So I'm still not convinced if this json.htm should stay, because it does not mean that it is api call from something else than browser (it can be api call from browser). But maybe we should consider to reimplement isPage and isAction and set "session.isnew = false;" if !isPage && !isAction

**Comment by gizmocuz** [comment]
Could you tell us some more information:

- Are you using a username/password to login, or is your IP address in the trusted networks in Domoticz?
- When you are using a private browser (control-shift-n) and browser to Domoticz, do you also get that many Incoming connection messages?

This PR consists of two patches, removal of an unused function, and your actual patch.
I took out the obsolete function in the current branch. Thanks for noticing.

**Comment by Krzysztof1234534** [comment]
This is a problem when it is trusted network. I've didn't notice this problems in private browser. In normal browser it is only once a day, not every time. This problem is related with 2 things:
1. Cookie must to be expired, but it is not only reason, because cookie expiring after 10 minutes. Also clearing browsers cache does not causing this problem. 
2. Browser needs to send multiple requests at the same time to refresh all page resources (probably it sends If-Modified-Since header, but I've didn't debug this too much, so do not know if domoticz responds 304 Not Modified or not) and browser does not doing it frequently. 

I'm using Firefox and I can observe this once a day after 10 hours period with PC turned off. When I introduced this change on my branch, it does not happen any more.

**Comment by gizmocuz** [comment]
Thanks for the explanation.
It could also be an issue of one of your extensions, that's why I asked if you see this in a private browser
Domoticz will send 304 for all resources except json.htm and the theme style css/js
You are using the default theme?
I get 1 incoming connection message, sometimes two, but no more than this.
Maybe you can also test with another browser (like edge)

**Comment by Krzysztof1234534** [comment]
I'm using elemental theme. I've installed Chrome browser, without any extension and there are 4 requests (much less than Firefox) so it is not the problem with browser plugins. I'll also try to investigate if there is something in domoticz settings that may cause this issue, but now I'm seeing that this is easy to repeat: no need to wait entire day, 30 min is enough, but during this time browser window with domoticz needs to be closed. After that I'm opening domoticz from favourites, using such url: http://192.168.4.111/#/Dashboard

I've extended logging in this area, and here is the list of resources requested by chrome:
```
2023-10-30 20:33:03.626 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /app/events/Events.css
2023-10-30 20:33:03.627 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /app/devices/Devices.css
2023-10-30 20:33:03.636 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/domoticz.js
2023-10-30 20:33:03.636 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/domoticzdevices.js 
```

And by Firefox:
```
2023-10-30 20:30:49.198 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/bootstrap.css
2023-10-30 20:30:49.199 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/ui-darkness/jquery-ui.min.css
2023-10-30 20:30:49.199 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/ui-grid.min.css
2023-10-30 20:30:49.200 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /font-awesome/css/fontawesome.min.css
2023-10-30 20:30:49.200 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/demo_table_jui.css
2023-10-30 20:30:49.201 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/style.css
2023-10-30 20:30:49.201 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/colpick.css
2023-10-30 20:30:49.202 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/jquery.uix.multiselect.css
2023-10-30 20:30:49.202 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/jquery-ui-timepicker-addon.css
2023-10-30 20:30:49.203 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/remote.css
2023-10-30 20:30:49.203 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /css/wheelcolorpicker.css
2023-10-30 20:30:49.204 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /font-awesome/css/solid.min.css
2023-10-30 20:30:49.204 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/noty/noty.css
2023-10-30 20:30:49.205 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/noty/relax.css
2023-10-30 20:30:49.205 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /app/events/Events.css
2023-10-30 20:30:49.205 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /app/devices/Devices.css
2023-10-30 20:30:49.207 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /styles/default/custom.css
2023-10-30 20:30:49.207 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/babel-polyfill-6.26.0.js
2023-10-30 20:30:49.208 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery-3.6.0.min.js
2023-10-30 20:30:49.208 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/i18next-1.8.0.min.js
2023-10-30 20:30:49.209 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/bootstrap.min.js
2023-10-30 20:30:49.209 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/bootbox.min.js
2023-10-30 20:30:49.210 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery-ui.min.js
2023-10-30 20:30:49.210 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery.ui.touch-punch.min.js
2023-10-30 20:30:49.211 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/highcharts/themes/dark-unica.js
2023-10-30 20:30:49.211 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery.uix.multiselect.min.js
2023-10-30 20:30:49.217 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/qrcode.js
2023-10-30 20:30:49.217 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery.ddslick.min.js
2023-10-30 20:30:49.228 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/domoticz.js
2023-10-30 20:30:49.237 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/domoticzdevices.js
2023-10-30 20:30:49.238 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery-ui-timepicker-addon.js
2023-10-30 20:30:49.238 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/colpick.js
2023-10-30 20:30:49.239 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /styles/default/custom.js
2023-10-30 20:30:49.240 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/jquery.wheelcolorpicker.js
2023-10-30 20:30:49.240 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/require.min.js
2023-10-30 20:30:49.241 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/noty/noty.min.js
2023-10-30 20:30:49.242 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/moment-with-locales.min.js
2023-10-30 20:30:49.242 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/moment-timezone-with-data.min.js
2023-10-30 20:30:49.242 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/data-tables/jquery.dataTables.min.js
2023-10-30 20:30:49.243 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/data-tables/dataTables.tableTools.min.js
2023-10-30 20:30:49.243 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/data-tables/dataTables.select.min.js
2023-10-30 20:30:49.244 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/ZeroClipboard.js
2023-10-30 20:30:49.244 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/date.format.js
2023-10-30 20:30:49.245 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/highcharts/highcharts.js
2023-10-30 20:30:49.245 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/highcharts/highcharts-more.js
2023-10-30 20:30:49.245 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/highcharts/modules/no-data-to-display.js
2023-10-30 20:30:49.246 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /js/highcharts/modules/exporting.js
2023-10-30 20:30:49.248 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Customw48_Sel.png
2023-10-30 20:30:49.248 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Customww48.png
2023-10-30 20:30:49.249 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Down48_2.png
2023-10-30 20:30:49.250 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Up48_2.png
2023-10-30 20:30:49.250 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Coltemp48.png
2023-10-30 20:30:49.253 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/hardware.png
2023-10-30 20:30:49.254 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/users.png
2023-10-30 20:30:49.254 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/restart.png
2023-10-30 20:30:49.255 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/shutdown.png
2023-10-30 20:30:49.255 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Push48_Off.png
2023-10-30 20:30:49.256 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/about.png
2023-10-30 20:30:49.257 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/house.png
2023-10-30 20:30:49.258 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Stop48.png
2023-10-30 20:30:49.258 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/RGB48_Sel.png
2023-10-30 20:30:49.259 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/temperature.png
2023-10-30 20:30:49.260 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/RGB48.png
2023-10-30 20:30:49.261 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/scenes.png
2023-10-30 20:30:49.261 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Customww48_Sel.png
2023-10-30 20:30:49.262 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Down48.png
2023-10-30 20:30:49.262 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Up48.png
2023-10-30 20:30:49.263 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Push48_On.png
2023-10-30 20:30:49.264 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Coltemp48_Sel.png
2023-10-30 20:30:49.264 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/White48.png
2023-10-30 20:30:49.265 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/White48_Sel.png
2023-10-30 20:30:49.266 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/Customw48.png
2023-10-30 20:30:49.266 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/setup.png
2023-10-30 20:30:49.267 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/devices.png
2023-10-30 20:30:49.268 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/utility.png
2023-10-30 20:30:49.268 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/rain.png
2023-10-30 20:30:49.269 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/camera_default.png
2023-10-30 20:30:49.269 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/desktop.png
2023-10-30 20:30:49.270 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/logo/57.png
2023-10-30 20:30:49.271 Status: [web:80] Incoming connection from: 192.168.4.52 Uri: /images/lightbulb.png 
```

**Comment by kiddigital** [comment]
Please run domoticz with additional startup flag `-debuglevel webserver,received`. The debuglogging will show what the domoticz webserver receives and returns. It might be related to the (lack of) presence of the session cookie.

**Comment by Krzysztof1234534** [comment]
I've perform more tests and the same as on Chrome we can see on Edge. I've also tested clean database (with Trusted Network configured) and also checked Win32 version - it is the same effect. 
Attached log files from windows for Firefox and Chrome:
[domoticz.Chrome.log](https://github.com/domoticz/domoticz/files/13253981/domoticz.Chrome.log)
[domoticz.Firefox.log](https://github.com/domoticz/domoticz/files/13253982/domoticz.Firefox.log)

The scenario to repeat this:
1. Open browser with URL to dashboard.
2. ctrl+shift+F5 to refresh page
3. close entire browser or only a tab with domoticz
4. Wait 15 or 30 minutes
5. open browser or new tab and enter URL to dashboard

Note that second time cookies are expired. It seams that Chrome sends expired cookie, but Firefox do not. 
On Chrome and Edge it sends this 4 files, because there is such header:
`Cache-Control: no-cache,must-revalidate`
On another files (for example /css/bootstrap.css) there is such header:
`Cache-Control: public,max-age=86400,s-maxage=86400,must-revalidate`

On firefox there is something called "Race Cache With Network (RCWN)" - when network connection is fast it can simultaneously download some files from cache and from network, when cache is faster, the version from cache is taken, when network is faster, the reading from cache is stopped. The effect is that some of the files are downloaded from network and another from cache. This causing that there is much more "Incoming connection from:" messages from Firrefox.

**Comment by kiddigital** [comment]
Thank you for your concise work in the effort to find the reasons behind this.

Chrome and Edge are using the same underlying browser engine which explains why the behavior is the same. Firefox (and Apple's Safari also) has its own browser engine behaving differently.

**Comment by kiddigital** [comment]
@Krzysztof1234534 , I have been looking at your proposed change (remove checking if API call) but the code block is specifically intended for API calls only.

The ways modern browsers try to speed up the user experience by doing multiple parallel calls (even when in cache like Firefox does) is causing the many 'Incoming connection' log messages.

Currently I am working on some code refactoring of the webserver which includes lowering the amount of these messages when additional resources are requested in parallel.

Therefor I have closed this PR.

Thank you again for getting to the bottom of this.

**Pull request closed without merging**
