### PR TITLE
Added subtype RM174RF smoke detector

### PR DESCRIPTION
**Pull request by tomsongurbo**
Added subtype for RM174RF smoke detector (sold e.g. under brand SmartWares)

### CODE REVIEW

**Comment by tomsongurbo** [comment]
Build is failing due to the changes in the OpenZwave. I am not expert enough to look into this.

**Comment by petergebruers** [comment]
I've noticed it too (I am an OZW contributor) and I cannot explain why the CI system fails that build, I tried locally with same compiler and commit and it worked. I've commented on it here:

https://github.com/domoticz/domoticz/pull/3341#issuecomment-504724027

**Comment by gizmocuz** [comment]
You have to add support for this on more locations....
I will make the needed changes and will commit this directly info the repo

**Comment by gizmocuz** [comment]
Done..

**Comment by tomsongurbo** [comment]
@gizmocus: thanks a lot. I did not want to put another lame "can you please support X" question on the Domoticz forum and (try) to contribute myself.  That was not completely successful and you fixed it in the end. Thx.

I'll test the beta somewhere in the following weeks to check if all works out as expected.

**Pull request closed without merging**
