### PR TITLE
Fix for Buienradar Rain sensor

### PR DESCRIPTION
**Pull request by akamming**
fix for issue #3598  (and possibly #3625 and #3613)

### CODE REVIEW

**Comment by gizmocuz** [comment]
@akamming , thank you for the PR, looking good !
Just to check what has changed, you removed all extra checks and instead of SendRainSensorWU you are now issuing SendRainRateSensor ?

One small favor to ask could you rewrite the last part as

	if (!root["precipitationmm"].empty())
	{
		float precipitation = root["precipitationmm"].asFloat();
                SendRainRateSensor(1, 255, precipitation,  "Rain");
	}

Then it's like the other sensors

**Comment by akamming** [comment]
> @akamming , thank you for the PR, looking good !
> Just to check what has changed, you removed all extra checks and instead of SendRainSensorWU you are now issuing SendRainRateSensor ?
> One small favor to ask could you rewrite the last part as
> if (!root["precipitationmm"].empty())
> {
> 	float precipitation = root["precipitationmm"].asFloat();
>             SendRainRateSensor(1, 255, precipitation,  "Rain");
> }
> 
> Then it's like the other sensors

Ok will do that tomorrow

**Comment by akamming** [comment]
> Just to check what has changed, you removed all extra checks and instead of SendRainSensorWU you are now issuing SendRainRateSensor ?

Correct

**Comment by akamming** [comment]
> @akamming , thank you for the PR, looking good !
> Just to check what has changed, you removed all extra checks and instead of SendRainSensorWU you are now issuing SendRainRateSensor ?
> One small favor to ask could you rewrite the last part as
> if (!root["precipitationmm"].empty())
> {
> 	float precipitation = root["precipitationmm"].asFloat();
>             SendRainRateSensor(1, 255, precipitation,  "Rain");
> }
> 
> Then it's like the other sensors

Done

**Comment by gizmocuz** [comment]
Thanks !!!

**Comment by rwaaren** [comment]
Many thanks for the PR !

Just one remark. Not very important but much obliged if you would want to consider.

The number of digits behind the decimal point gives the idea that the measurement / prediction is very accurate. Wouldn't it be sufficient to have only 1 digit behind the decimal point for Rain Intensity, Next Rainshower Avg Rainrate and Next Rainshower Max Rainrate ?

Buienradar

**Comment by gizmocuz** [comment]
@rwaaren , done in commit 
https://github.com/domoticz/domoticz/commit/a4bb7f284c75fa7c2e13313d2f2a178516cbe36f

**Pull request merged**
