### PR TITLE
[Events] small optimizing

### PR DESCRIPTION
**Pull request by szczukot**
Pls check this small optimizing for event:
1) values for devices read only when structure etc changed
2) read value only for one device (not for all) when is changed

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
I have reverted this patch for the moment to test if the eventsystem will work again as before.
There seems to be issues with values not updating, i also experience this.
Will report back here...

**Comment by szczukot** [comment]
Ok
Pls give me more info about this problem (post on forum or etc)

**Comment by gizmocuz** [comment]
There are multiple on the board...
Also here it stopped working since i upgraded to this version this morning.
I have a weather underground upload script
this is fired every minute, but run every 5 minutes

All devices are working, i receive then very frequently, but for example every excecution results in an error that the other_devices is compared against null

```
   **WU_URL = WU_URL .. "&tempf=" .. string.format("%3.1f", CelciusToFarenheit(otherdevices_temperature[Outside_Temp_Hum]))**
```

I now reverted, and we are up and running again

The sensors are not used in any other blockly/lua script, only in this time script, could that have anything todo with it ?

Here is the script (you need to replace the device names, and WU API settings (station name/pwd))

> -- Weatherunderground PWS upload script
> -- (C)2013-2015 GizMoCuz
> 
> commandArray = {}
> 
> -- Current date as date.year, date.month, date.day, date.hour, date.min, date.sec
> date = os.date("*t")
> if (date.min % 5 == 0) then
>   Outside_Temp_Hum = 'Buiten'
>   Barometer = 'MySensors KRob'
>   RainMeter = 'NRain'
>   WindMeter = 'Wind'
>         UVMeter = ''
> 
>   --WU Settings
>   baseurl = "http://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?"
>   ID = "INXXXXX"
>   PASSWORD = "mypassword"
>   Interval = 55
> 
>   local function CelciusToFarenheit(C)
>      return (C \* (9/5)) + 32
>   end 
> 
>   local function hPatoInches(hpa)
>      return hpa \* 0.0295301
>   end
> 
>   local function mmtoInches(mm)
>      return mm \* 0.039370
>   end
> 
>   utc_dtime = os.date("!%m-%d-%y %H:%M:%S",os.time())
> 
>   month = string.sub(utc_dtime, 1, 2)
>   day = string.sub(utc_dtime, 4, 5)
>   year = "20" .. string.sub(utc_dtime, 7, 8)
>   hour = string.sub(utc_dtime, 10, 11)
>   minutes = string.sub(utc_dtime, 13, 14)
>   seconds = string.sub(utc_dtime, 16, 17) 
> 
>   timestring = year .. "-" .. month .. "-" .. day .. "+" .. hour .. "%3A" .. minutes .. "%3A" .. seconds
> 
>   SoftwareType="Domoticz"
> 
>   WU_URL= baseurl .. "ID=" .. ID .. "&PASSWORD=" .. PASSWORD .. "&dateutc=" .. timestring
> 
>   if Outside_Temp_Hum ~= '' then
>      WU_URL = WU_URL .. "&tempf=" .. string.format("%3.1f", CelciusToFarenheit(otherdevices_temperature[Outside_Temp_Hum]))
>      WU_URL = WU_URL .. "&humidity=" .. otherdevices_humidity[Outside_Temp_Hum]
>      WU_URL = WU_URL .. "&dewptf=" .. string.format("%3.1f", CelciusToFarenheit(otherdevices_dewpoint[Outside_Temp_Hum]))
>   end
> 
>   if Barometer ~= '' then
>      WU_URL = WU_URL .. "&baromin=" .. string.format("%2.2f", hPatoInches(otherdevices_barometer[Barometer]))
>   end
> 
>   if RainMeter ~= '' then
>      WU_URL = WU_URL .. "&dailyrainin=" .. string.format("%2.2f", mmtoInches(otherdevices_rain[RainMeter]))
>      WU_URL = WU_URL .. "&rainin=" .. string.format("%2.2f", mmtoInches(otherdevices_rain_lasthour[RainMeter]))
>   end
> 
>   if WindMeter ~= '' then
>      WU_URL = WU_URL .. "&winddir=" .. string.format("%.0f", otherdevices_winddir[WindMeter])
>      WU_URL = WU_URL .. "&windspeedmph=" .. string.format("%.0f", (otherdevices_windspeed[WindMeter]/0.1)_0.223693629205)
>      WU_URL = WU_URL .. "&windgustmph=" .. string.format("%.0f", (otherdevices_windgust[WindMeter]/0.1)_0.223693629205)
>   end
> 
>   if UVMeter ~= '' then
>      WU_URL = WU_URL .. "&UV=" .. string.format("%.1f", otherdevices_uv[UVMeter])
>   end
> 
>   --&weather=
>   --&clouds=
> 
>   WU_URL = WU_URL .. "&softwaretype=" .. SoftwareType .. "&action=updateraw"
> 
>   --print (WU_URL)
> 
>   --remove the line below to actualy upload it
>   commandArray['OpenURL']=WU_URL
> end
> return commandArray

**Pull request merged**
