### PR TITLE
#4277 Kwh filter for ZWave devices

### PR DESCRIPTION
**Pull request by RDols**
PR addresses the folowing issues:
- General filter for KWh devices.
- Fixed a startup glitch with scaleMultiply
- Specific filter for the new Neo coolcam plugs.

### CODE REVIEW

**Comment by gizmocuz** [comment]
I think the only check needs to be in 'SendKwhMeter' if the power reported is above the threashold (4000) then we skip this value
If your 'new' neocoolcam always report 3 times to high, you better throw it out!

**Comment by RDols** [comment]
I agree on the neocam specific filters. These plugs have multiple showstopper bugs, including full hang-ups, and spontaneously output switches. I personally already have these put them in my square permanent archive.

But faulty usage reports are not only at NeoCam plugs. These are also present on the Fibaro plugs, fibaro double relais and on Aeon nano. Looking in the data table of domoticz i see all power reporting devices having faulty values. I traced back faulty values in domoticz and openzwave, but it's already in the serialport report. I even have seen values from a different plug inside other reports. I suspect the Aeon zwave stick has some bugs.

I suggest also keep the usage filtering in.

**Comment by gizmocuz** [comment]
@RDols , Is it OK for you if I have a go with a Fix ? I would like to make the Max. Power a configuration option as well
I think the counter values are also sometimes wrong

**Comment by RDols** [comment]
@gizmocuz Yes that's ok with me.

**Comment by gizmocuz** [comment]
I made a new commit, where you can now specify the maximum power in the settings:

image

For most households this will be ~3600, so 4000 should be OK, but I have to see a appliance that can measure above 3600 Watt yes.
New beta's are building and should be available within the hour

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/commit/f79cf66245cc27de722cf81cbe49481e0ee14490

https://github.com/domoticz/domoticz/commit/bee66dffacf7690a425cc37d93bcf69dc6930de9

**Comment by gizmocuz** [comment]
@RDols , Did you found some time to test the new version ? Is it working and can we close this issue ?

**Comment by RDols** [comment]
@gizmocuz I'm currently start trying this out. Takes a one or two days to have results.

**Comment by RDols** [comment]
The new beta crashes at startup in a plugin. I didn't update my beta for a while now. I will take a detailed look later today.

**Comment by gizmocuz** [comment]
@RDols , did you manage to have a look if this issue is solved?

**Pull request closed without merging**
