### PR TITLE
Generic sysfs gpio, new

### PR DESCRIPTION
**Pull request by hvbommel**
Generic sysfs gpio for Linux makes exported GPIO inputs and outputs available for use. Before adding the hardware within domoticz you need to export the GPIO's that you are going to use. By doing this you specify the direction of the GPIO, in or out, whether pull-ups or pull-downs are turned on etc. Then when this "Generic sysfs gpio" hardware is added it will detect the exported GPIOs and creates devices for it. After that you can fine tune the inputs and outputs for specific purposes like door-contacts etc. as always. Sysfs does not depend on any external libraries like wiringpi.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Wow, Great !! Thanks!
Have to wait a little to merge because i'm having issues with getting the openzwave dev branch to work.
I think i know where it crashes but needs some time

**Comment by gizmocuz** [comment]
Thanks!!! Hope some users also want to test this.. then we can remove the wiringpi stuff

**Comment by LKapie** [comment]
I tested this new hardware (on Raspi with version 3.7365) and it works ok for me with one PIR sensor on GPIO.
Only issue I found was that old and new GPIO seem to have a minor problem to coexist: 
When I switch the old GPIO (Raspberry's GPIO port) to OFF and after that to ON again Domoticz freezes and a restart is needed. (did not try this before so I can also be an issue of the "Raspberry's GPIO port" hardware/driver) After restart the old and new hardware seem to function/coexist properly. It think this is not a likely use-case though so for me it's ok.

**Comment by gizmocuz** [comment]
Well that makes sense as you probably can access a GPIO only once...
Great it works!
But when you disable the old GPIO and use the sysFS version, you can correctly switch On/Off the GPIO ?

**Comment by LKapie** [comment]
Just checked it and switching On/Off "Generic sysfs gpio" works correctly at my system.

**Comment by hvbommel** [comment]
Thanks for testing !

Can you also test the following:
1. Remove wiringpi (delete or rename the libraries, to _libwiringpi.a and _libwiringpi.so in /usr/lib and or /usr/local/lib) 2. Rebuild domoticz, now it will be build without “wiringpi” GPIO. 3. In hardware “Generic sysfs gpio” will still be present in the list but “Raspberry’s GPIO PORT” should be gone. 4. Then test “Generic sysfs gpio”.

Note:
Use raspi-gpio (instead of wiringpi gpio command) to configure inputs/outputs and pullups/downs etc. It will be the same way as you would have done, using the gpio commands, but slightly different syntax. If you don’t have it installed then install it using: 1. sudo apt-get install raspi-gpio 2. for help on usage type: “raspi-gpio help”

That should work. In that case your is system is no longer relying on wiringpi and its tools.

But also …
I also saw what you did see, problems during rundown of the “Raspberry’s GPIO PORT”. I don’t think it is failing because of a combination conflict (although a combination will never be supported, it either one or the other). I think Raspberry’s GPIO PORT” is failing on its own when we deselect “enabled” and then click on “update”. I did see it happen but did not debug it so far. I will debug it asap so that we exactly know whats going on and get back here with the results (and maybe with a fix for the old GPIO)

**Comment by hvbommel** [comment]
Question: Should we do a wiki page for "Generic sysfs gpio" similar to the "Raspberry GPIO port" one ? If yes, who would do it normally ? Or is it too early ?

**Comment by hvbommel** [comment]
I have entered a pull request to attempt to fix the "Rasberry's GPIO port" hang issue as described earlier by LenardKaptein in the blog. Note: The problem and fix are not related to the new "Generic sysfs gpio" hardware.

**Comment by LKapie** [comment]
Dear @hvbommel I have a very busy week this week and will be abroad from tomorrow until sunday so I'm sorry to tell I cannot find the time soon to do the tests you suggested...

**Comment by jvandenbroek** [comment]
I really like the idea of not using the wiringPi library and the code seems to be well written. But one thing I prefer about the wiringPi implementation, is that it spawns a thread per pin which uses the Linux poll function to efficiently wait for I/O to happen (this uses zero cpu time and reacts instantly). Maybe we can 'lend' some of it's code to make it independent? I think that's quite feasible.

**Comment by hvbommel** [comment]
I have also looked into implementing a edge based version. The reason I implemented the poller: 1. Its still light weight 2. quiet responsive (250 msec) 3. No interrupt storms. 4. No thread & I/O cancelation complexity on rundown. 5. Robust & simple. But indeed I also did a edge based version with a thread per I/O pin. It works. But for a start I thought; lets keep it simple. And if the max response time of 250 msec happens to be a problem in some use cases then an interrupt based extension can easily be added later on (it more of the same). Question: Are you in your case having a problem with the 250 msec input response time ?  I think for the time being we should keep both "sysfs gpio" and "wiringpi gpio" in the system so the user has the choice. Thanks for your feedback.

**Comment by jvandenbroek** [comment]
Well I agree that max +-250ms delay would be fine probably in most cases, but I'd suggest to make this configurable. It indeed has a negligible impact on performance, but running on a RPi 1 hosting multiple services, I'm always looking for ways to optimize things as much as possible. However I'd like to see how this runs with a configurable interval, so I can play with it's settings and monitor the real CPU time used. It might even be a better choice for me memory wise :) (not sure about how much overhead separate threads have, but sure there is some)

**Comment by hvbommel** [comment]
I hear what you say but when we make it configurable people need guidelines to determine the best settings. My vote would be to leave it as is for some time, 3 months or so, and see how it works. It think simple is better, if it does the job. You can always tweek the (3 related) definitions in top of the .cpp file and build a version you are interested in. When we find out fixed values are no good that is a good reason to put in (documented) flexibility. I know it sounds a bit hard minded but believe it or not ... I like the feedback so that we can improve where there is room/need for it. Thanks.

**Comment by gizmocuz** [comment]
I agree, keep it simple...

**Pull request merged**
