### PR TITLE
Extend for sTypeAlert type

### PR DESCRIPTION
**Pull request by szczukot**
Hi again

What do you think about this extension for sTypeAlert ?
I use sDecodeRXMessage instead UpdateValue method

Fantom

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks, looking good ;)

**Comment by szczukot** [comment]
Hi. I have problem - I think with this change.
But when i running domoticz from server (check updates etc) Satel Integra not working :(
Method sDevodeRXMessage was not called or not woking inside. I calling  ReportZoneViolation, but nothing changes, and "last seen" equal a few days ago.

When i compiling (the newest) code on Ubuntu or Rapsberry PI is working ok.

What is wrong ?

**Comment by gizmocuz** [comment]
Hi,

You made the patch, i can not debug this.

Could you try to debug this?

**Comment by szczukot** [comment]
but how to do this debugging ? 
I downloaded the latest sources, compiled both on Linux and in Raspberry PI and its working properly on both platform. But package from "auto update" is not working -value is not updated :(

How enabled DEBUG LOG on package from "auto update" ? I set verbose = 1 but i dont ssee too many logs.

Maybe i create patch for git with many debug logs ? 

Fantom

**Comment by gizmocuz** [comment]
maybe this patch was not yet available in the automatic beta update ?
if you go to the about page, you see the build hash number, you can then see in the commit log on github if this patch was included

**Comment by szczukot** [comment]
I have version with hash bdf47b0 - 22 sep 2015. My patch is exists in this version.
I will create new patch with more logs today.

Fantom

**Comment by gizmocuz** [comment]
just made another beta

**Pull request merged**
