### PR TITLE
correct repeated datetime in log

### PR DESCRIPTION
**Pull request by gordonb3**

### CODE REVIEW

**Comment by gizmocuz** [comment]
I think a comment has been lost i did before... 

I added this date/time always because otherwise when you enabled syslog, there was no date-time in the log file (outputfile)
The date-time was already in the domoticz web log because of a previous patch

or i must be overseeing something here

**Comment by gordonb3** [comment]
Look at line #130

szDate is already prepended to the message. In line #172 before patch it is prepended a second time, causing the repeated datetime on most lines (I have some Weather Underground log lines that do come out right)

Funny thing though: I just looked in the actual on disk log and this is correct. The repeated datetime entry thus only seems to occur in Setup->Log

**Comment by gizmocuz** [comment]
You're right... i have to remake this... getting to much if/then/else
First create the message (without date/time)
If syslog is enable, add a syslog message
Next add the date/time, and process like we always did before all these changes

**Comment by gordonb3** [comment]
Don't know the history of it. From the looks everything somehow seemed to have a purpose, so I did not want to touch that. It's just the unconditional adding of the datetime value after there had already been a conditional adding of the datetime that is wrong.

**Comment by gizmocuz** [comment]
Thanks!
Is it still a problem ? Made a recent commit that should solve it now

**Comment by gordonb3** [comment]
Doesn't seem to do the trick

>  2017-06-05 17:15:29.955 2017-06-05 17:15:29.955 Domoticz V3.7675 (c)2012-2017 GizMoCuz
2017-06-05 17:15:29.955 2017-06-05 17:15:29.955 Build Hash: d380668, Date: 2017-06-05 09:20:48
2017-06-05 17:15:29.955 2017-06-05 17:15:29.955 Startup Path: /opt/domoticz/
2017-06-05 17:15:30.078 2017-06-05 17:15:30.078 Sunrise: 05:26:00 SunSet:21:56:00
2017-06-05 17:15:30.078 2017-06-05 17:15:30.078 EventSystem: reset all events...
2017-06-05 17:15:32.528 2017-06-05 17:15:32.528 PluginSystem: Started, Python version '3.4.5'.
2017-06-05 17:15:32.549 2017-06-05 17:15:32.549 Active notification Subsystems: email (1/12)
2017-06-05 17:15:32.553 2017-06-05 17:15:32.553 WebServer(HTTP) started on address: 0.0.0.0 with port 10080
2017-06-05 17:15:32.554 2017-06-05 17:15:32.554 Proxymanager started.
2017-06-05 17:15:32.556 2017-06-05 17:15:32.556 Camera: settings (re)loaded
2017-06-05 17:15:32.558 2017-06-05 17:15:32.558 Starting shared server on: 0.0.0.0:6144
2017-06-05 17:15:32.563 2017-06-05 17:15:32.563 TCPServer: shared server started...
2017-06-05 17:15:32.563 2017-06-05 17:15:32.563 RxQueue: queue worker started...
2017-06-05 17:15:34.566 2017-06-05 17:15:34.566 EventSystem: reset all events...
2017-06-05 17:15:34.567 2017-06-05 17:15:34.567 EventSystem: reset all device statuses...
2017-06-05 17:15:34.570 2017-06-05 17:15:34.570 Hardware Monitor: Started
2017-06-05 17:15:34.679 2017-06-05 17:15:34.679 (Evohome) Worker started...
2017-06-05 17:15:34.679 2017-06-05 17:15:34.679 Wunderground: Worker started...
2017-06-05 17:15:34.679 2017-06-05 17:15:34.679 PluginSystem: Entering work loop.
2017-06-05 17:15:34.832 2017-06-05 17:15:34.832 Python EventSystem: Module not found - Trying to initialize.
2017-06-05 17:15:34.833 2017-06-05 17:15:34.833 Python EventSystem: Initalizing event module.
2017-06-05 17:15:34.834 2017-06-05 17:15:34.834 EventSystem: Started
2017-06-05 17:15:35.574 2017-06-05 17:15:35.574 RFXCOM: Using serial port: /dev/ttyUSB433
 2017-06-05 17:15:37.680 2017-06-05 17:15:37.680 Hardware Monitor: Fetching data (System sensors)
2017-06-05 17:15:41.995 2017-06-05 17:15:41.995 Incoming connection from: 127.0.0.1
2017-06-05 17:15:43.232 2017-06-05 17:15:43.232 P1 Smart Meter: Meter reports as DSMR 4.2
2017-06-05 17:15:43.233 (P1 Wifi Gateway) P1 Smart Meter (Elektriciteit)
2017-06-05 17:15:44.681 2017-06-05 17:15:44.681 (Evohome) connect to Evohome server
2017-06-05 17:15:44.995 (Weather) Temp + Humidity + Baro (Temp extern)
2017-06-05 17:15:45.003 (Weather) Wind (Wind extern)
2017-06-05 17:15:45.006 (Weather) UV (UV index)
2017-06-05 17:15:45.008 (Weather) Rain (Regen centrum)
2017-06-05 17:15:45.043 (Weather) General/Visibility ()
2017-06-05 17:15:47.827 2017-06-05 17:15:47.827 (Evohome) fetch data from server
2017-06-05 17:15:53.253 (P1 Wifi Gateway) P1 Smart Meter (Elektriciteit)

**Comment by gizmocuz** [comment]
Are you using a syslog?

**Comment by gordonb3** [comment]
No. Normal logging, just redirected to /var/log/

**Comment by gordonb3** [comment]
Might want to note that the messages generated by ProcessRXMessage are the only ones that do have correct (single) datetime.

**Comment by gizmocuz** [comment]
Okey, now its correct (new commit)

**Pull request closed without merging**
