### PR TITLE
Spelling correction: "childs" -> "children"

### PR DESCRIPTION
**Pull request by mbardea**
... on "hardware" page.

### CODE REVIEW

**Comment by gizmocuz** [comment]
i think both can be used ? Specially when talking about node's and child id's

**Comment by EddyK69** [comment]
I agree with @gizmocuz

**Comment by mbardea** [comment]
The change was for actual words which seem to show on a web page. "Childs" is broken English.

If the change does not affect the web page directly, please ignore.

**Comment by gizmocuz** [comment]
The (big) problem is, it needs to be changed in the web page, we need to add a new translation word, every translator has to translate this word, then we need to build a new version, and then its visible at the end user

**Pull request closed without merging**
