### PR TITLE
Fix web interface slider and send correct level to Domoticz

### PR DESCRIPTION
**Pull request by arjanwaard**
Fixes issue https://github.com/domoticz/domoticz/issues/513

### CODE REVIEW

**Comment by arjanwaard** [comment]
https://github.com/arjanwaard/domoticz/commit/4072ce7a7fe636c4b3ab092721d0edffeef11b08 adds event triggering for Hue Bridge changes from outside Domoticz. See issue https://github.com/domoticz/domoticz/issues/443

**Comment by gizmocuz** [comment]
Please keep different changes in different pull requests (maybe branching)

**Comment by arjanwaard** [comment]
Pull request now only consist of the web interface slider change.

**Comment by gizmocuz** [comment]
thanks, i have to triple check it... it will be one of the latest pulls that will be accepted before the new stable release

**Comment by gizmocuz** [comment]
Thanks!

**Comment by arjanwaard** [comment]
Just tested with a fresh compile from domoticz master, a Hue White dimmer, Hue RGBW dimmer and dummy dimmer all work as expected.

**Comment by gizmocuz** [comment]
Also just tested on an existing system, dummy switch (0-100%) and manual AC switch, all seem to work!

**Comment by arjanwaard** [comment]
@gizmocuz, could you fix the off by 1 in domoticz.js.gz ? In the function ShowRGBWPopupInt change $(this).slider("option", "max", $(this).data('maxlevel'));
to
$(this).slider("option", "max", $(this).data('maxlevel')+1);

**Comment by gizmocuz** [comment]
Done

**Comment by arjanwaard** [comment]
Thanks, RGB(W) switches now also work correctly.

**Pull request merged**
