### PR TITLE
Updated Mosquitto to version 1.5

### PR DESCRIPTION
**Pull request by jvandenbroek**
Should test this first, but seems to work fine on my test setup with a remote MQTT host configured. This will remove deprecated warnings when compiling on ARM based systems (gcc 6.3)

### CODE REVIEW

**Comment by sweetpants** [comment]
This should be tested very well. As I recall an earlier attempt by GizMoCuz which resulted in a revert to the previous version. I will be glad to help out on my test setup. My Setup is strongly depending on a good MQTT implementation.

**Comment by jvandenbroek** [comment]
Yes, that's what I said ;) Please help testing, thanks :)
Edit: meanwhile I see that the Windows build is struggling..

**Comment by sweetpants** [comment]
I'm subscribed to this topic, so when it is commited, i will check it out and test it. BTW, i'm on Linux (Ubuntu 16.04)

**Comment by jvandenbroek** [comment]
You can test it now, just need to make some changes to the project file for Win32..

**Comment by sweetpants** [comment]
Did some quick test using broker on the same system (127.0.0.1:1884) as domoticz and switching a dummy switch resulting in disconnects and re-connects to the broker.

2018-06-11 15:21:31.501  Status: MQTT: Connecting to 127.0.0.1:1884
2018-06-11 15:21:31.602  Status: MQTT: connected to: 127.0.0.1:1884
2018-06-11 15:21:31.702  Status: MQTT: Subscribed
2018-06-11 15:22:12.839  Status: EventSystem: reset all device statuses...
2018-06-11 15:23:03.806  Status: User: Admin initiated a switch command (1/MQTT_Switch/On)
2018-06-11 15:23:03.809  (Dummy Hardware) Light/Switch (MQTT_Switch)
2018-06-11 15:23:03.810  Error: MQTT: disconnected, restarting (rc=14)
2018-06-11 15:23:24.127  Status: MQTT: Connecting to 127.0.0.1:1884
2018-06-11 15:23:24.228  Status: MQTT: re-connected to: 127.0.0.1:1884
2018-06-11 15:23:24.328  Status: MQTT: Subscribed
2018-06-11 15:23:55.013  Status: User: Admin initiated a switch command (1/MQTT_Switch/Off)
2018-06-11 15:23:55.014  (Dummy Hardware) Light/Switch (MQTT_Switch)
2018-06-11 15:23:55.014  Error: MQTT: disconnected, restarting (rc=14)
2018-06-11 15:24:02.276  Status: User: Admin initiated a switch command (1/MQTT_Switch/On)
2018-06-11 15:24:02.277  (Dummy Hardware) Light/Switch (MQTT_Switch)
2018-06-11 15:24:22.040  Status: MQTT: Connecting to 127.0.0.1:1884
2018-06-11 15:24:22.141  Status: MQTT: re-connected to: 127.0.0.1:1884
2018-06-11 15:24:22.241  Status: MQTT: Subscribed
2018-06-11 15:24:57.225  Status: User: Admin initiated a switch command (1/MQTT_Switch/Off)
2018-06-11 15:24:57.226  (Dummy Hardware) Light/Switch (MQTT_Switch)
2018-06-11 15:25:01.386  Status: User: Admin initiated a switch command (1/MQTT_Switch/On)
2018-06-11 15:25:01.390  (Dummy Hardware) Light/Switch (MQTT_Switch)
2018-06-11 15:25:01.391  Error: MQTT: disconnected, restarting (rc=14)
2018-06-11 15:25:03.817  Status: User: Admin initiated a switch command (1/MQTT_Switch/Off)
2018-06-11 15:25:03.818  (Dummy Hardware) Light/Switch (MQTT_Switch)
2018-06-11 15:25:05.345  Status: User: Admin initiated a switch command (1/MQTT_Switch/On)
2018-06-11 15:25:05.346  (Dummy Hardware) Light/Switch (MQTT_Switch)

This used to work fine with the previous version of MQTT on the same machine
Mosquitto.log shows

1528723765: New connection from 127.0.0.1 on port 1884.
1528723765: New client connected from 127.0.0.1 as mosq/tNlAc`5gdrEEKUBBru (c1, k60, u'domoticz').
1528723774: Socket error on client mosq/tNlAc`5gdrEEKUBBru, disconnecting.
1528723803: New connection from 127.0.0.1 on port 1884.

**Comment by jvandenbroek** [comment]
Hmm bummer, thanks for testing! Then it's probably for a reason it's still on a version from 2014 then indeed ;) Finally fixed the Win32 build (AppVeyor disagrees, but it compiles fine locally), so was happy with the result so far... To be sure, you really don't have that behavior with the current (old) version?

**Comment by sweetpants** [comment]
Nope, previous version running on my production machine (also Ubuntu 16.04) runs fine without any errors in domotic.log or mosquitto.log.

**Comment by sweetpants** [comment]
I have to do some more testing. It seems limited when publishing to domoticz/out (flipping a dummy switch triggers this socket error). domoticz/in seems to work fine and domoticz is picking up the MQTT messages and updates devices.

**Comment by jvandenbroek** [comment]
Never mind, I've closed this one. It should be a drop-in replacement, otherwise too much hassle to make it work. Thanks.

**Pull request closed without merging**
