### PR TITLE
Fixed switching scenes/groups from Device-menu

### PR DESCRIPTION
**Pull request by EddyK69**

### CODE REVIEW

**Comment by EddyK69** [comment]
Patched to use the cached icons ;D

**Comment by gizmocuz** [comment]
Thanks! Looking good, only there seems to be a problem merging this request: "This branch has conflicts that must be resolved"

**Comment by EddyK69** [comment]
I'm pretty new to GitHub. Must find out how i can resolve these conflicts...

**Comment by gizmocuz** [comment]
so am i ;)

**Comment by EddyK69** [comment]
Sorry, i messed up. Closing this request

**Pull request closed without merging**
