### PR TITLE
Changing hardcoded colors

### PR DESCRIPTION
**Pull request by Michmis**
Changing item status colors from hardcoded to css classess. in dashboard Added classess for dashboard item types.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Sorry i can not see what you changed, because you also changed the formatting of other things
could you only change the relevant lines ?

**Comment by Michmis** [comment]
@gizmocuz sorry, thats my first commit ever, I will try to write it again, it seems that I deleted some spaces and it looks messy

**Comment by Michmis** [comment]
@gizmocuz  I tried to edit it again on my PC using GitHub desktop and Atom editor, but it still looks messy, there are blank lines shown as changed etc. I will describe my changes

There are items names in dashboard and for different item states it has different background color. For me hardcoding colors is wrong when there is possibility to use Domoticz themes. On the other hand there is no CSS class for item div to describe its state, so i wanted to change this parts:

`	var nbackcolor="#D4E1EE";
	if (item.HaveTimeout==true) {
		nbackcolor="#DF2D3A";
	}
	else if (item.Protected==true) {
		nbackcolor="#A4B1EE";
	}`

which affect td#name directly to:

`	var itemstatus="ok";
	if (item.HaveTimeout==true) {
		itemstatus="timeout";
	}
	else if (item.Protected==true) {
		itemstatus="protected;
	}`

and move it back before DIV of an item is created like:
`xhtm='\t<div class="span3 movable itemtype_temp itemstatus_' + itemstatus +'" id="temp_' + item.idx +'">\n';`

So whole DIV has now 2 new CSS classes, one for item type and one for item status, like .itemstatus_ok or itemstatus_timeout.

Then in style.css file we can make 
`div.itemstatus_timeout table tr td#name {background: #DF2D3A;}`

I am very sorry that I make it that messy, I believe that would be huge improvement for all theme designers.

**Comment by gizmocuz** [comment]
You are free to make a new pull request for the formatting ;)

**Comment by gizmocuz** [comment]
Try notepad2-mod as editor

**Comment by Michmis** [comment]
Thank you, I will try it tommorow and check formatting again

**Comment by gizmocuz** [comment]
Also note the colours are used in all tabs, not only the dashboard

**Comment by gizmocuz** [comment]
Is this still a work in progress ?

**Comment by gizmocuz** [comment]
Please open a new pull request when you have some updates

**Pull request closed without merging**
