### PR TITLE
About-background

### PR DESCRIPTION
**Pull request by ghost**
Better walpaper to background

### CODE REVIEW

**Comment by ghost** [comment]
Can you give reason why my PR was rejected ?

**Comment by gizmocuz** [comment]
Because, as we already discussed by email, this page is far from finished, it is now handy that it shows the branch number.
Also i am not going to change this background (as also discussed)

**Comment by PiterEL** [comment]
Ok but add translation with i add to other PR and add to Transifex. But what you plan change/add to this page ABOUT if it is not finished ?

But in brand h2 BUILD DATE is the same as in About page COMPILE DATE. Can we change in all site to BUILD DATE or COMPILE DATE ?Thi is the same info...with other name.

**Comment by gizmocuz** [comment]
it is in the beta, anything can be in there, and being worked on!

**Pull request closed without merging**
