### PR TITLE
Rtl433: add support for light_klx field (SendLuxSensor)

### PR DESCRIPTION
**Pull request by blmpl**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR! Is it possible to make it against the development branch (our active branch) and not against the master branch?

**Comment by blmpl** [comment]
sure, switched - sorry!

**Comment by gizmocuz** [comment]
Thank you ;) ... Is it possible to remove the change in main/SQLHelper.cpp ?

**Comment by blmpl** [comment]
mess sweet mess... maybe I will clone from development and start new pull request?
not sure how to revert second file and don't break anything else (it looks like there are more changes than visible on this diff :|)

**Comment by blmpl** [comment]
https://github.com/domoticz/domoticz/pull/4927 to stop confusion, sorry!

**Pull request closed without merging**
