### PR TITLE
VisualStudio build instruction update.

### PR DESCRIPTION
**Pull request by ajarzyn**
Small update of Visual Studio prep and building instruction.

What is most wonderful thing about this PR is this line:
`vcpkg install "@../vcpkg-packages.txt"`
and changes to `vcpkg-packages.txt`

no more you will need to open and copy the content of the file.

Here you can view updated content:
https://github.com/ajarzyn/domoticz/blob/dev_vs_configuration/build/README-visual-studio.md

Enjoy.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for your PR!!

Changes are perfect... but

Question, do you now install VCPKG underneath the Domoticz folder?

As a developer that is using VCPKG for other projects as well, as well as to build quick test projects before integrating some routines into a project, I think it is better to install VCPKG in the root of your sources harddisk (like S:\VCPKG)

**Comment by ajarzyn** [comment]
Hello @gizmocuz you are most welcome.

Domoticz is literally only one project I'm using VCPKG for, and I'm using it only because the instruction says so. (Till a moment ago I didn't event read what the heck is this).
But from the other hand I do not develop c++ under windows most of the time.

For developers (who like I) goes through the process only to debug, and maybe create small PR I believe it's 'a ok' to keep the VCPKG inside the Domoticz directory. I was worried if placing it into `msbuild` directory will mark the files to add by git, but fortunately `msbuild` is added to `.gitignore`.
Pros: As you clear the project later, you remove all the dependencies within one directory.

And if you are mature developer as yourself who have been using VCPKG for many project, you do not need instruction for that, or at least you know what/how you want to modify the instruction to feet your workflow.
I expect you to have `vcpkg.exe` added to system paths anyways, so you can freely use it from whatever directory you want.

**Comment by ajarzyn** [comment]
Sorry for the mess in commits... I did not wanted that MQTT fix to go with this PR so all that reverted now.

**Comment by gizmocuz** [comment]
Okey, that's true.
I don't think you need to use vcpkg if you use the win32 library zip file correct?

https://github.com/domoticz/win32-libraries

**Comment by ajarzyn** [comment]
> Okey, that's true. I don't think you need to use vcpkg if you use the win32 library zip file correct?

I do not think that's true in `win32-libraries` there are only
```
...\domoticz\msbuild\Windows Libraries\openzwave\
...\domoticz\msbuild\Windows Libraries\Redist\
```

but vcpkg delivers:
`boost cereal curl jsoncpp lua minizip mosquitto openssl pthreads sqlite3 zlib`

So I do think that it's still needed.

**Comment by gizmocuz** [comment]
Not in my version.... it contains all needed includes/libraries

**Comment by ajarzyn** [comment]
You are correct. It contains all the libraries:
```
WindowsLibraries.7z\Windows Libraries\include\
WindowsLibraries.7z\Windows Libraries\lib\
WindowsLibraries.7z\Windows Libraries\openzwave\
WindowsLibraries.7z\Windows Libraries\Redist\
```
in `include` and `lib` directories.

But again then there's this line in the guide:
```
- For building in debug mode: remove the `Windows Libraries/include` and `Windows Libraries/lib` folder.
```

Now I do not know if that's still the case. I've just followed this instruction.

**Comment by gizmocuz** [comment]
Only when using VCPKG, but you should be fine by checking out the code, downloading the win32 library zip file, unpacking it.
No need to use VCPKG, but for systems using VCPKG these are the libraries you need
I would not install VCPKG in the domoticz source folder but on a fixed location on a HDD

**Comment by ajarzyn** [comment]
I've made additional changes, please check if that satisfies you.

But if there's a vision that you have on your mind please write plainly how you imagine this readme, then I will (hopefully) will be able to follow that vision.

**Comment by gizmocuz** [comment]
Thank you for the changes... some small comments

Requirements:
- Visual Studio 2019 or higher (2022 recommended) (Community Edition is perfect and is free)

Optional: VCPKG Configuration

When using VCPKG remove following directories from msbuild/Windows Libraries/:

msbuild/Windows Libraries/include
msbuild/Windows Libraries/lib

To install all required ports, you can execute the following line inside your VCPKG folder:

Set target environment and install all modules from ../vcpkg-packages.txt
set VCPKG_DEFAULT_TRIPLET=x86-windows && vcpkg install "@../vcpkg-packages.txt"

* I would not include the steps to install or build or integrate VCPKG, if people need to do so, they where not using VCPKG and should probably stick to the zip file download

* Optional: Python support, I can't remember I ever had to set a additional library path. Sure this is needed?

**Comment by ajarzyn** [comment]
Applied your comments. But now it looks small and not important.
I feel that vcpkg info would be nice addition as this guide is here to help.

But it's your decision. Migrate if you like it and we close this PR.

**Comment by gizmocuz** [comment]
Yes, but now you removed the VCPKG part, and you included a patch for MQTT-AD in this PR

**Comment by ajarzyn** [comment]
Have I mentioned that I do not like git plugin for Visual Studio? It's the second time when it did not what I wanted it to do and thus created a mess...

Fixed it together with history. Hope it ok now.

**Comment by gizmocuz** [comment]
@ajarzyn , no not yet, but I totally agree with you here!
I use 'TortuiseGit Toolbar' from the below marketplace

https://marketplace.visualstudio.com/items?itemName=mdaviesnet.TortoiseGitToolbar

**Comment by gizmocuz** [comment]
Thanks looking good, the only thing I miss now is the explanation from me above (or here below) for people that are using 

> Optional: VCPKG Configuration
> 
> When using VCPKG remove following directories from msbuild/Windows Libraries/:
> 
> msbuild/Windows Libraries/include
> msbuild/Windows Libraries/lib
> 
> To install all required ports, you can execute the following line inside your VCPKG folder:
> 
> Set target environment and install all modules from ../vcpkg-packages.txt
> set VCPKG_DEFAULT_TRIPLET=x86-windows && vcpkg install "@../vcpkg-packages.txt"

**Comment by ajarzyn** [comment]
So you want to have vcpkg configuration guide but no installation, got it.
Fixed, plus crucial change to `vcpkg-packages.txt` which was lost in all that confusing mess.

**Comment by gizmocuz** [comment]
Thank you very much!!

**Pull request merged**
