### PR TITLE
Fix critical security issue and design issue #142

### PR DESCRIPTION
**Pull request by gaudryc**
First step : add request argument to all commands, rtypes and actions.
It keeps working, it just change methods signature.

### CODE REVIEW

**Comment by gaudryc** [comment]
I got to :
- rename m_sessionids to m_sessions ;
- move myNameValues to request ;
- move m_outputfilename to session ;
  ...

**Comment by gaudryc** [comment]
Job is done. I'm waiting for your validation.

**Comment by gizmocuz** [comment]
Thanks for the hard work and great patch! only thing i have seen where some strange characters (0x replaced by 0�
fill commit this here after

**Comment by gaudryc** [comment]
What is the file concerned ?
I commit it from OSX.

**Comment by gizmocuz** [comment]
Limited led. Cpp

**Pull request merged**
