### PR TITLE
Reduce or set a custom value as log interval for graph

### PR DESCRIPTION
**Pull request by pizzulicchio**
Hi,
for some devices or for general purpose, could be useful to set a custom ( per device or global ) value for log interval, so we can have higher resolution on the graphs/data logged.
Under "Setup"-->"Settings"-->"Log History" could be a good place for insert a global value.
Otherwise into every device at new creation.
We have talked into the forum at this link : https://www.domoticz.com/forum/viewtopic.php?f=47&t=10183
That's all.
Thank you

### CODE REVIEW

**Comment by rwaaren** [comment]
This is not how the process works. It could break domoticz in little pieces. 😀

Please first try to understand how a PR must be made  for domoticz

- create a fork of the domoticz github  
- clone your fork to local 
- develop and test  local
- commit- and push changes to fork
- create a PR from your fork to development branch of domoticz
- request a review from one / more of the members

**Comment by gizmocuz** [comment]
Next to this, it is already possible when you tweak a database value, BUT NOT recommended !

IF you want to have a high interval, please consider using InfluxDB in combination with Grafana
(Domoticz has build in support to push to InfluxDB)

**Comment by pizzulicchio** [comment]
i respect your response, gizmocuz, and i'm sorry, rwaaren, for not having done in the correct way a new feature request... but for a small installation i think that this feature could be implemented without a deep impact. Or a banal warning when you set a poller interval under 5 minutes...
if possible, is it avaiable an "how to" for tweaking the DB? 
Currently i have modified the html code of setup.html.

**Comment by gizmocuz** [comment]
Try exporting your database from the settings page, open this in (for example) "SQLite Exprert Personal Edition" , go to the preferences table

**Comment by 4cc3ssD3ni3d** [comment]
> Otherwise into every device at new creation.
[...]
> but for a small installation i think that this feature could be implemented without a deep impact. Or a banal warning when you set a poller interval under 5 minutes...

I share this point of view :)
This could be interesting for some devices, and for others less: therefore, it would be appropriate to have, for each device, properties allowing to define the frequency of data refresh ...

**Comment by gizmocuz** [comment]
@4cc3ssD3ni3d , You are replying to a very old topic. Have you read the two solution above (InfluxDB and having a look at the values of the preferences table)

**Pull request closed without merging**
