### PR TITLE
Fixed rain device for DarkSky

### PR DESCRIPTION
**Pull request by Olifant1990**
Fixed rain device for DarkSky.
DarkSky only sends a rate/hour. So you have to build a total yourself.

See https://github.com/domoticz/domoticz/issues/3109

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the patch !!
Could you make a SendRainRateSensor function ? (Instead of doing it directly in the DarkSky class)
This way we might be able to use it in other feature hardware classes that need the same type of rain calculation

**Comment by Olifant1990** [comment]
The calculations are done in mainworker.cpp ;)
So not depending on Darksky already, right?

**Comment by gizmocuz** [comment]
Yes, but the object creation is done in DarkSky, that should be moved to DomoticzHardware.cpp/h

RBUF tsen;
memset(&tsen,0,sizeof(RBUF));
...

**Comment by gizmocuz** [comment]
Thanks!!

**Comment by Olifant1990** [comment]
You were fast, just committed it xD

**Pull request merged**
