### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python, they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python, a __NameError__ is raised which will halt/crash the script on the user.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for your PR and time!

Question, could you modify your workflow to only trigger when files in the plugins folder are changed ?

https://stackoverflow.com/questions/63822219/how-to-run-github-action-only-if-the-pushed-files-are-in-a-specific-folder

**Comment by cclauss** [comment]
Python files exist in /main, /scripts, and /plugins.  Linting jobs are not long running
This job will take ~a minute or at the most two~ 3 seconds while the main job takes almost 30 minutes.

My approach here is a bit cumbersome for plug-in developers.  Perhaps a syntax like
```python
from Domoticz import Connections, Devices, Images, Parameters, Settings
```
would be less invasive and easier for Python plug-in developers to reason about.

**Comment by gizmocuz** [comment]
True, but there is no need to check the main folder ... also the python files do not change much
This github actions check would be great if all plugins where stored in the repository
For now, when you look at the dates of the files (2018) I don't think we need this action to be run all the time, it takes a lot of time and will check files that are already checked.
Your changes to the python files (because you checked them with lint) would be great to have in a PR

**Comment by cclauss** [comment]
The flake8 test runs in 3 seconds in the `pull_request_check.yml` job.

**Comment by cclauss** [comment]
Based on https://www.domoticz.com/wiki/Developing_a_Python_plugin, should `Connections` also be added?

**Comment by pipiche38** [comment]
> Python files exist in /main, /scripts, and /plugins. Linting jobs are not long running
> This job will take ~a minute or at the most two~ 3 seconds while the main job takes almost 30 minutes.
> 
> My approach here is a bit cumbersome for plug-in developers. Perhaps a syntax like
> 
> ```python
> from Domoticz import Devices, Images, Parameters, Settings
> ```
> 
> would be less invasive and easier for Python plug-in developers to reason about.

But is that working with the Python Framework ?

**Comment by cclauss** [comment]
> is that working with the Python Framework ?

Please say a bit more.  Does https://github.com/domoticz/domoticz/pull/4720/files#diff-5b2760af3536bb0815c7fb95a496885687546254ce0f97a20845d07c4d05cb92R38-R62 cover what you were looking for?

Should `Connections` be added?  Are all of 5 variables Python dicts to the plug-in developer?

**Comment by pipiche38** [comment]
here is what I'm getting after adding this line into my plugin.py file

> 
> 
> Mar 11 16:26:56 rasp domoticz[25656]: 2021-03-11 16:26:56.589  Error: Python Plugin System: (Zigate) failed to load 'plugin.py', Python Path used was '/var/lib/domoticz/plugins/Domoticz-Zigate/:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/site-packages:/usr/lib/python3.8/site-packages'.
> Mar 11 16:26:56 rasp domoticz[25656]: 2021-03-11 16:26:56.589  Error: Python Plugin System: (DIN ZiGate) Module Import failed, exception: 'ImportError'
> Mar 11 16:26:56 rasp domoticz[25656]: 2021-03-11 16:26:56.589  Error: Python Plugin System: (DIN ZiGate) Module Import failed: ' Name: Domoticz'
> Mar 11 16:26:56 rasp domoticz[25656]: 2021-03-11 16:26:56.589  Error: Python Plugin System: (DIN ZiGate) Error Line details not available.


So what I mean is that from a lint perspective it works, however I feel (except if I missing something) the Python Framework embedded in Domoticz when launching the plugin have issues

**Comment by cclauss** [comment]
Are you using a Domoticz build that was created from this branch?

**Comment by pipiche38** [comment]
Sorry , I didn't understood the PR, I was just under the impression that you were upding the python plugins. But if you are also updating the domoticz python framework to work with I'll wait for.

I'm currently building domoticz out of the development branch and I'm on build 13065

**Comment by cclauss** [comment]
@flopp999

**Comment by cclauss** [comment]
Added `Connections`...
```python
from Domoticz import Connections, Devices, Images, Parameters, Settings
```

**Comment by gizmocuz** [comment]
I really don't mind this PR, but running this when a html/c++ file has been changed is not really necessary

As I can see in the PR, it's 99% about the plugins folder, the files in the scripts folder do not change often

https://stackoverflow.com/questions/63822219/how-to-run-github-action-only-if-the-pushed-files-are-in-a-specific-folder

**Comment by pipiche38** [comment]
@cclauss from the Domoticz code it is Connection without 's'

https://github.com/domoticz/domoticz/blob/development/hardware/plugins/Plugins.cpp#L602

**Comment by cclauss** [comment]
It takes 3 seconds to install and run flake8 on the entire repo on a build that takes more than 30 minutes.

IMG_0587
Running flake8 on only the `plugins` directory is an optimization of 2/10s of one second.  If the 3 sec is a problem I could move flake8 tests to the AppVeyor run which only takes 19 minutes so we don't slow down the long-running GitHub Action.

My sense is that a far more interesting optimization would be to use [`actions/cache`](https://github.com/actions/cache) to streamline the 23-second `apt-get` job step.  https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

Perhaps the `boost` and `openzware` jobs steps could be similarly cached.

**Comment by cclauss** [comment]
Removed `Connections` again because PyDicts are declared for [`Devices`](https://github.com/domoticz/domoticz/blob/development/hardware/plugins/Plugins.cpp#L1331), [`Images`](https://github.com/domoticz/domoticz/blob/development/hardware/plugins/Plugins.cpp#L1363), [`Parameters`](https://github.com/domoticz/domoticz/blob/development/hardware/plugins/Plugins.cpp#L1280), and [`Settings`](https://github.com/domoticz/domoticz/blob/development/hardware/plugins/Plugins.cpp#L1995) but not for `Connections`.

% `grep "PyDict_SetItemString(pModuleDict" hardware/plugins/Plugins.cpp`
```
if (PyDict_SetItemString(pModuleDict, "Parameters", pParamsDict) == -1)
if (PyDict_SetItemString(pModuleDict, "Devices", (PyObject *)m_DeviceDict) == -1)
if (PyDict_SetItemString(pModuleDict, "Images", (PyObject *)m_ImageDict) == -1)
if (PyDict_SetItemString(pModuleDict, "Settings", (PyObject *)m_SettingsDict) == -1)
```

**Comment by gizmocuz** [comment]
@cclauss , I am open for suggestions, the faster things get checked the better. Hence my suggestion to only check the plugins folder

**Comment by gizmocuz** [comment]
https://stackoverflow.com/questions/63822219/how-to-run-github-action-only-if-the-pushed-files-are-in-a-specific-folder

**Comment by cclauss** [comment]
Yes.  That applies to the entire GitHub Action so no tests will be run unless one or more files in `./plugins` is modified.

**Comment by gizmocuz** [comment]
Yep that will do....
Please let me know if this is ready to be merged

**Comment by cclauss** [comment]
Ready to be merged.

**Comment by gizmocuz** [comment]
Thank you for this PR and time !!

**Comment by flopp999** [comment]
If I add that row
`from Domoticz import Devices`  
I get an error message 

> '/home/debian/domoticz/plugins/Tibber/:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages'.
> 2021-03-24 22:06:39.069 Error: (Tibber) Module Import failed, exception: 'ImportError'
> 2021-03-24 22:06:39.069 Error: (Tibber) Module Import failed: ' Name: Domoticz'
> 2021-03-24 22:06:39.069 Error: (Tibber) Error Line details not available.
> 

my plugin will not load, but the test on github will work

**Pull request merged**
