### PR TITLE
Implementing P1 Smart Meter Ampere per phase (Siconia T211 3 phases)

### PR DESCRIPTION
**Pull request by jg117945**
Currently running Domoticz:

Version: 2020.2
Build Hash: b63341b
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

The following 3 IDs (Ampere per phase) are not added as devices when adding hardware:

1-0:31.7.0(003.58A)
1-0:51.7.0(004.85A)
1-0:71.7.0(003.93*A)

Ideally, Ampere for each phase could be integrated in a single graph as well as the sum of the 3 phases.

E-mucs P1 v1.4 is defined [here](https://energieverbrauchimblick.be/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG9CIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51373b461e44c6a2ec8e3acd910594d1b70d525a/e-MUCS_P1_Ed_1_4%20%281%29%20%281%29.pdf?disposition=attachment):

When looking on page 9 and 10, you can read for 1-0:31.7.0255, 1-0:51.7.0255 & 1-0:71.7.0*255 this:

> Note 4: In deviation to the DSMR P1, the resolution for the instantaneous currents (1‐0:x1.7.0*255 with x
> =3, 5, 7) is improved from F3(0,0) to F5 (2,2)

Meaning that 2 digits are available. As you can see here below, those information available with my T211 3-phase device:

pi@raspberrypi:/home/giton $ cat /dev/ttyUSB0
/FLU5\253769484_A

0-0:96.1.4(50214)
0-0:96.1.1(3153414733313030303733363338)
0-0:1.0.0(201103121009W)
1-0:1.8.1(000760.864kWh)
1-0:1.8.2(001065.055kWh)
1-0:2.8.1(001036.195kWh)
1-0:2.8.2(000380.702kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.000kW)
1-0:2.7.0(00.906kW)
1-0:32.7.0(233.9V)
1-0:52.7.0(232.8V)
1-0:72.7.0(232.4V)
**1-0:31.7.0(000.98A)
1-0:51.7.0(002.53A)
1-0:71.7.0(002.45A)**
0-0:96.3.10(1)
0-0:17.0.0(999.9kW)
1-0:31.4.0(999A)
0-0:96.13.0()
!1A98

### CODE REVIEW

**Comment by gizmocuz** [comment]
@jg117945 , you are committing against the master branch.
Could you checkout the development branch (our active branch) or switch to the development branch,
then make the changes and make a PR?

**Comment by jg117945** [comment]
> @jg117945 , you are committing against the master branch.
> Could you checkout the development branch (our active branch) or switch to the development branch,
> then make the changes and make a PR?

@gizmocuz 
Hello, I'm quite new user in Github but cannot select development brach; only master and revert-4416-clng can be selected

**Comment by kiddigital** [comment]
@jg117945 , your PR is incorrect. It only has 'old' commits from others and I do not see the changes you have tried to make.

First make sure you create a local checkout of the development branch and then create a new branch from it where you apply your changes. Easiest than is to push these changes from you new branch to your own fork of Domoticz on your own Github account. Once the branch there contains the changes you want, you can create a Pull Request from your new branch in your fork to the main development branch from Domoticz.

There is plenty of material online to help you on understanding the GIT processes and how to use GitHub. Good luck...

@gizmocuz , this PR can better be closed.

**Comment by gizmocuz** [comment]
@jg117945 , this is indeed against the master branch, but as KidDigital says it contains some old code

**Pull request closed without merging**
