### PR TITLE
Added new notification "when" operators

### PR DESCRIPTION
**Pull request by sbouchex**
Added "greater or equal", "below or equal" and "equal" operators for the notifcations

### CODE REVIEW

**Comment by gizmocuz** [comment]
Where do you use this ? (that you need <= xx, if < x+1 is not the same

**Comment by sbouchex** [comment]
The objective is just to add equality to the current tests.

You may want to trigger an alarm when temp is >= xxx. I agree that you may use > xxx-1 but that's less readable . IMHO

**Comment by gizmocuz** [comment]
I dont think it is more readable/easier if you provide the novice user with a lot of options...?

**Comment by sbouchex** [comment]
ok for >= and <=  but = may be usefull

**Comment by gizmocuz** [comment]
Yes, but for what type of sensor ?

**Comment by sbouchex** [comment]
Temperature, Humidity and Ampere

**Comment by gizmocuz** [comment]
You will never get an exact temperature, not Humidity , nor Ampere, for those you Need to use the above/below for sure

**Comment by sbouchex** [comment]
If we exclude all environmental sensors, we have percentage, but I agree it's not very common.

Other operator idea : "Latched Greater" : The notification is emitted when the value goes above the threshold but the notification will not be emitted again if the value is above again. It will only emitted if the value is below once, then goes above again.

Same for "Latched Below"

**Comment by gizmocuz** [comment]
Nice when the temperature fluctuates between 1 degree ...
You can set a notification interval in the settings
Sorry, closing this issue, thanks for your effort !

**Pull request closed without merging**
