### PR TITLE
Helper use GetTickCount64 instead of GetTickCount

### PR DESCRIPTION
**Pull request by jvandenbroek**
Let's see what AppVeyor has to say about this before merging.. Will get a test environment soon! (I hope)

### CODE REVIEW

**Comment by jvandenbroek** [comment]
OK, annoying, too many things to fix before it's compatible with > Vista. Look into this later when I have a decent test environment.

At least it seems to build, but too many new warnings introduced...

**Comment by gizmocuz** [comment]
Why ? the only thing you have todo is in helper.cpp/h return a uint64_t and replace GetTickCount with GetTickCount64
Its not complaining here...

**Comment by gizmocuz** [comment]
this should do it
https://github.com/domoticz/domoticz/commit/602febb3c4ddfd7f260557df35a6c358eb504434

**Comment by jvandenbroek** [comment]
Hmm how could that work if the minimal version is set to XP , which doesn't support this function? That's what I tried to change, setting Vista as minimal version app wide, but as you can see in the AppVeyor logs, it will complain on many other parts.

**Comment by gizmocuz** [comment]
Hmmm your right ;) sorry, reverted it

**Comment by gizmocuz** [comment]
Fixed in latest commit ;)
https://github.com/domoticz/domoticz/commit/645a16cf3939906777ec28b31d3cf458aa4ce1a3

compiles correct

**Pull request closed without merging**
