### PR TITLE
Autorefreshing temperature chart completed and zoom buttons added

### PR DESCRIPTION
**Pull request by michahagg**
Hi @gizmocuz ,

I have a new PR containing the following:

**Updated the new charts**
- Added preset zoom buttons in top right corner of charts.
- Replaced highcharts zoom reset button with button in the same style as preset zoom buttons.
- Double click/tap zooms chart 50%.
- Using a mouse, shift-drag pan's the chart left and right.
- Using touch, tap-hold-move pan's the chart left and right.
- Removed Day, Week, Month and Year chart headers. 
- Made titles in the top-center of each chart responsive. When chart is too narrow, the title will appear just above the chart.

**Updated Temperature Chart**
- Refreshes automatically every 5 minutes.
- Added all missing plotlines/series since last PR.
- Changed month and year from spline to column. Is now same as week.

**Updated Counter Spline Log Chart**
- Refreshes automatically every 5 minutes.

_Zooming_
Added zoom buttons with easy zoom settings. Particularly useful on a smartphone with a small screen; zooming by pinching is quite awkward.
* Buttons are added to each chart where each button effectively limits the view to a specific time span. For example: 1d - one day, 3d - three days, 1w - one week, 1m - one month. The letter on the buttons is the first letter of the word 'day', 'week', 'month' or 'year' in the configured language.
* Limiting the view is always done to the left (backwards in time), not changing the time for the right view edge.
* Double clicking now zooms in 50%. (This makes zooming in on a smartphone easier as well.)
* The buttons and double clicking don't change the zoom edge stickyness. This is applicable for when the view is already zoomed in where one or both zoom edges are sticky to the time axis (using Ctrl-mousedown and/or Ctrl-mouseup).
* The reset button sets the chart back to the initial view.

Hope you like it.

Known issues:
- Domoticz UI no longer works on iPad2 (iOS 9.3.5)
- Tooltip shows midnight with one hour offset in year chart beyond daylight-saving-time boundary. Month chart probably too. (fixed)
- When panning on touch device (by touch-moving), some invisible text seems to be selected in the middle of the chart. (fixed)
- Legend background-color different from chart background-color. (workaround)
- Different value is used from previous data. (fixed)
- Provide minified/gzipped javascript files. (fixed)
- Markers (bullets) missing from Energy and Power day chart.

### CODE REVIEW

**Comment by gizmocuz** [comment]
@michahagg ,

Thank you for another great PR!!

I have some questions:

- GraphLog.html 
Are you still using 'chart-title' ? Or is the chart title set by calling getChartTitle?
If the later, maybe remove the chart-title here ?

Is it possible to post a screenshot with the new buttons ?
Will they not overlap a big part of the screen on (small) mobile devices?

In English w/h/m/s make sense ... in Dutch it would be w/u/m/s
Maybe we should add some translation to the buttons ?

**Comment by michahagg** [comment]
Hi @gizmocuz 

> * GraphLog.html
>   Are you still using 'chart-title' ? Or is the chart title set by calling getChartTitle?
>   If the later, maybe remove the chart-title here ?

Yes I think I can remove it. Maybe it is better to have the chart title be determined in one place as it's always going to be one of three variants.

> 
> Is it possible to post a screenshot with the new buttons ?
> Will they not overlap a big part of the screen on (small) mobile devices?

Here is a screenshot of the top of the screen in portrait orientation:
screenshot1

And the year chart zoomed in on the last three months in landscape orientation:
screenshot2

> 
> In English w/h/m/s make sense ... in Dutch it would be w/u/m/s
> Maybe we should add some translation to the buttons ?

We should huh?!  :-D I added the translation to the buttons.

**Comment by michahagg** [comment]
I guess eventually the zoom buttons should be positioned in a responsive way. It's just that I have to find out how that works first.

**Comment by gizmocuz** [comment]
@michahagg , Thank you for the screenshots.
I am not a very big fan of the buttons... Specially in the Month graph where only 31 items are.
It is very easy to the last week or 2 weeks ?
For the month graph i can understand it, as there could be 365 values in the chart.

Maybe instead of a button, just a text (white/bold) that you can click ? It will be much more less distracting for the eyes maybe ?

**Comment by michahagg** [comment]
> I am not a very big fan of the buttons... Specially in the Month graph where only 31 items are.
> It is very easy to the last week or 2 weeks ?
> For the month graph i can understand it, as there could be 365 values in the chart.

I removed the zoom buttons for the month chart.

> 
> Maybe instead of a button, just a text (white/bold) that you can click ? It will be much more less distracting for the eyes maybe ?

Now the buttons are just text and the reset button only appears when the chart is zoomed in. I attached two screenshots to show you how it looks.

Zoomed out (reset button does not appear):
screenshot3

Zoomed in (reset button appears left of the zoom buttons):
screenshot4

**Comment by gizmocuz** [comment]
@michahagg , looking great! Thank you for the change! Ready to be merged!
Once question, maybe it is possible, maybe not, is it possible to keep the 'Reset' action as a button ? It could be people are used to it. If not, no problem

**Comment by michahagg** [comment]
Sure, no problem. I'll fix that this morning. :-)

**Comment by michahagg** [comment]
@gizmocuz I changed 'reset' back to a button.

There is one thing though, when zooming in by using the mouse (dragging or double clicking) the reset button sometimes appears a few seconds after. My guess this has to do with the Angular digest cycle. I've been looking into $scope.$apply, but haven't found a working solution yet. Do you have any ideas?

**Comment by dannybloe** [comment]
While you'r at this one... perhaps you can look at dragging the chart when zoomed in on a touch device. Currently the chart is rather useless on touch in that case. Sometimes two-finger dragging works not usually not.

**Comment by michahagg** [comment]
> While you'r at this one... perhaps you can look at dragging the chart when zoomed in on a touch device. Currently the chart is rather useless on touch in that case. Sometimes two-finger dragging works not usually not.

I guess I understand what you mean. On my iPhone 7 panning with two fingers does work but it's rather awkward. With two fingers on the screen, the chart is completely hidden and you can't see what you're doing.
I'll see what I can do about it.

**Comment by gizmocuz** [comment]
@michahagg , I checked out the PR and yes, it seems it does not draw the reset button. It will only display when you hover the mouse over the possible position where it should normally appear.
If you don't do anything, it won't show
But sometimes no reset button is displayed regardless when hovering with the mouse

I also notice that the chart title is now Left aligned, and the title font is larger:

Before:
image

With this PR:
image

**Comment by gizmocuz** [comment]
I did notice that when I removed all code from 'setExtremes', that the reset button is never displayed, it could be it has todo with this function
When I press on the text buttons (like 1d or 1w) it always displays
It looks when the button is displayed some seconds later, that the chart data is refreshed ? I see a lot in the debug console

**Comment by michahagg** [comment]
> While you'r at this one... perhaps you can look at dragging the chart when zoomed in on a touch device. Currently the chart is rather useless on touch in that case. Sometimes two-finger dragging works not usually not.

Hi @dannybloe , I have added changes to the PR. Now it is possible on a touch device to pan a zoomed chart by holding your finger about half a second (400msecs) and then moving it left or right. Make sure you first zoom in so that there is part of the chart to pan to. You can zoom in by double tapping or clicking on the chart.

**Comment by michahagg** [comment]
> I did notice that when I removed all code from 'setExtremes', that the reset button is never displayed, it could be it has todo with this function
> When I press on the text buttons (like 1d or 1w) it always displays
> It looks when the button is displayed some seconds later, that the chart data is refreshed ? I see a lot in the debug console

Hi @gizmocuz I have made quite some changes and additions to the PR. The issue with the 'reset' button should be fixed. I found out how to use $timeout to always execute code within a angular digest cycle.
Furthermore, I have added all the series that were missing since the first rewrite of the temperature chart. 

Now the counter spline log chart is also autorefreshing.

**Comment by michahagg** [comment]
@gizmocuz, I found that the UI no longer loads in Safari on an iPad 2 with iOS 9.3.5. I'm not sure what causes this issue. Unfortunately I don't have another Apple device to which to connect the iPad with. That would enable me to view any errors in the console log. You don't happen to have both an iPad2 and an iMac or a MacBook by any chance, don't you? If not, I will post a request for help on the forum.

iPad2

**Comment by gizmocuz** [comment]
@m1ch4, thanks! Could you also add a reference in the html5.appcache file ?

**Comment by gizmocuz** [comment]
@michahagg, I recently corrected the appcache file as there were a few references in that did not exist.
Maybe that fixes the issue ? If not, please clear the cache + appcache (two different things) on the device
Sorry I have a iPAD 2019 (where i use Chrome 99%)

**Comment by gizmocuz** [comment]
@michahagg , let me know when I should merge this ! ;)

**Comment by michahagg** [comment]
> @michahagg , let me know when I should merge this ! ;)

@gizmocuz i'm happy with the PR now. Could you merge it?

Thanks!! :-D

**Comment by michahagg** [comment]
Hi @gizmocuz, in the mean time I made the P1 chart autorefresing (or rolling) as well. In addition to the following:

- Removed white border line from columns in column charts. Looks very fancy ;-)
- Changed month and year charts from spline-type to column-type. Now possible (readable) without the white border lines.
- Placed columns in column charts between the ticks. Now the spline and columns actually match.
- Fixed the appearance of the chart titles in the different themes.

Furthermore, Highcharts has a bug that effects panning a zoomed in chart when the columns are between the ticks. (Also the newest 8.2.2 version that I updated to.) I fixed the bug temporarily, and only just enough to work for how Domoticz uses Highcharts. This issue is being addressed by a Highcharts developer. (See highcharts/highcharts#9612)

I guess this PR is ready when you are ;-)  Could you merge it with development?

Spline and columns now actually match:
image
Before:
image

Month and year charts are now of the column-type:
image

On iPhone 7:
image

**Comment by gizmocuz** [comment]
@michahagg , thanks for this awesome PR !

**Comment by gizmocuz** [comment]
@michahagg , one problem with this PR, I now see 'Return' in the legend/graphs, and this was not the case with the original code
People not having a 'return' should not see those graphs, legends
Is it possible to correct this ? (I also assume the charts will look different)

**Comment by michahagg** [comment]
@gizmocuz Yes of course I'll fix that ASAP. Probably this evening. 

If anything else is broken, just comment here.
Hopefully other people will do the same.

**Comment by FireWizard52** [comment]
Thank you for your contribution.

I tested the new functionality with Firefox, Chrome and Waterfox.
The last one is a fork of Firefox.
See: https://www.waterfox.net/

While both Chrome and Firefox show the graphs with the new buttons (OK), Waterfox does only show the header text (E.g Internal Temperature) and no graphs at all. This could mean that more browser are not able to display the page correct.

Running Waterfox Classic 2020.09 on Linux.

**Comment by rwaaren** [comment]
Tested successfully on Opera and Edge

**Comment by michahagg** [comment]
> While both Chrome and Firefox show the graphs with the new buttons (OK), Waterfox does only show the header text (E.g Internal Temperature) and no graphs at all. This could mean that more browser are not able to display the page correct.

I've just downloaded Waterfox. I had never heard of it. But this is what I get on the console when I open a chart:
image

I think the main error is where it says 'SyntaxError: invalid regexp group'. That probably causes angular not recognizing the RefreshingChart constructor. Though I have no idea yet what regexp matcher it's talking about, let alone what group it's missing.

**Comment by FireWizard52** [comment]
@michahagg
 I would not spend a lot of time to find a solution, as not that many people will use that browser. It was just to let you know that the change has impact on (at least) one browser. It is a fork of Firefox But others could have the same issue. At least Chrome, Firefox, Opera and Edge are working and I think that one of these are used by the majority of Domoticz users.

**Comment by michahagg** [comment]
@FireWizard52 thanks for the heads up. It's a good thing people have enough browser options to choose from for using Domoticz. Furthermore, it seems overly cautious using a niche browser for security reasons on an internally hosted application. And what I noticed is that Waterfox is intensely slow. I would not recommend using that browser.

Other people don't recommend it for security reasons: https://www.howtogeek.com/335712/update-why-you-shouldnt-use-waterfox-pale-moon-or-basilisk/ 

Though I am curious about what is going on.

**Pull request merged**
