### PR TITLE
Notification interval issue fixed

### PR DESCRIPTION
**Pull request by jvandenbroek**
Small update to make sure that the notification interval is updated when changed in settings.

### CODE REVIEW

**Comment by jvandenbroek** [comment]
Will push a fix for ignoring interval setting when custom message has been set, please wait before merge :)

**Comment by jvandenbroek** [comment]
#1447 is now fixed, also fixed some other minor issues.

**Comment by gizmocuz** [comment]
Does this also solves:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=17060

**Comment by jvandenbroek** [comment]
Yes, it should.

gizmocuz <notifications@github.com> schreef op 9 april 2017 13:42:56 CEST:

**Comment by gizmocuz** [comment]
Thanks!!

**Pull request merged**
