### PR TITLE
fix for intermittend crash of domoticz and some refactoring of code

### PR DESCRIPTION
**Pull request by philippe72**
Okay, so here's the deal: I noticed that every few days my domoticz would crash on communicating with the Nefit easy server. After some debugging I found out that the cause was that I received a 'systemPressure' response to a 'uiStatus' request. They both contain a "value" key, but instead of the expected dictionary now it was a float causing NefitEasy.cpp:382 to crash.

Don't know the cause, maybe some delayed reply or a bug on Nefit side, but since the response contains the request type in the "id" key I added a check for this, so that we can 'guarantee' that the response type matches the request.

I also refactored the code to remove duplication and make it easier to read. I build and tested it on ubuntu 14.04.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for your work.
Could you make a patch with only the 'id' part ?

**Comment by philippe72** [comment]
I can, but I'd rather not? Are there issues with the refactored code?

**Comment by gizmocuz** [comment]
Yes, i liked my code, and found it very easy, also liked my logging
I would like to merge your 'id' checks

**Comment by philippe72** [comment]
Fair enough, your project, your rules. The main importance for me is getting the fix in! :-)

(I collected a lot of duplicate code in some functions: for me that is a natural thing to do but there is nothing as subjective as coding style preferences)

I will make the changes soon and resubmit it

**Comment by gizmocuz** [comment]
Is this still a problem ?

**Comment by gizmocuz** [comment]
If you have some updates, please open a new pull request

**Pull request closed without merging**
