### PR TITLE
Send RGBW from web to app

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by gizmocuz** [comment]
This is still on the todo list, and requires a lot more than this.
The whole hue stuff should be dropped

**Comment by szczukot** [comment]
Yes, i know.
This is a small first step - communication between web and app.
In the comming days, i will try use this value with blebox RGB devices.

**Comment by gizmocuz** [comment]
for now use the hue value as all other systems does, until this all gets rebuilded

**Comment by szczukot** [comment]
HUE is fake :)
This is only one number for poor devices. 
Blebox and others use 4 channels (RGBW) separately controlled.
Coolpick from domoticz is ok, but we must add support for RGB instead HUE

**Comment by gizmocuz** [comment]
i know... that is what i said.... we should drop the hue stuff
Only AppLamp is using it
But this has to be done in general, not with a quick hack like this

**Pull request closed without merging**
