### PR TITLE
PiFace: constexpr conversions

### PR DESCRIPTION
**Pull request by neheb**
Size from 8317280 to 8313184

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR. Aldo I liked the string formatting, it's best to not modify indents/formatting/white space changes in PR's as it produces a lot of changes.
Maybe this can be tidy up via a script in the feature?

**Comment by neheb** [comment]
I mean. Running clang-format on the entire codebase would produce a massive changeset. That's why I do it per commit.

**Comment by gizmocuz** [comment]
That is true for sure...

**Comment by Ne0k** [comment]
After this modification the RFXMeter counter from the inputs is not working anymore? Do you have a suggestion to fix this?

**Comment by gizmocuz** [comment]
@Ne0k , I have reverted this PR, not a big fan of std::array as well...
Hope all is working well in beta 13055 again

**Pull request merged**
