### PR TITLE
Add roomplan to device edit page

### LINKED ISSUE #5434: [enhancement] : add a device to a room from the device
Currently, we need to go the the "Plans" menu to search for devices and add them into a room.

I think it would be great to have the possibility to add a device to a room from the device "edit" pop-up window.

### PR DESCRIPTION
**Pull request by DewGew**
**Possible to add/remove device to roomplan in light/switches device edit page**:

dump

Translation 'No roomplan is added' key needs to be added.

### CODE REVIEW

**Comment by rezzalex** [comment]
Hello @DewGew , thanks a lot.

How can we link your PR to the enhancement ticket I have created ? : https://github.com/domoticz/domoticz/issues/5434

**Comment by gizmocuz** [comment]
Looking good, but it seems duplicate as you can do this from the roomplan editor.
Maybe change the text "No roomplan is added" to "No roomplan assigned" ?

**Comment by DewGew** [comment]
> Looking good, but it seems duplicate as you can do this from the roomplan editor. Maybe change the text "No roomplan is added" to "No roomplan assigned" ?

Or shortcut. I found it very useful.

**Comment by gizmocuz** [comment]
Thanks!! Looking great!
One request, please check the aligning/spacing of the HTML en extra (not needed spaces, for example the </div >
(and the td/tr alignment)

https://github.com/domoticz/domoticz/pull/6035/files#diff-a65e8bd21d65ffa2da595dec2b254e8d9ab22b5bb62e220052945a7d19f6a47a

Some editors do the aligning automatically, else you could try a online beatifier

**Comment by gizmocuz** [comment]
Hmmm what I meant was, there are many changes in the HTML code that are not part of this PR.
The 'beautify' code action made even more changes. 😂
But all looks OK. Thanks for the PR!!!

**Pull request merged**
