### PR TITLE
dzVents: include telegram as notification method

### PR DESCRIPTION
**Pull request by rwaaren**
Enable the use of telegram in domoticz.notify by using the constant domoticz.NSS_TELEGRAM

### CODE REVIEW

**Comment by dannybloe** [comment]
Oops.. 2.8.0 needs to be 2.4.8.

**Comment by rwaaren** [comment]
Got carried away :-) Updated README.md and wiki to reflect right version

**Comment by dannybloe** [comment]
Thanks

**Comment by sweetpants** [comment]
@rwaaren , I have tested this with domoticz.notify("subject", "message", PRIORITY_NORMAL, nil, NSS_TELEGRAM) and this works, but I also receive an email with the same message. Is thisright?

Using: domoticz.notify("subject", "message", PRIORITY_NORMAL, NSS_TELEGRAM) also sends a telegram, but also an email

**Comment by sweetpants** [comment]
Sorry my bad, had email notification enabled by default

**Pull request merged**
