### PR TITLE
dzVents integration

### PR DESCRIPTION
**Pull request by dannybloe**
Third try.. hope it will build now.

### CODE REVIEW

**Comment by koenkooi** [comment]
Would collapsing all the commits help with review? I've put up a branch with everything collapsed into a single commit: https://github.com/koenkooi/domoticz/commits/dzVents-collapsed

**Comment by dannybloe** [comment]
Well, there are only a handful of Domoticz files changes with a couple of lines of code changed. Everything in the scripts/dzVents folder can be skipped (well, you can look at it if you like...)

**Comment by koenkooi** [comment]
The changes being spread over 34 commits with merges and reverts makes it hard to track, for me at least.

**Comment by dannybloe** [comment]
I never understood why it matters to some. When I process a pull request I look at the end result. That's what matters to me. I don't care how that came to be.

**Comment by gizmocuz** [comment]
No thats not how it works.... its very hard to track all this

**Comment by dannybloe** [comment]
Oké I'll squash it next time.

**Comment by dannybloe** [comment]
If thats ok

**Comment by dannybloe** [comment]
Created a new one.. squashed.

**Pull request closed without merging**
