### PR TITLE
I2c check

### PR DESCRIPTION
**Pull request by samm-git**
This PR addressing issue #1109 by changing `__arm__` definition to corresponding headers check. Some arguments for it:

1. I2C/SPI buses are not ARM related and could be found on many architectures, including x86. Devices connected to this bus in the I2C.cpp/PiFace.cpp are also platform agnostic.
2. Current code will break compilation on FreeBSD/ARM because `__arm__` is defined but I2C/SPI bus interfaces are different. 

In the feature i am also planning to refactor SPI.cpp to add FreeBSD related code and isolate bus related parts from the sensor logic.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Great patch! Thanks!

**Comment by gizmocuz** [comment]
could it be that this patch is causing issues ? See the below forum post:
http://www.domoticz.com/forum/viewtopic.php?f=6&t=15468

**Comment by jackslayter** [comment]
Hi,
yes, I have an error on my BMP180 sensor

`Error: I2C_BMP085/180: I2C is unsupported on this architecture!...`
in domoticz log

working fine in < V3.6334 RPi2
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

thank you

**Comment by gizmocuz** [comment]
Think it's fixed now with:
https://github.com/domoticz/domoticz/commit/2063df831458891a0dad72cc052b02f6dd3c642a
https://github.com/domoticz/domoticz/commit/06562d20fa7fc5f7cd0a47037776076f7a10d7d0

**Comment by gizmocuz** [comment]
Yep it's fixed

**Pull request merged**
