### PR TITLE
Enocean: Add support for F6-05-xx profiles (smoke, wind and liquid detectors) + RSSI reporting

### PR DESCRIPTION
**Pull request by alexis-via**
Following discussion in issue #4623 
Screencast showing setup and use with my Enocean Ubiwizz UBILD001-QM smoke detector... with a real fire ! https://www.youtube.com/watch?v=s0fu1bFiu2Y

@gizmocuz I converted the log lines in the new code: instead of sprintf() + _log.Log(), I use Log() (without preceding sprintf). If you are OK with this, I'll change it everywhere in EnOceanESP3.cpp as you suggested.

If you agree, I propose to convert #ifdef ENOCEAN_BUTTON_DEBUG + _log.Log() by Debug(DEBUG_HARDWARE, "") without ifdef.

### CODE REVIEW

**Comment by alexis-via** [comment]
Two things I wanted to say:
1) Most of the diff is just adding one indentation for the code that handle the profile F6-02-01, to move that code inside an "IF profile = 2 and itype = 1". But the code itself hasn't been changed.
2) It's the first time I contribute to Domoticz and it's also the first time I write C++... so review carefully :)

**Comment by gizmocuz** [comment]
Thank you for the PR !!
For the switch, could you use the function

SendSwitch(int NodeID, uint8_t ChildID, int BatteryLevel, bool bOn, double Level, const std::string &defaultname, const std::string &userName, int RssiLevel = 12);

That is the new method for new switches , so the old switches have to be like it is now for backwards compatibility

You have one line

if (result.empty())

and further

else if (result.size()==1)

I think you can just use 'else' (without result.size......)

**Comment by alexis-via** [comment]
@gizmocuz  I took into account your 2 suggestions in my last commit. And I tested again with a real fire -> it works.

**Comment by gizmocuz** [comment]
Thank you very much for this PR!!

**Pull request merged**
