### PR TITLE
Update MQTT.cpp

### PR DESCRIPTION
**Pull request by jonferreira**
adds support for Stop command

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR!
Question, there are "Many" more switch commands... i don't think we need a validation check...
It's nice, but it depends on the switch type. Have a look at RFXNames.cpp, for example:

"Group On"
"Group Off"
"Set Group Level:"
"Dim"
"Bright"
"Sound 0 till Sound 8"
"Set to White"
Set Color
NightMode
Disco Mode 1 till 9
"Arm Home",
"Disarm",
"Light Off",
"Normal"
...
...
a lot of commands here....

**Comment by jonferreira** [comment]
OK I wasn't aware of all those but in that case maybe remove the validation entirely then?

**Comment by gizmocuz** [comment]
Yes, maybe comment it out for now...

**Comment by jonferreira** [comment]
as requested

**Comment by gizmocuz** [comment]
Not working.... please always test the code, at the very extreme least, compile it

**Comment by jonferreira** [comment]
sorry had a typo. my tests instance is down so don't have anywhere to test it

**Comment by gizmocuz** [comment]
Thanks!!!

**Comment by jonferreira** [comment]
No problem, pretty basic PR.

Just for curiosity, how does one know if PR X is part of beta / stable release Y?

**Comment by gizmocuz** [comment]
All PR's are based against the beta version. Releases are made from time to time...
When we are going to make a new release (should happen not to long from now) there will be a code freeze. At that time, only mandatory patches are taken and merged in both beta and the pre-release branch

**Pull request merged**
