### PR TITLE
Update XiaomiGateway.cpp - Aqara wireless single switch double click

### PR DESCRIPTION
**Pull request by twpeltenburg**
Not sure if this is the correct code. But the wireless aqara single was switch also supports double click. Do you need logs to confirm if this is the correct code?

### CODE REVIEW

**Comment by kovainfo** [comment]
Please, close pull request. Do not open before try yourself by your repo.

**Comment by kovainfo** [comment]
I have 86sw1 and it does not support double click! this code is wrong

**Comment by twpeltenburg** [comment]
> I have 86sw1 and it does not support double click! this code is wrong

It does show in the log when Xiaomi Message is enabled. I'll post logs tonight.
Also on Domoticz.com (https://www.domoticz.com/wiki/Xiaomi_Gateway_(Aqara)#Devices_Statuses_.28NOT_COMPLETE.29) it reports that this switch does support double click.

**Comment by kovainfo** [comment]
but Mihome reports that this switch does not support double click - only single click 
img_2249
((

**Comment by twpeltenburg** [comment]
> but Mihome reports that this switch does not support double click - only single click
> img_2249
> ((

Weird. I'll post screenshots of my MiHome + Domoticz logs tonight.

**Comment by twpeltenburg** [comment]
the log shows:

2018-10-03 21:27:40.646 Status: {"cmd":"report","model":"remote.b186acn01","sid":"158d00028f8863","short_id":48105,"data":"{\"channel_0\":\"click\"}"}
2018-10-03 21:27:45.273 Status: {"cmd":"report","model":"remote.b186acn01","sid":"158d00028f8863","short_id":48105,"data":"{\"channel_0\":\"double_click\"}"}
2018-10-03 21:27:50.747 Status: {"cmd":"report","model":"remote.b186acn01","sid":"158d00028f8863","short_id":48105,"data":"{\"channel_0\":\"long_click\"}"}

MiHome screenshot:

screenshot_20181003-215517__01

which means the remote.b186acn01 supports: click, double_click and long_click. Can you check if this is the same for 86sw1? @kovainfo maybe we need to setup remote.b186acn01 as new hardware instead of referencing remote.b186acn01 as 86sw1? @gizmocuz

**Comment by kovainfo** [comment]
but the code affects 86sw1, which DOES NOT support double-click.
in this case, you need to create a new device for remote.b186acn01
i think, you need close this PR and we will think how to do better

**Comment by twpeltenburg** [comment]
> but the code affects 86sw1, which DOES NOT support double-click.
> in this case, you need to create a new device for remote.b186acn01
> i think, you need close this PR and we will think how to do better

Right. But I don't think I can get that code working as I am not that skilled with programming. Do you have any idea? @gizmocuz

**Comment by kovainfo** [comment]
if you wait until the weekend, I will write the code))

**Comment by twpeltenburg** [comment]
> if you wait until the weekend, I will write the code))

Awesome!

**Comment by kovainfo** [comment]
I confirm once again - your code is completely wrong. Please, close this pull request. Also look in the logs - is there any command from your button to turn it off? 
eg:

_

> {"cmd":"report","model":"remote.b186acn01","sid":"158d00028f8863","short_id":48105,"data":"{"channel_0":"off"}"}

_

**Comment by twpeltenburg** [comment]
Closing pull request upon @kovainfo request. 

I will check this afternoon if there's a off command.

**Comment by twpeltenburg** [comment]
The is no off command only the commands stated in the log above. click, double click, long click. There should however be an Off state which can be triggerd by event within domoticz to prevent nasty loops.

**Pull request closed without merging**
