### PR TITLE
Refactor webserver server class v2

### PR DESCRIPTION
**Pull request by gaudryc**
Same as "Refactor webserver server class" branch but : 
- Fix compilation issue in environment with boost <= 1.57.
- Fix issue when no certificate file path is set in the command line.
- Set the secure listening address like listening address defined with the -wwwbind argument.
- Fix webserver socket graceful shutdown (#509)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Got build errors on the raspberry, same as yesterday

```
/home/pi/dev-domoticz/main/../tcpserver/../webserver/server_settings.hpp:181:26: error: ‘no_tlsv1_1’ is not a member of ‘boost::asio::ssl::context’
/home/pi/dev-domoticz/main/../tcpserver/../webserver/server_settings.hpp:183:26: error: ‘no_tlsv1_2’ is not a member of ‘boost::asio::ssl::context’

```

**Comment by gizmocuz** [comment]
boost version 1.59
ik see its here:
http://www.boost.org/doc/libs/1_59_0/boost/asio/ssl/context_base.hpp

but dont have this.... my boost version.hpp file tells me its 1.59

**Comment by gizmocuz** [comment]
We probably have to check for the below defines

SSL_OP_NO_TLSv1_1

SSL_OP_NO_TLSv1_2

**Comment by gaudryc** [comment]
Something like this :

#if defined(SSL_OP_NO_TLSv1_1)
            } else if (option.compare("no_tlsv1_1") == 0) {
                update_options(opts, boost::asio::ssl::context::no_tlsv1_1);
#endif
#if defined(SSL_OP_NO_TLSv1_2)
            } else if (option.compare("no_tlsv1_2") == 0) {
                update_options(opts, boost::asio::ssl::context::no_tlsv1_2);
#endif

**Comment by gaudryc** [comment]
But boost 1.59 always defines something for boost::asio::ssl::context::no_tlsv1_1 and boost::asio::ssl::context::no_tlsv1_2 even if SSL_OP_NO_TLSv1_1 and SSL_OP_NO_TLSv1_2 are not defined.
Are you sure about the boost version you use ?

**Comment by gaudryc** [comment]
I'm compiling on raspberry using boost 1.60 without any problem. And there is no difference between 1.59 and 1.60 at this level in the source code.

**Comment by gizmocuz** [comment]
Yes, its very odd...and i already tested with these defines and still received the error...

**Comment by gaudryc** [comment]
Did you make some "make -clean" (in both boost and domoticz) or "rm dev-domoticz/CMakeCache.txt" before ?

**Comment by gizmocuz** [comment]
testing this new commit, still receive errors:

```
2016-02-24 13:09:24.464  Domoticz V2.4747 (c)2012-2016 GizMoCuz
2016-02-24 13:09:24.464  Build Hash: 4c9d83a-modified, Date: 2016-02-24 07:58:58
2016-02-24 13:09:24.464  System: Raspberry Pi
2016-02-24 13:09:24.465  Startup Path: /home/pi/domoticz/
2016-02-24 13:09:24.547  Sunrise: 07:13:00 SunSet:19:13:00
2016-02-24 13:09:24.547  EventSystem: reset all events...
2016-02-24 13:09:24.565  Active notification subsystems: (0/11)
2016-02-24 13:09:24.568  Webserver(HTTP) started on port: 8080
2016-02-24 13:09:24.571  Error: WebServer(HTTP) exception occurred : 'resolve: H                                                                      ost not found (authoritative)'
2016-02-24 13:09:24.572  WebServer(HTTP) restart server in 5 seconds
2016-02-24 13:09:24.573  Webserver(SSL) started on port: 443
2016-02-24 13:09:24.576  Proxymanager started.
2016-02-24 13:09:24.580  Starting shared server on: 0.0.0.0:6144
2016-02-24 13:09:24.581  TCPServer: shared server started...
2016-02-24 13:09:24.582  RxQueue: queue worker started...
2016-02-24 13:09:24.583  Error: WebServer(SSL) exception occurred : 'resolve: Ho                                                                      st not found (authoritative)'
2016-02-24 13:09:24.583  WebServer(SSL) restart server in 5 seconds
2016-02-24 13:09:26.582  Hardware Monitor: Started
2016-02-24 13:09:26.583  EventSystem: reset all events...
2016-02-24 13:09:26.584  EventSystem: reset all device statuses...
2016-02-24 13:09:26.589  EventSystem: Started
2016-02-24 13:09:29.572  Error: WebServer(HTTP) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-24 13:09:29.573  WebServer(HTTP) restart server in 5 seconds
2016-02-24 13:09:29.583  Error: WebServer(SSL) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-24 13:09:29.584  WebServer(SSL) restart server in 5 seconds
2016-02-24 13:09:29.584  Hardware Monitor: Fetching data (System sensors)
2016-02-24 13:09:34.574  Error: WebServer(HTTP) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-24 13:09:34.575  WebServer(HTTP) restart server in 5 seconds
2016-02-24 13:09:34.585  Error: WebServer(SSL) exception occurred : 'resolve: Host not found (authoritative)'
2016-02-24 13:09:34.585  WebServer(SSL) restart server in 5 seconds

```

and i am just starting with

`./domoticz`

when pressing control-c i have a crash (this is new...)

```
^C2016-02-24 13:10:37.429  Closing application!...
2016-02-24 13:10:37.430  Stopping worker...
2016-02-24 13:10:37.430  RxQueue: queue worker stopped...
2016-02-24 13:10:37.431  TCPServer: shared server stopped
2016-02-24 13:10:37.432  Stopping all hardware...
2016-02-24 13:10:37.706  Hardware Monitor: Stopped...
2016-02-24 13:10:38.590  Scheduler stopped...
2016-02-24 13:10:38.608  EventSystem: Stopped...
2016-02-24 13:10:38.719  Mainworker Stopped...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted

```

#define APPVERSION 4747
#define APPHASH "4c9d83a-modified"
#define APPDATE 1456297138

**Comment by gaudryc** [comment]
I had tested it yesterday with or without any argument yesterday.
The first message contains only one quote as the -wwbind argument is set to something wrong.

**Comment by gaudryc** [comment]
If I do like you I got : 

pi@raspberrypi ~/domoticz_test_2 $ sudo ./domoticz_test_2
2016-02-24 13:34:23.900  Domoticz V2.4747 (c)2012-2016 GizMoCuz
2016-02-24 13:34:23.902  Build Hash: 4c9d83a-modified, Date: 2016-02-24 07:58:58
2016-02-24 13:34:23.904  System: Raspberry Pi
2016-02-24 13:34:23.905  Startup Path: /home/pi/domoticz_test_2/
2016-02-24 13:34:24.037  Active notification subsystems: http (1/11)
2016-02-24 13:34:24.042  Webserver(HTTP) started on port: 8080
2016-02-24 13:34:24.054  [web:443] create ssl_server using ssl_server_settings : ssl_server_settings['server_settings[is_secure_=true, listening_address='::', listening_port='443']', ssl_method='sslv23', certificate_chain_file_path='./server_cert.pem', ca_cert_file_path='./server_cert.pem', cert_file_path=./server_cert.pem', private_key_file_path='./server_cert.pem', private_key_pass_phrase='', options='default_workarounds,no_sslv2,single_dh_use', tmp_dh_file_path='./server_cert.pem', verify_peer=false, verify_fail_if_no_peer_cert=false, verify_file_path='']
2016-02-24 13:34:24.056  Webserver(SSL) started on port: 443
2016-02-24 13:34:24.065  Proxymanager started.
2016-02-24 13:34:24.072  Starting shared server on: :::10144
2016-02-24 13:34:24.074  [web:443] 'BEGIN DH PARAMETERS' found in file ./server_cert.pem
2016-02-24 13:34:24.077  RxQueue: queue worker started...
2016-02-24 13:34:24.079  TCPServer: shared server started...
2016-02-24 13:34:26.079  Domoticz Internal: Started
2016-02-24 13:34:26.080  EventSystem: reset all events...
2016-02-24 13:34:26.082  EventSystem: reset all device statuses...
2016-02-24 13:34:26.083  EventSystem: Started
^C2016-02-24 13:34:49.724  Closing application!...
2016-02-24 13:34:49.724  Stopping worker...
2016-02-24 13:34:49.725  RxQueue: queue worker stopped...
2016-02-24 13:34:49.726  WebServer(HTTP) stopped...
2016-02-24 13:34:49.727  WebServer(SSL) stopped...
2016-02-24 13:34:49.729  TCPServer: shared server stopped
2016-02-24 13:34:49.730  Stopping all hardware...
2016-02-24 13:34:50.090  Domoticz Internal: Stopped...
2016-02-24 13:34:51.080  Scheduler stopped...
2016-02-24 13:34:51.093  EventSystem: Stopped...
2016-02-24 13:34:51.593  Mainworker Stopped...
terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::lock_error >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

**Comment by gaudryc** [comment]
I've found why : server_base::init is called in server_base::run instead of server_base::server_base (like before).

**Comment by gaudryc** [comment]
I'm sumitting the change request #517

**Comment by gaudryc** [comment]
About boost, do you force the boost version somewhere in the compile configuration ? This could explain why your compilation enters in the ifdef.

**Comment by gizmocuz** [comment]
We have some build errors in #517

**Comment by gaudryc** [comment]
About "'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::lock_error >' what(): boost: mutex lock failed in pthread_mutex_lock: Invalid argument", I'm compiling a patch to keep a pointer to the thread created to start io_service in cWebem.

**Pull request merged**
