### PR TITLE
TTNMQTT: Many improvements including better handling of the CayenneLPP channels

### PR DESCRIPTION
**Pull request by kiddigital**
Also using customsensor for analog in/out, use of DevID as Mac, determining RSSI level, etc.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks you !!

**Comment by jeroenkl** [comment]
Only got the analog input in Domoticz, not the GPS, is this correct?:

{
  "analog_in_8": 3.75,
  "gps_1": {
    "altitude": 19.2,
    "latitude": 52.xxxx,
    "longitude": 5.xxxx
  }
}

I see in the script RSSI and gateway data (connected to this cayenne device through TTN) should also be available in Domoticz. Missing this data too.
Any advice appreciated

**Comment by kiddigital** [comment]
> 
> 
> Only got the analog input in Domoticz, not the GPS, is this correct?:
> 
> {
> "analog_in_8": 3.75,
> "gps_1": {
> "altitude": 19.2,
> "latitude": 52.xxxx,
> "longitude": 5.xxxx
> }
> }
> 
> I see in the script RSSI and gateway data (connected to this cayenne device through TTN) should also be available in Domoticz. Missing this data too.
> Any advice appreciated

Are you sending the GPS data as part of the CayenneLPP payload or did you expect the GPS coordinates of the receiving gateway?

If the GPS data comes from the sensor/payload, it should be stored. But it seems you found a bug in the patch :( I will see if I can make a fix asap and add a PR for it.

The RSSI is read from the receiving gateway (only the first at the moment and not looking for the best RSSI) and handed as values with the measurements. Same for batterylevel although that is is not actually available yet.

But somewhere down the line, Domoticz is not storing the RSSI and batterylevel as it should. Only seems to work for RFX and Z-wave devices (at least for me). Not sure (yet) where this needs to be fixed. Maybe @gizmocuz can give a pointer where this might go wrong.

BTW, what other gateway data (other than RSSI) would you like to see in Domoticz and how/why as a Gateway is not actually a sensor?

Thanks for reporting!

**Comment by jeroenkl** [comment]
Thanks for your fast reply.

Yes GPS coordinates are part of the cayenne payload. Also my another lora sensor with BME280 and GPS is not seen in domoticz. Yes I've got a valid MQTT connection.
Only my RAK7200 is partly working.
2020-04-25 12:49:28.890 (MQTT client gateway TTN RAK7200) General/Custom Sensor (rak7200_gps_tracker2_batt)

>>BTW, what other gateway data (other than RSSI) would you like to see in Domoticz and how/why as a Gateway is not actually a sensor?

Temp/Hum/Voltage/CO2/Barometer/ triple-axis gyroscope, a triple-axis accelerometer, and a triple-axis magnetometer

A gateway is not a sensor, but in TTN console you can see the sensor data which was received by which gateway including the RSSI of that related signal.
Like:
{
  "time": "2020-04-25T08:27:03.740505185Z",
  "frequency": 867.7,
  "modulation": "LORA",
  "data_rate": "SF11BW125",
  "coding_rate": "4/5",
  "gateways": [
    {
      "gtw_id": "eui-58xxxxxx",
      "timestamp": 3984616932,
      "time": "2020-04-25T08:27:03.754400014Z",
      "channel": 0,
      "rssi": -68,
      "snr": 11.75
    }
  ]
}

Thanks for checking!!!

**Comment by kiddigital** [comment]
Corrected the 'bug' by adding the missing code.

See [PR 4100](https://github.com/domoticz/domoticz/pull/4100)

**Comment by gizmocuz** [comment]
PR has been merged , and a new beta should be available (soon) 11984

**Pull request merged**
