### PR TITLE
bugfix in EcoCompteur.cpp

### PR DESCRIPTION
**Pull request by DenisMartin0**
I've replaced stod by strtod.
This replacement might fix an issue on specific compilers. cf. : #2107

### CODE REVIEW

**Comment by sweetpants** [comment]
Then it still won't compile without errors
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp: In member function ‘void CEcoCompteur::GetScript()’:
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:139:74: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
   SendKwhMeter(m_HwdID, 1, 255, root["data1"].asFloat(), strtod(fields[7]), "Conso 1");
                                                                          ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:144:74: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
   SendKwhMeter(m_HwdID, 2, 255, root["data2"].asFloat(), strtod(fields[9]), "Conso 2");
                                                                          ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:149:75: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
   SendKwhMeter(m_HwdID, 3, 255, root["data3"].asFloat(), strtod(fields[11]), "Conso 3");
                                                                           ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:154:75: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
   SendKwhMeter(m_HwdID, 4, 255, root["data4"].asFloat(), strtod(fields[13]), "Conso 4");
                                                                           ^
/home/harrys/MyProjects/Cpp/Domoticz/domoticz/hardware/EcoCompteur.cpp:159:75: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
   SendKwhMeter(m_HwdID, 5, 255, root["data5"].asFloat(), strtod(fields[15]), "Conso 5");

**Comment by DenisMartin0** [comment]
Very strange, because my lines are :
SendKwhMeter(m_HwdID, 1, 255, root["data1"].asFloat(), strtod(fields[7].c_str(), NULL), "Conso 1");
and yours are : 
SendKwhMeter(m_HwdID, 1, 255, root["data1"].asFloat(), strtod(fields[7]), "Conso 1");

Do you get the file from my commit ? or do you modifiy it on your side ?

**Comment by sweetpants** [comment]
I modified locally because your 2nd pull request #2111 is not committed yet. But I can wait until commited and do a new pull request

**Comment by gizmocuz** [comment]
please change the strtod to atof

**Comment by gizmocuz** [comment]
Fixed already...

**Comment by DenisMartin0** [comment]
Thanks for fixing it !
One more candid question : Why do you prefer atof versus strtod ?

**Comment by gizmocuz** [comment]
well... because it's an old function, easy function and does not give any problems, and it's used all over in domoticz code

**Comment by DenisMartin0** [comment]
clear :)

**Pull request closed without merging**
