### PR TITLE
Adding lost translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Still two translation is not display i my two browser IE11 and Chrome...
I cleared cookies... and still
Looks:
2015-10-12_22h27_05

**Comment by pepijng** [comment]
Could you please test your code before requesting a pull.

**Comment by ghost** [comment]
Ok but still ENergy day graph and Power day graph is noty show translated... In transifex is ok translation.

But i test my code but i dont know how add translation to files.json.gz and i dont have permission to add strings to TRANSIFEX

**Comment by gizmocuz** [comment]
Why would you translate strings like m/s, Watt etc ?
The 2 not working translations will be fixed in the next beta version

**Comment by ghost** [comment]
Becuase in polish is other: example Knots=Węzły, Waty, Ampery, Stopnie Celsjusza, Stopnie Faranheita

I added translation code to my domoticz and it work ok but with no translation becuase i dont know how add to domoticz-xx.json.gz and i can not add to Transifex.

**Comment by ghost** [comment]
Corrected in #140

**Pull request closed without merging**
