### PR TITLE
Fixed error code and carriage return when reloading server

### PR DESCRIPTION
**Pull request by sbouchex**

### CODE REVIEW

**Comment by gizmocuz** [comment]
I dont see any reason why we should exit with a code here ?

log_end_msg 3
exit 3

Looking at various other startup scripts, this is also not happening... why would you need/want this here ?

**Comment by gizmocuz** [comment]
Most scripts run 

$0 stop
$0 start

**Comment by sbouchex** [comment]
OK, I will remove the error code

**Comment by gizmocuz** [comment]
Okey, but then nothing will be changed ;)

**Comment by sbouchex** [comment]
yes, the missing carriage return ;-)

**Comment by gizmocuz** [comment]
hehe sorry, okey i wait for you patch then

**Comment by gizmocuz** [comment]
Sorry.. which missing carriage return ?

**Pull request closed without merging**
