### PR TITLE
Logitech Media Server: Add support for User Authentication on LMS server

### PR DESCRIPTION
**Pull request by EddyK69**
+Added LUA Favorites support

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the change!

Why are there 3 constructors of the class? This should only be one (including id/ip/port/username/password)

**Comment by EddyK69** [comment]
They're indeed obsolete, leftovers of Kodi-class. I wil remove them in a new commit in this PR.
(Only 2 are used)

**Comment by EddyK69** [comment]
Cleaned up code: removed unused constructors. Please merge ;)

**Comment by gizmocuz** [comment]
Had to manually commit to resolve a conflict (cache version, my fault)
Thanks for the patch!

**Pull request closed without merging**
