### PR TITLE
Better TopBar layout on Mobiles

### LINKED ISSUE #5466: livesearch layout on mobile
With introduction of livesearch (great addition!) I see a small layout issue when going on mobile and there is a roomplan selector and livesearch field visible
One of this fields could go on the same row as the sunrise/sunset entry

Screenshot_20221216-164821

When only one of the fields is available it looks OK

Screenshot_20221216-164952-954
Screenshot_20221216-164923-753

https://github.com/domoticz/domoticz/pull/5433

### PR DESCRIPTION
**Pull request by soif**
Fixes #5466

### CODE REVIEW

**Comment by soif** [comment]
@waltervl , Better?

**Comment by waltervl** [comment]
I did not push your changes to my system yet, will do that in an hour.

**Comment by waltervl** [comment]
Yes, better.
Screenshot_20221219-190150

**Comment by soif** [comment]
@gizmocuz .

If @waltervl validate it... 
I thing you might review it / merge! 😎

**Comment by gizmocuz** [comment]
@soif , I was away for the weekend and missed a screenshot ;) Thanks again!

**Comment by soif** [comment]
No worry, you're always welcome ! 🍻

**Pull request merged**
