### PR TITLE
EventsEditor: Add ability to choose script type (trigger) for Lua and Python

### PR DESCRIPTION
**Pull request by stas-demydiuk**
Based on Forum comment
https://www.domoticz.com/forum/viewtopic.php?p=202586#p202586

image

@gizmocuz I wonder if you could check if it is still valid option for events

### CODE REVIEW

**Comment by gizmocuz** [comment]
@stas-demydiuk , i am not that much into scripts/triggers, but looking in some previous backup code i found these trigger types: (22 may 2018, maybe there is a more recent version)

https://github.com/domoticz/domoticz/commit/525851f384fd8f28966549499b6ddfa6155272a0#diff-4eae35f1b35977a00ebd8086c259d4c9

```
<select name="dzVentsEventTypes" id="dzVentsEventTypes" class="ui-widget-content ui-corner-all" style="width: 12em; padding: .2em;display: none">
	<option value="All">All (commented)</option>
	<option value="Bare">Minimal</option>
	<option value="Device" selected="selected">Device</option>
	<option value="Group">Group</option>
	<option value="Security">Security</option>
	<option value="Scene">Scene</option>
	<option value="Timer">Timer</option>
	<option value="UserVariable">User variable</option>
	<option value="HTTPRequest">HTTP request</option>
	<option value="global_data">global_data</option>
</select>
```

**Comment by stas-demydiuk** [comment]
I'm actually still not sure if this `eventType` is used under the hood. For me it looked like that it was required only to generate script template in old eventsEditor and then it doesn't affect script execution. Later from forum's posts it sounds like it somehow affects. But I can't find any evidences for one or another side.

**Comment by rwaaren** [comment]
For dzVents only used for script template

**Comment by gizmocuz** [comment]
It seems to be used in 'void CEventSystem::EvaluateDatabaseEvents'

And the types are:
"all"

	"device",			// 0
	"scenegroup",		// 1
	"uservariable",		// 2
	"time",				// 3
	"security",			// 4
	"url"				// 5

**Comment by stas-demydiuk** [comment]
It is the code of original eventType select box
```
<select name="eventType" id="eventType" class="ui-widget-content ui-corner-all" style="width: 12em; padding: .2em;">
	  <option selected="selected">All</option>
	  <option>Device</option>
	  <option>Security</option>
	  <option>Time</option>
	  <option>UserVariable</option>
</select>
```

and according to `main/EventSystem.cpp:1967` looks like it is applicable for Blockly, Lua and Python events. Updated PR to reflect this.

**Comment by gizmocuz** [comment]
Thanks! Let's see if we get some feedback on this

**Pull request merged**
