### PR TITLE
Events-editor: fix scrolling in scripts list

### PR DESCRIPTION
**Pull request by stas-demydiuk**
Fix scrolling issue in scripts list for events editor page

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by freemann** [comment]
Oh yeah! 
Working great, thanks guys!!

**Comment by DewGew** [comment]
Please add translation also e.g:
`<h2 class="ng-binding" data-i18n="My automation scripts">My automation scripts</h2>`
In the data tables also..
@stas-demydiuk 
@gizmocuz

**Comment by gizmocuz** [comment]
I added the translation string in the Transifex system, i will update the language files when it's translated

**Pull request merged**
