### PR TITLE
2 extra ")" mess up the working

### PR DESCRIPTION
**Pull request by CyberClwn**
an extra ) on line 1006 and one on 5075 messed up the working of this file.

(indeed, wrong line number, not 5975, sorry :) )

### CODE REVIEW

**Comment by sweetpants** [comment]
I hope you removed a ')' one at 5075 instead of 5975!!!

**Comment by sweetpants** [comment]
Failed, it is stuck on: /Users/travis/build/domoticz/domoticz/hardware/plugins/PluginManager.cpp:34:10: fatal error: 'Python.h' file not found

**Comment by CyberClwn** [comment]
So is yours, and other pull requests. I guess something is wrong in the PluginManager.cpp. but is has nothing to do with my modification, i think :)

**Comment by gizmocuz** [comment]
Already fixed

**Pull request closed without merging**
