### PR TITLE
Added Telldus TZWP-102

### PR DESCRIPTION
**Pull request by flopp999**
exact line
<Product type="0003" id="0003" name="TZWP-102 Plug-in Switch" config="telldus/tzwp102.xml"/>

Will add TZWP102.xml file as well

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks, it is included by OZW and already available in our beta now

**Comment by flopp999** [comment]
Please update OZW soon again. I just found and error for my PR and have sent a new PR to OZW

**Comment by flopp999** [comment]
It is now updated in OZW

**Comment by gizmocuz** [comment]
Thanks

**Pull request closed without merging**
