### PR TITLE
Remove condition to have delta in data which prevented 'zeros' to pop…

### PR DESCRIPTION
**Pull request by ikkemaniac**
…ulate counter bar graph. Fixes domoticz/domoticz#958 and fixes domoticz/domoticz#1017

### CODE REVIEW

**Comment by gizmocuz** [comment]
Can you make a patch where you just 'remark' the checking for 0 ?

because it was obviously there for a reason, willing to make a new beta without it, but do not delete the code yet

**Comment by gizmocuz** [comment]
with other words just put // infront of the line

**Comment by gizmocuz** [comment]
I am closing this pull request, it gets not readably anymore, this time i see if (1==1) stuff in it, some beta comments, some formatting changes, i don't know what you want anymore
If i understand correctly, you only had to comment the above mentioned 'if' line right ?
If you want this, just make a comment on that line, leave the rest of the code alone, or wait until you have your final patch, and then make a pull request please

**Comment by ikkemaniac** [comment]
You asked me to revert the change and formatting i which i did by means of the 'revert' commit, no formatting changes persist.
Commenting out the condition would leave an unused group in the source, adding `if(1 == 1)` keeps it readable and understandable while it accomplishes the same as commenting out the original line. 
I added a comment stating this is a beta modification to keep the code readable and left the original condition in there.
I don't understand your coding rules or guidelines and find it makes it difficult to go through the code.

But I’ve pushed a commit as you requested nonetheless.

**Comment by gizmocuz** [comment]
My coding rules:
- Only change what needs to be changed.
Now your patch looks much better, except for the extra empty line on 12762
Before merging this pull request, it needs to be tested good, it might work in your situation, but these three checks i added for a reason...

**Pull request closed without merging**
