### PR TITLE
BleBox: constexpr conversions

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
code reading wise... I liked the std::string more then char*
Is it not possible to use std::string or maybe 'auto' here ?

**Comment by neheb** [comment]
std::string is not possible in constexpr context as it has a con/destructor. C++17 has std::string_view which does work in constexpr context. I tried using boost::string_view but it doesn't work in constexpr context.

edit: I think it's just defined to the std variant in C++17 mode.

I don't know where you would want to use auto.

```
constexpr std::array<STR_DEVICE, 9> DevicesType{
```

can be changed to

```
constexpr auto DevicesType = std::array<STR_DEVICE, 9>{
```

And in C++17:

```
constexpr auto DevicesType = std::array{
```

because of CTAD.

edit2: actually if all the members are changed to STR_DEVICE {x } , the extra parentheses can be removed.

**Comment by gizmocuz** [comment]
I was aiming at 'auto api_name;' , but no that does not work..... *g*

**Comment by gizmocuz** [comment]
Thank you !

**Comment by neheb** [comment]
Interesting...

LLVM's libcxx supports std::string_view under an experimental header. That's fairly useless unless building on FreeBSD.

fmtlib provides an implementation of string_view. I wasn't successful in getting the CMake stuff right though.

edit: NVM. https://en.cppreference.com/w/cpp/string/char_traits/length is the problem.

**Pull request merged**
