### PR TITLE
Added support for MCP23017: 16bit I2C GPIO expander

### PR DESCRIPTION
**Pull request by gneluka**
This is a new attempt since my previous PR could not be merged. 
Details:
Added support for Microchip's MCP23017: 16 bit I2C GPIO expander:
- Only output mode is supported currently.
- Hardcoded to use I2C port 1 on RPI 2 and 3.
- No dependency on wiringpi library.
- Output value is inverted on gpio ouput pin.( switch on == 0, switch off == 1)

Thanks

### CODE REVIEW

**Comment by gneluka** [comment]
Hi,

I've submitted this PR almost two weeks ago.  Please let me know if there's a reason why it cannot be merged. 

Thanks.

**Comment by gizmocuz** [comment]
Maybe because people had a late holiday ? ;)
Currently there is a conflict with this pull request (HTYPE_RaspberryMCP23017,	//107) should now be 109
Is it possible to fix them? Then i can merge this

**Comment by gneluka** [comment]
That's a totally valid reason. ;)
Any way I'll cancel this PR and submit a new one since I've made some improvements to the code and I have no idea how to merge all that changes into this PR.

Thanks!

**Comment by gneluka** [comment]
Closing as per note above.

**Comment by gizmocuz** [comment]
thanks

**Pull request closed without merging**
