### PR TITLE
setup: Tweak Pushover labels, add direct link to clone app

### PR DESCRIPTION
**Pull request by jcs**
(I am the author of Pushover)

Pushover calls an "API key" an "API token", and now that it is listed as a public app on https://pushover.net/apps, users can easily clone it at https://pushover.net/apps/clone/domoticz to get the same Domoticz icon and app name.

### CODE REVIEW

**Comment by jcs** [comment]
I didn't notice that there are i18n files that need to be updated to make label changes because they are gzipped (so grep didn't find them).  How are these files updated?

**Comment by gizmocuz** [comment]
I would not change them...
This because it is in the system for a long time now 
And with 30 translations... Every language has to be changed too
If you agree, please undo these..., else I will add them 
We use transifex for translation

**Comment by gizmocuz** [comment]
When you are not signed in (default) and go to the clone url, you are forced to create an account
I thought it was nicer to go to the main website, so users might read what pushover is
If you are logged in (not default), and go the the clone url, then you are presented with a nice page

**Comment by jcs** [comment]
Well I would have preferred two links, one on "Pushover" to go to the main site, and one on "API Token" to go to the clone page, but I didn't want to change the look of the page too much.

**Comment by gizmocuz** [comment]
I see no problem with added a second url underneath it

**Pull request closed without merging**
