### PR TITLE
main: Allow both On and on in switchcmd parm of switchScene JSON

### PR DESCRIPTION
**Pull request by rwaaren**
see  [forum post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=32804)

### CODE REVIEW

**Review by kiddigital — COMMENTED** [review]
Isn’t it easier and more readable to use the ‘stdlower’ function (Helper.cpp) so only checking the lowercase value instead of the different writing styles? 

They all mean the same in this situation.

**Comment by gizmocuz** [comment]
Yes, but people should use the correct Case .... this is not a Domoticz issue but a user issue, should not be solved in code

**Comment by rwaaren** [comment]
> Yes, but people should use the correct Case .... this is not a Domoticz issue but a user issue, should not be solved in code

I agree but in this case the confusion is understandable (if my understanding of the code is correct) because 'Off', 'off', 'OFF' are all considered as valid commands. (in fact anything else as 'On' is interpreted as 'Off'

**Comment by gizmocuz** [comment]
@rwaaren , not according out JSON documentation on the wiki ?

**Comment by rwaaren** [comment]
> not according out JSON documentation on the wiki ?

@gizmocuz; wiki documentation is correct on this. I was referring to the code. 

Fact that using 'on' is handled as 'Off' triggered me to create this PR

Do you want me to modify the code to return an error when this JSON is called with `switchcmd=off `  or `switchcmd=on` ?

**Comment by kiddigital** [comment]
> Yes, but people should use the correct Case .... this is not a Domoticz issue but a user issue, should not be solved in code

Agree, would be better/cleaner if everything was case-sensitive and invalid values should be an error (and not a ‘default’ value/action if not an exact match).

**Comment by gizmocuz** [comment]
Yes, for example for 'switchlight' this is checked/handled, because of a call to 'GetLightCommand', if the command is not valid for that type of hardware it returns false, and the JSON returns a ERROR
We could add a 'GetSceneCommand' and check for valid scene commands and bail out if there is a error (webserver.cpp, ~ line 6860)
Then again, i trust people that are able to call JSON API commands to also read the documentation

**Comment by rwaaren** [comment]
> Yes, for example for 'switchlight' this is checked/handled, because of a call to 'GetLightCommand', 
> We could add a 'GetSceneCommand' 

Like that idea. Will have a look somewhere today

**Comment by rwaaren** [comment]
Had a look and a couple of tries to implement it but my C++ knowledge is not enough for this yet.

**Pull request closed without merging**
