### PR TITLE
P1 Smartmeter for subtype Energy now shows correct graph from Floorplan

### PR DESCRIPTION
**Pull request by djoele**
In reply to:
P1 Smartmeter for subtype Energy now shows correct graph from Dashboard

### CODE REVIEW

**Comment by gizmocuz** [comment]
Do you mean the floorplan ? As the changed file is not the dashboard controller

**Comment by djoele** [comment]
yes, you are right. when you view the Floorplan and not the Dashboard.

my mistake.


Greetings.


________________________________
Van: gizmocuz <notifications@github.com>
Verzonden: zondag 16 juli 2017 07:47
Aan: domoticz/domoticz
CC: djoele; Author
Onderwerp: Re: [domoticz/domoticz] P1 Smartmeter for subtype Energy now shows correct graph from Dashboard (#1687)


Do you mean the floorplan ? As the changed file is not the dashboard controller

**Comment by gizmocuz** [comment]
Could you also increase the version number in the appcache file? This is needed when you make changes to the web files

**Comment by djoele** [comment]
I increased the version number in the appcache file.

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
