### PR TITLE
Add a new EnOcean ESP3 hardware controller setup screen

### PR DESCRIPTION
**Pull request by efdeb**
From Domoticz hardware screen, add a **Setup button on EnOcean ESP3 controllers** to display a new **EnOcean ESP3 hardware controller setup screen**.

This PR is a first version that can be used to :
 - display nodes attached to an EnOcean ESP3 controller with their characteristics :
	. NodeID
	. Type : Teached-in node, Virtual node created from domoticz, or Generic node (which may have an uncertain or unknown EEP)
	. Name (can be set by the user)
	. Manufacturer (can be set by the user)
	. EEP (can be changedby the user)
	. Description (can be set by the user)
	. Radio, Battery and Status informations
	. Last seen date/time
 - Allow to update some of these characteristics (name, manufacturer, EEP, Description)
 - Allow to delete a node (as wall as all associated devices)
 - Allow to enable learn mode, in order to ease teach-in of new EnOcean ESP3 nodes
 - Allow to soft reset EnOcean ESP3 controller

**Uncertain or unknown RORGS, leading to Generic nodes can now be easily specified by the user.  :**
_Uncertain_ : 1BS and 4BS teach-in do not always carry EEP information and might result in the creation of Generic nodes, for which the user has to confirm the real EEP.

_Unknown_ : as domoticz.db, up to version 149, did not record the full EEP (RORG was missing) which is the case since version 150. This shall be a problem when updating to 2022.1.

NB. This PR makes PR #5038 opened on 30 Nov 2021 by [labelette91580] useless : EnOcean nodes can now be deleted here, and all corresponding devices are deleted too. Correction of display status closed for blinds is also incorporated here.

**Added files :**

_www/app/hardware/setup/EnOceanESP3.html
www/app/hardware/setup/EnOceanESP3.js_

html & javascript for new EnOcean ESP3 setup screen for nodes visualisation and management.

**Modified files :**

_hardware/EnOceanESP3.h
hardware/EnOceanESP3.cpp_

Rework management of VIRTUAL_NODES created from m_hwdID/m_id_base to ease migration to 2022.1. In particular, insert them in EnOceanNodes table with EEP F6-02-01, so they will appear in EnOcean hardware setup screen.

Define WebServer helper commands necessary to manage new EnOcean ESP3 setup screen.
Add necessary support functions.

_hardware/EnOceanEEP.h
hardware/EnOceanEEP.cpp_

Define WebServer helper commands necessary to manage new EnOcean ESP3 setup screen.
Shorten and clarify EnOcean EEP descriptions.

_main/WebServer.h
main/WebServer.cpp_

Declare WebServer helper commands necessary to manage new EnOcean ESP3 setup screen.
Slightly rework EnOcean related code.
Insert virtual ESP3 switches created from LightsController in EnOceanNodes table with EEP F6-02-01, so they will appear in EnOcean hardware setup screen.
						
_www/app/hardware/Hardware.js
www/app/hardware/HardwareSetup.html
www/app/hardware/HardwareSetup.js
www/html5.appcache_

Take into account the new EnOcean ESP3 setup screen.
Add comments to explain the naming conventions for those screens between kebab and kamel case.

### CODE REVIEW

**Comment by efdeb** [comment]
@gizmocuz Thanks for your fixes, everything seems now OK with this PR.

**Comment by efdeb** [comment]
No changes to the code : just fix typo and small reorganisation.

Also replaced reinterpret_cast by dynamic_cast for class downcasting.
See reference documentation : https://docs.microsoft.com/en-us/cpp/cpp/dynamic-cast-operator?view=msvc-170

"The need for dynamic_cast generally arises because we want perform derived class operation on a derived class object, but we have only a pointer-or reference-to-base." -Scott Meyers

Nb. should be done anywhere appropriate in domoticz code as reinterpret_cast shall normally not be used for that purpose and could result in unexpected results.

**Comment by gizmocuz** [comment]
Could you change to code to not use 'auto' for pointer castings

auto pESP3Hardware

Else we can use auto for everything....

I just made a commit to change the casting to dynamic_cast

**Comment by gizmocuz** [comment]
Thank you very much again!!

**Pull request merged**
