### PR TITLE
Fix long term authentication cookie (DRAFT)

### PR DESCRIPTION
**Pull request by gaudryc**
Allow user authentication based on cookie even if the server is restarted.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks a lot again!!

**Comment by gizmocuz** [comment]
i had a crash when i restarted domoticz and go to the web page again (session.expire was not filled in and caused a crash)
fixed it, but please check
Also i made the log messages only to be displayed when compiled in debug mode (and _DEBUG is in te preprocessor settings)
Works great now!

**Comment by gizmocuz** [comment]
Could you change one thing ?
Keep the sessions in a vector/map, so we do not have to query the database for every web request?
Or do you think this will not matter for speed ? (i think this might be...)

**Comment by gizmocuz** [comment]
we have now many logs while in debug mode (hard to see anything)
could we add a remark (exclude) the line with

_log.Log(LOG_STATUS, "CheckAuthToken(%s_%s_%s) : user authenticated", session.id.c_str(), session.auth_token.c_str(), session.username.c_str());

(also in debug mode)

**Comment by gaudryc** [comment]
I'm finishing development, I will test and I will comment these logs ;-)

**Comment by gaudryc** [comment]
When you say you've got a crash, you have :
- logged in ;
- restart the server ;
- clicked some in the page before crashing ?

**Comment by gizmocuz** [comment]
quit domoticz
quit the browser
start domoticz
started the browser and pointed to my domoticz instance

**Comment by gizmocuz** [comment]
it retrieved the session from the database, but the session.expire was not filled in.
Made a patch, and it seems to be working now.... hope i did it right

**Comment by gaudryc** [comment]
I have no crash, the user is logged in automatically on browser start up as expected.
Could you tell me where you think the problem is ?

**Comment by gizmocuz** [comment]
please see my commit changes

**Comment by gaudryc** [comment]
OK, I finally found it, I didn't see you had merge my dev before it is finished.
Whatever, you were right, "session.expires" must be updated before being saved.

**Pull request merged**
