### PR TITLE
Change Level for lighting type

### PR DESCRIPTION
**Pull request by szczukot**
Regarding https://github.com/domoticz/domoticz/issues/778

KMTronic always send 0 as level
        bool bIsOn = false;
        SendSwitchIfNotExists(ii + 1, 1, 255, bIsOn, (bIsOn) ? 100 : 0, sstr.str());
ZWave don't use SendSwitch.

I didn't find hardware that using level <> 0 and type lighting2. I'm first :) And this is bug on this moment.

This is proposal for resolve bug and expand possibilities for futer hardware. Now new hardware may set level to max 255 (no limit to 15).

### CODE REVIEW

**Comment by szczukot** [comment]
Hi

Did You check this idea and code ?

regards
Fantom

**Comment by gizmocuz** [comment]
Lighting 2 does not have 255, but 15

**Comment by gizmocuz** [comment]
You should use the type general switch which does have 255

**Comment by szczukot** [comment]
If Lighting 2 have max value 15, why don't You fix this bug ?? https://github.com/domoticz/domoticz/blob/master/hardware/DomoticzHardware.cpp#L519

Fantom
ps. I can't using general switch, because i must code/decode ip adress and store it on deviceid column.

**Comment by gizmocuz** [comment]
Because i dont have a problem with it... only you
Anyway, enough of this, use the general switch ... or not
this is not a bug

**Comment by szczukot** [comment]
You dont't have problem because You don't use it yet - i wrote above about this.
But ok - i changed this in my code.

**Comment by gizmocuz** [comment]
Yep as said, thanks for implementing your own implementation in your class

**Pull request closed without merging**
