### PR TITLE
Fix for incorrect counter today calculation for Incremental Counters

### LINKED ISSUE #5340: Counter Today value not calculating correctly for Counter Incremental
This affects counter incremental virtual sensors (devType==pTypeGeneral && subType==sTypeCounterIncremental). 
The value displayed is zero even after the first counter increment is received and only updates after more than one short log rows are added to the Meter table and the subsequent values added are greater than the first row. On any case the Counter Today calculated value is incorrect.
Looking at the routine that calculates the counter today values, on WebServer.cpp, I see that it does it by subtracting the value of the first row for the current day (total_first below) from the current counter value (sValue from DeviceStatus table) (total_last below):

`

	strcpy(szTmp, "0");
	result2 = m_sql.safe_query(
		"SELECT Value FROM Meter WHERE (DeviceRowID='%q' AND Date>='%q') ORDER BY Date LIMIT 1", sd[0].c_str(), szDate );
	if (!result2.empty())
	{
		std::vector<std::string> sd2 = result2[0];

		uint64_t total_first = std::stoull(sd2[0]);
		uint64_t total_last = std::stoull(sValue);
		uint64_t total_real = total_last - total_first;

		double musage = 0;
		switch (metertype)
		{
			case MTYPE_ENERGY:
			case MTYPE_ENERGY_GENERATED:
				musage = double(total_real) / divider;
				sprintf(szTmp, "%.3f kWh", musage);
				break;
			case MTYPE_GAS:
				musage = double(total_real) / divider;
				sprintf(szTmp, "%.3f m3", musage);
				break;
			case MTYPE_WATER:
				musage = double(total_real) / divider;
				sprintf(szTmp, "%.3f m3", musage);
				break;
			case MTYPE_COUNTER:
				sprintf(szTmp, "%.10g", double(total_real) / divider);
				if (!ValueUnits.empty())
				{
					strcat(szTmp, " ");
					strcat(szTmp, ValueUnits.c_str());
				}
				break;
			default:
				strcpy(szTmp, "0");
				break;
		}
	}
	root["result"][ii]["Counter"] = sValue;
	root["result"][ii]["CounterToday"] = szTmp;`

I have found that for this to work correctly, just like it does for regular counters( dType == pTypeRFXMeter ) a routine adds a row  at the beginning of each day to the Meter table for the counter containing the latest value received on the previous day.  
That is done on CSQLHelper::AddCalendarUpdateMeter() and it works fine for Counter devices but it does not work for Incremental counters:

`

	time_t now = mytime(nullptr);
	struct tm ltime;
	localtime_r(&now, &ltime);
	sprintf(szDateEnd, "%04d-%02d-%02d", ltime.tm_year + 1900, ltime.tm_mon + 1, ltime.tm_mday);
	...
	...
	...

			if (
				(devType != pTypeAirQuality) &&
				(devType != pTypeRFXSensor) &&
				((devType != pTypeGeneral) && (subType != sTypeVisibility)) &&
				((devType != pTypeGeneral) && (subType != sTypeDistance)) &&
				((devType != pTypeGeneral) && (subType != sTypeSolarRadiation)) &&
				((devType != pTypeGeneral) && (subType != sTypeVoltage)) &&
				((devType != pTypeGeneral) && (subType != sTypeCurrent)) &&
				((devType != pTypeGeneral) && (subType != sTypePressure)) &&
				((devType != pTypeGeneral) && (subType != sTypeSoilMoisture)) &&
				((devType != pTypeGeneral) && (subType != sTypeLeafWetness)) &&
				((devType != pTypeGeneral) && (subType != sTypeSoundLevel)) &&
				(devType != pTypeLux) &&
				(devType != pTypeWEIGHT)
				)
			{
				result = safe_query("SELECT Value FROM Meter WHERE (DeviceRowID='%" PRIu64 "') ORDER BY ROWID DESC LIMIT 1", ID);
				if (!result.empty())
				{
					std::vector<std::string> sd = result[0];
					//Insert the last (max) counter value into the meter table to get the "today" value correct.
					result = safe_query(
						"INSERT INTO Meter (DeviceRowID, Value, Date) "
						"VALUES ('%" PRIu64 "', '%q', '%q')",
						ID,
						sd[0].c_str(),
						szDateEnd
					);
				}
			}

`

This is affecting not only incremental counter devices but potentially any counter on the meter table with dType == pTypeGeneral as the test above will evaluate to false and thus not inserting the required row.
To fix this issue the above if _test_ should be changed to:
`

			if (
				(devType != pTypeAirQuality) &&
				(devType != pTypeRFXSensor) &&
				(!((devType == pTypeGeneral) && (subType == sTypeVisibility))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeDistance))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeSolarRadiation))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeSoilMoisture))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeLeafWetness))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeVoltage))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeCurrent))) &&
				(!((devType == pTypeGeneral) && (subType == sTypePressure))) &&
				(!((devType == pTypeGeneral) && (subType == sTypeSoundLevel))) &&
				(devType != pTypeLux) &&
				(devType != pTypeWEIGHT)
				)

`
With this fix the row is inserted for counter incremental as well. Allowing the counter today to calculated correctly using the first row of the current day on the meter table for the corresponding counter.
I can submit the PR if this looks good to you.

Thanks

### PR DESCRIPTION
**Pull request by gneluka**
Fix for issue: #5340

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for this PR and it could indeed solve your issue

To be fair, I think it is safe to always add the latest value at the start of the day

I have made some changes here and I think the below code should solve the issue as well:

```
		//Insert the last (max) counter value into the meter table to get the "today" value correct.
		if (
			(devType == pTypeRFXMeter)
			|| (devType == pTypeP1Gas)
			|| (devType == pTypeYouLess)
			|| (devType == pTypeENERGY)
			|| (devType == pTypePOWER)
			|| ((devType == pTypeRego6XXValue) && (subType == sTypeRego6XXCounter))
			|| ((devType == pTypeGeneral) && (subType == sTypeCounterIncremental))
			|| ((devType == pTypeGeneral) && (subType == sTypeKwh))
			)
		{
			result = safe_query("SELECT Value,Date FROM Meter WHERE (DeviceRowID='%" PRIu64 "') ORDER BY ROWID DESC LIMIT 1", ID);
			if (!result.empty())
			{
				std::vector<std::string> sd = result[0];
				result = safe_query(
					"INSERT INTO Meter (DeviceRowID, Value) "
					"VALUES ('%" PRIu64 "', '%q', '%q')",
					ID,
					sd[0].c_str()
				);
			}
		}
```

It could be that there is already a value of today as the AddCalendar scripts are called from a timer... changes are small, but still
Even in this case the last value will be added with the current timestamp instead of a fixed hh:mm:ss of 00:00:00

**Comment by gneluka** [comment]
Hi @gizmocuz, thanks for looking into this.  
What you propose makes perfect sense to me as it is a more general fix. 
I have added a commit to this PR with your proposed changes.
Thanks

**Comment by gneluka** [comment]
Hi @gizmocuz, thanks for looking into this.  
What you propose makes perfect sense to me as it is a more general fix. 
I have added a commit to this PR with your proposed changes. 
After testing, I made minimal changes, removed the Date column from the select query since, from what I could see, it wasn't needed. Also removed the third Value parameter from the insert query as we are updating only two columns.
Thanks

**Comment by gizmocuz** [comment]
Thank you for the PR and your time!

**Pull request merged**
