### PR TITLE
Added two new denkovi devices and some minor bugs fixed

### PR DESCRIPTION
**Pull request by denkovi1**
New:
1. Added support for smartDEN IP-16R-MT (HTTP and ModBus TCP)
2. Added support for smartDEN IP-16R-MQ (HTTP)

Fixed:
1. Minor bugs in web server for Denkovi Devices
2. DAEnetIP2 (DAEnetIP2v2) incorrect ADC readings

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this great PR !
I do have one question/suggestion that could make things easier in the feature.
For each hardware type you have a separate 'log' line, for example:

**log.Log(LOG_STATUS, "SmartDEN IP-16R-MT: Started");**

Instead of this, you could make something like

**Log(LOG_STATUS, "%s: Started", szDenkoviHardwareNames[m_iModel]);**

where **szDenkoviHardwareNames** is a char* lookup table

instead of _log.Log it is adviced to use Log (without _log.), this will also automatically let the log lines start with the hardware name (Denkovi)

This will output:

"Denkovi: SmartDEN IP-16R-MT: Started"

(So maybe loose the second : )

**Comment by denkovi1** [comment]
Ok, tried to improve the code

**Comment by gizmocuz** [comment]
Thank you for the changes, looking perfect !!
One small request, could you move this to the .cpp file 

const char *szDenkoviHardwareNames[14]

**Comment by denkovi1** [comment]
Already moved,
thanks

**Comment by gizmocuz** [comment]
Thank you !!!

**Comment by rwaaren** [comment]
@denkov1 ; small request. Would it be possible for you to write an initial wiki page on the denkov hardware? Would be great. I searched but only see the denkov webpage and some posts on the forum.
Tia

**Comment by denkovi1** [comment]
Hello,
Sure. Can you please recommend what kind of information would be useful? I would need also the necessary credentials to make wiki page.
Thanks

**Comment by rwaaren** [comment]
Something like [Harmony wiki ](https://www.domoticz.com/wiki/Harmony_Hub) or [rflink wiki](https://www.domoticz.com/wiki/RFLink_Gateway_USB) would be a great start.

If you send me your preferred username and Email address (via forum PM or dzdomovents@gmail.com), I  will create it and the system will Email your wiki username and the option to set your own password.

**Pull request merged**
