### PR TITLE
OZW, Update detection of duplicate/invalid DeviceID

### PR DESCRIPTION
**Pull request by petergebruers**
1) Improves message in case of instanceID > 255

See https://github.com/domoticz/domoticz/issues/3627

Example log "Error: SendSwitchIfNotExists: Not adding '3.instance.1.index.256.commandClasses.113' (Previous Event Cleared) because instanceID 256 does not fit in byte"

2) Change "detection logic" of duplicate devices, avoids possible false positives.

3) Change logging level from ERROR to STATUS as per request of @gizmocuz

Example of a real message, caused by FGRM-222

"SendSwitchIfNotExists: Device '4.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00000401' matches '4.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch)."

The rationale behind that message is... this is the "matching" code in Domoticz:

//First find dimmer
pDevice = FindDevice(nodeID, instanceID, indexID, ZDTYPE_SWITCH_DIMMER);

Then retry with ZDTYPE_SWITCH_NORMAL

### CODE REVIEW

**Comment by gizmocuz** [comment]
@petergebruers , going to checking some changes that will adopt the status change, but checking the instanceID >255 < 0, does not work anymore because it's a uint8_t
Keep you posted here

**Comment by gizmocuz** [comment]
@petergebruers , I added the change in this commit

https://github.com/domoticz/domoticz/commit/3ace1a6c940eebdfb73751cf593f8907cf3b02a9

**Comment by petergebruers** [comment]
Im not checking instanceID but pDevice->instanceID

That is an int and the debugger 100 % for sure tells me it is 256

Domitcz then does `unsigned char ID4 = pDevice->instanceID;`which turns 256 into 0

**Comment by gizmocuz** [comment]
@petergebruers , have a look at the changes first please, 'instance' is 8 bit now (also in OZW)

**Comment by petergebruers** [comment]
I'll have to add flags to compile C++14 standard because it does not compile on my Mac yet, error "'auto' not allowed in lambda parameter"

So this is your solution to handle Index=256?

/Users/peter/ozw/domoticz/hardware/OpenZWave.cpp line 2544
```
		instance = GetIndexFromAlarm(vLabel);
		if (instance == 0)
			instance = (uint8_t)vOrgIndex;
```

So 256 -> 0 ?

**Comment by gizmocuz** [comment]
@petergebruers , most be the lambda calls... I will have a check for this, thanks for reporting.

No this is not a solution to handle index >=256 at all, this is part one of correcting the code, and in the near feature changing the DeviceID's for the ZWave switches

**Comment by rkluwen** [comment]
If instance would be an unsigned char, then yes, this is a solution. Just me 0.5 cents.

**Comment by gizmocuz** [comment]
@rkluwen , yes, but hmmm there is more then 256, see NotificationCCTypes.xml and ValueIDIndexesDefines.h

**Comment by gizmocuz** [comment]
At the moment the Alarm is handled as both switch (on/off) and as pTypeGeneral/sTypeZWaveAlarm
Best to delete the support for the on/off switch, but this needs more work in the correct handling/logging/scripting of pTypeGeneral/sTypeZWaveAlarm

**Comment by petergebruers** [comment]
Indeed,  I don't wonder about the cast. But the point is indeed vOrgIndex can be 256 or 512 or 513... You turn that into 8 bits sure but...

It is not "hypothetical" - an FGMS-001 does create such an index and I've seen similar posts by GravityRZ

eg 7.instance.1.index.256.commandClasses.113

**Comment by petergebruers** [comment]
> At the moment the Alarm is handles as both switch (on/off) and as pTypeGeneral/sTypeZWaveAlarm
> Best to delete the support for the on/off switch, but this needs more work in the correct handling/logging/scripting of pTypeGeneral/sTypeZWaveAlarm

I have to check that, I have not checked that "pTypeGeneral/sTypeZWaveAlarm" you've mentioned. I need more time, I am a slow old man 😉

**Comment by gizmocuz** [comment]
@petergebruers , so am I ;) ... project compiles again...

**Comment by gizmocuz** [comment]
@petergebruers , I think these '256' messages are from the automagic clears correct?
Maybe the best way is to find out what needs to be cleared, and clear this (value/device), and not add a switch/device with 256 in the first place, as it is a 'clear' for something

**Comment by petergebruers** [comment]
You are on the right track but it will become clearer after I have finished writing my report about handling this as promised in https://github.com/domoticz/domoticz/issues/3627

Very short answer: on the FGMS (and other devices as well but that is the one I use for testing) that ValueID tells you which one of the 2 possible alarms got clear.

The FGMS-001 can independently report Tamper (= shake the device) and Motion (= trigger the PIR). 

For example, OZW might log this when you pick up the device:

Class ALARM Instance 1 Index 7 Type list ValueAsString Motion Detected at Unknown Location
Class ALARM Instance 1 Index 7 Type list ValueAsString Tampering -  Cover Removed

Both alarms have independent "clear" signals. Eg you can shake the device, by default it will clear the tamper alarm after 30 s, but if you keep moving in front of it, the motion keeps "active" (does not clear). There are also parameters to set the timing of both alarms independently.

When you get a clear, you have to examine the contents of the Value with Index 256. Because the "Clear" packet tells you, with an extra byte, which alarm got cleared.

Class ALARM Instance 1 Index 256 Type byte ValueAsString 3 -> The three means "The Tamper alarm"

Class ALARM Instance 1 Index 256 Type byte ValueAsString 8 -> The eight means "Motion"

OpenZWave sets that index, prior to issuing a "clear", in the log that is:

Class ALARM Instance 1 Index 7 Type list ValueAsString Clear

This is not an example of "auto clear", quit the opposite, the device clearly signals "begin" and "end" of a an alarm condition. Some older device only signal a "begin". I'll try to find an example.

**Pull request closed without merging**
