### PR TITLE
Change in menu section from "Edit Users" to "Users"

### PR DESCRIPTION
**Pull request by ghost**
It is more compatible with other... 
Please add strings "Users" to trasifex , to we can add translation

### CODE REVIEW

**Comment by ghost** [comment]
Please Can you merged this...?

**Comment by ghost** [comment]
Please merged also this because a good way is to unify the menu and construction domoticz. The menu looks like it is better USERS not EDIT USERS . All default to that in each application users is their add and edit ...

**Comment by ghost** [comment]
??

**Comment by ghost** [comment]
GizmoCuz why you not merged my PR ?

**Comment by gizmocuz** [comment]
"Edit Users" is fine as it is!

**Comment by ghost** [comment]
It is a very professional to me. Looking at other various kinds of equipment is not used in the menu phrases like "EDIT USERS" only "USERS". The name is shorter and more consistent with the rest of returns.
Why for example it is not EDIT EVENTS only EVENTS? 
I wanted to in Domoticz was maintained consistency. I dont know nothing about programming, so I wanted to help in stylistic issues.

Any suggestion of my application is rejected, and now I know that probably none of my proposal will no longer be accepted. A little sorry for this reason. And all because I asked questions and suggestions please indicate with a lot of changes.

**Pull request closed without merging**
