### PR TITLE
#4301 added AirconWithMe

### PR DESCRIPTION
**Pull request by RDols**

### CODE REVIEW

**Comment by LarsenDX** [comment]
Successfully built and tested here on a MHI AC equipped with the AirconWithMe Wifi module.

**Comment by gizmocuz** [comment]
@RDols , thank you for this great addon!

Is it possible to move all structs/enums in the header file underneath the class declaration, so they are private to the class:

```
class CAirconWithMe: public CDomoticzHardwareBase
{
```

Do we need to let the user specify a poll internval ? This will only confuse people, does it need to be polled that frequently ?
Could we define the poll interval in the .cpp file ?

**Comment by LarsenDX** [comment]
The default poll interval in the UI of the device is 30s.
Screenshot 2020-10-02 at 11 07 22

**Comment by gizmocuz** [comment]
@RDols , great, is it possible to hard code this with a 'define' in the .cpp file ?
I just merged a very large PR, and there seems to be a conflict in the Hardware.html file, sorry

**Comment by LarsenDX** [comment]
> @RDols , thank you for this great addon!
> 
> Is it possible to move all structs/enums in the header file underneath the class declaration, so they are private to the class:
> 
> ```
> class CAirconWithMe: public CDomoticzHardwareBase
> {
> ```
> 
> Do we need to let the user specify a poll internval ? This will only confuse people, does it need to be polled that frequently ?
> Could we define the poll interval in the .cpp file ?

@gizmocuz I believe @RDols is really busy elsewhere at the moment so let me see if I can button this up.

I propose to move the declaration inside the class and leave the definition outside for readability.  Or would you rather have it all inside the class? Whatever fits the style of  C++ in domoticz best is fine with me.

class Container {
    struct Inner; // Declare, but not define, the struct.
};

struct Container::Inner {
   /* Define the struct here. */
};

**Comment by gizmocuz** [comment]
@LarsenDX , thanks for picking this up.
No everything inside the struct (also define it), as it is private to this class
I can also do it, takes me about 5 minutes.... let me know what you prefer

**Comment by LarsenDX** [comment]
@gizmocuz Alright, I've moved all remaining structs and enums into CAirconWithMe. I can't push those changes as I don't have write permissions. What am I missing?

**Comment by gizmocuz** [comment]
@LarsenDX , maybe you could make a new branch and create a PR ? I think the changes of RDols will be in there as well in that case

**Comment by LarsenDX** [comment]
Thanks, @gizmocuz . Please see #4383

**Pull request merged**
