### PR TITLE
[1WireByOWFS] fix for faster reading sensors

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by multinet33** [comment]
Hello 

I've a trouble with this commit on my last Domoticz beta 4618 build hash 8e3d9cd

The 1wire search functions is looping more and more and list x times my sensors (ds18b20) causing Domoticz to slow down dramatically 

Multinet.

**Comment by multinet33** [comment]
And not having this bug with the build hash 91e4915

**Comment by szczukot** [comment]
Pls give me a log from the newest version (and run domoticz with -verbose 2)

**Comment by szczukot** [comment]
Ok. I think I know where the problem is.
I creating pull request (https://github.com/domoticz/domoticz/issues/491).
For temporary you can disable "allow new devices" in settings.

**Comment by multinet33** [comment]
Thanks you ! I'm at the office i Will out a log later today

**Comment by multinet33** [comment]
Hello

here you have a log with the V2.4618 Build Hash: 8e3d9cd and allow new devices enabled.
http://pastebin.com/MTtGMJ2P

I confirm that disabling allow new devices is OK (no bug)

I will make the update of domoticz with your pull #491 tonight

Thanks

**Comment by szczukot** [comment]
Ok.
I think that https://github.com/domoticz/domoticz/pull/491 resolving problem.

**Comment by multinet33** [comment]
Problem solved with #491
Thanks !

**Pull request merged**
