### PR TITLE
Fix crash in CSQLHelper::UpdateValueInt (#2355)

### PR DESCRIPTION
**Pull request by emontnemery**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by Dylantje** [comment]
Dear Gizmocuz.....
Is there now only a solution for X64?
When do you think the X32 version is working wel?

Thanks

**Comment by gizmocuz** [comment]
@Dylantje , not sure what you mean ? If it is about a 32bit arm build, should be available now

**Comment by Dylantje** [comment]
Dear gizmocuz,,,, Everything works fine again, after this update
THANKS for the great work!!

**Pull request merged**
