### PR TITLE
compliance to rtl_433 newmodel (normalized keys)

### PR DESCRIPTION
**Pull request by dgrostoto**
works like a charm at home. Now should check that units are the same on domoticz side.
Units to be checked :
wind_avg in km/h
wind_dir in degre
wind_max in km/h
depth in cm
other units should be OK.

### CODE REVIEW

**Comment by MrHobbes74** [comment]
Your changes are not backwards compatible. Old devices that do not have the new API installed, will not work after this change. Am i correct? In that case, you can't just change the code to work with the new API, while forgetting about the old API.

**Comment by dgrostoto** [comment]
Not at all! every device support the new "API" (this is not really a new API but a new set of normalized keys but let's call it an API). It has been worked on rtl_433 side for more than a year now. And i pointed the remaining bugs i've found on rtl_433 and they 've been corrected. So all of the 201 devices supported by rtl_433 are functional with domoticz with the new API. I've checked every key of every device used in domoticz (that's quite a big work for me). I can also say that (moreover i did not left on side any device) there are other devices that did not correctly or at all that are now working correctly thanks to those normalized keys.
Bonus, the code is now simpler on domoticz side (no more trick depending of device type).
Let me know is the coding style is OK for you or if I could left some bug (i'm human after all :) )

**Comment by gizmocuz** [comment]
@dgrostoto , thanks for the explanation.
@MrHobbes74 , are you able to test this ? Else I merge the PR

**Comment by dgrostoto** [comment]
The point i'd like some additional checks concerns the units quoted above, to be sure they are interpreted in same unit that rtl_433 send or if they are additional conversion to be done.

**Comment by gizmocuz** [comment]
@dgrostoto , Domoticz works internally in m/s , see mainworker.cpp, decode_wind,  with 1 decimal.
3.6 mtr/sec should be stored as 36, same for temperature 5.1 should be 51

**Comment by MrHobbes74** [comment]
> @dgrostoto , thanks for the explanation.
> @MrHobbes74 , are you able to test this ? Else I merge the PR

@gizmocuz I cannot test this, I don’t have this hardware, I’m also not familiar with it, but it was just an observation. But it may mean all devices that users have and didn’t upgrade for a year, will need an upgrade? All devices may support the new API but not all may have this API installed. That was more my concern.

**Comment by dgrostoto** [comment]
@gizmocuz , OK i'll integrate the appropriate conversions. The metric system and unit used by the newmodel have a great advantage : they have chosen the smallest units, so precision is better and even more some events may be detected whereas they may be not (due to rounds) with bigger sized units (i had the concern with my PCR800 raining sensor device).
@MrHobbes74 , let me explain futhermore : the "API" (as i said, just a set of normalized keys called a model, not an API strictly speaking) is not on the device side (the hardware) but on rtl_433 software side. So every hardware device is compliant with this new model since rtl_433 is handling the mapping of the raw data to the corresponding key in the new model (temperature, wind direction, id, etc...). So there is no need to have any driver nor something specific on device side to be compliant for this model, which is great isn't it ? :)
For the users who have not upgrade for a year, the change will be transparent, provided of course they upgrade domoticz AND rtl_433. To have the things done right, i will tell which minimum version of rtl_433 must be used and we could add this information in the documentation.

**Comment by MrHobbes74** [comment]
Totally clear to me! Thanks for explaining!

**Comment by dgrostoto** [comment]
Conversions are done. it is OK for merging from my side.

**Comment by dgrostoto** [comment]
rtl_433 project  tagged its latest version. So i can tell now that version with flag "20.02" (2020-02-17 branch master) is the version minimal need for this PR (#3902 ) and also the recommended version.

**Comment by gizmocuz** [comment]
Thank you for this !!

**Comment by dgrostoto** [comment]
found some issue that should be solved by this PR
https://github.com/domoticz/domoticz/issues/3872
https://github.com/domoticz/domoticz/issues/3834
https://github.com/domoticz/domoticz/issues/3272
https://github.com/domoticz/domoticz/issues/3104
https://github.com/domoticz/domoticz/issues/2966
There is some device support demand that cannot be satisfied as is 
https://github.com/domoticz/domoticz/issues/3144

**Pull request merged**
