### PR TITLE
Adding few more predefine Typename

### PR DESCRIPTION
**Pull request by pipiche38**

### CODE REVIEW

**Comment by pipiche38** [comment]
I'll update the wiki, when merged, so wiki will be aligned with this additional typename

**Comment by gizmocuz** [comment]
Thanks for the PR!

In Domoticz (RFXNames.cpp, RFX_Type_Desc), pTypeColorSwitch is called "Color Switch"

To be consistent, I suggest to also name it like this

"ColorControlWW" -> "Color Switch WW" and also name them like in Domoticz

		{ pTypeColorSwitch, sTypeColor_RGB_W, "RGBW" },
		{ pTypeColorSwitch, sTypeColor_RGB, "RGB" },
		{ pTypeColorSwitch, sTypeColor_White, "White" },
		{ pTypeColorSwitch, sTypeColor_RGB_CW_WW, "RGBWW" },
		{ pTypeColorSwitch, sTypeColor_LivCol, "RGB" },
		{ pTypeColorSwitch, sTypeColor_RGB_W_Z, "RGBWZ" },
		{ pTypeColorSwitch, sTypeColor_RGB_CW_WW_Z, "RGBWWZ" },
		{ pTypeColorSwitch, sTypeColor_CW_WW, "WW" },

"Color Switch RGBWW"

Or drop the switch and call it "Color RGBWW" or just "RGBWW" like above.
It is actually labeled "RGBWW" in the GUI

**Comment by pipiche38** [comment]
It makes sense. Can you help me and provides a .vscode for domoticz, as it looks like mine which is more appropriate for python is changing a lot of stuff and makes the PR not good

**Comment by gizmocuz** [comment]
You can use Visual Studio (community edition is fine)
But you can make the changes and commit/push them and they will show up here

**Comment by gizmocuz** [comment]
Not sure what happened, but you have reformatted the complete code layout (please have a look here under files changed)

**Comment by pipiche38** [comment]
Wiki udpated accordingly https://www.domoticz.com/wiki/Developing_a_Python_plugin

**Comment by pipiche38** [comment]
> Not sure what happened, but you have reformatted the complete code layout (please have a look here under files changed)

that is my issue, I was wondering if you have a special .vscode with specific format, as mine is more aligned with what I'm doing on python
I found that you are using tab as 8 , but looks like they are so different things

**Comment by gizmocuz** [comment]
That's correct. For c++ (and all other languages then python/js I think...) it's 8 ;)
Looking great not! Thanks for the PR!
Later today I will make new beta versions as I found (hopefully) a small error JS error when changing the room plan (at least in the switches tab)

**Comment by gizmocuz** [comment]
New beta's are available

**Pull request merged**
