### PR TITLE
added support for Legrand/Bticino openwebnet : blinds via ip gateway

### PR DESCRIPTION
**Pull request by steplebr**
Hello,
I've created a new hardware for Legrand/Bticino Openwebnet IP gateway. As I own blinds, I've implemented blind control with the gateway.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this great patch!
Could you change the following to a pTypeGeneralSwitch/sSwitchBlindsT1

{ pTypeBlinds, sTypeBlindsT12, "Legrand MyHome" },

and if possible change the source comments to English ?

**Comment by gizmocuz** [comment]
Our build system have some compile issues, please check below

**Comment by steplebr** [comment]
I've corrected the problems you mentioned.

**Comment by gizmocuz** [comment]
Thanks!! Thanks for this great addon!
I read we maybe could also use this for KNX systems? (i got some few gira hardware (dutch)) working with a bus system

**Comment by steplebr** [comment]
The difference between KNX and Openwebnet is that Openwebnet has been designed to be simple while KNX is quite complicated. KNX bus can be accessed via different gateways, IP (using KNXNet protocol, which is KNX tunneling) or USB. However, KNXNet is not publicly documented. There is still a java project that uses KNXNet, it is called Calimero (https://github.com/calimero-project/calimero-core).
Some other home automation projects may use proxies : eibnetmux (http://eibnetmux.sourceforge.net/, it exposes a tcp socket protocol and a C client api) or eibd (exposes a tcp protocol, used by jeedom https://domotiga.nl/projects/domotiga/wiki/KNX and domotiga https://domotiga.nl/projects/domotiga/wiki/KNX).

**Pull request merged**
