### PR TITLE
Protect multimeter sValue values conversions (fix for #4568)

### PR DESCRIPTION
**Pull request by rwaaren**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the PR.
I like my commit better as it is consistent with the way the 'meter' catches the exception (it will use 0 for the values)
functions like atof/atoi/atol do not throw exceptions but returns 0 in case of invalid data

**Comment by rwaaren** [comment]
The reason why I did not use 0 was that the code then converts an invalid value into a valid value ( 0 ) Probably a matter of opinion but in this case I would prefer to have no value at all. 
Anyway; most important is that a potential crash is prevented and I learned something new today.

Maybe I overlook something but in your commit the other devicetypes ( pTypeCURRENT and pTypeCURRENTENERGY)
are not protected. Is that with a specific reason?

**Comment by gizmocuz** [comment]
The default behavior is to return 0, so this is simulating the default atol/atoi/atof commands now (same as the meter)
 That is correct, as mentioned atoi/atof/atol do not throw execptions

**Comment by rwaaren** [comment]
OK. Understand now. Thx for explaining !

**Pull request closed without merging**
