### PR TITLE
Added TSL2561 illuminance I2C sensor

### PR DESCRIPTION
**Pull request by ldrolez**
Please forget my previous pull since it was done on my master branch.

### CODE REVIEW

**Comment by ldrolez** [comment]
I've added local I2C grouping also. All sensors with a description begining with "Raspberry I2C sensor" will no longer appear in the main combo box.

**Comment by gizmocuz** [comment]
Thank you for this !!
One small request, i would expect this to run on other hardware as well (Cubieboard,ODroid,Pine64,... etc), as the libraries being used are from the linux kernel, and it is not using raspberry dedicated stuff
If thats correct, Maybe rename 'raspberry' to 'Local' ? Or 'System' ? or another name ?

**Comment by ldrolez** [comment]
Yes, sure, maybe Local is clearer?

**Comment by gizmocuz** [comment]
Sounds perfect ;)

**Comment by ldrolez** [comment]
also how do you handle i18n? :)

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
Via the site transifex, english file is the main file, best to PM me changes in there

**Comment by gizmocuz** [comment]
Seems there is a possible compile problem
https://github.com/domoticz/domoticz/issues/791

**Pull request merged**
