### PR TITLE
Fix selector buttons state on device refresh

### PR DESCRIPTION
**Pull request by gaudryc**
Fix selector buttons state on device refresh (due to a jqueryui bug) by unselecting all buttons and removing "active" style (ui-state-active or ui-state-focus class).

### CODE REVIEW

**Comment by ghost** [comment]
After this update all is crash
selector
. No icon and no level and no action to level

**Comment by gaudryc** [comment]
Please create one issue in "Issues" because you have posted three messages in three different places.

**Comment by PiterEL** [comment]
Ok i create issue #320

**Comment by ghost** [comment]
Ok i clear cache browser and works ok.
But tell me is any chance to add mixed type with slider dimmer and buttons ? Is anyu chance to you create it in next patch ?

**Comment by gizmocuz** [comment]
Welcome to 'PiterEL', i get sometimes 10 to 15 emails a day

**Comment by gaudryc** [comment]
@PiterEL 

No I will keep it as simple as it is. You should know that the UI is simple but the code is not, therefore I don't want to make things more complicated just for one person.
I'm sorry but I already tell you that you need something specialized.

**Comment by gaudryc** [comment]
@gizmocuz 

Do you know if someone is planning to develop a virtual device which acts as a media player (with source control, volume control, mute control) ?

**Comment by gizmocuz** [comment]
@gaudryc 
i think there is already on inside domoticz (kodi player)

**Comment by ghost** [comment]
But many user use AV Reciver like Denon, Onkyo and other and want control it by Domoticz.

**Pull request merged**
