### PR TITLE
[OpenWeatherMap] Done

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by gizmocuz** [comment]
it seems some people have issues with the current openweathermap implementation.
There system crashes after a few seconds, i think when the first request is made
Maybe you've seen it on the forum also...

could this have todo with these changes ?

**Comment by szczukot** [comment]
Ok. I'll check it. Where is about the error, at the forum ?

**Comment by gizmocuz** [comment]
Sorry... For example 
http://www.domoticz.com/forum/viewtopic.php?f=6&t=12777

**Comment by szczukot** [comment]
I tested it many times with many configurations - its works :(
But i only tested under windows. Maybe under linux is problem ? I will test it.

**Comment by szczukot** [comment]
i trying buld domoticz under rpi2 but i have error:
[ 24%] Building C object lua/src/CMakeFiles/lua.dir/lzio.c.o
Linking C static library liblua.a
Linking C static library libsqlite.a
[ 24%] Built target lua
[ 24%] Built target sqlite
CMakeFiles/domoticz.dir/depend.make:127145: warning: NUL character seen; rest of line ignored
CMakeFiles/domoticz.dir/depend.make:127145: **\* missing separator (did you mean TAB instead of 8 spaces?).  Stop.
CMakeFiles/Makefile2:64: recipe for target 'CMakeFiles/domoticz.dir/all' failed
make[1]: **\* [CMakeFiles/domoticz.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: **\* [all] Error 2

**Pull request merged**
