### PR TITLE
Fix lost domoticz.js changes for Panasonic Remote

### PR DESCRIPTION
**Pull request by sijones**

### CODE REVIEW

**Comment by sijones** [comment]
Looks like changes have been lost due to it being a compressed file and a compare can't be done so someone else could have checked in an older version and overwritten my changes. 

Not sure if there is something we can do to stop this from happening?

**Comment by nayrnet** [comment]
yeah I thought the same thing, perhaps we store those files uncompressed here on github and then have the build scripts re-compress them? storing compressed and uncompressed side by side might be a problem though.

**Comment by sijones** [comment]
I think that would be a lot better idea!

**Comment by gizmocuz** [comment]
Your right, that probably wont be an easy job
At the moment when there are multiple PR against the domoticz js file, this goes wrong

We also have to do this on travis/appveyor

**Comment by gizmocuz** [comment]
merged, new js file will be committed soon

**Pull request merged**
