### PR TITLE
[USBtin/Multibloc V8] - IBS integration with Bloc 9

### PR DESCRIPTION
**Pull request by ghost**
Add now possibility to read information of IBS (Hella) 12 or 24V to manage battery park (up to 6 IBS on each bloc 9). IBS can return multiple information, see screenshot 
image
IBS must be correctly set before use (hence the feedback of IBS settings)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you again for this PR!!

**Comment by waltervl** [comment]
@Reivax851 Is it somewhere documented what is does? I believe it is an implementation for a USB CAN Bus interface and now you made an enhancement for an  IBS (Hella)?

**Comment by ghost** [comment]
This implementation enable user to connect and read all data's from IBS sensor on a Bloc 9 (IBS works on Lin bus, the Lin bus is supported by some bloc in the Scheiber network, like Bloc 9 now supported in Domoticz and Bloc 7). Before use, it supposed to be correctly configure). This is a link to the official manual: https://cfb5c11b-afd4-42e4-a2ba-1497db9ff2d7.filesusr.com/ugd/084c74_97e81dcda19f40689e553001f6a52eec.pdf but for usage/configuration. This manual will help you to understand.

**Comment by waltervl** [comment]
I am busy in updating the Wiki in order to have better documentation for all domoticz users. I never heard of the USBTin hardware. there is no reference in the Wiki. I see a topic https://domoticz.com/forum/viewtopic.php?f=38&t=17726 where you introduced it.
Is it possible to give a short description of the complete USBtin implementation (including the latest modification in beta)?
If you have no wiki account please add it to the forum topic and I will put it into the wiki.

**Comment by ghost** [comment]
Ha, Yes I like to explain as best as possible all I do, I send you a PM on the forum. thanks

**Comment by waltervl** [comment]
@gizmocuz can you make a wiki account for @Reivax851 ? We contacted you trough forum PM also....

**Comment by gizmocuz** [comment]
@waltervl , @Reivax851 , I created the account and replied the PM
Best to use the Domoticz Slack channel

**Pull request merged**
