### PR TITLE
Update domoticzdevices.js - fix P1 meter on floorplan when meter has usage delivery (return usage)

### LINKED ISSUE #5888: P1 meter smallStatus on Floorplan is still looking odd once there is delivery/return
P1 meter smallStatus on Floorplan is still looking odd once there is delivery/return usage
image

_Originally posted by @martin-g-it in https://github.com/domoticz/domoticz/issues/5884#issuecomment-1819111255_

Same applies also to the dashboard:
image

With just return it looks like this on the dashboard:
image

And like this on the floorplan:
image

### PR DESCRIPTION
**Pull request by martin-g-it**
Fix P1 meter (counter) on floorplan when meter has usage delivery (return usage)

See issue https://github.com/domoticz/domoticz/issues/5888

### CODE REVIEW

**Comment by martin-g-it** [comment]
Added the comma to the status

image
in line with dashboard:
image

**Comment by gizmocuz** [comment]
Thanks for the PR. When this happens, how does the P1 widget on the dashboard looks like?

**Comment by martin-g-it** [comment]
> Thanks for the PR. When this happens, how does the P1 widget on the dashboard looks like?

With both actual usage and actual return it looks like the above screenshot
>  in line with dashboard: 
image

Device status like this:
image

-----------------

With 0 usage and eg. 456 Watt return like this:
image

Device status like this:
image

-----------------

To complete; with 123 usage and 0 return:
image

Device status like this:
image

-----------------
I just made one more adjustment to align the **floorplan popup** with the dashboard in case of 0 usage, 456 return (also added the various smallstatus for the floorplan for completeness:
image
image

-----------------

With 123 / -456
image
image

-----------------

With 123 / 0
image
image

**Comment by gizmocuz** [comment]
Thanks for this ! Looking great now!

**Comment by gizmocuz** [comment]
Thank you for this PR and your time! Going to solve this also in the Dashboard/Utility tab

**Comment by martin-g-it** [comment]
I think for the dashboard it looks OK (it is aligned with the popup).
On that popup/dashboard there is enough space to show both the usage and return in case both apply.

Dashboard:
image

Floorplan popup:
image

For the floorplan smallstatus, it makes more sense to balance them like done (and get the full info when you hover over it).

**Comment by gizmocuz** [comment]
true, but it looks a bit wierd, but these are indeed the actual values reported by the meter.
Okey leaving it like it is ;)

**Pull request merged**
