### PR TITLE
Decode, display and store Evohome DHW Setpoint

### PR DESCRIPTION
**Pull request by brucemiranda**
The only bit that I cannot figure out how to do is when the EditState window is called, how to default the State to "On" when the Set point is set to a numeric value other than 60C

### CODE REVIEW

**Comment by brucemiranda** [comment]
OK this PR can be merged. The lack of a Default doesn't affect the functionality.

**Comment by Olifant1990** [comment]
This fixed the bug in https://github.com/domoticz/domoticz/issues/3861

**Comment by brucemiranda** [comment]
@gizmocuz any reason why this PR hasn't been merged yet?
It's a feature that quite a lot of Evohome users have asked for.

**Comment by gizmocuz** [comment]
@brucemiranda , Not sure, but it seems fixed by the comment of Olifant1990 ?

What is the deal in

SQLHelper::UpdateTemperatureLog()

If On/Off then 0 or 60 ?
For example on my heating system the DHW value is 75, so a SetPoint above 60 is valid
Can't see in the code where there is a check for 60 or 0, is it in the Gui/Graph code ?
Another way is to use a Switch for the On/Off state ?

Happy to merge, but just need to be sure if it is fixed already

**Comment by Olifant1990** [comment]
@gizmocuz sorry, with "this fixed the bug in 3861" I meant to refer to the originating bug ticket.

I did not test it, but wrote it to connect the dots/history ;)

**Comment by brucemiranda** [comment]
> @brucemiranda , Not sure, but it seems fixed by the comment of Olifant1990 ?
> 
> What is the deal in
> 
> SQLHelper::UpdateTemperatureLog()
> 
> If On/Off then 0 or 60 ?
> For example on my heating system the DHW value is 75, so a SetPoint above 60 is valid
> Can't see in the code where there is a check for 60 or 0, is it in the Gui/Graph code ?
> Another way is to use a Switch for the On/Off state ?
> 
> Happy to merge, but just need to be sure if it is fixed already

@gizmocuz Before this change Evohome DHW used to only use ON and OFF states. However within the db, ON was being stored as 60C and OFF was 0C. What the change now does is if there is a value besides ON or OFF, then it uses the actual value to update the database. So in your example if the DHW setpoint is 75C it would store 75C. The code just keeps the old functionality still working, where ON and OFF were set to hard coded values. BTW : OFF is still stored as 0C, which is correct.

**Comment by gizmocuz** [comment]
@brucemiranda , thank you for the explanation. Do we still need the old functionality ? It seems you rebuild it and it is now obsolete?

**Comment by brucemiranda** [comment]
> @brucemiranda , thank you for the explanation. Do we still need the old functionality ? It seems you rebuild it and it is now obsolete?

Probably best to keep the old functionality for a while. We can phase it out in time.

**Comment by gizmocuz** [comment]
Thanks!!

**Pull request merged**
