### PR TITLE
Update NotificationPushsafer.cpp

### PR DESCRIPTION
**Pull request by appzer**
add new [Pushsafer](https://www.pushsafer.com) parameter, priority, retry, expire, answer

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the PR.
The priority is already in the function call (SendMessageImplementation)

If you check above for 'if (splitresults.size() == 11)', are you sure you can do 'std::string PS_a = splitresults[14];'

Is this verified ?

How are you using this ?

**Comment by appzer** [comment]
the priority in SendMessageImplementation is not needed i delete it.
All other is OK!

**Comment by gizmocuz** [comment]
@appzer , no you can not do this, and you should use this if you want to use the priority in the message system.
This priority can be set on various places in Domoticz.
How are you using the other fields ?
I do not think are checking the code changes you are pushing as they contain build errors, and also the split size was incorrect in your initial post.
Please be carefull

**Comment by appzer** [comment]
OK, the priority func I have involved again.
The split size adjusted to 15
All the parameter are send to the Pushsafer API to generate a push-notification based on the [API](https://www.pushsafer.com/en/pushapi)

Now it works fine!

**Comment by gizmocuz** [comment]
@appzer , yes i believe it does,  but 'how' are you using it with domoticz?
How do you use the 'answer' or the 'retry' or expire ?

**Comment by appzer** [comment]
here a documentation to use the pushsafer plugin in domoticz
[https://www.pushsafer.com/en/domoticz](https://www.pushsafer.com/en/domoticz)

**Comment by gizmocuz** [comment]
@appzer , thanks for the documentaton. Maybe this can de added to our wiki page.
But these 4 parameters Priority|Retry|Expire|Answer are optional, and do not needed to be send
It will probably also break the implementation for current users, who do not use the optional 3 parameters
Because of this, i would say, if size()>11 (meaning 12 or higher) then we can use the Retry, if size()>12, we have the Expire, if size()>13 the user entered the answer

In the documentation, the priority can be removed as this can already be specified in the userinterface/script

**Comment by appzer** [comment]
i changed the documentation and also the plugin.
Now the domoticz priority are passed throught the pr parameter of pushsafer.

I also changed the split size to >=11, so user with new and older domoticz version can work with parameters.

Kevin

**Comment by gizmocuz** [comment]
You have some strange code here

```
if (PS_m.length() >= 1)
		{
		}
		else
		{
			PS_m = Text;
		}
```

Do we need those extra parameters at all ? Just that it is possible, does not mean it is useful right ?

**Comment by appzer** [comment]
@gizmocuz  it is ok so, yes many domoticz customers want the new parameter.

**Comment by gizmocuz** [comment]
Sure thats not OK code, maybe you mean this:

```
if (PS_m.empty())
{
	PS_m = Text;
}
```

Please point me to some references where uses want these parameters please

**Comment by appzer** [comment]
i fix the code.
I got many mails from domoticz users, they ask me, when i implement the new pushsafer parameters.
especially the priority parameter, because domoticz also handle this.

Kevin

**Comment by gizmocuz** [comment]
But the sendmessage implementation had already a priority field.
You can use this.
So if the other parameters are not needed, please only implement the priority

**Comment by appzer** [comment]
@gizmocuz 
i only use the implement priority.
`const int Priority`
The other 3 new pushsafer parameters also needed.
Why it is wrong to add them!

Kevin

**Comment by gizmocuz** [comment]
@appzer , first, as no other pusher implement these new tree actions, not is there any facility to invoke these actions straight from domoticz without using a third party script.
Next, i do not see any use of these tree new actions, and have not seen any post that people desperately need them.
And it's not the best code practice. 
So it you would like to see the priority added, please undo the other changes, or create a new PR with only the priority option.
Or please show me (like asked before) the forum thread where many people are requesting the other tree options

**Comment by appzer** [comment]
@gizmocuz  I get the requests to add the new parameters via email, for privacy reasons, I can not post complete emails here.

Priority, Retry and Expire are really needed.

With retry and expire the user has the possibility to resend notifications in a given time > independent of domoticz or other platforms. It is really usefull.

What part it's not the best code practice? I already changed the if clauses to .empty().

I ask you to release this changes

Thanks Kevin

**Comment by gizmocuz** [comment]
Okey Kevin, first things first, i do not need to accept any pull requests.
But i am willing to consider them, if i think they are correct.
So, going back to my question then, please submit a new PR with the priority implementation

Next we can discuss (here, on on slack in a private channel), why you need retry and expire, and how this will be implemented in domoticz.
As you say it is requested on the forum, show me a link for that

**Comment by appzer** [comment]
@gizmocuz 
OK, i update the PR and added only the priorty value.
How we can discuss it on a private way here?

Kevin

**Comment by gizmocuz** [comment]
Thanks! , Feel free to join https://domoticz.slack.com

**Comment by appzer** [comment]
@gizmocuz  thanks for merging!
How i can create an domoticz slack account?

**Comment by gizmocuz** [comment]
Good question, i need your email address for that. Can you send me a PM on the forum ?

**Comment by appzer** [comment]
@gizmocuz is sent out

**Pull request merged**
