### PR TITLE
Add multiply field to UVI widget

### PR DESCRIPTION
**Pull request by IanDury**
UV sensors are typically very sensitive to aging.  Often this can be calibrated with a gain correction applied to the receiving weather station. This PR provides a solution to apply a gain correction to the Domoticz UVI widget.

image
image

### CODE REVIEW

**Comment by kiddigital** [comment]
Hi @IanDury , could you provide some description for this PR and a few screenshots so it is more clear why and what this PR does? Thx

**Comment by IanDury** [comment]
Wrote description as requested

**Comment by gizmocuz** [comment]
@IanDury , thank you for this PR and your time.
As you have seen, there are also UVI sensors that contains a temperature sensor.
Currently it is already possible to have a temperature correction, and this was done in the normal adjustment/multiply
In your PR I see you now assume that this is done with "GetAddjustment2", but that is not correct.
In your case, you do want to have the adjustment for the UVI to be in these fields and leave the 'GetAddjustment' for the temperature.
When you update the UVI sensor you need to use 'addjmulti2' instead of 'addjmulti' and use GetAddjustment2 in your code

**Comment by IanDury** [comment]
I assumed GetAddjustment and GetAddjustment2 were identical and should be used in order of appearance.
Now using GetAddjustment2 and addjmulti2 for UVI multiply.

**Comment by kiddigital** [comment]
@IanDury , thx for the update but shouldn't the UI update call also not be modified to store the multiplier into the addjmulti2 instead?

**Comment by IanDury** [comment]
You're right. Overlooked this.

**Comment by kiddigital** [comment]
Thanks!

**Pull request merged**
