### PR TITLE
Fix MQTT AutoDiscover device vs. sensor name confusion

### PR DESCRIPTION
**Pull request by dwmw2**
In MQTT AutoDiscovery, many sensors can be attached to a single "device". The device doesn't have an MQTT topic of its own; it is reported as a property of each sensor, e.g.:
```
   "dev" : {
      "cns" : [
         [
            "mac",
            "782184bb134c"
         ]
      ],
      "ids" : "782184bb134c",
      "mdl" : "esp32-gateway",
      "mf" : "Espressif",
      "name" : "bathroom",
      "sw" : "2024.9.0-dev (Sep  6 2024, 22:54:39)"
   },
```
During sensor discovery, we look for an existing device with the same 'ids' and use that if it exists, otherwise we create a new one. We keep track of which sensors are attached to which device, for matching up things like electricity power/usage and temp/hum/baro sensors.

However, as we discover each sensor and work out what its name should be, we *overwrite* the name of the device it's attached to. So the device ends up bearing the name of the last sensor that happens to be discovered on it.

Clean that up, to set the device name using only information about the device itself, and then set the sensor name as before.

This shouldn't make any difference to the sensor names, *except* for the combined Temperature/Humidity/Barometer devices which are later synthesised based on the device name. That's the only time the device name actually gets used.

Fixes: 6164

### CODE REVIEW

**Comment by gizmocuz** [comment]
Sorry but this goes still wrong. For instance with light devices.

_homeassistant/switch/0x00158d000217ac86/switch/config_

`{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/WCD_Master_Bedroom/set","device":{"identifiers":["zigbee2mqtt_0x00158d000217ac86"],"manufacturer":"Innr","model":"Smart plug (SP 120)","name":"WCD_Master_Bedroom","sw_version":"2.0","via_device":"zigbee2mqtt_bridge_0x00124b0021cc4112"},"json_attributes_topic":"zigbee2mqtt/WCD_Master_Bedroom","name":null,"object_id":"wcd_master_bedroom","origin":{"name":"Zigbee2MQTT","sw":"1.40.1-dev","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/WCD_Master_Bedroom","unique_id":"0x00158d000217ac86_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}
`

Seems you do not take over the Name....

How many Zigbee devices do you have? Maybe post a complete config topic/payload for a device that goes wrong on your end, and I try to solve it.
Otherwise, we better close these PR's, as there should be no issue and all is working good for 90% of the users

**Comment by dwmw2** [comment]
Thanks. I'll take a look and see what I got wrong. What *was* the name your sensor got, and what name is it getting now?

The config topics for the MQTT "device" (one `_TMQTTADevice` with three_`tMQTTASensor`s,) are posted in #6164.

The problem is that each time a *sensor* is processed, the code updates the name on the *`_TMQTTADevice`* to match the name of that *sensor*. As Domoticz processes the three sensors, it *changes* the name of the underlying `_TMQTTADevice` each time. So when it's finished, the name of the `_TMQTTADevice` (to which all of the sensors and switches are attached) is left as "`toilet (Blue LED)`".

Then Domoticz gets readings for the temperature and humidity devices, and creates a new sensor based on the name of the `_TMQTTADevice` ... which is why the combined Temp+Hum sensor ends up with the wrong name. (Creating these combined Temp+Hum+Baro sensors is the only time Domoticz will ever *use* the name from the `_TMQTTADevice`, I think).

The `_TMQTTADevice` name should never have anything about any individual *sensor* that was found on it.

In this patch I thought I'd left the actual sensor names being generated precisely the same as before, just without overwriting the `_TMQTTADevice` name each time. I'll check...

**Comment by dwmw2** [comment]
```
${mqtt_prefix}/homeassistant/sensor/toilet/device_info/config {"name":"Device Info","ic":"mdi:chip","ent_cat":"diagnostic","stat_t":"toilet/sensor/device_info/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-eff5da39","obj_id":"toilet_device_info","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/reset_reason/config {"name":"Reset Reason","ic":"mdi:restart","ent_cat":"diagnostic","stat_t":"toilet/sensor/reset_reason/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-2a9f2c0a","obj_id":"toilet_reset_reason","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/heap_free/config {"unit_of_meas":"B","name":"Heap Free","ic":"mdi:counter","ent_cat":"diagnostic","stat_t":"toilet/sensor/heap_free/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-acee5b6b","obj_id":"toilet_heap_free","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/loop_time/config {"unit_of_meas":"ms","name":"Loop Time","ic":"mdi:timer-outline","ent_cat":"diagnostic","stat_t":"toilet/sensor/loop_time/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-8a395f6a","obj_id":"toilet_loop_time","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/uptime/config {"dev_cla":"duration","unit_of_meas":"s","stat_cla":"total_increasing","name":"Uptime","ic":"mdi:timer-outline","ent_cat":"diagnostic","stat_t":"toilet/sensor/uptime/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-uptime","obj_id":"toilet_uptime","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/toilet_temperature/config {"dev_cla":"temperature","unit_of_meas":"°C","stat_cla":"measurement","name":"Toilet Temperature","stat_t":"toilet/sensor/toilet_temperature/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-a6f8b010","obj_id":"toilet_toilet_temperature","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/toilet_humidity/config {"dev_cla":"humidity","unit_of_meas":"%","stat_cla":"measurement","name":"Toilet Humidity","stat_t":"toilet/sensor/toilet_humidity/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-af5adc1d","obj_id":"toilet_toilet_humidity","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/switch/toilet/fan/config {"name":"Fan","stat_t":"toilet/switch/fan/state","cmd_t":"toilet/switch/fan/command","avty_t":"toilet/status","uniq_id":"48e729b53a18-switch-46414960","obj_id":"toilet_fan","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/light/toilet/blue_led/config {"schema":"json","clrm":true,"supported_color_modes":["onoff"],"name":"Blue LED","stat_t":"toilet/light/blue_led/state","cmd_t":"toilet/light/blue_led/command","avty_t":"toilet/status","uniq_id":"48e729b53a18-light-6a29e1c2","obj_id":"toilet_blue_led","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}

```

**Comment by gizmocuz** [comment]
Okey, so the only interesting sensors are

```
${mqtt_prefix}/homeassistant/sensor/toilet/toilet_temperature/config {"dev_cla":"temperature","unit_of_meas":"°C","stat_cla":"measurement","name":"Toilet Temperature","stat_t":"toilet/sensor/toilet_temperature/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-a6f8b010","obj_id":"toilet_toilet_temperature","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/sensor/toilet/toilet_humidity/config {"dev_cla":"humidity","unit_of_meas":"%","stat_cla":"measurement","name":"Toilet Humidity","stat_t":"toilet/sensor/toilet_humidity/state","avty_t":"toilet/status","uniq_id":"48e729b53a18-sensor-af5adc1d","obj_id":"toilet_toilet_humidity","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/switch/toilet/fan/config {"name":"Fan","stat_t":"toilet/switch/fan/state","cmd_t":"toilet/switch/fan/command","avty_t":"toilet/status","uniq_id":"48e729b53a18-switch-46414960","obj_id":"toilet_fan","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
${mqtt_prefix}/homeassistant/light/toilet/blue_led/config {"schema":"json","clrm":true,"supported_color_modes":["onoff"],"name":"Blue LED","stat_t":"toilet/light/blue_led/state","cmd_t":"toilet/light/blue_led/command","avty_t":"toilet/status","uniq_id":"48e729b53a18-light-6a29e1c2","obj_id":"toilet_blue_led","dev":{"ids":"48e729b53a18","name":"toilet","sw":"2024.9.0-dev (Sep  6 2024, 22:49:20)","mdl":"esp32-gateway","mf":"Espressif","cns":[["mac","48e729b53a18"]]}}
```

They all have a normal name, you say this is not working?

**Comment by dwmw2** [comment]
> They all have a normal name, you say this is not working?

Right. All of those *sensors* are attached to the *same* MQTT "device", this one:
```
   "dev" : {
      "cns" : [
         [
            "mac",
            "48e729b53a18"
         ]
      ],
      "ids" : "48e729b53a18",
      "mdl" : "esp32-gateway",
      "mf" : "Espressif",
      "name" : "toilet",
      "sw" : "2024.9.0-dev (Sep  6 2024, 22:49:20)"
   },
```

Every time we process one of those sensors (or lights or switches), we look up the same `_tMQTTADevice` object, and re-use it rather than creating a new one:
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L731-L738

Each time, we scribble over its name and set it to the same as the name as the sensor that's being processed. So at the end, the `_tMQTTADevice` is left with the name of the last sensor (or switch or light, etc). that was discovered on it.

This *mostly* doesn't matter because nobody ever uses the name of the underlying `_tMQTTADevice`.... except *one* place where we use it, when we're creating the combined Temp+Hum+Baro sensor:
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L2520

And that's why I end up with a Temp+Hum sensor named "toilet (Blue LED)".

**Comment by gizmocuz** [comment]
As mentioned this still goes wrong with most if the names I get from z8gbee2mqtt
If you only have sensor than please just named it manually

**Pull request closed without merging**
