### PR TITLE
add resilience to RGBWW API calls and add actualWatt attribute (= WhActual)

### PR DESCRIPTION
**Pull request by rwaaren**
```
========= domoticz V4.11535, dzVents V2.5.2 =======+========================== Tests ==============================+
  time  | test-script                              | expected | tests | result  | successful |  failed  | seconds  |
===================================================+===============================================================+
00:00:02  Device                                        1        115      OK            115         0      0.5664
00:00:03  Domoticz                                      1         70      OK             70         0      0.5090
00:00:03  EventHelpers                                  1         32      OK             32         0      0.4816
00:00:04  EventHelpersStorage                           1         50      OK             50         0      0.4560
00:00:05  HTTPResponse                                  1          6      OK              6         0      0.0248
00:00:05  ScriptdzVentsDispatching                      1          2      OK              2         0      0.1105
00:00:05  TimedCommand                                  1         42      OK             42         0      0.1725
00:00:05  Time                                          3        326      OK            326         0      1.2167
00:00:07  Utils                                         1         19      OK             19         0      0.0616
00:00:07  Variable                                      1         15      OK             15         0      0.0552
00:00:07  ContactDoorLockInvertedSwitch                 3          2      OK              2         0      3.1251
00:00:10  DelayedVariableScene                          8          2      OK              2         0      7.1260
00:00:17  EventState                                   19          2      OK              2         0     18.1409
00:00:36  Integration                                  33        217      OK            217         0     31.6969
00:01:07  SelectorSwitch                               10          2      OK              2         0      9.4225

Total tests: 902
Tue 26 Nov 2019 10:48:55 PM CET; dzVents version 2.5.2 tested without erors after 00:01:17
```

	modified:   History.txt
	modified:   dzVents/documentation/README.md
	modified:   dzVents/documentation/README.wiki
	modified:   dzVents/documentation/history.md
	modified:   dzVents/runtime/Utils.lua
	modified:   dzVents/runtime/device-adapters/electric_usage_device.lua
	modified:   dzVents/runtime/device-adapters/kwh_device.lua
	modified:   dzVents/runtime/device-adapters/p1_smartmeter_device.lua
	modified:   dzVents/runtime/device-adapters/rgbw_device.lua
	modified:   dzVents/runtime/misc/testdzVents.sh
	modified:   dzVents/runtime/tests/testDevice.lua
	modified:   main/dzVents.cpp

### CODE REVIEW

**Comment by gizmocuz** [comment]
You  ould also remove this brightness call as you can not set it to a fixed brightness
It's of no use to use it?

**Comment by rwaaren** [comment]
> You could also remove this brightness call as you can not set it to a fixed brightness
> It's of no use to use it?

It's of limited use but does work as designed for Yeelights. It increase / decease the brightness with about 10%.  For some reason the Yeelight state is set after a couple of seconds (kind of polling I assume)  and therefore do not suffer from the issue I see on other RGBWW types.

**Comment by gizmocuz** [comment]
@rwaaren , I am not fond of using hardware that you can not program to a fixed value.
For instance there is hardware where you can only 'Toggle' the on/off status, you can not use this in timers or scripts, you have no idea what the current state will be when you 'toggle' something
Same for devices where you can brightness up/down ... you have no idea what the current brightness is, if you can turn it up, if it is already on the highest brightness, or when you turn it up, it is still to low
Yes YeeLight also supports 'Disco' mode .... yeah ....

**Comment by rwaaren** [comment]
@gizmocuz, It is not my cup of tea either but the developer who created the Yeelight.cpp put the functions  in and I don't think it is for me to remove them.
dzVents is just providing an easy to use API to the functions and I added some resilience to the dzVents methods to ensure they can only be used for the Yeelight hardware. I hesitate to remove them from dzVents completely because it will break user scripts that implemented it and in my opinion it will not harm anything if we leave it in until these functions have been removed from Yeelight.cpp

**Comment by gizmocuz** [comment]
@rwaaren , i think this was created/added before dzVents, and i think it could have been me as well..
That does not mean that 'every' json/api call should be available through dzVents..

**Comment by rwaaren** [comment]
> That does not mean that 'every' json/api call should be available through dzVents..

@gizmocuz , I agree on that part; it was already in when I started with dzVents. 
I still think we should leave it in but if you want to have it out I will do so. and make a new PR.

**Pull request closed without merging**
