### PR TITLE
Fix issue with timer events not initialized in SetSunRiseSetTimers

### PR DESCRIPTION
**Pull request by ghost**
Load the allTimes array with pointers instead of values as discussed [here](https://github.com/domoticz/domoticz/pull/1998).

Thanks to @gordonb3 for drawing my attention to this issue!

### CODE REVIEW

**Comment by ghost** [comment]
The Travis CI build could not complete says: The job exceeded the maximum time limit for jobs, and has been terminated. I can't restart that check.

**Comment by toaomatis** [comment]
Why is this PR still pending?

I'm experiencing serious difficulties due to this issue.

**Comment by pierrenicolasr** [comment]
Yeah, would be nice to have this issue fixed - fake modules based on sunset / sunrise are not updated as expected anymore.

**Comment by a3vd** [comment]
Issue still not solved, sunset sunsrise, or even the at time timer not working properly.

No problems before , the problem started after the daylength issue :-(

**Comment by ghost** [comment]
@a3vd Have you applied this PR to your local repo? As you know, this PR is still pending  waiting to be merged into domoticz:development

**Comment by a3vd** [comment]
am using domtociz for years with timers no problems until the update of the length of daytime i can not use timers anymore.
this is a major issue not a simple bug

**Comment by jvanderzande** [comment]
@a3vd, No this is a development/beta branch that has an bug which is recognized and still needs to be merged. Since this is Beta, there is no way this can be major as Beta shouldn't run on a production system without an option to rollback to any stable previous version. So your options are:

1. Rollback to your latest backup of your stable setup.
2. Checkout the appropriate github branch, apply the patch yourself and compile.
3. Wait till the new Beta is produced after this patch is merged.

**Comment by a3vd** [comment]
allright ill wait until the bug is patched no problem !

**Comment by chrisverhoef** [comment]
Tested the proposed fix: Load the allTimes array with pointers instead of values. This solves the issue of not working timers based on Sunset and Sunrise

**Comment by ghost** [comment]
Sounds great @chrisverhoef 

Let's hope that someone will merge it soon.

**Comment by dannybloe** [comment]
Thanks :)

**Pull request merged**
