### PR TITLE
Added parameters to log line, in case a script is executed (for examp…

### PR DESCRIPTION
**Pull request by djoele**
…le when switching a light)

### CODE REVIEW

**Comment by gizmocuz** [comment]
That does not seem a good idea as sValue is used for various things.
(and can also be private)

the script ID (a string/name) is already displayed

**Comment by djoele** [comment]
Alright, then it is best to close this pull request.

**Comment by gizmocuz** [comment]
if something is not clear at all with the 'ID' that is logged, maybe best to change it on those places.
But from what i see, this is already done very good

**Comment by djoele** [comment]
Agree to keep the log the way it is.
Already was able to see that the scripts that I want to execute with On/Off action are executed the right way.

---

Perhaps it is better if I describe what I wanted to achieve:
1. I have configured a switch with an On and Off action
2. The On action for example is: script:///home/pi/domoticz/swith.sh 1234
3. The Off action for example is: script:///home/pi/domoticz/swith.sh 4321
4. This shell script takes one argument: the code to send (so in this case, 1234 or 4321)

Now the following appears in the log file for either action: 
'Executing script: /home/pi/domoticz/swith.sh'

To be able to figure out exactly what was trigger, it would be good to have the following log lines:
'Executing script: /home/pi/domoticz/swith.sh 1234'
'Executing script: /home/pi/domoticz/swith.sh 4321'

**Pull request closed without merging**
