### PR TITLE
Change icon in menu logout

### PR DESCRIPTION
**Pull request by pp1984**
Looks better. Now icon logout and shutdown is very similiar. My icon is
better loook.

### CODE REVIEW

**Comment by pp1984** [comment]
Hi
I also change icon devices, settings and add new icon for update.

**Comment by pp1984** [comment]
Screenshot after changes:
screen

screen2

**Comment by gizmocuz** [comment]
I like  my icons more!

**Comment by pp1984** [comment]
But some menu have no icon. Maybe only this icon you can add ?

After analysis I see that a lot of reports from users about appearance and style do not want to accept. So if the project is closed?

**Comment by gizmocuz** [comment]
Yes

**Comment by pp1984** [comment]
Not good. But OK. 
And why some menu have no icon ?
But i dont understand why is on GitHub if is close ?

**Comment by nayrnet** [comment]
make your own theme if you want your own icons.. changing the default for everyone, simply for your personal aesthetics is unlikely to be approved.

I think the original icons look better than yours, Gizmocuz does too.. so there you go, only you want these changes and thats why they wont be merged.

If you find serious display bugs in the default theme, patches are welcome.. if all you want to do is alter its appearance for aesthetic reasons, well good luck.. those typically get rejected so your going to have to do better than this.

**Pull request closed without merging**
