### PR TITLE
Fix humidity graphs title

### PR DESCRIPTION
**Pull request by ikkemaniac**
Fix chart title when viewing humidity logs. If chart is 'humidity', update title when data is updated. Original chart title remains 'temperature' but is replaced as even the initial data update/load is done through the 'data update' function. probably fixes domoticz/domoticz#1533

### CODE REVIEW

**Comment by gizmocuz** [comment]
Did you test this code with also a temp+hum sensor ?
This just seems to replace the chart title always when there is humidity data, even if it can also contain temperature data
better to check in the end if there is no temp data, but hum data, and then replace the title

**Comment by gizmocuz** [comment]
If you make a pull request, please answer the questions (also on your last one)
Else i have to close them

**Comment by ikkemaniac** [comment]
not tested and will replace temp+hum, so merging this will fix 1 out of 2 bug's.

What do you mean with "also on your last one"? The security issue rone hasn't had response yet.

**Comment by gizmocuz** [comment]
Sorry, but i did give a response in the crc check pull request
Please test with the temp+hum sensor

**Comment by gizmocuz** [comment]
Not working, see above comment

**Pull request closed without merging**
