### PR TITLE
Upgrade of several libraries and Temperature Log now supports autorefresh

### PR DESCRIPTION
**Pull request by michahagg**
This has become a large PR. My apologies!

What it contains:

- Upgrade jQuery to 3.5.1 (had to change html to not use self-closing tags to fix compatibility)
- Upgrade angularjs to 1.8.0
- Upgrade requirejs to 2.3.6
- Upgrade ui-grid to 4.9.0 (formerly known as ng-grid)
- Fix for #4356 
- Pushed all highlevel chart functionality into a separate module RefreshingChart.
- Made GraphLog use RefreshingChart.
- Made TemperatureLog use RefreshingChart. (only the short chart for now)

### CODE REVIEW

**Comment by gizmocuz** [comment]
@michahagg , thank you very much for this PR, cleanup and all the work !!

I have two questions:
Could you add the 'www-test' folder to the git ignore ? Or move this to a 'test' folder and describe with a small test/md file how to use this?

I noticed you changed a lot of html closing tags changed this to use the beginning element (closing) tag,
was this change necessary or was is this done for better reading ?

If you press the 'Files changed' tab here, you see some files that now have no 'end-of-line' and the end of the file,
you can see this indicated by the red icon.
Is it possible to add this ?

Thanks again!

**Comment by michahagg** [comment]
@gizmocuz it's my pleasure and of course in my own interest ;-)  Thank you for having setup Domoticz! Very impressive piece of software! And quite useful :-D


> I have two questions:
> Could you add the 'www-test' folder to the git ignore ? Or move this to a 'test' folder and describe with a small test/md file how to use this?

I will move it to a test folder and write some instructions on how to use it. And of course add some useful scenarios to the test as well. Are you familiar with unittests?

> 
> I noticed you changed a lot of html closing tags changed this to use the beginning element (closing) tag,
> was this change necessary or was is this done for better reading ?

Unfortunately this was necessary for jQuery 3.5.1 to work. After bumping jQuery, somehow the components weren't rendered anymore. It took me some time to find out what the problem was; I ended up using the jquery-migrate plugin that told me exactly what to fix.

> 
> If you press the 'Files changed' tab here, you see some files that now have no 'end-of-line' and the end of the file,
> you can see this indicated by the red icon.
> Is it possible to add this ?

Sure! Thanks for pointing this out. I was wondering what the icon meant.

**Comment by gizmocuz** [comment]
@michahagg ,
No I am not familiar with unit tests. Once there was a user that pushed 20+ files in a PR, did not know what to do with it so it was removed.

**Comment by gizmocuz** [comment]
@michahagg , Sorry I accidently pressed the Merge button. (Needed to be merged anyway...)
Is it possible to make a new PR for the changes ?

**Comment by kiddigital** [comment]
> @michahagg ,
> 
> No I am not familiar with unit tests. Once there was a user that pushed 20+ files in a PR, did not know what to do with it so it was removed.
> 
> 

@gizmocuz , @michahagg
I have been looking into the possibilities of introducing automated testing as well at least for some of the hardware modules I have worked on. Such tests would be useful to catch regressions and prevent unwanted errors. Maybe an idea to discuss option and possibilities using a feature request here or on the forum?

Let me know what place has your preference.

**Comment by gizmocuz** [comment]
@kiddigital , A feature request will do, or we can talk on Slack ?

**Comment by michahagg** [comment]
I'm ok with whatever works. I'm just not familiar with feature requests on GitHub. Where do I look?

**Pull request merged**
