### PR TITLE
Add Configuration Parameter for StationID to BuienRadar

### PR DESCRIPTION
**Pull request by akamming**
This PR allows a custom station ID for the BuienRadar hardware. If the parameter is 0, the Buienradar hardware will have the same behaviour as without this PR. But if it is filled you can get weather data for a different station.

this allows to have multiple stations in your domoticz instance. (e.g. if you want to monitor the weather of different sites)

It is also a workaround for [this issue](https://www.domoticz.com/forum/viewtopic.php?f=6&t=32214) which is now solved, but might happen again.

Edit:
I just  found out that the rain prediction is not derived from the station id, but from the long/lattitude coordinates in the domoticz settings. So another config setting should be added here as well. I propose to merge this PR 1st. 

And i will create another one for the long/lattitude config param (i am thinking of something like that if long/lattitude is provided as config param that will be used, if not, depending on config param station id. If provided, then get the long/latt from buienradar. If  not, use long/latt from domoticz config).

### CODE REVIEW

**Comment by akamming** [comment]
Since not yet merged i just added another commit to the PR which retrieves the latitude and longitude from Buienradar if a custom id is provided in the config

**Comment by akamming** [comment]
and since this one is not yet merged, i now also included the last changes i wanted to make in also in this PR. The location is now also customizable. You can now ignore the update remark, because that's fixed in this same PR now.

**Comment by gizmocuz** [comment]
Is there somewhere a page where the Station ID's can be found ?

**Comment by akamming** [comment]
@rwaaren made a list here: https://github.com/domoticz/domoticz/issues/4083. I don't know what is the origin

And there is also a list on this location (with slightly  different longitude/latitude) : http://projects.knmi.nl/datacentrum/catalogus/catalogus/content/nl-obs-surf-stationslijst.htm

**Comment by gizmocuz** [comment]
You can get it by calling

https://observations.buienradar.nl/1.0/actual/weatherstation/all

But there will be questions like 'what is this station ID, how do i know my nearest station id, how to convert the output of the above to readable format etc...'

I am thinking about added a 'Help' getter function for each Hardware class that can be displayed when you select a hardware type in domoticz (and clicking on a blue questionmark for example)

**Comment by akamming** [comment]
That's a good idea. I would not let it block the merge of this item. In hardware classes like weather underground and darksky you can also configure stationid or location without any help function. 

Basically this commit brings buienradar on par with these hardware classes for this capability. 

And on the forum there are users requesting this capability.

**Comment by rwaaren** [comment]
@akamming 
I created this list by visiting the individual links of these weatherstations

**Comment by gizmocuz** [comment]
That's correct. Going to make some small changes to be more compatible with WU and coding style...
Will be merged soon!

**Comment by gizmocuz** [comment]
Thanks for the PR!

I merged it with some small adjustments (tested of course):

Using same Gui text as in WU, that saves us new translation strings
Merged Station ID/Lat,Long in one field (same as WU)
Removed extra log lines (I always use breakpoints and use my mouse to hover over variables, saved these debug lines)
Changed to internal log function (we should do that for all hardware one day)
Small code style adjustments

**Comment by akamming** [comment]
Nice!

**Comment by akamming** [comment]
@gizmocuz  i just checked. looks good!  

although I do have have 1 finding. although the combining of stationid and location into 1 config makes is more consistent with other weather services. I coded it to be able to configure both, so you can also use it as a workaround for the issues with buienradar that it does not always provide the longitude/lattitude (giving errors on the rain prediction).   If you can configure both, you're not dependent of Buienradar to provide this info anymore.  

So i think splitting of the fields is better for Buienradar.  What do you think?

**Comment by gizmocuz** [comment]
I think we are fine as it is now. The rain prediction is only depended on a coordinate.
If a station does not report it, don't use it... And what happened earlier was a bug, should not be the default....
It there will be a protocol change we can always split it

**Comment by akamming** [comment]
ok clear...

**Pull request merged**
