### PR TITLE
Support for civil twilight in dzVents

### PR DESCRIPTION
**Pull request by trandbert37**
Add support for civil twilight in dzVents. It's a copy / paste of the existing for normal daytime / nighttime.
I can also do it for NautTwilight and AstrTwilight.

### CODE REVIEW

**Comment by dannybloe** [comment]
Wow, looks good. With tests! Only thing missing I guess is updating the documentation. You can copy/paste documentation/README.md into https://stackedit.io/, then add the proper section and paste it back into the source. 
Also, add an entry in history.md.
I will update the wiki myself by converting the md doc to mediawiki using pandoc.

**Comment by trandbert37** [comment]
Ok thanks !
Should I increment the version number or add the entry in 2.4.6 ?

**Comment by dannybloe** [comment]
Yes. Increment in all places including in a test. And mark the property as such in the docs as well. See the other marks in the docs.

**Comment by trandbert37** [comment]
It's ok like this ? :)

**Comment by dannybloe** [comment]
Almost. Add <sup>2.4.7</sup> to the new attributes in the doc. See the other attributes.

**Comment by trandbert37** [comment]
Done :smile:

**Comment by dannybloe** [comment]
Excellent. Now wait for someone to fix the appVeyor builds. 
/me looks at @gizmocuz

**Comment by gizmocuz** [comment]
Apparently they updated InnoSetup but did not mention it yet here:
https://www.appveyor.com/docs/build-environment/

**Comment by gizmocuz** [comment]
Thanks !!

**Pull request merged**
