### PR TITLE
Add support for PCF8574 and PCF8574A chips (8-bit I/O expander for I2C bus).

### PR DESCRIPTION
**Pull request by OndrejLycka**
I use this chip in Seahu SH017 PLC computer based on raspberryPI (www.seahu.cz).

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for your hard work !
We have some build errors under appveyor, please check the log above or below this message
Could you rename your HTYPE to be consistent of the other I2C types?

HTYPE_PCF8574 --> HTYPE_RaspberryPCF8574

**Comment by gizmocuz** [comment]
Instead of an additional addhardware document, could extend the wiki maybe if something is unclear ?
http://www.domoticz.com/wiki/Developing_a_hardware_plugin

**Comment by gizmocuz** [comment]
Got more compile errors
could you please compile under visual studio as well ? If you do not have windows, try virtual box or parallel desktop or simular

**Comment by OndrejLycka** [comment]
Sorry githup is not may friend, smuggle my working version. Now may be finish version.

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
