### PR TITLE
MQTT-AD Add hold* topics to the climate mode topicz of Thermostats

### LINKED ISSUE #5196: MQTT-AD some device is missing from thermostat TuYa TV02
From this device the selector device is missing: https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html#tuya-tv02-zigbee
This is the config message:
`homeassistant/climate/0xb4e3f9fffebd9f7f/climate/config`
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"current_temperature_template":"{{ value_json.local_temperature }}","current_temperature_topic":"zigbee2mqtt/BadkamerThermostaat","device":{"identifiers":["zigbee2mqtt_0xb4e3f9fffebd9f7f"],"manufacturer":"TuYa","model":"Thermostat radiator valve (TV02-Zigbee)","name":"BadkamerThermostaat"},"hold_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/preset","hold_modes":["auto","manual","holiday"],"hold_state_template":"{{ value_json.preset }}","hold_state_topic":"zigbee2mqtt/BadkamerThermostaat","json_attributes_topic":"zigbee2mqtt/BadkamerThermostaat","max_temp":"30","min_temp":"0","name":"BadkamerThermostaat","temp_step":0.5,"temperature_command_topic":"zigbee2mqtt/BadkamerThermostaat/set/current_heating_setpoint","temperature_state_template":"{{ value_json.current_heating_setpoint }}","temperature_state_topic":"zigbee2mqtt/BadkamerThermostaat","temperature_unit":"C","unique_id":"0xb4e3f9fffebd9f7f_climate_zigbee2mqtt"}`

### PR DESCRIPTION
**Pull request by SargonofAssyria**
As discussed in https://github.com/domoticz/domoticz/issues/5196#issuecomment-1106027903

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR.
The problem here is that you overwrite the 'modes' with 'hold_modes' but both can co-exist, for example this config template:

```
{
"action_template": "{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}",
"action_topic": "zigbee2mqtt/Darba istaba radiators",
"availability": [
{
"topic": "zigbee2mqtt/bridge/state"
}
],
"away_mode_command_topic": "zigbee2mqtt/Darba istaba radiators/set/away_mode",
"away_mode_state_template": "{{ value_json.away_mode }}",
"away_mode_state_topic": "zigbee2mqtt/Darba istaba radiators",
"current_temperature_template": "{{ value_json.local_temperature }}",
"current_temperature_topic": "zigbee2mqtt/Darba istaba radiators",
"device": {
"identifiers": [
"zigbee2mqtt_0x60a423fffea3b2bb"
],
"manufacturer": "TuYa",
"model": "Radiator valve with thermostat (TS0601_thermostat)",
"name": "Darba istaba radiators",
"sw_version": "Zigbee2MQTT 1.17.0"
},
"hold_command_topic": "zigbee2mqtt/Darba istaba radiators/set/preset",
"hold_modes": [
"schedule",
"manual",
"boost",
"complex",
"comfort",
"eco"
],
"hold_state_template": "{{ value_json.preset }}",
"hold_state_topic": "zigbee2mqtt/Darba istaba radiators",
"json_attributes_topic": "zigbee2mqtt/Darba istaba radiators",
"max_temp": "35",
"min_temp": "5",
"mode_command_topic": "zigbee2mqtt/Darba istaba radiators/set/system_mode",
"mode_state_template": "{{ value_json.system_mode }}",
"mode_state_topic": "zigbee2mqtt/Darba istaba radiators",
"modes": [
"heat",
"auto",
"off"
],
"name": "Darba istaba radiators",
"temp_step": 0.5,
"temperature_command_topic": "zigbee2mqtt/Darba istaba radiators/set/current_heating_setpoint",
"temperature_state_template": "{{ value_json.current_heating_setpoint }}",
"temperature_state_topic": "zigbee2mqtt/Darba istaba radiators",
"temperature_unit": "C",
"unique_id": "0x60a423fffea3b2bb_climate_zigbee2mqtt",
"platform": "mqtt"
}
```

Maybe it is best to create a additional selector switch for the hold_modes ?

**Comment by SargonofAssyria** [comment]
I assumed that is one or the other. I will create an additional selector switch for the hold_modes.
But I have to fresh up my programming skills, so could take a few days....

**Comment by gizmocuz** [comment]
That would be great! It can be a bit of a chalange ... (both selector switches need to have a unique ID otherwise you can not distinquis the two...) Maybe add something like '_hm' for the hold-mode device id

**Comment by SargonofAssyria** [comment]
I tried, but lack the competence to finish this PR.

**Pull request closed without merging**
