### PR TITLE
Fix typo on HTTPS on install.sh script

### PR DESCRIPTION
**Pull request by vonglasow**
During the installation we can display information related to http or https protocol. Rename HTPS to HTTPS.

### CODE REVIEW

**Comment by vonglasow** [comment]
Hello, what can I do to fix this error as I modified only a typo in information displayed ?

```sh
Error: Failed installing dependency: https://luarocks.org/say-1.3-1.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz - v1.3-1.tar.gz
[829](https://github.com/domoticz/domoticz/runs/6634986319?check_suite_focus=true#step:4:830)
Error: Process completed with exit code 1.Error: Failed installing dependency: https://luarocks.org/say-1.3-1.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz - v1.3-1.tar.gz
[829](https://github.com/domoticz/domoticz/runs/6634986319?check_suite_focus=true#step:4:830)
Error: Process completed with exit code 1.
```

**Comment by vonglasow** [comment]
Hello, what can I do to fix this error as I modified only a typo in information displayed ?

```sh
Error: Failed installing dependency: https://luarocks.org/say-1.3-1.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz - v1.3-1.tar.gz
[829](https://github.com/domoticz/domoticz/runs/6634986319?check_suite_focus=true#step:4:830)
Error: Process completed with exit code 1.Error: Failed installing dependency: https://luarocks.org/say-1.3-1.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz - v1.3-1.tar.gz
[829](https://github.com/domoticz/domoticz/runs/6634986319?check_suite_focus=true#step:4:830)
Error: Process completed with exit code 1.
```

**Comment by kiddigital** [comment]
@vonglasow , hm.. seems something wrong with the PR building process. I will take a look... does not look like a problem on your end... will get back

**Comment by kiddigital** [comment]
Thanks!

**Pull request merged**
