### PR TITLE
Add an option on meter device for managed meter

### PR DESCRIPTION
**Pull request by guillaumezin**
This PR relates to #2271 and to scripts like https://github.com/empierre/domoticz_linky

It adds an option to meter device, to prevent Domoticz to call UpdateMeter() and AddCalendarUpdateMeter() to do change on this device, this is usefull for meters handled by external scripts or plugins

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could you revert the change in the language file ? If you need a change in the language file, this has first to be added in the English file, and later translated online via transifex.
Please tell me what lines you need to add to the english file

**Comment by guillaumezin** [comment]
Reverted. The line I want to add:
"Externally managed": "Externally managed"
In French:
"Externally managed": "Géré à distance"

**Comment by gizmocuz** [comment]
Thanks, could you show a screenshot of where (in English) this line is used?

**Comment by guillaumezin** [comment]
screenshot_20180403_213641

**Comment by guillaumezin** [comment]
I close the PR, useless thanks to PR #2417

**Pull request closed without merging**
