### PR TITLE
replace boost::tuple with std variant

### PR DESCRIPTION
**Pull request by neheb**
boost variant offers nothing

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
@neheb , thank you for this PR! Always great to use default stuff....
In **webserver/request_parser.hpp** there is still boost/tuple use with your PR, was this intended ?

**Comment by neheb** [comment]
Yeah. That uses boost::tuple for some boost APIs. That one can't be swapped.

**Comment by gizmocuz** [comment]
Perhaps then the current patch in this file is converting the std variant to a boost::tuple again, maybe it's best to keep the existing code and directly use the boost::tuple ?

**Comment by neheb** [comment]
Not sure what you mean. The only change in request_parser.hpp is replacing make_tuple with {}. The only point of make_tuple is to avoid template parameters.

**Comment by gizmocuz** [comment]
Thank you for this PR and your time !!

**Pull request merged**
