### PR TITLE
Added check if vcruntime140.dll (32bit/x86) is installed.

### PR DESCRIPTION
**Pull request by dotnetniet**
Added check if vcruntime140.dll (32bit/x86) is installed. If not installed or older version then 14.29, VC_redist.x86.exe is used to install VC++ runtime libraries.

### CODE REVIEW

**Comment by gizmocuz** [comment]
This will add 13MB to the installer. Is this needed ? It's the first time I hear about this .... Assuming you are running windows 10 with all updates installed ?

**Comment by dotnetniet** [comment]
Correct, Windows 10 with all updates installed. Also checked on Windows server 2019 and that one even has less runtime dll's. 
Microsoft recommends to use the redistributable installer, because of these different possible environments.

**Comment by dotnetniet** [comment]
Regarding the extra 13MB, Inno setup can also use the DownloadTemporaryFile function, but you need to have an internet connection to use that. That will also introduce an external dependency and will fail when Microsoft moves the file on there end.
I like to have everything in one package, that's why is chose for this solution.

**Comment by dotnetniet** [comment]
See https://github.com/domoticz/domoticz/issues/4895 for further discussion.

**Comment by dotnetniet** [comment]
We choose to include missing dll's in setup: https://github.com/domoticz/win32-libraries/pull/2

This change is not needed.

**Pull request closed without merging**
