### PR TITLE
RGBW Picker Angular component

### PR DESCRIPTION
**Pull request by stas-demydiuk**
-- Extract rgbw picker initialization to angular component
-- Replace rgbw picker in timer editor with new component
-- Replace rgbw picker in device editor with new component
-- Fix issue with rgbw picker initial value on timers and scenes page

### CODE REVIEW

**Comment by stas-demydiuk** [comment]
@emontnemery I've fixed the issues we discussed yesterday, but see you done almost the same in your #2810 PR. 

Anyway I would like to have this rgbwPicker as separate component for future reuse, so your PR could be merged first and I update mine after if you prefer

**Comment by emontnemery** [comment]
@stas-demydiuk Wow, awesome!!

I don't really know angular, so it would be nice if #2810 is merged first :)

**Comment by gizmocuz** [comment]
@stas-demydiuk , i assume you would like to make some modifications to this PR before merging ?

**Comment by stas-demydiuk** [comment]
Yes, need to address changes from @emontnemery PR

**Comment by stas-demydiuk** [comment]
@gizmocuz now it should be ok

**Comment by gizmocuz** [comment]
Thanks again for this one !!

**Pull request merged**
