### PR TITLE
clang-tidy: replace bind calls with lambdas

### PR DESCRIPTION
**Pull request by neheb**
Found with modernize-avoid-bind

Signed-off-by: Rosen Penev <rosenp@gmail.com>

The motivation to remove boost::bind is the change in boost 1.73 where the placeholders moved namespaces.

All of these were manually done. The actual check relies on C++14 as it uses auto&& whereas here I've removed such things to keep it compatible with C++11.

From the description page:

std::bind can be hard to read and can result in larger object files and binaries due to type information that will not be produced by equivalent lambdas.

### CODE REVIEW

**Comment by neheb** [comment]
This is finished.

**Comment by neheb** [comment]
I'll rebase after everything else goes through.

**Comment by gizmocuz** [comment]
@neheb , Not sure if this PR was ready to be merged?

**Comment by neheb** [comment]
I have a newer version that gets rid of all bind calls. Will update soon.

**Comment by neheb** [comment]
Done. The only exception is all of the binds in main/WebServer.cpp. For some reason, replacing those bind calls results in larger compiled size.

**Comment by neheb** [comment]
Meh. replaced with std::bind for those.

**Comment by gizmocuz** [comment]
I think this could be because the bind takes a pointer, and the lambda is compiled inline
The speed of a Lambda is faster than the bind, but in this case/project it would not matter much ;)

**Comment by gizmocuz** [comment]
Thank you for all the work again !!!

**Comment by neheb** [comment]
Right but the lamba conversions elsewhere result in lower compiled size. Maybe lambdas being const default allows the optimizer to do some work.

Anyway, whatever.

**Comment by kofec** [comment]
After all clang cleaning the size grow about 1,5MB for arm (Rasp PI) on Openwrt:
```
10 098 871 domoticz_2020.2.12279-1_arm_arm1176jzf-s_vfp.ipk
11 744 169 domoticz_2020.2.12686-1_arm_arm1176jzf-s_vfp.ipk
```

**Comment by neheb** [comment]
Hmm maybe it's a clang thing. I compile with clang instead of GCC.

**Comment by gizmocuz** [comment]
I have a crash when using the web interface (http)

connection.cpp
Line 210

```
			else {
				// Perform plain read
				socket_->async_read_some(buf, [this](const boost::system::error_code &err, size_t bytes) { shared_from_this()->handle_read(err, bytes); });
			}
```

I have to revert this PR...

**Comment by gizmocuz** [comment]
It's working again.
I suspect the issue is because the whole webserver code heavily depends on boost ... 
I was not able to test the other changes as connecting to my Domoticz debug instance via HTTP already caused the above crash
Maybe changing the boost usage to std would be more standard c++11

**Pull request merged**
