### PR TITLE
main/EventSystem.cpp: Add notification to python events

### PR DESCRIPTION
**Pull request by thertp**
Add support for email and notifications to python events. The code is using the lua code so the syntax is the same.

### CODE REVIEW

**Comment by gizmocuz** [comment]
We have some compile errors here for windows. Please see the AppVeyor details

```
C:\projects\domoticz\main\EventSystem.cpp(3403,26): error C2146: syntax error: missing ')' before identifier 'and' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
  (compiling source file '/main/EventSystem.cpp')
  
C:\projects\domoticz\main\EventSystem.cpp(3403,26): error C3861: 'and': identifier not found [C:\projects\domoticz\msbuild\domoticz.vcxproj]
  (compiling source file '/main/EventSystem.cpp')
  
C:\projects\domoticz\main\EventSystem.cpp(3403,50): error C2059: syntax error: ')' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
  (compiling source file '/main/EventSystem.cpp')
  
C:\projects\domoticz\main\EventSystem.cpp(3404,3): error C2146: syntax error: missing ';' before identifier 'body' [C:\projects\domoticz\msbuild\domoticz.vcxproj]
  (compiling source file '/main/EventSystem.cpp')
  
  HTMLSanitizer.cpp
  IFTTT.cpp

```

**Comment by gizmocuz** [comment]
this does not look like c++ code (**and**)

```
if ((aParam.size() > 1) and (!aParam[1].empty()))
		body = aParam[1];
```

could you test the code before making a PR please... did you also tested the working of lua/dzVents/Blockly is all is still working?

**Comment by thertp** [comment]
hm. probably applied the wrong version of the patch. The first version had this issue. I'm using the change on my domoticz install and I've tested it with lua and python on a test instance (blockly should not be affected). Since the tests were working, it can only be a mistake when applying the patch to git. I'll try to find time to fix the PR soon.

**Comment by gizmocuz** [comment]
Thank you for the patch. There are more places where 'SendNotification' is used (and SendEmail), is it possible you can also rewrite those functions to use the new functions?

**Pull request closed without merging**
