### PR TITLE
treewide: remove most uses of static_cast

### PR DESCRIPTION
**Pull request by neheb**
static_cast is verbose for no reason. Just replace with normal cast.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this PR. Is it possible to solve the merge conflicts ? The code in OTGW has been updated recently

**Comment by neheb** [comment]
It's rebased.

**Comment by gizmocuz** [comment]
@neheb , the reason why I changed a lot of casts to use c++ style casting is because my compiler (VStudio) complained about the use of old style casting...

**Comment by neheb** [comment]
Note that (char) is a C cast. I changed it to char(), which should be fine with C++.

**Comment by gizmocuz** [comment]
Most warnings I received where about integers and floats

**Comment by neheb** [comment]
Hillarious. One issue I found with AppVeyor is long == 32-bits under windows. 64-bits under Linux. Joy...

**Comment by gizmocuz** [comment]
Still I think we should use c++ style casting

https://stackoverflow.com/questions/332030/when-should-static-cast-dynamic-cast-const-cast-and-reinterpret-cast-be-used/332086#332086

**Comment by neheb** [comment]
That link calls it a function style cast. It's C++ only. But your call.

**Comment by gizmocuz** [comment]
Having some merge conflicts here, and it's also not a desired patch.

 return float(atof(readValue.c_str()));

should be

 return static_cast<float>(atof(readValue.c_str()));

as this is the preferred way of c++ style casting

**Comment by neheb** [comment]
Alright.

**Pull request closed without merging**
