### PR TITLE
More logs for devices

### PR DESCRIPTION
**Pull request by szczukot**
What Do You think about this change ? 
This gives more possibilities for logs (Debug). Not only in mainworker, but in all modules.
I wrote this for testing for example this problem : https://github.com/domoticz/domoticz/issues/430#issuecomment-183398606

### CODE REVIEW

**Comment by gizmocuz** [comment]
I dont know why this patch was made, but 1=status

**Comment by gizmocuz** [comment]
I have to check this, because we have also a status level, and i dont see that here
But for the OWFS you can enable debug, that was the idea with verbose

**Comment by gizmocuz** [comment]
I think verbose debug should be sufficient to debug things like this ?

**Comment by szczukot** [comment]
Define DEBUG is not solution for this situation.

Im dont testing this in my system. This problem have one of users.
Maybe i enable DEBUG, compile and send app for him

**Comment by szczukot** [comment]
Ok. I did only optimization for reading sensor (1wire).
Pls merge it (but i dont know, how i can set properly one inlcude - Travis is failed)

**Comment by gizmocuz** [comment]
Well above (or below) you can click on the details of travis and see why there is a problem
i can not merge a pull request when our build system fails, thats why we have some build systems

`In file included from /home/travis/build/domoticz/domoticz/main/mainworker.cpp:36:0:
/home/travis/build/domoticz/domoticz/main/../hardware/1Wire.h:4:34: fatal error: ..\1Wire\1WireCommon.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/domoticz.dir/main/`

**Comment by szczukot** [comment]
I see this error, but i don;'t know, how path is properly :(
I tested:
1) "..\1Wire\1WireCommon.h"
2) "1Wire\1WireCommon.h"
Both is inproperly

**Comment by szczukot** [comment]
Maybe now is ok :)

**Comment by gizmocuz** [comment]
Thanks, this is working !

**Pull request merged**
