### PR TITLE
1Wire using proper logging methods (Fixes #5642)

### LINKED ISSUE #5642: DomoticZ logs for 1wire
hello, i see a possible bug related to 1wire hardware.
if i select in hardware page the 1wire and i deselect the error log like in the below picture
immagine

i still receive errors on domoticz log ragarding missing reading on DS18B20 sensor
i expect that these errors should not be logged due to settings in harware page, isn't it?
it could be a little bug?
below the error logs that i see reported by domoticz
```
 2023-03-15 05:32:32.479 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074881f9
2023-03-15 06:37:48.613 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074881f9
2023-03-15 07:07:00.450 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 07:09:56.128 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 07:57:18.206 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 10:25:33.704 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 10:31:53.060 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 10:36:35.339 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 11:01:55.735 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 13:12:02.171 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 13:46:07.023 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 14:08:59.304 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 14:10:01.507 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 14:11:20.365 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 14:12:36.836 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 14:14:57.239 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074930a1
2023-03-15 14:36:06.119 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d
2023-03-15 14:49:01.635 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-0000074881f9
2023-03-15 14:50:04.330 Error: 1-Wire system : error reading value from /sys/bus/w1/devices/28-00000746702d 
```
note: these 3 DS18b20 sensors are connected directly to GPIO of raspberry, but i think that is doesn't matter.

thanks

### PR DESCRIPTION
**Pull request by kiddigital**
This PR tries to fix #5642 

As 1 don't have the 1Wire system in use or quickly available for testing, I could not really test this other than Domoticz creating the HW device and shows proper (debug) logging.

@megamarco833 , could you test this PR build?

### CODE REVIEW

**Comment by megamarco833** [comment]
> This PR tries to fix #5642
> 
> As 1 don't have the 1Wire system in use or quickly available for testing, I could not really test this other than Domoticz creating the HW device and shows proper (debug) logging.
> 
> @megamarco833 , could you test this PR build?

@kiddigital thanks for your efforts!!!
yes i can test it, but unfortunately only when will be available a download for RPI3 i can't compile it :(

anyhow right now i'm on build15109 and also deactivating all logs level for 1wire (info, status, error) i still see the error message displayed on domoticz logs

**Comment by gizmocuz** [comment]
Thank you for this PR! Looks perfectly fine!

**Comment by gizmocuz** [comment]
@megamarco833 , could you try beta 15175?

**Comment by megamarco833** [comment]
> @megamarco833 , could you try beta 15175?

Yes sure! Give me a couple of days, ok?
Thanks very much for PR

**Comment by megamarco833** [comment]
@kiddigital and @gizmocuz 
i tested the build 15175 and if ihave selected ON the error log i still se the error on 1wire sensor, then i put OFF only the error log for 1wire, and till now (6 hours) i don't see any error displayed.
so i think that it's working!!!
thanks so much for PR

**Pull request merged**
