### PR TITLE
Add support for evohome setpoint background colours

### PR DESCRIPTION
**Pull request by fullTalgoRythm**
Please can you add back support for setpoint colours for evohome temperature devices

### CODE REVIEW

**Comment by gizmocuz** [comment]
There already seems to be a function 'EvoSetPointColor' in this class, maybe this function should be called ?

**Comment by fullTalgoRythm** [comment]
That function is legacy code it's not compatible with the new code which atm requires a css style. The old function can be remove or left for reference as preferred. The colours were default behaviour until 4.9700 so the patch just restores original behaviour.

**Comment by gizmocuz** [comment]
@fullTalgoRythm , thats for the explanation. Could you remove them in your patch ?

**Comment by fullTalgoRythm** [comment]
Right that should be done now are we OK to merge?

**Comment by gizmocuz** [comment]
Thanks !!

**Pull request merged**
