### PR TITLE
dzVents: runtime is based in szStartupFolder not szUserDataFolder

### PR DESCRIPTION
**Pull request by dwmw2**
It doesn't matter in the "normal" Domoticz setup where everything lives
in /opt/domoticz, but for packaged builds we really care about read-only
bits (szStartupFolder or /usr/share/domoticz) vs. editable data (which
is szUserDataFolder or /var/lib/domoticz).

### CODE REVIEW

**Comment by dwmw2** [comment]
Ping @dannybloe

**Comment by dannybloe** [comment]
I’ll look into this 😀

**Comment by gizmocuz** [comment]
@dannybloe, no stress ;)

**Comment by dannybloe** [comment]
I merged this PR in my own branch.. will create a PR from that one very soon. Closing this one.

**Comment by dwmw2** [comment]
Thanks @dannybloe. And #2386 too?

**Pull request closed without merging**
