### PR TITLE
Added delimiter which is required by the new HEOS Firmware

### PR DESCRIPTION
**Pull request by Sneezydevil**
A recent HEOS update breaks HEOS support in Domotcz, this should fix that.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks, rather than this way to fix it, would it be not better that you concat the \n\r at the moment you are sending ? So your messages still be clear, and only when ssMessage is actually send, you add the CRLF ?

**Comment by Sneezydevil** [comment]
You are right, I was so happy I found the problem that I did't really take a nice approach at fixing it.

I will change it and update the pull request

**Comment by Sneezydevil** [comment]
I don't do alot of c++ so if I do silly stuff like that just call me out on it. I think this is cleaner.

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
