### PR TITLE
Code refactoring in WebServer.cpp

### PR DESCRIPTION
**Pull request by efdeb**
**Strictly no functional changes : just code refactoring to improve readability.**

void CWebServer::HandleCommand(const std::string &cparam, WebEmSession &session, const request &req, Json::Value &root)
when (cparam == "testswitch")

1/ Ordening of "_if (lighttype == XX)_" blocks  by increasing XX values
2/ Simplification of _return_ statement for HTYPE_EnOceanESP2/HTYPE_EnOceanESP3/HTYPE_USBtinGateway when (lighttype == 70)

_Please note "else if (lighttype < 70)" becomes "else if (lighttype < 68)" because "else if (lighttype == 68)" and "else if (lighttype == 69)" are present._

void CWebServer::RType_Hardware(WebEmSession &session, const request &req, Json::Value &root)

1/ _#ifdef / #endif_ for Special case for openzwave (status for nodes queried)

### CODE REVIEW

**Comment by kiddigital** [comment]
Hi @efdeb this PR also contains the change you made in PR #4911. Better to remove that change from this PR.

**Comment by efdeb** [comment]
Hi @kiddigital
My mistake!
I removed this unwanted change from this PR.
Thank you.

**Comment by kiddigital** [comment]
@efdeb , it is better to 'git rebase -i upstream/development' (or whatever other name than 'upstream' you gave to track against the original Domoticz repo) than 'pull' the latest changes. Prevents getting al these unneeded _merge commits_ 😁

**Comment by efdeb** [comment]
Hi @kiddigital 
I promise I'll soon read some git/github documentation to accelerate my learning curve !
Many thanks for your help anyway.

**Pull request closed without merging**
