### PR TITLE
Add servercert.pem save/restore if non default file found (user cert)…

### PR DESCRIPTION
**Pull request by ghost**
… to updatebeta only for now (TBD: Do the same in updaterelease if no side effect).

### CODE REVIEW

**Comment by gizmocuz** [comment]
Or you could use another filename for your certificate, and modify the Domoticz startup parameters to use this file?

**Comment by waltervl** [comment]
So it is better to modify the instruction in wiki as it is stating there that the original file name should be used? https://www.domoticz.com/wiki/Native_secure_access_with_Lets_Encrypt#Add_the_certificate_to_Domoticz

So better to use a new filename and modify /etc/init.d/domoticz.sh with -sslcert path_to_cert_file

**Comment by ghost** [comment]
Hi Gizmocuz, That's indeed better to use startup params... Il just did not noticed this was possible using -sslcert. Anyway the PR had to be modified as there was a mistake in pushed file so better close it if useless!

**Comment by gizmocuz** [comment]
@waltervl , yes, otherwise with each update that file is overwritten

**Comment by waltervl** [comment]
Wiki is updated.

**Pull request closed without merging**
