### PR TITLE
Door Lock Inverted

### PR DESCRIPTION
**Pull request by gibbo520**
Added Door Lock Inverted switch type feature 
added delay off on Door Lock and Door Lock Inverted switch type
removed delay (on/off) on door contact switch

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for this patch !
Still not sure why there would be a need for an 'inverted' door lock ... is the wiring OK ?

One minor request, could you remove the changes in hardware/OpenWebNetTCP.cpp ?

**Comment by gibbo520** [comment]
If a door is closed , and i i want open it i send on for unlock and Not for lock it. 
wiring is ok yes !

**Comment by gibbo520** [comment]
Other prople have same problem 
http://www.domoticz.com/forum/viewtopic.php?f=31&t=22191

**Comment by gizmocuz** [comment]
Okey i understand. Please remove the changes in hardware/OpenWebNetTCP.cpp

**Comment by gibbo520** [comment]
done!

**Comment by gizmocuz** [comment]
Thanks !!

**Pull request merged**
