### PR TITLE
Fix cmake dependencies on git

### PR DESCRIPTION
**Pull request by ffontaine**
Proposal to fix issue #258
Set 0 default values for ProjectRevision, ProjectHash and ProjectDate if source
code has not be retrieved through git clone. Moreover, this patch will add a
default appversion.h.txt with default values. This file should be updated each
time an official release is made. Finally, add ProjectDirty to detect if a
modification has been made locally, in this case "-modified" will be added to
hash.

### CODE REVIEW

**Comment by gms1** [comment]
+1 
additional: because of this dependence to git the out-of-source build is broken

**Comment by gizmocuz** [comment]
Hmmmm yes... but that means we have to update this file by hand each time ?
I agree this is needed, if the source is not retrieved from git (but it should?)
I can't think of on offline build system that needs to 'upload' the packages ?
Then it's online, and why not clone/fetch from git

And if we make a new script (like makebeta/makerelease) that pulls the code from git, generates that version file, and nothing more
Then you can transfer it to the offline/online build system ?

If all this does not make sense we merge the patch of course ;) But who's going to maintain this version file ?

**Comment by ffontaine** [comment]
If you retrieve the source code from git clone, the patch will keep the current behavior. The values will be retrieved from git and the appversion.h.txt will be updated automatically.

You will only have to update this file "manually" when tagging an official release to be sure than the values in this file are up to date.

Thanks to this patch, if the source are retrieved out of tree (for example buildroot use this kind of mechanism), the compilation will not fail and the buildsystem will have the version number and date of your latest official release.

**Comment by gizmocuz** [comment]
Thanks, hope i won't forget when we do a new release ;) (Scheduled for 29th feb)

**Comment by gizmocuz** [comment]
This is not working, output of build:

-- domoticz has been modified locally: add "-modified" to hash

why.. because:
appversion.h.txt

I will remove appversion.h.txt from the repo
If you want to use something like this, it should not be a file that the build system is generating
You could name it for instance appversion.default

**Pull request merged**
