### PR TITLE
Check WiringPi libraries without Raspberry check [e.g. when run on or…

### PR DESCRIPTION
**Pull request by blmpl**
…ange pi, banana pi or other pi ;) ]

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the patch, could you move the ident to the left ? (not it contains spaces before the lines because you removed the surroundings)

**Comment by gizmocuz** [comment]
Closing this... no reply... so not important i suppose !

**Comment by blmpl** [comment]
I'm very sorry - I just read the closing notice. I didn't receive notification about other comment  :( 
[I can't completely disable spam filters in my mail account, I white listed github email just now]

I fixed the indent in my branch, should I create new pull requests or you can merge without this?
https://github.com/blmpl/domoticz/commit/ee85a0bb81f0d7af955a0a00c459c2f45fd66089

Sorry!

**Comment by gizmocuz** [comment]
Please create a new pull request (or update this pull request if possible)

**Comment by blmpl** [comment]
I created new pull requests - sorry for the mess.
Thanks!

**Pull request closed without merging**
