### PR TITLE
JSON: Added PlanID and PlanIDs to output for Groups/Scenes

### PR DESCRIPTION
**Pull request by EddyK69**
Also added HistoryLog method. This shows all switchdata orderd by date. Can be used for making custom log info incl. types & icons etc...

### CODE REVIEW

**Comment by gizmocuz** [comment]
Is this history log not the same as the current RType_LightLog ?

**Comment by EddyK69** [comment]
No, that one only shows 1 device of the Light-types, not the sensors, doorbells & smoke-detectors etc. The RType_HistoryLog shows ALL devices.
Alternativly i could change the existing RType_LightLog to make it show all devices.
Whats you're opinion: 1) change existing RType_LightLog or 2) add new RType_HistoryLog?

**Comment by EddyK69** [comment]
I think i'll close this PR to split in 2: 
1) JSON: Added PlanID and PlanIDs to output for Groups/Scenes
2) JSON: Added HistoryLog method

**Comment by gizmocuz** [comment]
Please split it in two, because the lightlog does show the log of PIR's, Doorbells, smokesensors, all lighting devices

**Comment by EddyK69** [comment]
Done ;)

**Pull request closed without merging**
