### PR TITLE
for range loop conversions

### PR DESCRIPTION
**Pull request by neheb**
Some of the manually done ones have a size reduction as there is no need for a copy.

### CODE REVIEW

**Comment by gizmocuz** [comment]
@neheb , sure not the right place here, but 'SortIncludes' in the clang-format configuration file is giving issues as 'stdafx.h' needs to be included as first include.
Sure we can add everywhere '// clang-format off/on' but that does not seem right
Sometimes you want includes in a logical order then alphabetical order...
Maybe set it to false?

**Comment by neheb** [comment]
I think there's a different way to accomplish that. Setting it to false seems correct for now.

**Comment by gizmocuz** [comment]
Not sure why you choose to call it 'm' instead of 'itt' (from iterator)

for (auto& itt : m_devices)
	for (auto &m : m_devices)

'itt' seems more logical as you know it's from the iterator loop

... actually, because of my spelling error, maybe it should be 'it' ?

**Comment by neheb** [comment]
Because it's not an iterator at all. It's a reference to what the iterator points to.

edit: maybe d or device is better...

**Comment by gizmocuz** [comment]
Sure if it's related to devices, 'd' would also be good
Its a iterator ... "An Iterator is an object that can be used to loop through collections" does not matter how its used ;)
The thing is, if you keep renaming it, it's not really consistent and you don't know what it is... like 'm' could be a member
like 'i' is used (a lot) for indexes

**Comment by neheb** [comment]
I believe m_devices is an std::map. const auto& m evaluates to std::pair<x, y>. In other words, a reference to the map member. That’s why -> is replaced with . Also note some of the other changes where *itt is completely removed as it’s not needed.

edit: and results in a smaller binary as a copy is not needed.

**Comment by gizmocuz** [comment]
Yes I know that this is the result, still it's a Iteration you do over the members of a map.
calling it 'm' is not clear, specially when 'm' ... 'm_' is used for members
'**It**' (Iterator) seems more clear in some cases then '**m**'

**Comment by gizmocuz** [comment]
For example:
			for (const auto &val : values)

... later in the code you can't see the for loop... and you might think like... val ... was a structure? 
when it was called 'it' (itt), you should think, ahhh it's from the for loop

**Comment by kiddigital** [comment]
As the goal is to have readable code, I would say that variablenames should reflect/explain what the variable is about.

When iteration over a list, the object you are working with is the actual object (and not the list) and for the functions you are applying to it, it is usually not relevant that the object comes from a list.

So I would argue that the variablename should at least indicate the object(type).

But knowing that the object comes from a list that is iterated, can be valuable as well in understanding the purpose of the processing.

So maybe combine that?
d_it instead of it(t) or just d?

**Comment by neheb** [comment]
I'll get rid of the m when I get a chance.

C++17 has structured binding declarations, which avoid having to set a variable to x.first and another to x.second. From reading the CMake file, this project is C++11 with no plans to move to a higher version.

**Comment by neheb** [comment]
Renamed all &m

**Comment by gizmocuz** [comment]
@neheb , we just moved C++11, C++17 is a bit to soon and could introduce some compile issues on various hardware platforms

**Comment by gizmocuz** [comment]
Thank you for all the work !!

**Comment by gizmocuz** [comment]
@neheb , there was a problem with at least eHouseTCP.cpp:

1>eHouseTCP.cpp
1>hardware\eHouseTCP.cpp(908): warning C4700: uninitialized local variable 'i' used

I used to be a index and was not used anymore.
VS2019 did notice this, so please if possible, use VC2019 and GCC to test the changes

**Comment by gizmocuz** [comment]
@neheb , there was also a problem reported in void CEventSystem::WWWGetItemStates, this was caused by the usage of 'unsigned long' , instead of 'uint64_t)

**Comment by neheb** [comment]
Those are warnings to be fair. I’ll look into them when I can.

**Comment by gizmocuz** [comment]
Not really, the eHouseTCP code used a uninitialized variable as a index in a function
(Do note I am not pointing fingers!)

I just solved a crash where a iterator was still being used but this was replaced by a for-loop conversion
The iterator was not used/assigned before, but was parsed as a pointer to another function (CEventSystem::ParseBlocklyLua)
VS2019 did also not warn... because the pointer was parsed as 'const' and not assigned yet, it could/should have given a warning

https://github.com/domoticz/domoticz/commit/c301f6632e95b8cf40dbc37bb2656b8cbff61546

**Comment by neheb** [comment]
:). Happens with manual conversions unfortunately. To add to that, I should probably change my editor. I'm still using nano...

**Comment by gizmocuz** [comment]
@neheb , I know... it was a lot of work for sure !!!

Yes, please use VStudio 2019!, It's very good

Found another left over:
https://github.com/domoticz/domoticz/commit/d4bfea473be6ec0a5acb1226b9b372a232bcad73

Ps. If you search in all source files for '::const_iterator' ... there are a few for loop left overs ;)
(And a few when searching for '::iterator'

**Pull request merged**
