### PR TITLE
Update TeleinfoBase.cpp

### PR DESCRIPTION
**Pull request by darrepac**
Remove to not update the PAPP value if similar to previous (was causing some values to never update)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!! Beta building (11316) could take up 2 more then an hour

**Comment by darrepac** [comment]
> Thanks!! Beta building (11316) could take up 2 more then an hour

I do not see the change in the changelog (https://releases.domoticz.com/releases/beta/history_linux_armv7l.txt). Is it in?

**Comment by gizmocuz** [comment]
Check the github repository

**Comment by darrepac** [comment]
I confirm that the bug is solved with this change.

**Pull request merged**
