### PR TITLE
[1Wire] OWFS is always available

### PR DESCRIPTION
**Pull request by szczukot**

### CODE REVIEW

**Comment by gizmocuz** [comment]
Why is this, even if it is not installed?

**Comment by szczukot** [comment]
One Wire File System may be installed on any hardware. Domoticz can be installed on another computer.
OWFS is only file system - we can set path to it from everywhere. This is not only file system from local machine (domoticz). We can use shared path resource etc.

For example, i run domoticz on computer with Windows, but it get data from OWFS, installed on RaspberryPI.

**Comment by gizmocuz** [comment]
Sorry, this is not what i meant.
When OWFS is not installed, we should not show the hardware (like it is now)
When OWFS is installed and detected, then we should show it

**Comment by szczukot** [comment]
What means "OWFS is not installed" or "installed".
Domoticz don't know that owfs is installed or not.

**Comment by szczukot** [comment]
Domoticz get data from path, where exists info about devices. This path may by for example //SERVER/path_to_1wire
Domoticz dont check that OWFS is installed on local machine or not.

**Comment by gizmocuz** [comment]
Maybe this was indeed the case when this library was build... a long time ago...
There is also an windows owfs version... not sure if this is been in use by anyone, but now we have some duplicate code

**Comment by szczukot** [comment]
Exactly.
Today, domoticz don't working with OWFS on Windows.
After fix - will work.

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
