### PR TITLE
correct  Domoticz Weekly Planning Selector #5052 :

### PR DESCRIPTION
**Pull request by labelette91580**
This are some correction about PR from xbaudouin : Domoticz Weekly Planning Selector #5052 
 
display table by default
correct background select entry
correct scene timer regression
no display Grid in case Led/scene
correct display of blinds in grid

I hope this will suit to merge it!

### CODE REVIEW

**Comment by gizmocuz** [comment]
Yes, great!!!! thanks again!!

Some small requests if possible
- the red/green are 100% saturated, my eyes are in pain... could you make it a bit less green/red
- the selected mode tab (Table/Grid), could you make it the same as in Settings (also the selected style)

If possible the color rectangle a little bit down so it is vertically aligned with the text in front of it:
image

For the thermostats, please change the default frost protection temperature to 5 degrees.

The only thing that feels a bit weird is that I'm used to draw a rectangle and when I release the left mouse it should change the selection.
At least, this is my experience from camera monitoring systems
Here when you have the left mouse button down, it directly sets the value and it is very easily to move your mouse to a wrong value
But that's how the control is designed.... 

Looking great!

**Comment by gizmocuz** [comment]
Looking great!
More than happy to merge!

Question, are you able to draw a rectangle between the left mouse button down and up (or touch down/up) instead of displaying the blocks?

**Comment by labelette91580** [comment]
i will see if it is simple to do !
________________________________
De : gizmocuz ***@***.***>
Envoyé : dimanche 22 janvier 2023 15:59
À : domoticz/domoticz ***@***.***>
Cc : labelette91580 ***@***.***>; Author ***@***.***>
Objet : Re: [domoticz/domoticz] correct Domoticz Weekly Planning Selector #5052 : (PR #5542)


Looking great!
More than happy to merge!

Question, are you able to draw a rectangle between the left mouse button down and up (or touch down/up) instead of displaying the blocks?

**Comment by gizmocuz** [comment]
Lightning fast! Thanks for another amazing job!!!

I noticed it is not (yet) possible to use the grid with RGB(w/ww/..) lights.
I guess this is because we need to specify a colour to turn on to.
Maybe this is possible to specify once the rectangle has been drawn (when ON was specified), than op popup to specify the RGB/W/WW value

Thanks again!

**Comment by labelette91580** [comment]
no.
this is not possible because the color identify the state.
or for rgb there are to many differents state.

for example I have to reduce tthe state for the dimmer to 10 color

________________________________
De : gizmocuz ***@***.***>
Envoyé : lundi 23 janvier 2023 12:14
À : domoticz/domoticz ***@***.***>
Cc : labelette91580 ***@***.***>; Author ***@***.***>
Objet : Re: [domoticz/domoticz] correct Domoticz Weekly Planning Selector #5052 : (PR #5542)


Lightning fast! Thanks for another amazing job!!!

I noticed it is not (yet) possible to use the grid with RGB(w/ww/..) lights.
I guess this is because we need to specify a colour to turn on to.
Maybe this is possible to specify once the rectangle has been drawn (when ON was specified), than op popup to specify the RGB/W/WW value

Thanks again!

**Pull request merged**
