### PR TITLE
Fixes for XiaomiGateway

### PR DESCRIPTION
**Pull request by corbinmunce**
Fixes for wall switch.  Fix for round wireless switch to always update Domoticz. Totally ignore 'heartbeat' messages.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by marcotini** [comment]
@deennoo it doesn't surprise me. In my experience I can tell you that my sensor go on with an heartbeat in middle night and turn on the light lol but @corbinmunce could not replicate my problem.

**Comment by deennoo** [comment]
@marcotini, which kind of sensor please ? (round switch? door switch ? motion ? wireless 1 button or 2 button ? wired 1 button or 2 button ?

on future merge heartbeat will be disable to solve this

**Comment by marcotini** [comment]
@deennoo as you can see here: https://github.com/marcotini/domoticz/commit/b8e10e711cbb3e69696bd69dd89201a0104c5b49 I solved removing completely the heartbeat (just for the color of the Gateway).

Btw all the sensor (door and motion) go ON randomly, sometimes just 1 or 2, sometimes all togheter. I don't know about the switch because it came to me when I already fixed this problem of fake positive.

**Comment by deennoo** [comment]
ok thanks ! 

maybe you can help to another problem ?

**Pull request merged**
