### PR TITLE
Evo web revision 5

### PR DESCRIPTION
**Pull request by gordonb3**
Now referencing development branch

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks!

**Comment by MikeyMan83** [comment]
So where are we on this? @gordonb3 has put in a lot of hard work. We know the plugin needs change. Any estimates?

**Comment by gizmocuz** [comment]
@MikeyMan83 , please use the forum, there is already a discussion there

**Comment by MikeyMan83** [comment]
@gizmocuz care to share a link? Lots of topics, but cannot find to find the discussion.

**Pull request merged**
