### PR TITLE
LiveSearch

### PR DESCRIPTION
**Pull request by soif**
This PR aims to add a Live (instant) Search form on all devices pages ( Lights, Scenes, Temperatures, Weather, Utility).

_For people like me having tons of devices, this features is **very** convenient (**a true game-changer**) to quicky filter devices, by name or description._

This is currently a **draft** PR  that showcases  the useness of this feature.
_(No need to compil to test it, as it only changes webserver's files...)_
--> It will obviously needs some design's enhancements!

ezgif com-gif-maker

---------

Currently working Features:
- Searches as you type
- Searches both in device's Names and Descriptions (very useful when you use descriptions, to ie store Alexa_Name, Devices IP addresses, aliases,etc..)
- Handles filtering while refreshing devices
- Shows device's description when "hovering" device's names

To enhance:
- Refactors the "Top Bar" (Time, Search, Rooms, Links) to nicely include the search's field.
- Standardizes Temperature,Weather templates vs other pages templates
- Fixes showing description on name's hover in  Temperature,Weather pages

---------

**If you like it, and consider to accept it, I would  be pleased to finish it, including all your advices and wishes ...**

HTH

### CODE REVIEW

**Comment by kiddigital** [comment]
Hi @soif , thank you for this very nice enhancement!

How do you see it compared to the 'rooms' functionality where a 'room' effectively groups (or filters) a certain set of devices together? Often, people like to see certain groups of devices (and hide others) which is now done by the main Tabs (Dashboard, Switches, etc. which group Types of devices) and through the use Rooms (explicitly selected devices that are group together).

And we can definitely use more help from front-end/UI developers to move the UI ahead quicker :)

**Comment by soif** [comment]
hi @kiddigital, thanks for the quick reply.

For people like me (more than 500 devices used), the current way to group devices by 'floor', is really a pain to maintain.
(I finally just use an "Alexa" floor to allow the Alexa plugin to work)...

But anyway, this Search feature searches **thru the currently displayed devices**, so it searches thru "All" devices, or just the ones displayed if you'd filter by room....

Try it for yourself ;-)

**Comment by xbeaudouin** [comment]
Really love this feature (have *exactly* same problems) with 470 devices (and growing...)

**Comment by rezzalex** [comment]
I love it as well !!!

**Comment by gizmocuz** [comment]
That many devices is crazy!!! Surely you don’t operate those
You should not add all possible sensors because you can’ 😀

but for this reason the rooms were created

**Comment by gizmocuz** [comment]
Maybe it is a option to have the search option collapsed as a search icon and when clicked expanded? That will save some room

**Comment by soif** [comment]
@gizmocuz

>That many devices is crazy!!! Surely you don’t operate those
>You should not add all possible sensors because you can’ 😀

FYI Here is an example of devices consumption (mostly "dummy" devices):
- AIr conditioner IR (ie broadlink) -> one dummy device per IR signal:
 In my case 5 IR signal (off, cold 20°, cold 22°, hot 18°, hot 22° ) + 1 dummy selector to group them = 6 dummy devices used per AC. I have 4 AC in my house , so 4x6 = 24  devices just for AC.
 - Another big consumer are sensors: I have both a RFXcom and a RFLink. Most of my sensors are seen 3 times (1 on the RFX, 1 on the RFL, and 1 bogus on the RFL) --->  33 sensors x 3 = 99 devices (66 "unused")
 - Virtual switches also count a lot. I have 24 PIR motion sensors, but each one has a second virtual switch that just act as a "master" switch for the PIR (select if the PIR is active, or disconnected from its light target ). So 24x2 : another 48 devices....
 - then comes the leds strips, using the excellent wled firmware: 6 devices used per led strip. I have 10 led strips, so another 60 devices...
 
etc....

As you can see the Dz devices count easily gets high, without that much _real devices_ used. :-/

>but for this reason the rooms were created

In my case, this is not convenient. I would spend hours, just to assign each devices to a "Floor". and then there is no quick way to see which room(s) a sensor is assigned to. You have to browse each room, to figure if the device is assigned to. Definitively a tedious task, for people like me having a lot of devices.

**Comment by gizmocuz** [comment]
Yes but what I mean is, you can have them in your system, but don't set them all as 'Used'
They will still show up under 'devices' but it won't flood your system.

Okey but regarding room plans, if you name them correct and place the correct devices in this plan you should be able to find your devices quickly

- living room
- PIR's
- etc

About the IR, you could add a 'Selector Switch' and based on the action execute a group/scene/script, and not add add them all as 'used'
This way you have only 6 selector switches for your 6 AC's (and create a group to perform some group actions)

Regarding the LED strips, you have 6 led strips, why don't you have 6 RGB/W/WW switches and that's it?
(Not sure if WLED supports MQTT Auto Discovery, if it does not you can also look at ESPHome)

RFXCom + RFLink, sure you get a lot of duplicates, but if it is working on one transceiver, there is no need to add it twice to the system.
Yes, it is possible, but there is no need. Why look at the same temperature sensor twice?
So set 1 as used, ignore the other. Still visible on the devices page if you need to

Place your most used switches/devices at the top of the page

This way your system stays clean

Another way, there is an Admin user, he/she sees ALL devices....

But you can create many users and assign only the needed devices to them.

So, use a normal user by default, and an Admin user to perform admin stuff

This will also make sure the database stays as small as possible

**Comment by soif** [comment]
>About the IR, you could add a 'Selector Switch' and based on the action execute a group/scene/script, and not add add them all as 'used'

That's the way i use it, but I didn't knew that I can still control "unused" devices (in my case each IR command as separate devices) from a script. **Thanks for the tips**!

>Regarding the LED strips, you have 6 led strips, why don't you have 6 RGB/W/WW switches and that's it?

Because Wled offer much more very COOL features (ie Presets, Animations, Palettes, Intensity & Speed)! 
I would love to see this integrated into the  RGB/W/WW switch, but this not currently implemented...

>RFXCom + RFLink, sure you get a lot of duplicates, but if it is working on one transceiver, there is no need to add it twice to the system.

Then the next time you add a new RF device, and  turn On the "Accept new Hardware Devices" button, you end up with all those devices being re-created (66 in my case). It is thus difficult to figure out what is the new one that you really wanted to add, and then have to deleted those 66 new devices. That's the only reason, why i keep those devices as "unused". This getting tedious each time you change a sensor battery, as the 2 unused devices get recreated with a different RF ID, and the old one have to be found and deleted manually.... 
_A way of grouping real devices, with their associated unused duplicates devices,could certainly solve this, but I guess that this feature would certainly be needed by a very few people..._

>Another way, there is an Admin user, he/she sees ALL devices....

For family (non-admin), I only use [phpMyDomo](http://www.phpmydomo.org) on every tablets/phones. It only shows the devices we all need to control. 
I am thus the only person who uses Domoticz, only for admin things.

**Comment by soif** [comment]
As you seems to be interested in this PR (yes?), Now back to the subject:

1) ---

>Maybe it is a option to have the search option collapsed as a search icon and when clicked expanded? That will save some room

I was thinking of the exact same idea! 👍 On the other hand, It might be the right time, to re-design the whole "top bar", that is not normalized between each devices page (some have buttons, in some place, while some other pages have less buttons, or not at the same place)... and the whole thing take a lot of (unneeded) space IMHO.
So I'm suggesting, to maybe group all those bits, in a single brand-new responsive horizontal bar.

**What do you think? Should I provide you some draft ideas?**

2) ---

Regarding the devices blocks. They are not normalized between the 5 devices pages. Some can be manipulated using the "item" class, while some other are themselves contained in a "xxxWidget" Div. This makes the CSS unnecessarily more complicated, and add extra headache to the JavaScript responsible for showing/hiding/fixing margins/flow during search. Also some pages use a "row" DIV per 3 devices line, while others also add a "clearfix" DIV...
I would like to normalize the whole thing (using the same CSS class, for each device block, everywhere), get rid of all this "row" & "clearfix" DIVs, to finally  just get a "floating" (float:left) list of devices DIVs, that would nicely be filtered by the search form, without having to tweak the CSS from the JavaScript. _BTW I'm not sure it wont break the draggable feature, so I'll have to investigate first..._

**Do you agree?**

3) ---

Some pages (Temperatures and Weather) use a totally different view/controller design than the 4 other ones (dashboard, Light, Scenes, Utility). I guess that this is due either to different people designing the pages, or some pages that were upgraded, while some were not. 

So, the questions is: **What are the pages supposed to be the "main" ones, in term of code design?**
(I would like to stick to one of the 2 designs, and make a kind of patch for the second case).

4) ---

I can not figure the right way to name CSS classes: The naming rules seems to not be normalized.
So, between:
- newclassname
- new-class-name
- new_class_name
- newClassName

**What is the right naming rule that I should stick to?**

**Comment by gizmocuz** [comment]
I will come back to your questions but the idea is to redesign the gui part with angular(14+)/typescript (ng)
I’m already playing with this
Do you have angular/typescript experience? I could create a git repo with a start frame
But it needs some work as to integrate JWT integration for user authentication 

once that works a search/filter option should be possible to implement easily 

as admin I use a computer and a browser

this has a keyboard and with Ctrl-f I can search as well

those very cool rgb effects…. Nice, but you probably timed the strips to have a nice glow in the evening daily
The times you use the disco feature will probably be a few times a year (and then add them as used)

**Comment by kiddigital** [comment]
My 2 cents
1) Yes, please propose an optimized "top bar". And maybe consider even displaying the logged-in User (maybe just icon with hover). Keep in mind the different view-sizes to support mobile's (phones, tablets and 'bigger' screens)

2) Always in favor of refactoring to make things simpler/easier to maintain (no one to blame, this is just what happens over time when many people contribute and which we encourage of course). If you feel confident to do it, please go ahead :)

3) See above, although I can image that this one is harder because of specific processing both on the front-end and back-end code.

4) Not sure here, I think a see camelCase the most, so newClassName (maybe look at [W3C](https://www.w3schools.com/js/js_conventions.asp)?)?

And I just saw @gizmocuz post a few minutes before mine.. I am in favor of updating/rewriting the UI (and separating it from the back-end), but that feels a lot more work and I am not a skilled front-end dev so my contributions will be limited :)

**Comment by kiddigital** [comment]
@soif , are you on the Domoticz slack? Maybe useful to discuss things?

**Comment by soif** [comment]
@gizmocuz

> I will come back to your questions but the idea is to redesign the gui part with angular(14+)/typescript (ng) I’m already playing with this Do you have angular/typescript experience? I could create a git repo with a start frame But it needs some work as to integrate JWT integration for user authentication

I have quite a good experience in php, HTML, SQL, Javascript (+jQuery +Vue +HighCharts)  and CSS, but not with Angular/typescript. So I might be able to learn from YOUR code, and make additions/modifications, but I'm certainly not the right guy to start an Angular project nearly from scratch....

> once that works a search/filter option should be possible to implement easily

So should I just drop this PR, or quickly finish it asis, until you develop the new UI?

> as admin I use a computer and a browser 
> this has a keyboard and with Ctrl-f I can search as well

So do I, but to filter more than one device, the livesearch is way more convenient and faster. 
Also, the livesearch feature searches in the descriptions as well, which is very convenient, and not feasible using Ctrl-F

**Comment by soif** [comment]
>     1. Yes, please propose an optimized "top bar". And maybe consider even displaying the logged-in User (maybe just icon with hover). Keep in mind the different view-sizes to support mobile's (phones, tablets and 'bigger' screens)

Depending on what @gizmocuz plan to do with the UI (see previous post), I would be happy to make some proposal , ASAP.
 
>     2. Always in favor of refactoring to make things simpler/easier to maintain (no one to blame, this is just what happens over time when many people contribute and which we encourage of course). If you feel confident to do it, please go ahead :)

It also depends, on @gizmocuz  decision for the UI, but if let's say, it stay asis for the moment, I would at least start to normalize device block, in order to make then more easily controllable from the JS.
 
>     4. Not sure here, I think a see camelCase the most, so newClassName (maybe look at [W3C](https://www.w3schools.com/js/js_conventions.asp)?)?
 
I personally use camelCase in CSS name. I also use to separate "view" only classes, from those used only by javascript.
So that JS Developer and CSS developer can change the class names, when they want , without having to worry if this particular name was used by the other developer or not. For example

```
HTML
<div class='myDiv jsMyDiv'>Hello</div>

CSS
.myDiv{
 background-color: #ccc;
}

JS
$('.jsMyDiv').fade();

```

**Comment by soif** [comment]
> @soif , are you on the Domoticz slack? Maybe useful to discuss things?

I'm afraid not. Would you like me to join? How?

**Comment by soif** [comment]
BTW @kiddigital, here a **quick-and-dirty draft** of a new "Top Bar", including the Search..

Big:
dz_new1

Medium:
dz_new2

Small:
dz_new3

-----

vs the Current One:

dz_old

----

I removed the date part, because it takes precious space, and IMHO it is not really needed.
I suggest that we could also remove the Sun's times. Maybe just showing them in a popup, when hovering the sun icon.

Do you like it (this is a draft) ?

**Comment by gizmocuz** [comment]
> @gizmocuz
> 
> > I will come back to your questions but the idea is to redesign the gui part with angular(14+)/typescript (ng) I’m already playing with this Do you have angular/typescript experience? I could create a git repo with a start frame But it needs some work as to integrate JWT integration for user authentication
> 
> I have quite a good experience in php, HTML, SQL, Javascript (+jQuery +Vue +HighCharts) and CSS, but not with Angular/typescript. So I might be able to learn from YOUR code, and make additions/modifications, but I'm certainly not the right guy to start an Angular project nearly from scratch....
> 
> > once that works a search/filter option should be possible to implement easily
> 
> So should I just drop this PR, or quickly finish it asis, until you develop the new UI?
> 
> > as admin I use a computer and a browser
> > this has a keyboard and with Ctrl-f I can search as well
> 
> So do I, but to filter more than one device, the livesearch is way more convenient and faster. Also, the livesearch feature searches in the descriptions as well, which is very convenient, and not feasible using Ctrl-F

It will take some time as my weekends are filled up rapidly during December....
You will see already some angularJS code in the GUI (very old angular) it's a great framework!
Specially the latest versions that's using typescript, making the whole project/code much more robust!

Sure, please go ahead with this enhancement!  It looks great!

But the point I was making is that to keep the system fast and organized it is not a good idea to just add all sensors to the system.
It will also rapidly fill up the underlying database.
You can always create custom pages to enable the disco modes....

> As you seems to be interested in this PR (yes?), Now back to the subject:

Yes

> Regarding the CSS mess (row div, clearfix, dragdrop)

Domoticz started (many years ago) as HTML/JS and migrated to AngularJS more and more
You can see this also in for example the weather page

The ultimate plan is to have widget types (components) for all possible types
So items can be rendered based on their type and we can use a simple ngFor loop and don't have to rewrite all rendering code for all pages
This will also make it very easy to add a 'filter', for example based on the content of the search box

Once that is possible, we can also support custom pages and make use of libraries as Angular Grister2 etc

But please make sure the sorting stays working, drag/drop (maybe in edit mode or like now always possible unless disabled in settings)
Dashboard rendering in normal/compact/mobile mode
It is good to have (make use) of a grid, so the layout stays organized

I hope to devote my time in the near feature to implementing user-based authentication to JWT and then finish a boiler template for Domoticz in Angular/typescript

**Comment by gizmocuz** [comment]
Feel free to join our slack channel for discussions

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

**Comment by soif** [comment]
@gizmocuz

> > So should I just drop this PR, or quickly finish it asis, until you develop the new UI?
> 
> Sure, please go ahead with this enhancement! It looks great!

> > As you seems to be interested in this PR (yes?), Now back to the subject:
> 
> Yes

Great! 😎 
So before starting to finish the code, I have a few quick questions:
1) Do I include my latest "TopBar" proposal? Any changes/wishes?
2) What is the right place to put the CSS? /css/style.css ?
3) What is the right place to put the (jQuery) Javascript ? /js/domoticz.js ?
4) Do you validate that I use camelCase for CSS rules?

> Feel free to join our slack channel for discussions

done! 
Should I rather continue discussion on slack, or here?

**Comment by soif** [comment]
OK, following discussions in Slack, This PR it now almost finished.

**Just Added:**
- global TopBar component
- itemBlock CSS class added to easily handle devices blocks whatever their code structure is (new Angular pages, vs Old JS pages)
- Dynamically build TopBar links, from the controller
- TopBar Links Icons
- i18n fixes for the TopBar
- Hovering name to show descriptions now works everywhere
- font-awesome updated to the latest 6.2.1 version

**To Enhance:**
- while live searching, some devices still show some empty space before them. _A fix would certainly need to rewrite the device list DOM structure, which unfortunately is very different in the current 2 controllers code used_
- when a hidden (by search) device is ajax refreshed, it briefly show up , before disappearing. _Again, fixing this would certainly be a lot easier once both code structures have been first normalized._

**To maybe change:**
- CSS classes naming uses camelCase style... OK?
- files used to add the new JS/CSS code.
- anything you wish

Do you like it? 
Any suggestions, wishes, comments?

**Comment by kiddigital** [comment]
@soif , for clarity. Is it possible to do the font-awesome update independent of this PR? Not sure if something breaks/fails if the update is not performed?

Maybe make it a separate PR (just the fa update) which can/should be done anyway? And should not cause any harm?

It makes this PR much more clean and readable.

**Comment by soif** [comment]
You're right, Font-awesome should be in a separate PR.
I'm gonna push it separately ASAP.
_But as this LiveSearch PR relies on the future font-awesome PR, please merge it before accepting this one_

**Comment by soif** [comment]
BTW, I've added the topBar (showing ONLY the links) in theses pages:
- CustomTempLog, 
- Forecast, 
- RoomPlans
- Cam
- TimerPlan

Thus, those pages links are consistent with the new TopBar Links : same placememnt (right), same size, and use icons.

I've made the changes in my **topbar-everywhere** branch, that you can checkout from :
https://github.com/soif/domoticz/tree/topbar-everywhere
If you like it, i will merge it in this 'livesearch' branch, so that it would be included i this PR.

Like it?

**Comment by gizmocuz** [comment]
Tested the PR, looks nice but there is something odd... When I enter the first letter of a visible device it gets about 10 pixels shifted to the right
For example, on the dashboard, you see the devices not left aligned anymore underneath the header (like Utility Sensors) but there is a shift to the right

The date/time is now displayed as time, which is OK i suppose
But it is not aligned on the left anymore

The select/dropdown for the room plans, it should be a bit wider to hold bigger names

**Comment by soif** [comment]
> Tested the PR, looks nice 

cool , thanks for the review 😎 

>but there is something odd... When I enter the first letter of a visible device it gets about 10 pixels shifted to the right For example, on the dashboard, you see the devices not left aligned anymore underneath the header (like Utility Sensors) but there is a shift to the right

I know: This is a very basic workaround against the current DOM structure (not very filtering friendly):
As the devices are groupped by 3 in a "row" class div, they cant "float" to the left when filtering. 
So currently the JS, remove the "row" CSS class, and change it to "display:inline", so that it can float. But doing this change the left margins to the main page div.... I had simply changed the devices margins to a lower one, so that they can still fit in a row, but obviously it changed alignements. 
_As you dont like it that much, I'm going to figure if I can find a better workaround, to keep the devices with the same alignement...._


> The date/time is now displayed as time, which is OK i suppose 

This was to save some width (especially with smaller screen widths), and displaying the date is not really needed IMHO... 
But you're the boss, you decide. 😛 

>But it is not aligned on the left anymore

What you mean? You want it before the seach input, at left?
 
> The select/dropdown for the room plans, it should be a bit wider to hold bigger names

 Long room names are still shown (not truncated) when clicking on the popup. I've slightly reduced the size to 146px, to again save some width , on small screen sizes...
 What size would you like?

**Comment by soif** [comment]
I found a new workaround for the devices margin issue when filtering! 🍺 

Commit follows....

**Comment by kiddigital** [comment]
Agree that search bar can be omitted at the Dashboard. It is a Dashboard 😁

**Comment by soif** [comment]
I've just removed Search from the Dashboard page, as suggested by @kiddigital ...
 I might revert this commit back, as whished...
 
 BTW should I merge my [topbar-everywhere](https://github.com/soif/domoticz/tree/topbar-everywhere) branch (see above for further information) into this PR ?

**Comment by gizmocuz** [comment]
The margin issue has been solved, great!

The room plan dropdown needs to be wider... for example I cannot see plans with common names complete like 'Master Bedroom', 'Guest Bedroom', or 'Jonathan's Bedroom'

image

**Comment by soif** [comment]
just enlarged... 😇

**Comment by kiddigital** [comment]
@soif , took a quick look at the livesearch **& topbar** and I like what I see.... my suggestion would be to replace this PR with the combined PR (close current and open new one).

image

When I click the searchbar to start typing, the rendering of the searchbox is a little weird (FireFox latest), see image.
image

I know in the current UI we display time with _seconds_, but these are not updated every second. Maybe we could leave the seconds out?

Can we show the date for the larger viewports and hide the date for the small screen?

The text 'room :' before the roomplan selector has been replaced by an icon. The _house_ (_home_?) icon might be a little confusing.. feels like I have to press it somehow.... (ET phone home :) ). An icon instead of text makes sense to save space, we just need a better icon :)

@gizmocuz  , agree with these suggestions?

**Comment by gizmocuz** [comment]
Hmmm sometimes the second counter could be of interest to see when timers/scripts are executed
Maybe we could make a general timer that increments the time each second? So it keeps counting if it's not being updated?

**Comment by soif** [comment]
> @soif , took a quick look at the livesearch **& topbar** and I like what I see.

Happy that you like it

>... my suggestion would be to replace this PR with the combined PR (close current and open new one).

You mean combined with my "topbar-everywhere" branch ?
If yes this branch simply replace the "back" button in a few others pages (listed above), with the same button that are used in the top bar (use same icons, same placement) to make the UI more consistent.
I could then just merge it to this PR. Or post it in a separate PR...

> When I click the searchbar to start typing, the rendering of the searchbox is a little weird (FireFox latest), see image. 

Sorry I cant really understand what you feel weird... Black background? Blue border? 

> I know in the current UI we display time with _seconds_, but these are not updated every second. Maybe we could leave the seconds out?

I guess seconds are updated each time an ajax call is processed...
I dont think my PR changed anything about that.

> Can we show the date for the larger viewports and hide the date for the small screen?

Can be easily done in the CSS, if you all wish that.
 
> The text 'room :' before the roomplan selector has been replaced by an icon. The _house_ (_home_?) icon might be a little confusing.. feels like I have to press it somehow.... (ET phone home :) ). An icon instead of text makes sense to save space, we just need a better icon :)

For Sure, I did not found a better icon in font-awesome, but if you find a better one at at:
 https://fontawesome.com/search?o=r&m=free
 
 Please give  the icon name, and i would be glad to change it according to your wish.

**Comment by soif** [comment]
>Hmmm sometimes the second counter could be of interest to see when timers/scripts are executed
>Maybe we could make a general timer that increments the time each second? So it keeps counting if it's not being updated?

I thought that the main reason of having the time displayed, was in fact to know WHEN a device has just been updated. 😛

**Comment by gizmocuz** [comment]
Yes, that's another way of using the time indeed ;) but there is already a time in the widget (last seen)

About the room icon, we need some kind of a floormap icon. 

Otherwise my votes would go to

house-laptop
house-chimney-window
map

**Comment by kiddigital** [comment]
I indeed mean the rendering of the searchbox where it get some white 'shading' around the blue surroundings. (Same happens when selecting the rooms dropdown btw).

And maybe use 'person-shelter' as icon for the room selector?

**Comment by soif** [comment]
just changed: 
- input style on focus
- All your room suggested icons : Checkout the commit you want to try. Then tell me the final icon to use..

**Comment by gizmocuz** [comment]
person-shelter
image

house-laptop
image

house-chimney-window
image

**Comment by gizmocuz** [comment]
I think either person-shelter or house-laptop. house-laptop shows some kind of a device, which is what you place in the rooms...

**Comment by kiddigital** [comment]
house-laptop is fine by me :)

**Comment by soif** [comment]
Changed to house-laptop!

Anything Else? 
Should I merge my [topbar-everywhere](https://github.com/soif/domoticz/tree/topbar-everywhere) branch?

**Comment by kiddigital** [comment]
> Changed to house-laptop!

Thx

> 
> Anything Else? Should I merge my [topbar-everywhere](https://github.com/soif/domoticz/tree/topbar-everywhere) branch?

I would say Yes. Agree @gizmocuz ?

**Comment by gizmocuz** [comment]
Yes that sounds perfect

**Comment by soif** [comment]
Ok, I've just merged my topbar-everywhere branch into this PR branch.
As stated above, but as a reminder, here are the pages affected by theses commits:

  -  CustomTempLog ("back" btn),
  -  Forecast ("back" btn),
  -  RoomPlans ("back" btn... BTW "Add Plan", could also be easily moved to the TopBar, if you wish)
  -  Cam ("Add Camera" btn)
  - TimerPlan ("Add Plan" btn)

Those pages mainly move the "Back" links into the topBar (showing ONLY links, in these cases)

Also , the "devices" page "refresh" button now include a refresh icon...

**Comment by gizmocuz** [comment]
Looking great! One thing, the sunset/sunrise is almost not readable, looks transparent, not white. Is it also possible to make the tooltip (arrow/text) 'SunRise' and 'SunSet'

**Comment by soif** [comment]
>One thing, the sunset/sunrise is almost not readable, looks transparent, not white..

I'm gonna brightest it.

>is it also possible to make the tooltip (arrow/text) 'SunRise' and 'SunSet'

For $ 10,000, sure! (just kidding)...

**Comment by soif** [comment]
Done! 
Better? OK?

_BTW please note that IMK, those tooltips can not be handled/translated by i18n_

**Comment by gizmocuz** [comment]
Hmmm why can't they be translated? There are other tooltips that are translated

**Comment by soif** [comment]
Certainly an Angular thing i'm not aware of.. 
Would you please point me to a page with an i18n translated tooltip.

**Comment by gizmocuz** [comment]
@soif , whoops yeah not for AngularJS 1.8x i suppose... there is 'tooltip-html-unsafe' but best to keep it untranslated for now if there is no other way (Sorry)

Font for sunrise/set looks much better now by brightness,!

Happy to merge... maybe just the revert of the tooltip text but it would have been nice if it was possible

**Comment by soif** [comment]
Again I'm a totally Angular newbie! And their documentation is.....

Anyway, I'm gonna remove the  tooltip, in a few minutes...

While I'm here, Is there any other changes that I should make?

**Comment by gizmocuz** [comment]
Thank you very much for this PR and your time!!! We're always happy to see some frontend changes!

"IF" you have some spare time and work with timers, maybe you could have a look to get an old PR working

https://github.com/domoticz/domoticz/pull/5052

**Comment by soif** [comment]
> Thank you very much for this PR and your time!!! We're always happy to see some frontend changes!

Happy to help, when i can! 😎 

Thank you for the merge 🍺 

>"IF" you have some spare time and work with timers, maybe you could have a look to get an old PR working

Took a quick look... What you would need me to fix? 
CSS color of the "entries" popup ?

**Comment by gizmocuz** [comment]
I left a few comments in this PR
I like the design! But for example the look of the timers should initially be the table view we have now

- In the PR it is a grid as default, and you can switch to a table view
- The checkboxes for the day names are broken with this PR (See the original theme screenshots above)
- It seems that the Scene/Group timers is broke
- The table top/left entry (amount of items) is broke (black text)

**Comment by soif** [comment]
Let's continue in #5052 ....

**Pull request merged**
