### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by mvmn**
Please accept this PR with Ukrainian translation for Domoticz.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Great, thank you !
From now on, please send me a PM if you want to have the language file updated, i have to run a script, its not done via git

**Comment by mvmn** [comment]
Sure
Thanks

**Comment by gizmocuz** [comment]
We got a problem... did you use the translation system to translate ? This because i updated all translations here and can not find any translation in the file ?
(the translation file generated by transifex)

**Comment by gizmocuz** [comment]
The ukrainian translation file does not end with 'ua', going to undo this change... you have to use the transifex system, and use the domoticz-uk as file

**Comment by mvmn** [comment]
I tried Transifex first, but it didn't seem to work, so I've made a fork and added translation to the fork instead. I made translation by hand, didn't use any translation systems.

I'm not sure what's missing though - I've added translation to www/i18n/domoticz-ua.json.gz (and made changes to 2 more files - WebServer.cpp (where options for language dropdowns are) and html5.appcache (which seems to list all i18n JSON files).

**Comment by gizmocuz** [comment]
the filename for Ukrain ends with 'uk', you should login to the transifex system and translate there
You can copy/paste from your file

**Comment by gizmocuz** [comment]
But sorry, i know this is a lot of work

**Comment by gizmocuz** [comment]
I think i did it and uploaded your translations in the system, only down-side it will say all strings are translated... but maybe not all are done ...
I will add the 'uk' also to the webserver/html class in a minute

**Comment by mvmn** [comment]
I've checked all strings on Transifex - they all seem to be translated as expected, only made 1 correction. Seems to be good to go there.

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/commit/e91522383739f17f871fb55fffb7d43b52e80133

**Comment by gizmocuz** [comment]
Think we're all good now ! Thanks once again !

**Comment by mvmn** [comment]
You're welcome

**Comment by mvmn** [comment]
One thing though - in WebServier.cpp you still have "ua" as language code, not "uk". Is that expected? Might be an omission.

https://github.com/domoticz/domoticz/commit/e91522383739f17f871fb55fffb7d43b52e80133

**Comment by gizmocuz** [comment]
Sorry,fixed now

**Pull request merged**
