### PR TITLE
Fix for group on/off command (dimmers)

### PR DESCRIPTION
**Pull request by EddyK69**

### CODE REVIEW

**Comment by gizmocuz** [comment]
I see only cosmetic changes, and no code changes, correct?

**Comment by EddyK69** [comment]
No, see changes in MainWorker::SwitchScene:
In MainWorker::SwitchScene the maxDimLevel is not read/set for Groups, therefor the SetLevel is not set  :(

**Comment by EddyK69** [comment]
Now, the maxDimLevel is also read if it is a group

**Comment by EddyK69** [comment]
Thanx for merging! Could you please build a new beta, so i could test it further on my rpi?

**Pull request merged**
