### PR TITLE
Work on Pusher tables

### LINKED ISSUE #4036: Device delete does not propagate to fibarolink, httplink and pushlink
Triggered by this  [forum post ](https://www.domoticz.com/forum/viewtopic.php?f=6&t=31983#p241859) I looked in SQLHelper.cpp and did not found the expected delete statements in CSQLHelper::DeleteDevices.  I then tested a device in httplink and it remained in the database after deletion from the device tab.
I will create a PR to add the delete statements.

### PR DESCRIPTION
**Pull request by gizmocuz**
Migrate all pusher tables to one
Rename DeviceID to DeviceRowID
Propagate device deletes to Push table (Should fix #4036)

### CODE REVIEW

**Comment by rwaaren** [comment]
Don't know for sure howto change this in the PR (don't want to run the risk that I push something to development 😀  )
Small left over from Fibarolink table..

push/FibaroPush.cpp:309:                        result = m_sql.safe_query("SELECT A.ID,A.DeviceRowID,A.Delimitedvalue,A.TargetType,A.TargetVariable,A.TargetDeviceID,A.TargetProperty,A.Enabled, B.Name, A.IncludeUnit FROM **FibaroLink** as A, DeviceStatus as B WHERE (A.PushType==%d AND A.DeviceRowID==B.ID)", CBasePush::PushType::PUSHTYPE_FIBARO);

in History.txt
```
Version 202x.x ( 202x)
- Fixed: Daikin wifi adaptor module
- Fixed: Delete device now propagates to all relevant tables
- Updated: dzVents version 3.0.2 ( https://www.domoticz.com/wiki/DzVents:_next_generation_LUA_scripting#History )
- For a full overview visit: https://www.domoticz.com/wiki/Domoticz_versions_-_Commits for details
```

**Comment by gizmocuz** [comment]
Thanks for spotting, I fixed the missing change and updated the history

**Review by rwaaren — COMMENTED** [review]
Looks OK now

**Comment by gizmocuz** [comment]
Thanks !

**Pull request merged**
