### PR TITLE
Netatmo credentials cannot be set anymore

### PR DESCRIPTION
**Pull request by sbouchex**
Renaming has not been done everywhere...

### CODE REVIEW

**Comment by gizmocuz** [comment]
The fix should be in the hardware setup controller, not in the c++ code
i will have a look

**Comment by sbouchex** [comment]
The fix can be at different places depending on the name of the hardware device you want to see. My fix displays the name "Netatmo Weather Station" instead of "Netatmo" but the controller (HardwareController.js) is detecting "Netatmo Weather Station"

**Comment by gizmocuz** [comment]
True, but as we now also support the Netatmo Thermostat (users dont have to have a weather station) 'Netatmo' was a good name

**Comment by gizmocuz** [comment]
fixed in #3619

**Pull request closed without merging**
