### PR TITLE
Python-Plugins dirent usage in DelayedLink

### PR DESCRIPTION
**Pull request by oohlaf**
Make use of dirent_is_directory again in DelayedLink

### CODE REVIEW

**Comment by oohlaf** [comment]
Hmm, no response on this...
Now that you merged your branch into main without this, shall I rebase against main?

**Comment by dnpwwo** [comment]
Go for it.

I don't know why it wouldn't compile for me but if you can make it work then using common code is always a good think.

**Comment by oohlaf** [comment]
Well, that's easy as it already compiled :)
As you can see by the green marks. You needed to rearrange the order of the headers files include.

**Comment by gizmocuz** [comment]
Thanks!

**Pull request merged**
