### PR TITLE
Migrate to Angular 8

### PR DESCRIPTION
**Pull request by gaeljw**
This PR aims to solve #2806, which is get rid of AngularJS and use Angular 8.

Only changes are on the web UI, API is kept as is. But it's still a pretty big rewriting and refactoring:
- bye bye JavaScript, welcome Typescript
- bye bye big fat controllers, welcome components (there were already a few components that I reused)

I understand it's hard to trust someone with only a few commits in the domoticz codebase with such a big PR, actually even if I had written hundreds of commits in Domoticz I would not trust myself!
It's almost impossible to review the code I wrote.
But I hope we can find a way to ensure everything is working :)

**I guess the first thing would be to find few volunteers to try out this version and get feedbacks.**

_Note that I will take care of rebasing regularly this branch on top of the development branch unless other people want to participate and in such case I will do merges to preserve a common consistent Git history._

# How to try this version?

2 options:
- download the compiled version of this branch, move the `www` folder of your Domoticz installation to `www.old` for instance and create a new directory `www` with the content of the downloaded archive
  - ~~v1: https://drive.google.com/file/d/1_QAzXUXqzS0qFro1TMEIh-AABdi31Vp-/view?usp=sharing~~
  - ~~v2: https://drive.google.com/file/d/1En8nzjlRTretMq1Kl2swzeC3YQ_uK__d/view?usp=sharing~~
  - ~~v3: https://drive.google.com/file/d/1VPy71nKt6ia6Oo784D8b300Yem2qN1u0/view?usp=sharing (non obfuscated, with debug info)~~
  - ~~v4: https://drive.google.com/file/d/1VSLqUWJM-b6_WmTQRKiGFpPvSR2Lh0FX/view?usp=sharing (non obfuscated)~~
  - v5: https://drive.google.com/file/d/1JnKEbCqelT2-YCmCalHIPPFp236AOvLT/view?usp=sharing (non obfuscated)
- clone this branch, build locally (you will need NPM) and run. The `README` in the `www-src` folder should contain necessary information.

# Known issues

- [ ] Accessing a page other than `/` directly does not work (probably something to change on the webserver)
  - See below
- [x] "TypeError: undefined is not an object (evaluating 'e.settings.Location.Latitude')"
- [ ] Errors on backend when saving settings (@devrosx)
  - Not reproduced :cry: 
- [x] Link to find location (settings page) not working (@devrosx)

# Things to change before merging the PR

- [x] Re-enable Travis build for the backend
- [x] Fix the Windows build
- [x] **(In progress...)** Split the app into modules / lazy loading (@ben33880)
- [x] Unsubscribe from observales https://github.com/gaeljw/domoticz/issues/1 (@ben33880)

# Features I'm not confident with, thus to be tested in priority :innocent: 

- Authentication (login.logout)
- Themes
- Custom pages
- ZWave setup tabs
- IE compatibility
- Language switch
- RFX firmware update

# Stuff that could be better but are out of scope

- Get rid of jQuery, only use Angular to manipulate DOM
- Get rid of JS libraries in `libs` folder, use NPM for all libraries
- Write tests

# Missing piece(s) before considering to merge

## Routing issue

> The main remaining issue is the fact that directly accessing a page other than / is not working.
> 
> For instance:
> 
>   -  http://192.168.1.19:8080/ => redirects to index.html which loads the Angular app
>   -  http://192.168.1.19:8080/Dashboard => tries to find Dashboard which does not exist (it should redirect to index.html)
> 
> With AngularJS, routes were always on /#Something so it was always index.html which was requested from the webserver point of view.
> 
> :bulb: I see two options to solve this out:
> 
>   -  move the Angular app under /app or /ui for instance and always redirect to index.html in this subpath
>   -  implement some kind of fallback, instead of giving a 404, if resource not found, redirect to index.html
> 
> Option 1 looks better IMHO.
> 
> :sos: Anyway I will need some help from someone who knows how the C++ webserver works to make this change and help me test.

### CODE REVIEW

**Comment by ben33880** [comment]
Nice job, could you try to use lazy loading ?

**Comment by gaeljw** [comment]
Sure @ben33880, any idea in mind? A module for the admin part definitely but do you see other part to split?

**Comment by ben33880** [comment]
Settings, dashboard, device... One module by menu.
It will improve fast display of the application

**Comment by ben33880** [comment]
Need a core module, shared module also

**Comment by ben33880** [comment]
See https://github.com/pipiche38/Domoticz-Zigate-UI on beta branche for exemple

**Comment by gaeljw** [comment]
Ok, I had the feeling that it was not necessary to split that much but it can't harm I guess.
And it will also help structure a bit more the components dependencies.

**Comment by devrosx** [comment]
thanks for great patch
tried compiled version on clean domoticz install 
and i get
`2020-02-07 21:48:41.965  Error: [web:8080] exception occurred : 'in Json::Value::resolveReference(key, end): requires objectValue' (need to run again)
2020-02-07 21:48:41.965  Error: WebServer(HTTP) exception occurred : 'in Json::Value::resolveReference(key, end): requires objectValue'
`
these errors are in web inscpector (safari)
`[Error] ERROR – TypeError: undefined is not an object (evaluating 'e.settings.Location.Latitude')
TypeError: undefined is not an object (evaluating 'e.settings.Location.Latitude')

domoticz web works but all setting texts are empty...

**Comment by ben33880** [comment]
i have this error in domoticz log : 
2020-02-08 17:27:11.741 Error: WebsocketHandler::Handle Exception: in Json::Value::resolveReference(key, end): requires objectValue

but it works :
Capture d’écran de 2020-02-08 17-29-37

**Comment by gaeljw** [comment]
> thanks for great patch
> tried compiled version on clean domoticz install
> and i get
> `2020-02-07 21:48:41.965 Error: [web:8080] exception occurred : 'in Json::Value::resolveReference(key, end): requires objectValue' (need to run again) 2020-02-07 21:48:41.965 Error: WebServer(HTTP) exception occurred : 'in Json::Value::resolveReference(key, end): requires objectValue' `
> these errors are in web inscpector (safari)
> `[Error] ERROR – TypeError: undefined is not an object (evaluating 'e.settings.Location.Latitude')
> TypeError: undefined is not an object (evaluating 'e.settings.Location.Latitude')
> 
> domoticz web works but all setting texts are empty...

I guess, there's a piece of code assuming location settings are always defined, which is not the case.
I'll try to reproduce and provide a fix soon for you to test.
Thanks @devrosx  :+1:

**Comment by gaeljw** [comment]
@devrosx Can you please try new version?
v2: https://drive.google.com/file/d/1En8nzjlRTretMq1Kl2swzeC3YQ_uK__d/view?usp=sharing

**Comment by devrosx** [comment]
tried new version but still have some problems with setting tab
looks like i cant save any change (tried on my current running domoticz system)
in log is 
2020-02-10 18:59:20.781 Error: WebsocketHandler::Handle Exception: in Json::Value::resolveReference(key, end): requires objectValue

also noticed that when i switch panels (dashboard, switches, etc) i can see for short time info that i have no switches (like on fresh install) before all elements are loaded..

**Comment by gaeljw** [comment]
Thanks for the feedback @devrosx 

> also noticed that when i switch panels (dashboard, switches, etc) i can see for short time info that i have no switches (like on fresh install) before all elements are loaded..

This is expected, I could display a message like "Loading.." instead of "No switches". In the current implementation (AngularJS), almost everything is synchronous, so it doesn't behave exactly the same as the new which is totally asynchronous (the page loads even if the data are not here yet).

> tried new version but still have some problems with setting tab
> looks like i cant save any change (tried on my current running domoticz system)
> in log is
> 2020-02-10 18:59:20.781 Error: WebsocketHandler::Handle Exception: in Json::Value::resolveReference(key, end): requires objectValue

Do you have more logs in the browser console logs?
I'll try to reproduce but on my system I can save without issue.
Is your Domoticz system up to date? The UI version I'm building is assuming latest version of Domoticz is installed.

**Comment by devrosx** [comment]
In on Mac, maybe thats the probem, i have my own compiled and updated domoticz...
and stil have Invalid Location Settings... on setting panel.
To find your location clickHere link isnt working.
```
[Error] Origin http://XXXXX is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://maps.googleapis.com/maps/api/js?v=3&sensor=false due to access control checks.
[Error] Failed to load resource: Origin http://XXXXX is not allowed by Access-Control-Allow-Origin. (js, line 0)
```
error on safari on page load:
ERROR
InvalidCharacterError: The string contains invalid characters.
atob
(anonymous function) — main-es2015.67f1e5c92154c93f544c.js:1:1436259
__tryOrUnsub — main-es2015.67f1e5c92154c93f544c.js:1:373515
next — main-es2015.67f1e5c92154c93f544c.js:1:372744
_next — main-es2015.67f1e5c92154c93f544c.js:1:371907
next — main-es2015.67f1e5c92154c93f544c.js:1:371682
_next — main-es2015.67f1e5c92154c93f544c.js:1:2045021
next — main-es2015.67f1e5c92154c93f544c.js:1:371682
_next — main-es2015.67f1e5c92154c93f544c.js:1:2052555
next — main-es2015.67f1e5c92154c93f544c.js:1:371682
notifyNext — main-es2015.67f1e5c92154c93f544c.js:1:136544
_next — main-es2015.67f1e5c92154c93f544c.js:1:136942
next — main-es2015.67f1e5c92154c93f544c.js:1:371682
_next — main-es2015.67f1e5c92154c93f544c.js:1:371907
next — main-es2015.67f1e5c92154c93f544c.js:1:371682
o — main-es2015.67f1e5c92154c93f544c.js:1:750107
onInvokeTask — main-es2015.67f1e5c92154c93f544c.js:1:575518
runTask — polyfills-es2015.199047876b72d3a8e347.js:1:2529
invokeTask — polyfills-es2015.199047876b72d3a8e347.js:1:8021
u — polyfills-es2015.199047876b72d3a8e347.js:1:19628
p — polyfills-es2015.199047876b72d3a8e347.js:1:19978

error when i insert Latitude Longitude manualy
ROR
TypeError: undefined is not an object (evaluating 'l.length')
(anonymous function) — main-es2015.67f1e5c92154c93f544c.js:1:2041878
(anonymous function) — main-es2015.67f1e5c92154c93f544c.js:1:2037946
StoreSettings — main-es2015.67f1e5c92154c93f544c.js:1:1439551
(anonymous function) — main-es2015.67f1e5c92154c93f544c.js:1:4066790
np — main-es2015.67f1e5c92154c93f544c.js:1:518079
(anonymous function) — main-es2015.67f1e5c92154c93f544c.js:1:1390555
onInvokeTask — main-es2015.67f1e5c92154c93f544c.js:1:575518
runTask — polyfills-es2015.199047876b72d3a8e347.js:1:2529
invokeTask — polyfills-es2015.199047876b72d3a8e347.js:1:8021
u — polyfills-es2015.199047876b72d3a8e347.js:1:19628
p — polyfills-es2015.199047876b72d3a8e347.js:1:19868

hope this helps... :)

**Comment by gaeljw** [comment]
@devrosx Unfortunately it's not helping because everything is obfuscated. I will provide versions which should contain more useful information for debugging.

For instance, you can try to the v3 listed in the MR (or here https://drive.google.com/file/d/1VPy71nKt6ia6Oo784D8b300Yem2qN1u0/view?usp=sharing).

I don't expect any of the issues you encounter to be fixed, but the errors should give me more info like which line, which function...

**Comment by devrosx** [comment]
hello, tried new version still cant save setting
but now red box in domoticz gui with cant save settings message isnt visible...
in domoticz log is only Error: WebsocketHandler::Handle Exception: in Json::Value::resolveReference(key, end): requires objectValue
and safari log is empty.. weird...
maybe is becase of language in system.... but cant save any change

noticed one thing: when i switch to old www folder all changes  i did in setting in your version are changed.... (language, theme... etc)

**Comment by gaeljw** [comment]
I'll try to test on Safari but this is very strange if you say settings are saved.
Thanks for having taken some time to test :)

**Comment by gizmocuz** [comment]
Did you know you could remote desktop to a appveyor session ? have a google on it, that safes maybe 100 'test' commits, and also does not let all our build systems build it, and increase our build number by 50 ;)

**Comment by gaeljw** [comment]
> Did you know you could remote desktop to a appveyor session ? have a google on it, that safes maybe 100 'test' commits, and also does not let all our build systems build it, and increase our build number by 50 ;)

Erf, thx @gizmocuz I didn't know! Will use it starting now :)

**Comment by pipiche38** [comment]
looking forward to get on beta

**Comment by gaeljw** [comment]
New version (v5) up to date with latest changes on the development branch:
:arrow_right: https://drive.google.com/file/d/1JnKEbCqelT2-YCmCalHIPPFp236AOvLT/view?usp=sharing (non obfuscated)

**Comment by gaeljw** [comment]
The main remaining issue is the fact that directly accessing a page other than `/` is not working.

For instance:
- http://192.168.1.19:8080/ => redirects to `index.html` which loads the Angular app
- http://192.168.1.19:8080/Dashboard => tries to find `Dashboard` which does not exist (it should redirect to `index.html`)

With AngularJS, routes were always on `/#Something` so it was always `index.html` which was requested from the webserver point of view.

:bulb:  **I see two options to solve this out:**
- move the Angular app under `/app` or `/ui` for instance and always redirect to `index.html` in this subpath
- implement some kind of fallback, instead of giving a 404, if resource not found, redirect to `index.html`

Option 1 looks better IMHO.

:sos:  **Anyway I will need some help from someone who knows how the C++ webserver works to make this change and help me test.**

**Comment by pipiche38** [comment]
How can we help to get this migration integrated into Domoticz ? This will give a great new look to the old UI

**Comment by gaeljw** [comment]
We need someone to help us with the routing issue I described in a comment above (I will copy paste it to the MR itself so that it's more visible).

Also note that the UI won't change at all. The goal of the migration was only to update the code behind the scene :) But I guess it will help for any future change as it's now component oriented.

As soon as someone can provide help with the routing issue, I'll be happy to rebase on the `development` branch to include the latest changes. I didn't do it recently because I was kinda pessimistic that this MR would eventually be merged..

**Comment by nielsvissers** [comment]
why not using the angular router?
i'v downloaded v5 and didn't see it

**Comment by gaeljw** [comment]
> why not using the angular router?
> i'v downloaded v5 and didn't see it

@nielsvissers  what do you mean? The routes are defined in the AppRoutingModule which uses the Angular Router (`www-src/src/app/app-routing.module.ts`).

Please note that I gave up on this PR. I'll be happy to help anyone that wants to finish the work but I won't spend anymore time on it myself.

**Comment by gizmocuz** [comment]
Closing PR as this is impossible to merge.
I do thank all authors for their time and devotion to this.
Maybe it is best to keep the current AngularJS version and if needed optimize some code ?

**Pull request closed without merging**
