### PR TITLE
Remove the attribute m_Firmware_Buffer from RFXComSerial class

### PR DESCRIPTION
**Pull request by gaudryc**
Remove the attribute m_Firmware_Buffer from RFXComSerial class in order to update RFX firmware using a local variable instead.

### CODE REVIEW

**Comment by gaudryc** [comment]
Last commit (e5577e8) was needed because I'd forgotten it the first time (it had been commited from my office instead of my home).

**Comment by gizmocuz** [comment]
just to verify (as i currently can not do this), you tested this a few times?

**Comment by gaudryc** [comment]
Yes, 6 times.

**Comment by gizmocuz** [comment]
Great, thanks!

**Pull request merged**
