### PR TITLE
update/fix read past zone/output 128

### PR DESCRIPTION
**Pull request by Jero-neo**
With this change it if finaly possible for user with the INTEGRA 256 plus type of panels with a ETMH-1 module to read past zone/output 128.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thank you for the PR!

Question, you changed this line

m_data32 ? "false" : "true");

I do not use this hardware, but code-wise, it seems wrong.
when m_data32 has any other value then 0, it seems to me that it should be 'true' as you set a string

(32 bytes mode = %s)

**Comment by Jero-neo** [comment]
> Thank you for the PR!
> 
> Question, you changed this line
> 
> m_data32 ? "false" : "true");
> 
> I do not use this hardware, but code-wise, it seems wrong. when m_data32 has any other value then 0, it seems to me that it should be 'true' as you set a string
> 
> (32 bytes mode = %s)

Thank you for your quick reply.
If i do not change this true : false line it keeps comming with the message that it is 16bit, after change this problem was gone.
Also the ETMH-1 module (the ethernet communicator)  is always being 32 bit. 
I have try this on 3 types of the Satel INTEGRA panel. they al worked like a charm.
i think this true : false string has always been programmed wrong. thats why the INTEGRA 256 plus could never show the zone/output status above 128.

**Comment by kofec** [comment]
Maybe we should change error to warning in this case:
`  
# example
2022-12-22 09:18:49.705 Satel: General/Alert (Garaż)
2022-12-22 09:18:49.078 Status: : Create instance
2022-12-22 09:18:49.166 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:49.189 Status: Satel: Model Integra 32
2022-12-22 09:18:49.230 Status: Satel: RTC 2022-12-22 09:18:50
2022-12-22 09:18:49.253 Status: Satel: ETHM-1 ver. 1.07 2015-03-02 (32 bytes mode = false)
2022-12-22 09:18:49.254 Status: Satel: worker started
......
2022-12-22 09:18:52.559 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:52.526 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:52.529 Error: Satel: Receive info about zone 9 failed (probably zone is not used)
2022-12-22 09:18:53.253 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:53.526 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:53.797 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:53.221 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:53.223 Error: Satel: Receive info about zone 11 failed (probably zone is not used)
2022-12-22 09:18:53.491 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:53.494 Error: Satel: Receive info about zone 12 failed (probably zone is not used)
2022-12-22 09:18:53.763 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:53.765 Error: Satel: Receive info about zone 13 failed (probably zone is not used)
2022-12-22 09:18:54.169 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:54.446 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:54.915 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:54.136 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:54.138 Error: Satel: Receive info about zone 14 failed (probably zone is not used)
2022-12-22 09:18:54.407 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:54.408 Error: Satel: Receive info about zone 15 failed (probably zone is not used)
2022-12-22 09:18:54.880 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:54.881 Error: Satel: Receive info about zone 16 failed (probably zone is not used)
2022-12-22 09:18:55.237 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:55.508 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:55.780 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:55.201 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:55.203 Error: Satel: Receive info about zone 17 failed (probably zone is not used)
2022-12-22 09:18:55.474 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:55.476 Error: Satel: Receive info about zone 18 failed (probably zone is not used)
2022-12-22 09:18:55.745 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:55.747 Error: Satel: Receive info about zone 19 failed (probably zone is not used)
2022-12-22 09:18:56.152 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:56.424 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:56.748 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:56.117 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:56.118 Error: Satel: Receive info about zone 20 failed (probably zone is not used)
2022-12-22 09:18:56.389 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:56.392 Error: Satel: Receive info about zone 21 failed (probably zone is not used)
2022-12-22 09:18:56.711 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:56.713 Error: Satel: Receive info about zone 22 failed (probably zone is not used)
2022-12-22 09:18:57.218 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:57.541 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:57.815 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:57.184 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:57.186 Error: Satel: Receive info about zone 23 failed (probably zone is not used)
2022-12-22 09:18:57.506 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:57.508 Error: Satel: Receive info about zone 24 failed (probably zone is not used)
2022-12-22 09:18:57.779 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:57.780 Error: Satel: Receive info about zone 25 failed (probably zone is not used)
........
2022-12-22 09:18:59.299 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:59.674 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:59.941 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:18:59.267 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:59.269 Error: Satel: Receive info about zone 29 failed (probably zone is not used)
2022-12-22 09:18:59.639 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:59.640 Error: Satel: Receive info about zone 30 failed (probably zone is not used)
2022-12-22 09:18:59.910 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:18:59.915 Error: Satel: Receive info about zone 31 failed (probably zone is not used)
....
2022-12-22 09:19:00.270 Status: Satel: connected to 192.168.X.X:7094
2022-12-22 09:19:00.307 Status: Satel: Alarm not set
2022-12-22 09:19:00.407 Status: Satel: partition 1 not arm
2022-12-22 09:19:00.419 Status: Satel: partition 2 not arm
2022-12-22 09:19:00.441 Status: Satel: partition 3 not arm
2022-12-22 09:19:00.442 Status: Satel: partition 4 not arm
2022-12-22 09:19:00.233 Error: Satel: bad data length received (totalRet 7)
2022-12-22 09:19:00.234 Error: Satel: Receive info about zone 32 failed (probably zone is not used)
2022-12-22 09:19:01.073 Satel: Light/Switch (Arm 4 partition
`

**Comment by gizmocuz** [comment]
Then I think the below code is wrong and sets this incorrectly to true?

`m_data32 = ((buffer[12] & 1) == 1) && (m_modelIndex == 72); // supported and required 256 PLUS`

**Comment by Jero-neo** [comment]
You are right, if i delete 
> && (m_modelIndex == 72)

I get a "true" result.  
So there is a problem with this code. However, all the INTEGRA models reacts to 32 bit so if we leave it out it should not matter.
32bit is only a problem in the INT-RS V1.xx but this is read out in "buffer[12]"  (the part that does work in the code).

**Comment by Jero-neo** [comment]
>Then I think the below code is wrong and sets this incorrectly to true?

>>m_data32 = ((buffer[12] & 1) == 1) && (m_modelIndex == 72); // supported and required 256 PLUS

Corrected, and added a comment in the code.

**Comment by gizmocuz** [comment]
Thank you again!

**Pull request merged**
