### PR TITLE
Get HTTP statusCode from HTTP header

### PR DESCRIPTION
**Pull request by rwaaren**
#3169 	modified:   dzVents/runtime/HTTPResponse.lua
	modified:   main/dzVents.cpp

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks for the fast change !!

**Comment by gizmocuz** [comment]
Can't this also be used with a GET ?

**Comment by rwaaren** [comment]
> Can't this also be used with a GET ?

Yes. tested and working. I also keep using the 2nd method and deal with in HTTPResponse.lua in the theoretical case the header method should not give the expected result but have not seen such a case using my test-set and in my production environment.

**Comment by gizmocuz** [comment]
@rwaaren , i would drop the additional adding of the status code to the http headers in SQLHelper
You always get a result code back in the original headers, and i think also always on the first line
Better to scan against the string "HTTP/1" if that's found, split it in an array (separated by a space), and you should have your result/return code

http://crimsonsecurity.blogspot.com/2016/08/format-of-http-response.html

"The very first line of a valid HTTP Response is consists of the protocol name, it's version, status code of the request, and a short description of the status code"

**Comment by rwaaren** [comment]
@gizmocuz, sorry but I am not sure I completely understand.

Can you please confirm that this is what you want me to do ?

in dzVents.cpp CdzVents::ProcessHttpResponse 

- take statusCode out as separate value
- take status out of lua-subtable "headers" and create new lua-subtable "status" with keys: "protocol/version", "statusCode" and "statusMessage"    // by splitting line that begins with HTTP/

**Comment by gizmocuz** [comment]
Sorry, yes it would be great if you could take the status code from the first HTTP Header array.
And remove the code in SQLHelper.cpp that pushes a status code in the array before it is send to CdzVents::ProcessHttpResponse

**Comment by rwaaren** [comment]
Will try and test but might take a while. My C++ is not at the same level as my Lua

**Comment by rwaaren** [comment]
PR #3181 is ready for review

**Comment by dannybloe** [comment]
Lua part looks ok to me.

**Comment by gizmocuz** [comment]
@rwaaren , thanks for the PR !
I would do it a bit differently... domoticz already contains a 'StringSplit' in helper.h/cpp,
you can use this in CdzVents::ProcessHttpResponse
Then for lua you can provide the status code only, you do not need a stringsplit function in lua

Please revert the change in History.txt, i will add it manually later...

**Pull request merged**
