### PR TITLE
Extract device graph log to own page

### PR DESCRIPTION
**Pull request by stas-demydiuk**
-- Own page for GeneralGraph log page
-- Combine PercentageLog with GeneralGraph log
-- Combine LuxLog with GeneralGraph log
-- Combine UsageLog with GeneralGraph log

### CODE REVIEW

**Comment by sweetpants** [comment]
@stas-demydiuk A little off-topic, but do you have a change to look at #2495. When using Chrome on Linux i'm not able to delete timers anymore, only FF allows me to do so. When the API is called, with Chrome the idx=<IDX> is missing in the API call

**Comment by stas-demydiuk** [comment]
@gizmocuz any updates on this PR or you want to merge it after 4.x release?

**Comment by gizmocuz** [comment]
@stas-demydiuk , i have to test this 100%, i would love it in 4.x, but i need more time.
Probably it is best to merge this after 4.x.

**Comment by gizmocuz** [comment]
Where you able to test all sensor types ?
I don't see how you can go back to the page where you pressed the 'log' button from, for example, when you are on the utility tab, and press the log button on a sensor, how to get back ?
Remember, there is no browser back button on an offline application

**Comment by stas-demydiuk** [comment]
@gizmocuz, could you please explain what do you mean: there should regular back button in top left corner of the page, under the main menu - nothing was changed from that perspective

image

**Comment by gizmocuz** [comment]
@stas-demydiuk , sorry, i really should test this in real life...
I was looking at the changes, site-by-site, and previously i passed the callback to show the previous page

Before:

`ShowGeneralGraph('#weathercontent', 'ShowWeathers', item.idx, escape(item.Name), item.SwitchTypeVal, 'Visibility');
`

Where ShowWeathers was the callback

Now:

`return $location.path('/Devices/' + item.idx + '/GraphLog');`

It looked i missed something.

Going to check this soon!

**Comment by gizmocuz** [comment]
I needed to correct two widgets on the dashboard (usage/sound)

**Comment by gizmocuz** [comment]
Thanks for this great patch again !! Keep 'm coming :ok_hand: ;)

**Pull request merged**
