### PR TITLE
Travis-CI: Linux & OSX build support

### PR DESCRIPTION
**Pull request by ToniA**
See https://travis-ci.org/ToniA/domoticz/builds/85155076 for an example of a matrix build.

The .travis.yml is really clumsy, and the OSX 'brew' dependencies should be reviewed. Also the final 'tar' command to create the package needs to be checked. And yes, the artifacts still aren't deployed anywhere.

### CODE REVIEW

**Comment by ToniA** [comment]
The Windows installer script seems to be broken, but it has nothing to do with the .travis.yml changes.

**Comment by gizmocuz** [comment]
i know!, see latest commit... just swapped from zip to 7z, saves 40 megabytes !!

**Comment by gizmocuz** [comment]
build passed

**Comment by gizmocuz** [comment]
Would you like me to merge this ? Or was this a test?

**Comment by ToniA** [comment]
Yes, please merge

Lähetetty Windows Phonesta

---

Lähettäjä: gizmocuzmailto:notifications@github.com
Lähetetty: ‎14.‎10.‎2015 20:13
Vastaanottaja: domoticz/domoticzmailto:domoticz@noreply.github.com
Kopio: Tonimailto:toni.arte@iki.fi
Aihe: Re: [domoticz] Travis-CI: Linux & OSX build support (#141)

Would you like me to merge this ? Or was this a test?

---

**Pull request merged**
