### PR TITLE
Fix for serving already compressed sourcefiles and some refactoring

### PR DESCRIPTION
**Pull request by kiddigital**
This PR is to fix issue #4960 (caused by PR #4942).

That issue was found on the _Openwrt_ build where by default most webserver content files (the _www_ directory) are being zipped to save diskspace.

This PR also does some more refactoring of the webserver code base.
- Now it looks for the 'Cache-Control' header and when 'no-cache' is requested, it will serve the local file even if it doesn't seem modified.
- Adding the (optional) charset encoding (UTF-8) is now done at 1 place instead on multiple pieces of code

### CODE REVIEW

**Comment by gizmocuz** [comment]
Could you please undo the utf-8 charges as this is needed for a lot more types and this has been done in the code.
Also worked previously without issue and should still work correctly.

**Comment by kiddigital** [comment]
Hi @gizmocuz , I can do that but not sure if it is necessary.

I removed the code that adds the UTF-8 in several places as it was duplicate to reach the same goal. Also, when for whatever reason the content-type could not be determined based on the file extension (unknown or no extension) than the content-header was just wrong with only containing ';charset=UTF-8' without a proper actual type.

Also the way the extension and content-type where determined was different at different places and should now be at 1 place and consistent.

Do you foresee any issues somewhere? Or have certain (edge)cases in mind that I can test and verify if everything still works as expected?

Btw: for which additional content-types do you think we should add the charset type?

**Comment by kiddigital** [comment]
@gizmocuz , removed the UTF-8 charset from the mime-types (so back to the original code) and have the 'add_header_content_type' function (reply.cpp) take care of adding it when needed. And made sure that other code pieces don't do it manual anymore but use this function.

**Comment by kiddigital** [comment]
This PR is ready as far as I can tell. Once merged, people can create a new (beta)build for platforms like OpenWRT that work again with serving compressed content.

See issue #4960

**Comment by gizmocuz** [comment]
Thanks! I just want to verify the workings before merging, hope to do shortly!

**Comment by gizmocuz** [comment]
Something is not correct.... For example go to the settings, you will see there are no languages to select anymore

**Comment by kiddigital** [comment]
Weird.. you think that it is related to this change? I will look into it asap.

Let me know if you find anything else.

Thx for testing.

**Comment by kiddigital** [comment]
@gizmocuz , found the issue. Include processing didn't work properly anymore because content was compressed before include.

Now works fine again.

**Comment by gizmocuz** [comment]
Great, so we do not the other PR ? There are multiple places where these comboboxes are used

**Comment by kiddigital** [comment]
@gizmocuz , for this PR the other PR is not needed indeed.

The other PR is to remove the only ServerSideInclude from the Settings screen. That would make it possible to serve the settings screen from another webserver instead of the Domoticz webserver itself..  Could not find any other place where the language combobox gets embedded other than on the settings screen. The _switchtypes_ and _metertypes_ combo's are used still at a few (found 4) places.

So if we do or don't merge the other PR is irrelevant for this PR. This one fixes the open issue.

**Comment by gizmocuz** [comment]
Thank you for the change! Maybe you could tweak the other PR to not touch the settings page, but leave the GetLanguages call, and if you want you can do the same for the other ServerSideIncludes...
Going to test/merge this soon

**Comment by gizmocuz** [comment]
Thank you !!

**Pull request merged**
