### PR TITLE
[Logitech] Fix bug in set timeout

### PR DESCRIPTION
**Pull request by szczukot**
Before, Logitech set http timeout to other devices too.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Instead of this, in the Logitech class, issue a call to
HTTPClient::SetConnectionTimeout(const long timeout)
And your set

**Comment by szczukot** [comment]
SetConnectionTimeout and SetTimeout set timeouts global - for all other modules, which uses httpclient

**Comment by gizmocuz** [comment]
Yes... but look in which classes it is used

**Comment by szczukot** [comment]
I fixed it, because i want use it in BleBox, but default timeout is too big for me.
And i found this bug in Logitech
This commit only fixing bug in logitech - don't change any logic for other modules.
And when in Logitech, someone set ping less that 1000 ms, ale other modules have infinity timeuot.

**Comment by gizmocuz** [comment]
Then before the call to the HTTP class, set the timeout, in both classes and your find
There is really no need to patch the HTTP class

**Comment by szczukot** [comment]
Ok. i set timeout in my module (blebox).
But now 99% of modules don't set this value, and will may work inproperly.

**Comment by gizmocuz** [comment]
your mixing up things here... logitech, blebox, httpclient ...

Logitech is using csocket ?

**Comment by szczukot** [comment]
i closed this pull request a 2 days ago
As You want

**Comment by gizmocuz** [comment]
Yes, but your last comment wat '99% of modules don;t set this value....'
But if you got it working, great!

**Comment by szczukot** [comment]
I think, that this is bug, or all other modules must set timeout. Now about 20 modules use httpclinet, and none of them sets this value. Only Logitech.

**Comment by gizmocuz** [comment]
None of them needs this... no problem with the timeout
I made a recent patch in the logitech harmony class, there was a error
maybe its not needed anymore

**Pull request closed without merging**
