### PR TITLE
Update manufacturer_specific.xml

### PR DESCRIPTION
**Pull request by tlpeter**
Added product type for new fgcd001 (Fibaro CO sensor)

### CODE REVIEW

**Comment by gizmocuz** [comment]
We merge from time to time with the openzwave repo?
Is this already in the ozw repo?

**Comment by tlpeter** [comment]
I did the same there and then realized that it would be taken from there.
So i guess it is not needed.
The same applies for #1719 i think.



Op 25 jul. 2017 17:05 schreef "gizmocuz" <notifications@github.com>:

**Comment by gizmocuz** [comment]
True... Okey let us know when it is merged...

**Comment by tlpeter** [comment]
It is merged and i see you already put it in but it has changed a little bit.
Parameter 3 and for do have a max of 7 instead of 4.

**Comment by gizmocuz** [comment]
you have to contact OZW for this...

**Comment by tlpeter** [comment]
I did and was changed after you pulled it from there i guess.

**Pull request closed without merging**
