### PR TITLE
Update EnOceanESP3.cpp

### PR DESCRIPTION
**Pull request by EdddieN**
Added support for combined Pressac CO2 Temperature and Humidity (and maybe other 3 sensors in one)

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thanks ! Please change the code to use SendTempSensor and SendAirQualitySensor

**Comment by EdddieN** [comment]
Sorry, I'm confused, I do not see any reference to SendTempSensor and SendAirQualitySensor on the original code. Have I pulled an old version of the code?

**Comment by gizmocuz** [comment]
No, but please use the new functions when possible

**Comment by gizmocuz** [comment]
@EdddieN , are you going to patch the code (or your adjustments) to use 'SendTempSensor' and SendAirQualitySensor' calls ?

**Comment by EdddieN** [comment]
Yes! sorry a few days holidays over here :D - I'll update shortly (tomorrow hopefully)

**Comment by gizmocuz** [comment]
No worries, enjoy your holiday!!

**Comment by gizmocuz** [comment]
Thanks for this!

**Comment by gizmocuz** [comment]
There where to errors in your code (missing semicolon ';')
Please test the patch next time before committing the code

**Comment by EdddieN** [comment]
Thanks for correcting it! :) The boost files were giving trouble trying to compile. Still trying to short it out.

**Comment by gizmocuz** [comment]
What platform are you using ?
If windows, download the new libraries
If unix, issue:

make clean

remove the CMakeFiles folder and CMakeCache folder

install boost 1.67 (see our wiki for raspberry pi, works on almost every unix system)

Else remove the whole development folder and start again

But even so, best to test the code before committing

**Pull request merged**
