### PR TITLE
	Restart hardware after a long period of inactivity

### PR DESCRIPTION
**Pull request by szczukot**
What do You think about this ?

### CODE REVIEW

**Comment by gizmocuz** [comment]
Thats why we have implemented a data timeout ?

**Comment by szczukot** [comment]
Ahh, i see.
That maybe m_LastHeartbeat is not needed anymore ? And it is for remove from all modules ? Is it needed ? Is it only for logs ?

**Comment by gizmocuz** [comment]
Nope

**Comment by szczukot** [comment]
Is it neede or not ? :) I wrote I too many questions.

**Comment by szczukot** [comment]
Is it needed ?

**Comment by szczukot** [comment]
??
If it is unnecessary, i do refactoring, and I remove it with all code

**Comment by gizmocuz** [comment]
Why do you think that m_LastHeartbeat is not needed anymore ?
Have a look in the mainworker
Please only do refactoring on your own code

**Comment by szczukot** [comment]
I don't know. 
In mainworker this uses only for logs "warning" when device don't responses for more than 60 sec.
I can not found another use for this property.

**Pull request closed without merging**
