### PR TITLE
Save svalue to database for LimitlessLights

### PR DESCRIPTION
**Pull request by corbinmunce**
I hope this simple addition is OK

### CODE REVIEW

**Comment by gizmocuz** [comment]
Did you had a chance to test this change ? There is a build error
I think this also might have implications later

**Comment by corbinmunce** [comment]
I didn't compile for this pull request since I the change ready to paste in, and then forgot to remove the original line in my rush.  Will make sure to test properly next time.

Regarding implications later... is updating the sValue in this way potentially going to cause a problem?

**Comment by gizmocuz** [comment]
Thanks, let me check the sValue ...

**Comment by gizmocuz** [comment]
Nope, no problem at all.
But what is the value of sValue ?
I think the limitedled type should be converted to a new General Led type... where we can also have more parameters... but thats for later ;)

**Comment by corbinmunce** [comment]
it is for the brightness, which is in lastlevel - but I don't think last level is is available via Lua, when sValue is.  So it can then be used in a script to control bulb brightness: https://www.youtube.com/watch?v=g5sUVF3R2Pk

**Comment by gizmocuz** [comment]
Nice... in the end i think we need more values like also the RGB color

**Comment by corbinmunce** [comment]
yes would be good to always have the RGB color and brightness states available for the lights

**Comment by gizmocuz** [comment]
This would be a semicolon separated sValue later then

**Pull request merged**
