### PR TITLE
Deallocate CharReader after use

### PR DESCRIPTION
**Pull request by akamming**
Fixes issue #3761 (Memory leak at json_helper)

### CODE REVIEW

**Comment by akamming** [comment]
> What happens if you have many cases of inStr.empty() ? Could this lead to memory leak ?

no c++ expert either, but I do not suspect this statement. the .empty() function is just a check whether the string is filled or not. If it it leaks i should still see a leak on my system. This is what i see on my system:
fixes_effect
16.14: 4.11539 is started, has a big memory leak. Memory keeps rising as long as it runs
08.47: 4.11540 is started, contains this PR, memory leak no longer leaks
11.40: 4.11540 is started, with now contains an alternate fix, no memory leak, but average memory usage went up by 5mb). 

In the alternate fix, the code ParseJSon function is change to
```
bool ParseJSon(const std::string& inStr, Json::Value& json_output, std::string *errstr)
{
        Json::CharReaderBuilder builder;
        const std::unique_ptr<Json::CharReader> reader(builder.newCharReader());

        if (inStr.empty())
                return false;

        return reader->parse(
                reinterpret_cast<const char*>(inStr.c_str()),
                reinterpret_cast<const char*>(inStr.c_str() + inStr.size()), &json_output,
                errstr);
}

```
@gizmocuz  This is cleaner c++ code, but because of the 5mb memory rise i did not change this PR. But if you think this would be better from a code quality perspective, i can change the PR if you like...

**Comment by akamming** [comment]
@rwaaren  Sorry for the spam. I just thought of it. I would not remove the check on empty strings. but there is still another leak in this code indeed, which could explain why my fix makes it much better, but not fully fixes is it. In case of an empty string the "delete reader" is not called before the return!, leaking memory in case of empty strings! 


I don't have access to my system now (at work ;-)), so i cannot add this to the PR now.   In my alternate solution this would already be fixed. 

My suggestion is to have this PR pulled in asap, it would then be solved for many users. And then based on which solution of the code @gizmocuz  decides, we can make an additional PR to solve the other leak.

[EDIT] aha... you edited your remark; i understand now we are talking about the same thing ;-)
An additional remark: It might not a bad idea to debug why empty strings are sent.... has nothing to do with this leak (this function should be resistent to empty strings), but an empty string might be indication that something else is wrong in the code which sends the empty string.

**Comment by gizmocuz** [comment]
Thanks for the PR. I have corrected the code and made it consistent with the ParseJSonStrict helper function.
Thank you for spotting this!

**Comment by akamming** [comment]
Tx. I switched back to "normal" beta (4.11544) branch again this morning, now running for 4 hrs. I can confirm memory leak is gone

**Pull request closed without merging**
