### PR TITLE
Update highcharts 9.2.2

### PR DESCRIPTION
**Pull request by michahagg**
The issue in highcharts/highcharts#9612 has been fixed in a newer version. A good reason to update the library.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Yahoo great!! Thanks for the PR!

**Comment by neheb** [comment]
Why was .clang-format removed?

**Comment by michahagg** [comment]
@neheb I'm not sure what you mean. Please explain.

**Comment by neheb** [comment]
the .clang-format file was removed in this PR.

**Comment by gizmocuz** [comment]
@neheb , don't think it was removed in this PR, I might have removed it in another commit when getting extreme frustrated about the code formatting that was happening to my if/then/else lines.
Was not meant to be physically removed (and should have been placed back)
Maybe the clang-format line that reformats the code onto a single line can be removed, or at least that if statements can look like

if (
  (a == 1)
  || (b == 1)
  || (c == 1)
 ) {
  ....
 }
 
 that would help, otherwise with 20 compare lines , all spread over 2 lines, does not make to code readable

**Comment by neheb** [comment]
I tried looking through git history. It seems to have been lost while resolving merge conflicts somewhere.

**Comment by michahagg** [comment]
@neheb and @gizmocuz I made a new PR recovering the .clang-format file: #5022

**Pull request merged**
