### PR TITLE
Tesla: Introduced optional keep-asleep mode

### PR DESCRIPTION
**Pull request by MrHobbes74**
This will prevent the car to be woken up by domoticz.

This prevents battery drain. In this mode, car updates are only retrieved at the configured
interval when the car is awake. In case the car wakes up by itself for any reason, an update is
also retrieved. User commands sent to the car (e.g. start charge) will always wake up the car.

Also reconfigured the state device, it now provides only a new value when it's different from the
previous value.

### CODE REVIEW

**Comment by Nougreche** [comment]
labview

**Comment by MrHobbes74** [comment]
@gizmocuz can you integrate this PR? There are no issues found after running for a week :-)

**Comment by gizmocuz** [comment]
Thanks for the work again !!

**Comment by MrHobbes74** [comment]
Thanks a lot!

**Comment by gohamstergo** [comment]
@MrHobbes74 Great work on this module! I've started some suggestions on the forums here: https://www.domoticz.com/forum/viewtopic.php?f=31&t=31781&p=240402

Sorry to semi-hijack these comments, couldn't find another way to get in touch.

**Pull request merged**
